### ISSUE TITLE
DecoratorManager not singleton and please check @midwayjs/decorator version by "npm ls @midwayjs/decorator"

### ISSUE THREAD

**Issue by xiaoyanzheng** [midwayjs/midway#1007]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
新版本做的一个检查，本地请使用同一个版本的 @midwayjs/decorator，出现这个错误意味着有多个版本或者实例，需要删除下 package-lock 文件重新 install 一下。

**Comment by wgcairui** [comment]
其它@midway版本都是2.11.4,怎么@midwayjs/decorator还是2.11.1 ??,我写自定义框架这个消不掉,不管它要不要紧??

**Comment by czy88840616** [comment]
放dev依赖里就行，因为业务是一定会有这个依赖的。
