### ISSUE TITLE
IMidwayjApplication接口中是不是少了use、generateMiddleware两个方法

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#1013]
如题
![image](https://user-images.githubusercontent.com/35318575/115944904-57120280-a4eb-11eb-82e4-77854736d189.png)

**Comment by czy88840616** [comment]
只有web框架我们扩展了这接口，这个定义直接用 Application from egg

**Comment by feiyueXH** [comment]
因为我是以开发组件的方式去开发业务，所以我希望的业务组件不受任何Web框架限制，所以在代码中一直都是使用接口限制类型。

**Comment by feiyueXH** [comment]
![image](https://user-images.githubusercontent.com/35318575/115945658-41064100-a4ef-11eb-8ce1-eeebc3a2d53a.png)

**Comment by feiyueXH** [comment]
既然各个Web框架都提供了方法，那我觉得定义在接口里面也没多大问题。

**Comment by czy88840616** [comment]
当前不是一个通用定义，只有通用的才会放到 IMidwayApplication，事实上现在除了web类框架都没有中间件，所以自然也没有 use 这些方法。所以你的组件其实还是限定在web领域的

**Comment by czy88840616** [comment]
不过我们正在设计全框架类型的中间件，等中间件通用之后就可以提升到通用了。

**Comment by feiyueXH** [comment]
行。那我先用config注入中间件的方式看看能不能实现吧
