### ISSUE TITLE
@midwayjs/egg-ts-helper 生成typing

### ISSUE THREAD

**Issue by gogogo1024** [midwayjs/midway#1021]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

最终只生成一个app/index.d.ts文件，哪个环节出现问题了。。。

**Comment by czy88840616** [comment]
需要提供可复现仓库。

**Comment by waitingsong** [comment]
midway 项目基本不需要用 egg-ts-helper  生成 .d.ts 了吧

**Comment by czy88840616** [comment]
要的，不然 egg 插件那些定义是弄不进来

**Comment by czy88840616** [comment]
@gogogo1024 尽快给我个复现例子哈 。

**Comment by gogogo1024** [comment]
> @gogogo1024 尽快给我个复现例子哈 。

终于得空了。。。
https://github.com/gogogo1024/midway-demo

**Comment by czy88840616** [comment]
看着没问题啊。

![image](https://user-images.githubusercontent.com/418820/116802674-3f6bf700-ab47-11eb-8901-588aa1c951df.png)

**Comment by gogogo1024** [comment]
> 看着没问题，typings 的内容就是这些。
> 
> ![image](https://user-images.githubusercontent.com/418820/116802674-3f6bf700-ab47-11eb-8901-588aa1c951df.png)

extend的里面helper就没有，所以我在使用helper的时候基本等于没有智能提示～

**Comment by czy88840616** [comment]
业务代码里的一向不会生成的，也不属于midway 的标准功能更，这里只会生成插件和框架的部分。如有需要，得自己写。https://www.yuque.com/midwayjs/midway_v2/eggjs#KfNUZ

**Comment by gogogo1024** [comment]
> 业务代码里的一向不会生成的，也不属于midway 的标准功能，这里只会生成插件和框架的部分。如有需要，得自己写。https://www.yuque.com/midwayjs/midway_v2/eggjs#KfNUZ<img width="963" alt="截屏2021-05-02 下午11 00 45" src="https://user-images.githubusercontent.com/16661897/116817723-60116c80-ab9a-11eb-901d-9f2483a482d2.png">
这个是我用egg ts模版生成的，我的意思是midway把这个申明弄没了。也就是说这个我也得自己写了。。。

**Comment by czy88840616** [comment]
额。的确一直就没有这个功能，甚至我都没见过 helper 的定义。。。。。

**Comment by czy88840616** [comment]
看了下，这几个定义是固定的。。我写死就行了。。

**Comment by czy88840616** [comment]
发了 1.2.0 重装下试试。

**Comment by gogogo1024** [comment]
> 发了 1.2.0 重装下试试。

ok了，helper里面就不能用你们仓库的那种写法了 https://github.com/fsd-nodejs/service-mw2/blob/master/src/app/extend/helper.ts，必须export default {} 这样来写了。感谢。。。

**Comment by czy88840616** [comment]
哦，是的，不然ts不认识。。
