### ISSUE TITLE
有腾讯云开发相关的使用教程吗

### ISSUE THREAD

**Issue by houta-higuchi** [midwayjs/midway#1026]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/116960066-ebd9e480-acd1-11eb-8a87-629fa202148f.png)

文档都有的。

**Comment by houta-higuchi** [comment]
腾讯云开发(cloudbase)和SCF是不一样的。现在我不知道怎么部署上去

**Comment by czy88840616** [comment]
的确，cloudbase和 scf 是不同的产品，我们对接的是 scf，我也没理解他们的定位和差异。

**Comment by xuedaobian** [comment]
cloudbase 是腾讯自己封装的一套开发环境，你用midway咋部署，用tcb自己的部署
