### ISSUE TITLE
@midwayjs/orm/dist的formatConfig方法有问题。。。

### ISSUE THREAD

**Issue by gogogo1024** [midwayjs/midway#1033]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我改成截图的样子。可以正常启动了，代码注释的地方是源码～
<img width="1314" alt="截屏2021-05-07 下午6 16 44" src="https://user-images.githubusercontent.com/16661897/117435431-6fa90080-af60-11eb-81e8-98876f14cb5f.png">

**Comment by czy88840616** [comment]
没问题吧，多数据库的时候配置是数组。

**Comment by gogogo1024** [comment]
> -_- 好像是有点不对，和文档没统一。

好神奇，我删掉node_modules以及package-lock.json文件后，重新yarn安装后，识别了我单个数据库postgres的配置信息～

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/117461701-70ea2580-af80-11eb-982d-d01f7bb1f097.png)

我又测了下，这里写的是没错。。

**Comment by gogogo1024** [comment]
> ![image](https://user-images.githubusercontent.com/418820/117461701-70ea2580-af80-11eb-982d-d01f7bb1f097.png)
> 
> 我又测了下，这里写的是没错，多库和单库都可以。。

所以很神奇，typescript的机制问题还是缓存的问题，我代码都没改过～

**Comment by czy88840616** [comment]
这我就不知道了，建议把package-lock去了。。

**Comment by czy88840616** [comment]
既然没问题了我先关了。
