### ISSUE TITLE
运行时， api 接口404

### ISSUE THREAD

**Issue by LINALINLINA** [midwayjs/midway#1036]
* **Npm Version**: 6.14.11
* **Node Version**:v14.15.5
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/19849988/117629737-0ec23800-b1ad-11eb-8f23-fa83aed15496.png)

**Comment by waitingsong** [comment]
复现仓库？

**Comment by czy88840616** [comment]
大概率是包版本啥的问题，可以把node_modules + package-lock 删了，重装一次。

**Comment by waitingsong** [comment]
package.json 可以加个 script
```
"purge": "npm run clean && lerna run purge && rm node_modules -rf",
```

**Comment by czy88840616** [comment]
是lerna才需要吧

**Comment by LINALINLINA** [comment]
npm v7.19.1
node v16.6.0
仓库就是npm init midway @czy88840616 
![Uploading  @image.png…]()

**Comment by LINALINLINA** [comment]
![image](https://user-images.githubusercontent.com/19849988/133713035-ed968e3f-1174-4366-a0ef-b3ca37351271.png)
图片重新上传
@czy88840616

**Comment by czy88840616** [comment]
dev，你这个7001端口冲突了吧，访问要7002了
