### ISSUE TITLE
布署阿里云函数计算后，method不同path相同时都走get方法

### ISSUE THREAD

**Issue by snailzzj** [midwayjs/midway#1040]
1、本地调试时，下面这么写是没问题的，但是布署到阿里云后，无论用什么method请求，都走Get修饰的方法，这里是有什么限制吗？路径不能一样？RESTFul风格的API要怎样实现。
@Get('/')
async aaa() {}
@Post('/')
async bbb() {}
@Patch('/')
async ccc() {}

布署时是使用聚合布署（所有函数）
aggregation: 
  all:
    functionsPattern: 
       '*'

2、控制器中有使用到PATCH方法，但是布署到阿里云后，触发器配置里边只有GET,PUT,POST,DELETE,HEAD这五个，是需要在哪里配置吗，好像文档里面没找到。

求解惑~

**Comment by czy88840616** [comment]
平台不支持 patch 方法。

**Comment by snailzzj** [comment]
但是为什么我可以在阿里云后台的触发器编辑里手动加上Patch方法...

**Comment by czy88840616** [comment]
看了下，平台应该是新加了。

**Comment by snailzzj** [comment]
第1点有解决方法吗

**Comment by czy88840616** [comment]
明天我找工具链的同学验证下。

**Comment by echosoar** [comment]
第一点fc验证没有复现
+ `GET`: fetch('http://50963443-1213677042792422.test.functioncompute.com/api/test', {method: 'GET'}).then(res => res.text()).then(console.log); // res:a
+ `POST`: fetch('http://50963443-1213677042792422.test.functioncompute.com/api/test', {method: 'POST'}).then(res => res.text()).then(console.log); // res:b
+ `PATCH`: fetch('http://50963443-1213677042792422.test.functioncompute.com/api/test', {method: 'PATCH'}).then(res => res.text()).then(console.log); // res:c


第二点已添加Patch支持

**Comment by snailzzj** [comment]
好吧，我把node_modules删掉重新install之后，第一个问题就消失了~

**Comment by czy88840616** [comment]
我先close了，有问题再开。
