### ISSUE TITLE
midwayjs 有计划支持bull吗？

### ISSUE THREAD

**Issue by zkamisama** [midwayjs/midway#1042]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by stone-jin** [comment]
支持了：https://www.yuque.com/docs/share/7dbbeb94-aa09-480f-b9b5-35813c593beb?# 《定时任务&延时任务》

看一下这个能满足你需求吗？

**Comment by zkamisama** [comment]
> 支持了：https://www.yuque.com/docs/share/7dbbeb94-aa09-480f-b9b5-35813c593beb?# 《定时任务&延时任务》
> 
> 看一下这个能满足你需求吗？

看了下可以满足了， 谢谢， 这个文档好像在官网教程文档里面找不到呢。

**Comment by stone-jin** [comment]
这不是刚开发没多久，找了一些人在内测，你试试

**Comment by stone-jin** [comment]
你在Midway 钉钉群，找一下我：聚海，然后有什么需要修改的，可以方便沟通

**Comment by zkamisama** [comment]
@stone-jin 
![image](https://user-images.githubusercontent.com/6882016/117917498-cecd9300-b31b-11eb-8cb0-f9bbeccdf7f7.png)
这里的配置可以使用对象形式吗？ 因为应用本身也配置了redis
![image](https://user-images.githubusercontent.com/6882016/117917569-f7ee2380-b31b-11eb-8807-43756e9f82ad.png)

**Comment by czy88840616** [comment]
可以

**Comment by zkamisama** [comment]
@stone-jin 
提个小建议
queue触发执行的时候，可以传多个job参数吗， 或者参数直接传job对象， 这样执行任务的时候，就可以通过job设置进度了
![image](https://user-images.githubusercontent.com/6882016/117931112-5e317100-b331-11eb-997c-cba22bb3033e.png)
![image](https://user-images.githubusercontent.com/6882016/117931155-6d182380-b331-11eb-8a06-15c8bfb43561.png)

**Comment by stone-jin** [comment]
@zkamisama 
如果加入job，然后你能设置progress，然后你那边可以使用这个进度？
想问一下用户的使用方法？

我Midway的群里：叫聚海，我们钉钉沟通一下？
