### ISSUE TITLE
console 被吞？

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#1050]
![image](https://user-images.githubusercontent.com/418820/118602885-d7274180-b7e5-11eb-9771-4cf6552c0b9c.png)

**Comment by waitingsong** [comment]
应该异步日志延迟输出导致的（app 已被关闭）

![图片](https://user-images.githubusercontent.com/1763067/118627682-82dc8b80-b7fe-11eb-8914-865568bc957d.png)

**Comment by czy88840616** [comment]
感觉是异步引起的，但是console在beforeAll的地方输出，理论上不会受到close影响..
