### ISSUE TITLE
typing目录下的plugin.d.ts缺少例如redis，mongoose等定义

### ISSUE THREAD

**Issue by gogogo1024** [midwayjs/midway#1056]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

egg生成的
// This file is created by egg-ts-helper@1.25.8
// Do not modify this file!!!!!!!!!

import 'egg';
import 'egg-onerror';
import 'egg-session';
import 'egg-i18n';
import 'egg-watcher';
import 'egg-multipart';
import 'egg-security';
import 'egg-development';
import 'egg-logrotator';
import 'egg-schedule';
import 'egg-static';
import 'egg-jsonp';
import 'egg-view';
import 'egg-validate';
import 'egg-mongoose';
import 'egg-sequelize';
import 'egg-jwt';
import 'egg-redis';
import 'egg-passport';
import 'egg-passport-twitter';
import 'egg-passport-facebook';
import 'egg-passport-qq';
import 'egg-passport-weixin';
import 'egg-email';
import { EggPluginItem } from 'egg';
declare module 'egg' {
  interface EggPlugin {
    onerror?: EggPluginItem;
    session?: EggPluginItem;
    i18n?: EggPluginItem;
    watcher?: EggPluginItem;
    multipart?: EggPluginItem;
    security?: EggPluginItem;
    development?: EggPluginItem;
    logrotator?: EggPluginItem;
    schedule?: EggPluginItem;
    static?: EggPluginItem;
    jsonp?: EggPluginItem;
    view?: EggPluginItem;
    validate?: EggPluginItem;
    mongoose?: EggPluginItem;
    redis?: EggPluginItem;
  }
}

midwayjs生成的
// This file is created by egg-ts-helper
// Do not modify this file!!!!!!!!!
import 'egg';
import '@midwayjs/web';
import 'egg-onerror';
import 'egg-session';
import 'egg-i18n';
import 'egg-watcher';
import 'egg-multipart';
import 'egg-security';
import 'egg-development';
import 'egg-logrotator';
import 'egg-schedule';
import 'egg-static';
import 'egg-jsonp';
import 'egg-view';
import 'midway-schedule';
import 'egg-cors';
import { EggPluginItem } from 'egg';
declare module 'egg' {
  interface EggPlugin {
    onerror?: EggPluginItem;
    session?: EggPluginItem;
    i18n?: EggPluginItem;
    watcher?: EggPluginItem;
    multipart?: EggPluginItem;
    security?: EggPluginItem;
    development?: EggPluginItem;
    logrotator?: EggPluginItem;
    schedule?: EggPluginItem;
    static?: EggPluginItem;
    jsonp?: EggPluginItem;
    view?: EggPluginItem;
    schedulePlus?: EggPluginItem;
    cors?: EggPluginItem;
  }
}
感觉就是egg相关的插件会有自动注入到这个d.ts文件

**Comment by czy88840616** [comment]
是的，这里只是列举了egg插件，并将其导入，如果egg插件里没有写定义，那也生成不了。

**Comment by czy88840616** [comment]
egg-mongoose 是在哪引的？

**Comment by gogogo1024** [comment]
> egg-mongoose 是在哪引的？

自己在项目lib中包了一个层，然后在plugin中替换掉的。
我的意思是egg-redis这个插件会注入进去的。

**Comment by czy88840616** [comment]
项目lib里库搜索不到了。。。

**Comment by gogogo1024** [comment]
> https://github.com/midwayjs/egg-ts-helper/blob/master/index.js

咋说呢，现在引入redis,还没有插件,所以目前midwayjs又没有好的redis插件。。。

**Comment by czy88840616** [comment]
redis 的sdk已经很成熟了吧，这个做成插件没有什么复用的价值啊。

**Comment by gogogo1024** [comment]
> https://www.yuque.com/midwayjs/midway_v2/redis

是可以，先用着吧，之前自己也是引用ioredis，然后再添加了些代码支持bloom filter。看来确实是纯sdk，想怎么使用自己去包装下。
