### ISSUE TITLE
分布式任务调度有问题，见截图。

### ISSUE THREAD

**Issue by gogogo1024** [midwayjs/midway#1059]
<img width="1197" alt="截屏2021-05-21 上午10 25 20" src="https://user-images.githubusercontent.com/16661897/119073005-12608500-ba1f-11eb-84de-37288ab2b78f.png">

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
<img width="1197" alt="截屏2021-05-21 上午10 25 20" src="https://user-images.githubusercontent.com/16661897/119073023-1b515680-ba1f-11eb-9d08-da69d1cd7aee.png">

**Comment by czy88840616** [comment]
你的decorator包版本太低了，需要更新，删除package-lock.json 重新安装

**Comment by gogogo1024** [comment]
> 你的decorator包版本太低了，需要更新，删除package-lock.json 重新安装

更新好了， 是不是decorator升级太快了，我用的比较新的midwayjs脚手架，结果decorator包版本低了，看了下这个分布式定时任务文档是5-12加进来的，所以decorator这之前是没有Task的导出么？

**Comment by czy88840616** [comment]
对的，你如果要用新功能，需要配合升级框架依赖的版本（我们内部没有 package-lock，所以没有这个问题）。

**Comment by gogogo1024** [comment]
好的，我这边也删掉这个版本锁，目前看版本锁没啥用

**Comment by liuwensa** [comment]
怎么设置固定环境下开启呢，比如只有prod开启，修改cron之前的定时还在执行中怎么解决

**Comment by gogogo1024** [comment]
可能还是需要开启了，对于之前的定时任务，我修改了定时任务的时间，之前的定时任务竟然还跑着。。。代码里设置的时间完全没有生效。

**Comment by gogogo1024** [comment]
> 怎么设置固定环境下开启呢，比如只有prod开启，修改cron之前的定时还在执行中怎么解决

固定环境应该可以试试这种写法
`@Configuration({
  importConfigs: [join(__dirname, './config')],
  conflictCheck: true,
  imports: [
    {
      component: task,
      enabledEnvironment: ['local'],
    },
    {
      component: swagger,
      enabledEnvironment: ['local'],
    },
    orm,
  ],
})`

**Comment by czy88840616** [comment]
应该需要一个清理以前定时任务的接口吧。

**Comment by gogogo1024** [comment]
> 应该需要一个清理以前定时任务的接口吧。

对的。

**Comment by czy88840616** [comment]
@gogogo1024 这个issue已经关闭了，跟踪 #1065 吧
