### ISSUE TITLE
为什么要放弃egg.js？

### ISSUE THREAD

**Issue by TEsTsLA** [midwayjs/midway#106]
官网是这么写的==>" Egg.js 为企业级框架和应用而生"。

**Comment by TEsTsLA** [comment]
https://github.com/xitu/gold-miner/blob/master/TODO/how-to-start-with-backend-typescript-and-use-its-full-potential.md

**Comment by czy88840616** [comment]
eggjs 挺好的呀，只是 eggjs本身定位就是一个框架的核心，从 egg 上生长出不同领域，解决不同问题的框架没有问题。

至于 KPI 框架，是担心不维护么？Midway 在集团内部存在了6年之久，算是 Node.js 国内第一批就诞生的框架，算算历史比 Egg 还要悠久呢。

**Comment by Lellansin** [comment]
知乎味十足的问题。那么按照惯例，应该先问是不是，再问为什么。

**Comment by TEsTsLA** [comment]
@czy88840616 都诞生了6年才发展成这样，反正我是不会用这么丑陋的框架的，你看隔壁的angular都7.0版本了，类springboot的node.js 后端框架，我只认nest.js。NEST.JS大法 吼！！！ [Nest.js](https://docs.nestjs.com/)

**Comment by czy88840616** [comment]
没意义的 issue。
