### ISSUE TITLE
提议: controller 修饰的装饰器可以修改为 Singleton 

### ISSUE THREAD

**Issue by zhangwinning** [midwayjs/midway#1060]
对 controller 装饰器修饰的类 scope 只能是 request 级别的还是有些疑问。看到这里把 @controller 的 scope 默认修改为 request。

https://github.com/midwayjs/midway/blob/10d2e7fd6a1246a9ae400d5e564685afdb4e4d6c/packages/decorator/src/web/controller.ts#L36

但是如果按照以下写法，其实还是可以把 @Controller 变成 singleton 的(遵照 decorator 的加载顺序)，并且也可以获取的相应的请求参数。
```
@Scope(ScopeEnum.Singleton)
@Controller("/")
export class Index {
  value1 = 0
。。。
```
另外记得 spring 和 nest.js 都对 controller 有过 singleton，单例模式对性能应该是提高很多的，因此为了性能考虑，这里可否修改为以下呢

```
export function Controller(
  prefix = '/',
  routerOptions: {
    sensitive?: boolean;
    middleware?: MiddlewareParamArray;
    description?: string;
    tagName?: string;
  } = { middleware: [], sensitive: true }
): ClassDecorator {
  return (target: any) => {
    saveModule(CONTROLLER_KEY, target);
    if (prefix)
      saveClassMetadata(
        CONTROLLER_KEY,
        {
          prefix,
          routerOptions,
        } as ControllerOption,
        target
      );
    if (装饰器scope不存在) {
      Scope(ScopeEnum.Request)(target);
    }
  };
}
```

**Comment by czy88840616** [comment]
这里变成请求作用域而不是单例是有原因的，在很多场景下，用户会习惯于从上下文ctx拿数据，这就意味着代码会和 ctx 绑定（不管是 controller还是 service），如果单例，那么用户必须要手动透传 ctx 才行，从代码结构，使用习惯（inject ctx），或者是测试和模拟都不是一个最佳的选择。

其次，ctx 是 Node.js 应用监控现阶段比较成熟的 tracing 数据存储处（否则就得使用 async hooks 等更耗性能的方式），没有他，整个 Node.js 没法保证链路的稳定性。

如果 controller 变成 singleton，那么在 midway 体系下，其后面所有的代码都会被缓存（当成单例），会出现很多不可预知的问题。

综合考虑，虽然单例可以提升性能，但是我们建议只在更底层，或者在明确需要使用的场景（明确是单例），而不是纯粹为了性能来考虑。

所以我们更倾向于代码统一（默认请求作用域），也不给用户增加额外的理解负担。
