### ISSUE TITLE
能否提供2.0的sequelize-typescript组件或者例子

### ISSUE THREAD

**Issue by mkanako** [midwayjs/midway#1061]
如题

**Comment by mkanako** [comment]
项目从egg.js换成midway,原本用的是sequelize，结果这边没啥支持，例子都没有 [裂开]

**Comment by czy88840616** [comment]
https://github.com/midwayjs/midway-examples/tree/master/v2/demo-sequelize-typescript

**Comment by mkanako** [comment]
感谢连夜添加，我也在摸索中，看了例子，那个模型好像没有用到依赖注入那些

我自己摸索到的
```
import { Model, Table, Column, HasMany}  from 'sequelize-typescript';
import { providerWrapper } from '@midwayjs/core'
import { Post } from './post';

export const factory = () => User

providerWrapper([
  {
    id: 'UserModel',
    provider: factory,
  },
])

@Table
export class User extends Model {

  @Column name!: string;
  @HasMany(() => Post) posts: Post[];

}

```

相比有官方组件支持的TypeORM麻烦了点

**Comment by czy88840616** [comment]
是想在 Model 里写方法和逻辑么?

**Comment by mkanako** [comment]
目前也没想这样，不过以后也许需要

现在我只是在照着TypeORM的套路学着来，把模型加载进容器，然后在service注入模型这样用而已

**Comment by czy88840616** [comment]
我看了下 sequelize 和typeorm稍微有点不同，typeorm 是用实例注册，所以可以将 ioc 创出来的实例再添加到 typeorm 逻辑中，sequelize 是类注册，方法是静态的，这就不太一样的了。

**Comment by mkanako** [comment]
好的，感谢指点！
