### ISSUE TITLE
@Get等装饰器无法被继承使用

### ISSUE THREAD

**Issue by fclefang** [midwayjs/midway#1062]
您好：
基于最新版的midway框架搭建的后端工程实现了BaseController：
`@Provide()
export default abstract class baseController<T extends BaseEntity> {
    @Inject() ctx: IMidwayWebContext;
    @Inject() baseService: BaseService<T>;

    @Get('/get')
    async get(@Query() id: string) {
        const result = await this.baseService.findOne(id);
        this.success(result);
    }
}`

另外定义了UserController继承BaseController：
@Provide()
@Controller('/user')
export class UserController extends BaseController<XXXEntity> {
    @Inject() userService: UserService;
}

这里我期望能够继承BaseController提供/user/get接口，但是本地测试并不行，所以目前还不能支持@Get这一类装饰器的继承么？如果不支持，后续会支持解决这个问题么？

**Comment by czy88840616** [comment]
方法装饰器不支持继承，会出现歧义，目前只支持属性继承。

**Comment by waitingsong** [comment]
baseController  基类避免使用  `@Provide()` 装饰器吧
