### ISSUE TITLE
Serverless 中，云函数之间如何互相调用？

### ISSUE THREAD

**Issue by mneumi** [midwayjs/midway#1064]
我第一次接触 Serverless，看了 Midway 文档中关于 Serverless 那一部分的内容。

文档中好像没有讲到云函数之间如何相互调用？（也有可能是我没看懂）

比如有云函数 A 和 B，A 应该如何去调用 B，并获得相应的返回值？

谢谢！

**Comment by mneumi** [comment]
可能需要通过消息队列之类的方式实现？

**Comment by czy88840616** [comment]
跨函数调用其实是由各个平台的sdk来做的，比如阿里云有fc2模块来做，腾讯云我不太了解。

**Comment by mneumi** [comment]
我看了下腾讯云的 SDK 文档，也有类似的功能。Midway 以后会考虑集成这种功能吗？

**Comment by czy88840616** [comment]
现阶段应该不会集成，平台测的功能基本是平台测在维护，封装他们的 sdk 或者重写会增加非常多的维护成本，如果直接引入这和用户自己调用没有本质的区别。

另外，平台容器中会默认埋入这些 SDK，如果框架去封装会无法享受这部分缓存，所以这部分功能目前来看还是业务自己引入并使用就好。

**Comment by mneumi** [comment]
好的，谢谢！
