### ISSUE TITLE
Task 的一些问题

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#1065]
后续迭代的能力

- 1、execute 拼写错误
- 2、清理旧的定时器
- 3、调度的日志

**Comment by renaesop** [comment]
> 后续迭代的能力
> 
> * 1、execute 拼写错误
> * 2、清理旧的定时器
> * 3、调度的日志

试了一下bull带的那几个ui，还是可以用的，建议增加一下日志自动清理功能，比如最多保存一万条。否则redis容易撑爆

**Comment by liuwensa** [comment]
``

> > 后续迭代的能力
> > 
> > * 1、execute 拼写错误
> > * 2、清理旧的定时器
> > * 3、调度的日志
> 
> 试了一下bull带的那几个ui，还是可以用的，建议增加一下日志自动清理功能，比如最多保存一万条。否则redis容易撑爆

`defaultJobOptions: {
    removeOnComplete: true,
    removeOnFail: true,
  },`  可以设置，配置选项就是bull的配置

**Comment by renaesop** [comment]
> ``
> 
> > > 后续迭代的能力
> > > 
> > > * 1、execute 拼写错误
> > > * 2、清理旧的定时器
> > > * 3、调度的日志
> > 
> > 
> > 试了一下bull带的那几个ui，还是可以用的，建议增加一下日志自动清理功能，比如最多保存一万条。否则redis容易撑爆
> 
> `defaultJobOptions: { removeOnComplete: true, removeOnFail: true, },` 可以设置，配置选项就是bull的配置
嗯，的确是可以手工配置，试了也可以。要是“开箱即用”—默认配置就有最优的配置就好了

**Comment by mkanako** [comment]
还有个小问题
`this.queueService.execute(HelloTask, params, {delay: 3000})`

这第三个参数应该是可选才对，现在ts不传第三个会报错

**Comment by stone-jin** [comment]
@mkanako #1090 这个版本里面给加上了，最近发布。
@renaesop ui的结合，我试了一下bull-board，里面原生是express的。后面会发一个component：task-ui做类似的功能。
@liuwensa 想咨询一下，就是数据清理这块的建议，这块后续建议大家比如怎么操作比较好？

**Comment by gogogo1024** [comment]
已经完成的任务从redis删除，删除前先写log日志到本地。
