### ISSUE TITLE
middleware 是否可以获取 egg-session-redis egg-redis 挂载到 app上的 redis 对象?

### ISSUE THREAD

**Issue by jsbay** [midwayjs/midway#1073]
我通过 `egg-session-redis`, `egg-redis` 将用户信息存储在 `redis` 中, 现在我打算自己实现一个 egg [renew](https://eggjs.org/zh-cn/core/cookie-and-session.html#session-%E5%AE%9E%E8%B7%B5) 类似的操作逻辑,

在 `middleware` 中对 `redis` 中存储的数据进行操作和判断, 但是我发现貌似 `middleware` 中无法获取到 挂载到 `app` 的上 `redis` 对象.

所以 请问一下 `middleware` 可以获取 `egg-session-redis` `egg-redis` 挂载到 app上的 redis 对象吗?

**Comment by czy88840616** [comment]
this.ctx.app.redis 么

**Comment by jsbay** [comment]
> this.ctx.app.redis 么

是的

**Comment by jsbay** [comment]
本意是打算 通过this.ctx.app.redis.get(key), 查看 数据的过期时间, 然后进行简单判断后决定是否更新数据的过期时间
