### ISSUE TITLE
同为TS的node框架与nest相比 有什么优劣呢？

### ISSUE THREAD

**Issue by ShaofeiZi** [midwayjs/midway#108]
没有恶意，纯粹咨询下。
[nest](https://github.com/nestjs/nest)

**Comment by zuohuadong** [comment]
配ioc比nest方便，可以直接自动扫描。
midway 目前生态还没健全。
nest.js 好处是跟angular 比较“兼容” 。看 nest.js 6 咋样吧

**Comment by czy88840616** [comment]
其实egg的生态现在就是我们的生态啦。

**Comment by zuohuadong** [comment]
> 其实egg的生态现在就是我们的生态啦。

grpc 支持， graphql 支持，typeorm ....
缓存...

**Comment by czy88840616** [comment]
目前我们的设想是egg的插件体系都能用，让从js过渡的用户能比较熟悉，然后在ts层面如果觉得不好用，就用装饰器慢慢包装，替代，变得更加简单和好用。

**Comment by ShaofeiZi** [comment]
@zuohuadong  nest.js 好处是跟angular 比较“兼容”  是什么意思？
设计的理念上么？

**Comment by zuohuadong** [comment]
> @zuohuadong nest.js 好处是跟angular 比较“兼容” 是什么意思？
> 设计的理念上么？

装饰器名字，以及很多方面都基本一致。 基本上学会 nest.js 就差不多学会 angular 了

**Comment by zuohuadong** [comment]
> 是说 nest 本身就是自家出的，比较方便统一或者兼容？
1. 生态方面：nest.js 目前下载量已经达到  koa 的四分之一了，大有超越 koa 成为node.js 第二大框架之势，而midway在国外的认同程度肯定不同以nest 。
2. 底层框架方面，nest 支持express 或者 fastify 作为底层框架，换句话说，实际上稍加修改就可以把 egg 作为底层框架来使用，如果需要插件就选express，需要性能就选fastify，再造轮子的意义不大。

**Comment by zuohuadong** [comment]
> 是说 nest 本身就是自家出的，比较方便统一或者兼容？

1. 生态方面：nest.js 目前下载量已经达到  koa 的四分之一了，大有超越 koa 成为node.js 第二大框架之势，而midway在国外的认同程度肯定不同以nest 。
2. 底层框架方面，nest 支持express 或者 fastify 作为底层框架，换句话说，实际上稍加修改就可以把 egg 作为底层框架来使用，如果需要插件就选express，需要性能就选fastify，再造轮子的意义不大。

**Comment by i5ting** [comment]
1）nest和koa不具有可比较性。偏应用的框架和内核级别的框架不合适。 下载量和star一样，是参考依据，但也不是一定能说明什么
2）egg自身就是一个很好的生态，为什么要去兼容nest呢？从社区角度讲，百花争放是好事，更富有创造性。
3）midway是新发布没多久的框架，基于Egg之上，对ts有更好的支持，这就够了。定位明确，随着ts全面落地，必有一席之地。

**Comment by g770728y** [comment]
赞同. nest.js 确实比较看好, 但写小项目感觉太重了. midway 更轻量些. 各有应用场景吧.
