### ISSUE TITLE
@midwayjs/cli有bug?

### ISSUE THREAD

**Issue by mkanako** [midwayjs/midway#1084]
CLI - v1.2.69（2021-06-01）
• 支持 ts path alias  #103
这个版本ok

然后CLI - v1.2.70这个版本ts path alias就不行了

翻看源码
https://github.com/midwayjs/cli/blob/2debe5ade730261402d308ebc43a837c0a1db8f3/packages/cli-plugin-dev/src/index.ts#L316-L335

```
if (tsconfigJson?.compilerOptions?.module?.toLowerCase() === 'commonjs') {     
 return;    
}
```

commonjs就直接return？？导致后面this.tsconfigJson 啥也没有，最终ts path alias不行了

**Comment by waitingsong** [comment]
只处理ts类型？
