### ISSUE TITLE
Plans about english website and documents?

### ISSUE THREAD

**Issue by Hazealign** [midwayjs/midway#109]
Thanks for nice project. Is there any plans about provide english website and documents? It'll be better for non-Chinese developers. (And maybe somebody can translate it to another language too. 😄)

**Comment by czy88840616** [comment]
We will launch English version of the document as soon as possible. 💖

**Comment by Lellansin** [comment]
We just add the  readme & quick guide of document ([link](https://midwayjs.org/midway/en/)). Welcome to feedback if there is something confused.

**Comment by Hazealign** [comment]
We can close this issue. Thanks for nice documents! :+1:
