### ISSUE TITLE
getCurrentMainApp函数build出来后运行不正常

### ISSUE THREAD

**Issue by mkanako** [midwayjs/midway#1094]
代码在开发状态下是ok的，但是build出来后运行npm run start就不正常了
```
2021-06-12 14:30:02,186 ERROR 55 TypeError: Cannot read property 'getApplication' of undefined
    at Object.getCurrentMainApp (/workspace/node_modules/@midwayjs/core/dist/util/contextUtil.js:13:45)
    at Object.getApp (/workspace/dist/utils/index.js:22:19)
```

翻了源码发现问题出在这https://github.com/midwayjs/midway/blob/3c87f9533952960fef97de1b9bfe3e1c7d29aa98/packages/core/src/util/contextUtil.ts#L16
`global['MIDWAY_MAIN_FRAMEWORK']`
这个调用在开发环境是正常，build之后运行是undefined

怀疑是不是global在多进程环境下不能共享的原因啊

node版本是16

**Comment by czy88840616** [comment]
1、多进程本身就不共享，每个进程的global对象是独立的
2、只有使用bootstrap启动才有这个机制，egg-scripts启动是没有的（文档里有写）

**Comment by mkanako** [comment]
好吧，那请教下，现在我/src/utils.ts里面好多的函数都是`const app=getCurrentMainApp()`然后从app上面拿东西，现在可咋办好

**Comment by czy88840616** [comment]
util应该是纯方法比较好吧，尽可能都是和app解耦的，通过参数传递

**Comment by mkanako** [comment]
@czy88840616 好吧想来也只能这样。开发没问题，上线全面奔溃，惨啊😂

**Comment by czy88840616** [comment]
或者pm2 走bootstrap咯

**Comment by mkanako** [comment]
> 或者在configration 里往global自己塞一下

 这个办法相当不错啊，稍微改下代码就ok了，太感谢了！！😭

@czy88840616

**Comment by ltc007** [comment]
我塞了之后 还不行，为什么
