### ISSUE TITLE
Swagger问题：Body参数的示例不能显示，在swagger-ui/index.html上面显示为空对象

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#1096]
![image](https://user-images.githubusercontent.com/35318575/122020610-7fd1bc80-cdf7-11eb-9a4c-d349ea672af8.png)
![image](https://user-images.githubusercontent.com/35318575/122020829-af80c480-cdf7-11eb-9ab3-a9f36ce7dadc.png)

**Comment by gogogo1024** [comment]
export class ProjScheDTO {
  @Rule(RuleType.number())
  id: number;
}
@Body(ALL) pro: ProjScheDTO
这样才会有吧。。。

**Comment by mowatermelon** [comment]
在 DTO 中写就行 可以参考我写的示例    https://github.com/mowatermelon/mwegg
