### ISSUE TITLE
刚入门，post出错，啥问题?

### ISSUE THREAD

**Issue by StiffFy** [midwayjs/midway#1099]
![a8ab7a18f74543cef2827cd5a331b3da](https://user-images.githubusercontent.com/10766864/122496792-eab10c80-d01e-11eb-9f29-0d09bdf6f40e.jpg)

**Comment by czy88840616** [comment]
太笼统了，详细点，用了什么模式，框架，代码

**Comment by danielsss** [comment]
> 太笼统了，详细点，用了什么模式，框架，代码

The Q makes brain circuits to knot. :D

**Comment by StiffFy** [comment]
按文档新建的项目，加了个post而已
![6C329778-C9EA-48cb-ADBF-5376EAD23116](https://user-images.githubusercontent.com/10766864/122498298-73c94300-d021-11eb-8288-cd98b66ce181.png)
