### ISSUE TITLE
关于 cli 的 mw --tsconfig 的bug

### ISSUE THREAD

**Issue by SOVLOOKUP** [midwayjs/midway#1101]
https://github.com/midwayjs/cli/blob/master/packages/cli-plugin-build/src/index.ts#L237

```
tsConfigResult = JSON.parse(tsConfig);
```

根据提示

`  --tsConfig     tsConfig json file path`

这里传入的应当是 tsConfig 的 json 字符串 

但实际上这里传入的是命令行中的 filepath，导致在指定 --tsconfig 编译时load tsconfig错误

本来想提交[PR](https://github.com/sovlookup/cli/blob/master/packages/cli-plugin-build/src/index.ts#L237)，但是在 [test](https://github.com/SOVLOOKUP/cli/blob/master/packages/cli-plugin-build/test/build.test.ts#L101) 中我看到中传入的又是字符串化的json，这让我有些迷惑

**Comment by echosoar** [comment]
option的提示内容写得有问题，目前的运行情况是只支持 json string，而不支持 json file path。
在下一个cli版本会修复此问题，使tsConfig参数既支持json string，也支持 json file ptah
