### ISSUE TITLE
希望增强下 cache 组件

### ISSUE THREAD

**Issue by mkanako** [midwayjs/midway#1103]
get方法需要泛型支持，如下
`let result = await this.cache.get<string>('name');`

set方法现在value只能传string,需要传其他例如number之类的就不行了

https://github.com/midwayjs/midway/blob/844b9383dc3b162d27f9bd02ba999ad31371c36b/packages/cache/src/service/cache.ts#L34

**Comment by stone-jin** [comment]
嗯，收到，我支持一下
