### ISSUE TITLE
关于方法拦截器（切面）的使用有点不合理

### ISSUE THREAD

**Issue by lyklll** [midwayjs/midway#1105]
切面方法的使用感觉有点不合理，现在是在切面方法中配置哪些函数会用到，相当于我每新增一个函数就得回去修改切面的作用范围；
如果改成是我写好函数后，需要用到哪个切面就用哪个装饰器不是更方便吗？

**Comment by czy88840616** [comment]
切面其实不是给普通场景用的，最初是为了不侵入现有的代码（组件）而设计的，校验拦截等能力后续会出独立的相似能力，切面会弱化。

**Comment by lyklll** [comment]
期待了
