### ISSUE TITLE
@Query 中参数的类型不管设置啥，得到的都是string

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#1106]
```

@Get("/start)
async startWithLevel(@Query() level: number, @Query() restart: boolean) {
...
}
```
调用 /start?level=1&restart=false 在方法中获得的level和restart都是string类型？
why？

**Comment by czy88840616** [comment]
因为 http 拿到的都是 string，这个层面是无法得知类型的。

**Comment by xmsz** [comment]
这个确实很蛋疼 例如写了number 编辑器虽然通过了 但是代码里还是string 相当于形同虚设

**Comment by Thetiso** [comment]
sad。 老老实实把@validate用起来
