### ISSUE TITLE
前后端一体化项目中，前端如何读取config

### ISSUE THREAD

**Issue by lide14** [midwayjs/midway#1107]
如题，前后端一体化项目中，前端如何读取config？
我试过@Config以及hooks的userConfig，都会报错，如何在前端读取自定义的config
谢谢

**Comment by Lxxyx** [comment]
> 如题，前后端一体化项目中，前端如何读取config？
> 我试过@config以及hooks的userConfig，都会报错，如何在前端读取自定义的config
> 谢谢

前后端在运行时是隔离的。这里推荐你写一个接口来返回后端的 config。
