### ISSUE TITLE
[Question]有没有办法加快`Install layers`这步

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1110]
背景
- 执行命令

然后这步大概要卡个5分钟左右
```
Install layers
```

npm: 使用的yarn的源
网络环境没问题

需求
- 有没有办法加快这步，每次deploy的时候已经很久了，这步还要卡个5分钟

**Comment by czy88840616** [comment]
提前加到依赖里？

**Comment by xmsz** [comment]
> 提前加到依赖里？

能解决就行 layers对应的是哪个依赖

**Comment by xmsz** [comment]
测试

- 普通情况：2分钟
- 将@midwayjs/static-layer放在devDep里：2分钟（说明没有效果）
- --npm=yarn 失败因为无法执行`yarn install` 
- --npm=cnpm 5s

当然比较奇怪的是我的npm本身源地址
```
* yarn ------- https://registry.yarnpkg.com/
```
理论上应该跟不会那么慢

不过好在能解决就行
