### ISSUE TITLE
如何自动开启或配置`sls日志服务 `

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1117]
背景
- 函数计算
- 需要用到sls日志服务
- 现在每次npm run deploy就会导致sls关掉，所以手动在后台开启

需求
- 如何自动开启sls日志服务
- 如果不能自动开启，要如何配置才能启用

**Comment by czy88840616** [comment]
https://www.yuque.com/midwayjs/midway_v2/serverless_yml#1a63ac23-1

**Comment by xmsz** [comment]
> https://www.yuque.com/midwayjs/midway_v2/serverless_yml#1a63ac23-1

ok 看到了

有没有'auto'的值可以自动开通

我现在操作流程（只需要一次）
- 登录后台开通日志服务
- 导出配置template.yml
- 配置本地f.yml
- 部署

**Comment by czy88840616** [comment]
直接 yml 里配置我理解应该就不需要再手动开了吧，这块是 fun 工具的功能，我们也没法控制。

**Comment by xmsz** [comment]
> 直接 yml 里配置我理解应该就不需要再手动开了吧，这块是 fun 工具的功能，我们也没法控制。

ok 明白了
