### ISSUE TITLE
this.applicationContext.getInformationService is not a function

### ISSUE THREAD

**Issue by liuwensa** [midwayjs/midway#1121]
* **Node Version**: 15.10.0
* **Egg Version**: 2.29.4
* **Plugin Name**: @midwayjs/web
* **Plugin Version**: 2.11.2
* **Platform**: Windows
* **Mini Showcase Repository**:

@midwayjs/web从到2.10.3升级到2.11.2，启动服务报错。

![image](https://user-images.githubusercontent.com/9549725/123747351-65164200-d8e5-11eb-8269-0627a7b19c59.png)

**Comment by czy88840616** [comment]
别只升一个包。。所有的要配合升级（ core）
