### ISSUE TITLE
bootstrap timeout

### ISSUE THREAD

**Issue by wgcairui** [midwayjs/midway#1132]
⠦ Midway Starting 
[ Midway ] start error: [midway]: bootstrap timeout
Error: [midway]: bootstrap timeout
    at Timeout._onTimeout (/Users/cairui/Code/midway/midwayuartserver/node_modules/_@midwayjs_mock@2.11.1@@midwayjs/mock/dist/utils.js:92:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

bootstrap.js
`const WebFramework = require('@midwayjs/koa').Framework;
const SocketFramework = require('@midwayjs/socketio').Framework
const WsFramework = require('@midwayjs/ws').Framework

const web = new WebFramework().configure({
  port: 9010,
});

const socket = new SocketFramework().configure({
  path: "/client",
  /* cors: {
    origin: "http://120.202.61.88:9010",
    methods: ["GET", "POST"]
  } */
})

const ws = new WsFramework().configure({
  path: '/wx',
})

const { Bootstrap } = require('@midwayjs/bootstrap');
Bootstrap
  .load(web)
  .load(socket)
  //.load(ws)
  .run();`

请问有修改超时的配置吗?

**Comment by czy88840616** [comment]
是啥启动这么慢？默认应该是 30s。。

**Comment by wgcairui** [comment]
问题找到了,有个单例的容器我加了autoload装饰器,init需要联网初始化,去掉autoload就好了,但之前也有这个情况,在我加载两个框架之后才有的,默认的可以修改吗?

**Comment by czy88840616** [comment]
我看了下，cli没有透传这个timeout参数，需要 @echosoar 增加。

**Comment by wgcairui** [comment]
嗯嗯,感谢解答..
