### ISSUE TITLE
前后端一体化项目中，能否以组件方式提供后端接口

### ISSUE THREAD

**Issue by lide14** [midwayjs/midway#1138]
请教下，我想以import 组件方式来提供后端接口，实现接口的动态化，这种能否实现，谢谢。

**Comment by waitingsong** [comment]
midway 的组件(componet) 可以包含 api 接口实现 (controller)

**Comment by lide14** [comment]
> midway 的组件(componet) 可以包含 api 接口实现 (controller)

感谢回复，写了controller之后前端该怎么写调用呀，之前一体化的时候可以直接import，用api的方式来写。

**Comment by czy88840616** [comment]
组件里的 hooks 路由是没法扫出来的，所以一体化的路由不支持放到组件里。

**Comment by lide14** [comment]
> 组件里的 hooks 路由（强依赖目录）是没法扫出来的，所以一体化的路由不支持放到组件里。

感谢大神，再接着刚才那位老师的回答问一下，一体化项目里支持controller吗？要是支持路由规则是怎样的，是否和单纯的后台项目一样

**Comment by czy88840616** [comment]
支持的，一体化中也可以单独写 controller。

**Comment by lide14** [comment]
> 支持的，一体化中也可以单独写 controller，路由就是传统的路由形式， @get 等装饰器用户自己指定的路由。

这个是不是也只能写在项目工程中，比如/src/apis，放在组件中可以吗？

**Comment by waitingsong** [comment]
可以把路由写到枚举中，然后 export 出去，这样大家都可以引用了

![2021-07-07_163707](https://user-images.githubusercontent.com/1763067/124728172-f028b500-df41-11eb-8327-cdbcf038e281.png)

![2021-07-07_163744](https://user-images.githubusercontent.com/1763067/124728206-f9198680-df41-11eb-958a-55024891d04e.png)

```ts
const url = `${host}${ServerAgent.base}/${ServerAgent.getInfo}`
```

**Comment by czy88840616** [comment]
@lide14 可以的，参考 https://github.com/czy88840616/midway-test-component

**Comment by lide14** [comment]
> 可以把路由写到枚举中，然后 export 出去，这样大家都可以引用了
> 
> ![2021-07-07_163707](https://user-images.githubusercontent.com/1763067/124728172-f028b500-df41-11eb-8327-cdbcf038e281.png)
> 
> ![2021-07-07_163744](https://user-images.githubusercontent.com/1763067/124728206-f9198680-df41-11eb-958a-55024891d04e.png)
> 
> 前端或者其它服务调用接口：
> 
> ```ts
> const url = `${host}${ServerAgent.base}/${ServerAgent.getInfo}`
> ```

多谢

**Comment by lide14** [comment]
> @lide14 可以的，参考 https://github.com/czy88840616/midway-test-component

谢谢
