### ISSUE TITLE
建议：一体化方向，与umi结合

### ISSUE THREAD

**Issue by 18583952605** [midwayjs/midway#1143]
刚用了下midway一体化，
函数式的接口调用确实很好，
这是最吸引我的一点，

但是，，
前端方面的一些基础设施，基本都没有，
比如：路由、菜单
不能开箱即用。。

建议脚手架里加个包含umi方案的版本
让用户能装完就用，不再配置其它的

**Comment by hzd1219809916** [comment]
自己配置啊，又不难

**Comment by 18583952605** [comment]
> 自己配置啊，又不难

midway用的vite，umi用的webpack，还是有点难的吧，我搞不了。。

**Comment by hzd1219809916** [comment]
那你也可以期待umi的vite版本

**Comment by 18583952605** [comment]
umi搞了hfsu   大概率是不会支持vite了吧

**Comment by Lxxyx** [comment]
umi 后续主流应该还是 Webpack，webpack 的支持我们一直是有的，但是前端框架太多了，每个接入方式也不一样，这部分只能是有需要的用户自己 maintain 一份对应框架的接入代码了
