### ISSUE TITLE
请问在service里面怎么取得之前egg的那个app属性？

### ISSUE THREAD

**Issue by qgqceo** [midwayjs/midway#115]
如题所示。谢谢。

**Comment by czy88840616** [comment]
为什么要取app？理论上service层不应该跟app有关联了来着...

**Comment by qgqceo** [comment]
> 为什么要取app？理论上service层不应该跟app有关联了来着...

我之前常在service层用app.curl()发起HTTP请求。

还是有其他更好的方案？

**Comment by qgqceo** [comment]
> ```ts
> @inject()
> ctx: any;
> 
> public async test(): Promise<any> {
>     // this.ctx 可以拿到ctx
>     this.ctx
> }
> ```

可以。非常感谢。

**Comment by ZQun** [comment]
```typescript
import { IConfigService } from '../../interface';

@config('xxx')
config: IConfigService; // 配置一下接口就可以提示了

```

**Comment by qgqceo** [comment]
> ```ts
> import { IConfigService } from '../../interface';
> 
> @config('xxx')
> config: IConfigService; // 配置一下接口就可以提示了
> ```

好的。多谢。

**Comment by czy88840616** [comment]
👍
目前因为是请求作用域的关系，所以可以直接从 ctx 种获取这个 curl 方法，如果真的需要 app，其实也可以 `ctx.app` ，但是就不太优雅了。

**Comment by czy88840616** [comment]
我本来以为可以直接用 `@plugin() httpclient` 这样拿到。。。但是我发现外部版我没做这个特性，🐶

**Comment by qgqceo** [comment]
> 我本来以为可以直接用 `@plugin() httpclient` 这样拿到。。。但是我发现外部版我没做这个特性…… 🐶

一开始我以为还可以像下面这样来拿：
```
@inject()
app
```

哈哈。谢谢。

**Comment by czy88840616** [comment]
用依赖注入就是为了解耦和隔离，service 除了本身自己，不应该和框架，koa 这些上层有过多的联系，这样才能保证单测弱耦合，可测可维护。

**Comment by qgqceo** [comment]
多谢多谢。
遇到问题还要多向你们这些大神请教。
