### ISSUE TITLE
@midwayjs/cli的生命周期after:dev:run不会执行

### ISSUE THREAD

**Issue by mkanako** [midwayjs/midway#1164]
package.json
```
"midway-integration": {
    "lifecycle": {
      "after:dev:run": "mycommand1",
      "before:dev:run": "mycommand2",
      "dev:run": "mycommand3"
    }
  }
```
before:dev:run和dev:run是ok的，但对我并没有什么用，我希望项目编译完成真正运行起来的时候执行一条命令，结果after:dev:run没反应啊

**Comment by mkanako** [comment]
而且还有个问题，我改了代码，npm run dev会重新编译运行，我预期before:dev:run，dev:run，after:dev:run是应该再执行一次的，但实际并没有

**Comment by echosoar** [comment]
给dev的生命周期添加after钩子是不会执行的，before钩子也只会执行一次。
dev的run生命周期是不会重复执行的，dev的执行表现就是启动一个server，并启动文件变化侦听，并且不会让进程退出。
