### ISSUE TITLE
是否考虑向 typeorm 捐赠？

### ISSUE THREAD

**Issue by zuohuadong** [midwayjs/midway#117]
typeorm 说它是node.js 里最好的orm 也不为过。
https://github.com/typeorm/typeorm

可惜 typeorm 太缺钱了，以至于 至今未能发布 1.0 ，甚至 0.3.x 没正式版。
官方现在发布issues 筹集资金。

typeorm 是个伟大的项目，是否可以考虑一起向 typeorm 捐赠？？

**Comment by czy88840616** [comment]
这个得内部沟通下，我们也只是同样在公司上班的团队，凭几个人可能没办法有过多的帮助。

**Comment by zuohuadong** [comment]
> 这个得内部沟通下，我们也只是同样在公司上班的团队，凭几个人可能没办法有过多的帮助。

感谢回复，midway 团队感觉比阿里其他的项目友善一些。

**Comment by Lellansin** [comment]
sequelize 比较多

**Comment by zuohuadong** [comment]
> sequelize

sequelize 跟 typeorm 比起来，还是有点太过于“玩具” 了，typeorm 如果真的 1.0 发布，感觉不会比 java 那堆 orm 差。

**Comment by czy88840616** [comment]
sequelize 应该还是一个传统函数式模型的工具，主要是比较习惯，用的人多，之前内部是有其他的的 orm 工具的，不过貌似维护不动就放着了。

**Comment by Lellansin** [comment]
@zuohuadong  有没有比较好的介绍文章之类的链接贴一下？

**Comment by i5ting** [comment]
我觉得还是close这个issue吧，开源最好不要做道德绑架，有心就默默奉献好了
