### ISSUE TITLE
Database链接问题

### ISSUE THREAD

**Issue by 160905** [midwayjs/midway#1184]
* **Node Version**: `v14.17.3`
* **Egg Version**: `^2.29.4`
* **Plugin Name**: `import * as orm from '@midwayjs/orm'`
* **Plugin Version**: `"@midwayjs/orm": "^2.11.6"`
* **Platform**: `web`
* **Mini Showcase Repository**:

[安装](https://www.midwayjs.org/doc/component/typeorm)文档接入，启动应用后一直报错。

<img width="1021" alt="截屏2021-07-27 下午9 58 50" src="https://user-images.githubusercontent.com/22002759/127167209-749f084d-6bc4-4f10-803e-1ab96d8d5d49.png">

**Comment by czy88840616** [comment]
这个是没有配置或者地址不对连接超时了吧
