### ISSUE TITLE
midway build之后是否可以删除node_modules

### ISSUE THREAD

**Issue by yyshengfan** [midwayjs/midway#1185]
"midway-bin-build": {
    "include": [
      "node_modules"
    ]
  }
  "build": "midway-bin build -c"

我自己建了一个权限的midway demo发现打包之后，删除了node_modules,项目就无法运行了，请问这个是我哪里做的不对吗？以上是我build的配置，下边是我运行的命令
node bootstrap.js

**Comment by waitingsong** [comment]
没有依赖，你运行啥呢？

**Comment by yyshengfan** [comment]
我的意思是打包之后不是这些都打包到dist里边了么，我删除node_modules怎么还会有影响呢？

**Comment by czy88840616** [comment]
node打包只是把src源码里的ts编译为 js，还是需要 node_modules，不像前端 webpack 是打成一个bundle

**Comment by yyshengfan** [comment]
哦哦，这样吗？想请问这边有没有类似的工具支持呢？我现在是想要把项目build之后在用PKG打包成应用程序的，发现打包之后删除了依赖就无法启动了，这才过来请教一下，希望大佬可以给点建议！

**Comment by czy88840616** [comment]
比如 ncc 工具，但是或多或少会有一些问题，当前的 node 项目不像前端，机制是不一样的。

**Comment by yyshengfan** [comment]
非常感谢大佬的解答👍
