### ISSUE TITLE
我用midway-init test 初始化了一个项目，用npm start 启动访问的时候报错。

### ISSUE THREAD

**Issue by arden** [midwayjs/midway#120]
我用midway-init test 初始化了一个项目，用npm start 启动访问的时候报错，Internal Server Error, real status: 500，但是我用npm run dev 启动访问的时候就是正常的，就是简单的初始化了一个项目而已，什么事情都没做。

**Comment by czy88840616** [comment]
start 走的是线上部署的模式，你需要先在本地或者服务器端构建 (执行 npm run build)

**Comment by zhump** [comment]
npm run build 会报错 
![image](https://user-images.githubusercontent.com/7962067/52914376-680acc00-3302-11e9-8e51-e65793b99db2.png)
