### ISSUE TITLE
bootstrap timeout

### ISSUE THREAD

**Issue by wgcairui** [midwayjs/midway#1214]
npm run dev每次都bootstrap timeout,但是build之后start就可以正常启动

⠴ Midway Starting 
[ Midway ] start error: [midway]: bootstrap timeout
Error: [midway]: bootstrap timeout
    at Timeout._onTimeout (/Users/cairui/Code/midway/midwayuartserver/node_modules/_@midwayjs_mock@2.12.3@@midwayjs/mock/dist/utils.js:92:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
2021-08-10 13:34:15,521 INFO 64682 [midway:socketIO] Socket.io server start success and attach to web server
2021-08-10 13:34:15,525 INFO 64682 [midway:bootstrap] current app started

**Comment by wgcairui** [comment]
我修改mock里面util中的超时时间*10就好了,不知道是哪里的问题,
await new Promise((resolve, reject) => {
            const timeoutHandler = setTimeout(() => {
                clearInterval(internalHandler);
                reject(new Error('[midway]: bootstrap timeout'));
            }, `options.bootstrapTimeout || 300 * 1000`);
            const internalHandler = setInterval(() => {
                if (global['MIDWAY_BOOTSTRAP_APP_READY'] === true) {
                    clearInterval(internalHandler);
                    clearTimeout(timeoutHandler);
                    resolve();
                }
            }, 200);
        });

**Comment by czy88840616** [comment]
30s 超时还不过你启动么。。。

**Comment by wgcairui** [comment]
就一个koa,一个socket.io,不知道运行在哪里卡住了
```
const WebFramework = require('@midwayjs/koa').Framework;
const SocketFramework = require('@midwayjs/socketio').Framework

const web = new WebFramework().configure({
  port: 9010,
  hostname: "0.0.0.0"
});

const socket = new SocketFramework().configure({
  path: "/client",
  /* cors: {
    origin: "http://120.202.61.88:9010",
    methods: ["GET", "POST"]
  } */
})


const { Bootstrap } = require('@midwayjs/bootstrap');
Bootstrap
  .load(web)
  .load(socket)
  .run();
```


```

import { Configuration, App } from '@midwayjs/decorator';
import { Application } from '@midwayjs/koa';
import * as body from 'koa-body';
import { ILifeCycle } from "@midwayjs/core"
import * as typegoose from "@midwayjs/typegoose"
import * as task from "@midwayjs/task"
import { join } from "path"

@Configuration({
  conflictCheck: true,
  imports: [
    typegoose,
    task
  ],
  importConfigs: [
    join(__dirname, "./config")
  ]
})
export class ContainerLifeCycle implements ILifeCycle {
  @App()
  app: Application;

  async onReady() {
    this.app.proxy = true
    this.app.use(body({
      multipart: true,
      formidable: {
        maxFileSize: (1024 * 1024 * 100) * 100
      }
    }));
  }
}
```

**Comment by czy88840616** [comment]
似乎就 typegoose 和 task 这两个组件，排除法看看？

**Comment by wgcairui** [comment]
好的,感谢解答哈
