### ISSUE TITLE
使用typegoose时，如何在model里拿到config

### ISSUE THREAD

**Issue by chenxiwei** [midwayjs/midway#1215]
我在使用mongoose-field-encryption插件时，想把secret密钥放在配置中，但是发现无法通过装饰器拿到config，
![image](https://user-images.githubusercontent.com/3908001/128829784-a631c95d-979e-4f1f-b67d-e250d49490c4.png)
请问如何拿到config,或者拿到app对象；

import { modelOptions, prop, plugin } from '@typegoose/typegoose';
// import { Config } from '@midwayjs/decorator';
import { fieldEncryption } from 'mongoose-field-encryption';

/**
 * 用于测试加解密
 * 针对password进行透明加密
 */
@plugin(fieldEncryption, {
  fields: ['password'],
  secret: '123456789',
})
@modelOptions({
  schemaOptions: { collection: 'test_encrypts' },
})
export class TestEncrypt {
  @prop()
  public name!: string;
  @prop()
  public account?: string;
  @prop()
  public password?: string;
}

**Comment by czy88840616** [comment]
看了一下，实体类不在 midway container的加载范围内，属于静态代码，可以使用静态 API 获取。https://www.yuque.com/midwayjs/midway_v2/container#BCfrP，如果是 egg-scripts 启动，需要额外把app自行挂载到全局 global。

**Comment by chenxiwei** [comment]
> 看了一下，实体类不在 midway container的加载范围内，属于静态代码，可以使用静态 API 获取。[https://www.yuque.com/midwayjs/midway_v2/container#BCfrP，如果是](https://www.yuque.com/midwayjs/midway_v2/container#BCfrP%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%98%AF) egg-scripts 启动，需要额外把app自行挂载到全局 global。

我在app.ts的didLoad中挂载global，然而在entity中仍取不到，我猜测是挂载的顺序问题，你可以说明下在什么地方挂载app吗（我是底层是eggjs，用egg-script启动）

**Comment by czy88840616** [comment]
configuration定位onReady中？

**Comment by chenxiwei** [comment]
> configuration定位onReady中？
![image](https://user-images.githubusercontent.com/3908001/128844283-1ee45d2c-9128-4954-88a0-3a6fedd19ea9.png)
![image](https://user-images.githubusercontent.com/3908001/128845078-d5c5c445-99a4-4f48-9962-e2477c78bf28.png)


import { modelOptions, prop, plugin } from '@typegoose/typegoose';
import { fieldEncryption } from 'mongoose-field-encryption';

console.log('entity load', global['app']);

/**
 * 用于测试加解密
 * 针对password进行透明加密
 */
@plugin(fieldEncryption, {
  fields: ['password'],
  secret: '123456789',
})
@modelOptions({
  schemaOptions: { collection: 'test_encrypts' },
})
export class TestEncrypt {
  @prop()
  public name!: string;
  @prop()
  public account?: string;
  @prop()
  public password?: string;
}

**Comment by chenxiwei** [comment]
> configuration定位onReady中？

我看了文档onReady应该是依赖全部装载后执行，然而这个地方应该是依赖加载前即需要设置

**Comment by czy88840616** [comment]
你这个entity其实是在require 的阶段，是非常前面的地方，所以不管在哪里设置都是不行的，这也是为什么装饰器无法使用配置的原因。

**Comment by chenxiwei** [comment]
> 你这个entity其实是在require 的阶段，是非常前面的地方，所以不管在哪里设置都是不行的，这也是为什么装饰器无法使用配置的原因。

我也发现这点了，感觉这么不太好；因为这种需求应该还是不是那么偶发的；
在egg里使用mongoose时，类似这样：
![image](https://user-images.githubusercontent.com/3908001/128954535-22956cf3-06bb-4fd9-8163-e93ddddf9b98.png)
是可以拿到config的；
midway能否在configuration里加一个生命周期，比如beforeLoad这样；
又或者这种需求是否在使用bootstrap启动时，使用before是否可以挂载设置；
（但是把app对象挂载到global上终究是种不好的做法，暂时也没想到有没有别的方式）

**Comment by czy88840616** [comment]
仔细看了一下，这里有两个地方的问题。

一是 typegoose 本身的装饰器写法，似乎并不适合动态的加载其他的东西（装饰器限制肯定是不能回调写法，这个是node本身的模块机制限制），我不确定的是否可以通过后面拿到 model 再动态加入的形式去扩展。我理解可以直接用原生的 mongoose 来做。

二是提前配置修改，这个问题不大，有方案。
