### ISSUE TITLE
如何写多个配置文件

### ISSUE THREAD

**Issue by hodgevk** [midwayjs/midway#122]
看文档是支持多环境配置文件的。我添加了一个单元测试配置文件，按egg的命名
config.unittest.ts
```javascript
export = (appInfo: any) => {
  const config: any = exports = {};

  config.sequelize = {
    host: 'localhost',
    port: '3306',
    user: 'root',
    password: '123456',
    database: 'test_unittest',
    dialect: 'mysql',
  };
  return config;
};
```
但是没有用，还是使用的default的配置，是不是我写法有问题？

**Comment by czy88840616** [comment]
这块和 egg 相同。

```ts
export = (appInfo: any) => {
  const config: any = {};

  config.sequelize = {
    host: 'localhost',
    port: '3306',
    user: 'root',
    password: '123456',
    database: 'test_unittest',
    dialect: 'mysql',
  };
  return config;
};
```

**Comment by hodgevk** [comment]
可是没有起作用啊

**Comment by czy88840616** [comment]
启动环境是 unitest 吗

**Comment by hodgevk** [comment]
使用默认的test，没有配置。因为以前使用egg时也不需要配置任何启动环境啊。当然，我也试着添加了NODE_ENV=test、NODE_ENV=unittest，也是没有用。

**Comment by czy88840616** [comment]
你是在用测试么，我用 `"test": "NODE_ENV=test midway-bin test --ts` 是可以的。

**Comment by hodgevk** [comment]
我这跑你的demo-unittest,也报错
```
 2) test/controller/home.test.ts
       should get untest test config:
     TypeError: Cannot read property 'a' of undefined
      at Context.it (test/controller/home.test.ts:10:28)
      [use `--full-trace` to display the full stack trace]
```

**Comment by czy88840616** [comment]
貌似是刚发的 v1.1 有点问题，我先切回 v1.0.5

**Comment by czy88840616** [comment]
我的锅。。。多导了个同名对象。

**Comment by czy88840616** [comment]
@hodgevk 应该没问题了，可以再试试

**Comment by hodgevk** [comment]
@czy88840616 更新到1.1.1后是可以跑通你写的demo了，但是我这使用的是sequelize-typescript，在app.ts中把app.config.sequelize传递给DB.initDB,但是这里获取到的app.config还是default里的，我调试了下发现app.config.evn是local而不是预期的unittest

**Comment by hodgevk** [comment]
@czy88840616 更新到1.1.1后，我在我工程中跑还是没有通过，后来发现在init生成的package.json中test命令先运行了npm run lint，删除这段后就可以了。不知道为啥。

**Comment by czy88840616** [comment]
@hodgevk 你那个应该是 tslint 的报错吧，这个规则可能需要调整下，我们会在尝试新的 [tslint](https://github.com/midwayjs/midway/tree/master/packages/tslint-midway-contrib) 规则之后，将脚手架统一修改。

**Comment by hodgevk** [comment]
@czy88840616 不知道什么原因，运行并没有报错，但是就是unittest配置不起作用。反正现在删除能用，我就先用着等脚手架更新后再改动吧。
