### ISSUE TITLE
新建faas类型应用引入puppeteer依赖，发布时会无限循环触发nas上传操作

### ISSUE THREAD

**Issue by DengXiaChen** [midwayjs/midway#1226]
* **Node Version**: 12.22.3
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:https://github.com/DengXiaChen/midway_puppeteer
![image](https://user-images.githubusercontent.com/13409926/129307106-7d716cd1-0dd4-42e8-8536-d716ac9d3fbe.png)

**Comment by DengXiaChen** [comment]
![Uploading image.png…]()

**Comment by DengXiaChen** [comment]
使用阿里云，发布时选择自动配置nas

**Comment by czy88840616** [comment]
这个记一下，比较麻烦，毕竟函数测的 nas 还是有点问题的，另外这块似乎是 fun 本身的功能。。。

**Comment by DengXiaChen** [comment]
嗯 目前手动配置nas并改写deploy命令暂时解决了 cross-env UDEV_NODE_ENV=production midway-bin package --skipZip -V && cd .serverless && fun install -d && fun nas sync && fun deploy -y

**Comment by GreatAuk** [comment]
目前这个 issue 依然存在

**Comment by GreatAuk** [comment]
> 嗯 目前手动配置nas并改写deploy命令暂时解决了 cross-env UDEV_NODE_ENV=production midway-bin package --skipZip -V && cd .serverless && fun install -d && fun nas sync && fun deploy -y

按这个命令可以部署成功。但是每次更新完代码，部署命令需要运行 10 几分钟，请问是否可以优化？

**Comment by czy88840616** [comment]
fun 工具不是我们维护，这个我们动不了。

**Comment by GreatAuk** [comment]
> fun 工具不是我们维护，这个我们动不了。现在阿里云那边已经不动 fun 工具了，只在推 serverless devs，感觉工具链依旧在变动，我们也很无奈。

谢谢，了解了

**Comment by jiaosl** [comment]
大佬，有没有使用 serverless devs 部署midway的例子

**Comment by czy88840616** [comment]
@jiaosl 执行 package 之后，进入 .serverless 目录使用 serverless devs 发布。
