### ISSUE TITLE
有新的vue3一体化模板吗

### ISSUE THREAD

**Issue by wgcairui** [midwayjs/midway#1229]
有新的vue3一体化模板吗,网上找到的都是去年过时的,文档使用的例子是react的,npm init midway脚手架也没有vue的选项

**Comment by wgcairui** [comment]
我使用react的模板修改了一下,可以使用vue3了,有需要的可以clone,[template链接](https://github.com/wgcairui/midway-hooks-vue3-template.git)

**Comment by czy88840616** [comment]
👍
