### ISSUE TITLE
grpc-helper 生成的类型文件为什么是 namespace 而不是 module 呢？

### ISSUE THREAD

**Issue by ishowman** [midwayjs/midway#1247]
比较好奇这个问题，是基于哪些因素考虑呢？

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
因为 module 更多但是和包名相关的，而 grpc 的 proto 文件生成的时候和包并不对应，而且和 java 的package 一样，可能会有 a.b.c.d 这样好几层，如果用 module 会非常的繁琐，而用 namespace 就不会有问题（虽然 ts 官方希望用 module 替代 namespace，但是在这种场景下显然用 namespace 更好）。

**Comment by ishowman** [comment]
> 因为 module 更多是和包名相关的，而 grpc 的 proto 文件生成的时候和包并不对应，而且和 java 的package 一样，可能会有 a.b.c.d 这样好几层，如果用 module 会非常的繁琐，而用 namespace 就不会有问题（虽然 ts 官方希望用 module 替代 namespace，但是在这种场景下显然用 namespace 更好）。

意思是 module 生成的代码对比 namespace 会多几层嵌套，导致可阅读性很差对吗？namespace 声明的是全局变量，开发者需要注意不重名这点有一点不友好。

**Comment by czy88840616** [comment]
走 declare module ，嵌套 declare module 就很怪了，不管从阅读和使用都不太对。从语义来说，这里其实并不是 ”模块“ 概念，更像是 “包" 或者 ”命名空间“的概念。

**Comment by ishowman** [comment]
目前我试用了一下，proto 文件中如果是这样声明 package `package tss.hall.liveroom.v1;  //协议包名`，也会生成多层嵌套的 nameSpace 难以阅读，这个可以通过增加配置项去支持自定义吗？例如指定 package 的分隔符？

**Comment by czy88840616** [comment]
印象里这个package好像grpc服务里要消费的（有点忘了）所以最好别随便改吧...
