### ISSUE TITLE
this.app.getApplicationContext().isAsync 返回 undefined

### ISSUE THREAD

**Issue by roy2an** [midwayjs/midway#1256]
* **Node Version**: 14.17.3
* **Egg Version**: 2.30.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Mac 10.15.7
* **Mini Showcase Repository**:

你好：
因为需要异步处理对象的初始化，所以有用到`getAsync`。但如果对象查询不到会直接报错。所以在`getAsync`之前，使用了`isAsync`来进行判断。

官网的说明是这个函数是返回boolean类型
```js
isAsync(identifier: ObjectIdentifier): boolean
```
实际情况下，如果查询的对象不存在，返回值是false。但如果返回的对象存在，返回值却可能是undefined

```js
import { Provide } from '@midwayjs/decorator';

@Provide()
export class UserService {
}

// 判断一个存在的Service
console.log(this.app.getApplicationContext().isAsync('userService')) // undefined
console.log(this.app.getApplicationContext().registry.hasDefinition('userService')) // true
console.log(await this.app.getApplicationContext().getAsync('userService')) // UserService { ctx: undefined, app: [Getter], model: [Getter] }

// 判断一个不存在的Service
console.log(this.app.getApplicationContext().isAsync('xxService')) // false
console.log(this.app.getApplicationContext().registry.hasDefinition('xxService')) // false
console.log(await this.app.getApplicationContext().getAsync('xxService')) // throw error
```

**Comment by czy88840616** [comment]
不直接用异步初始化么？https://www.yuque.com/midwayjs/midway_v2/container#5f36aa241ca1de03d125e4076bf0065b

**Comment by roy2an** [comment]
抱歉，没有说明使用场景。
我的场景是，某个component判断 应用中 是否引入了另一个 component，然后根据情况执行相应服务的功能。所以在Service内部异步初始化对我来说，作用不大。

**Comment by czy88840616** [comment]
我理解：

- 1、如果 component A 强依赖 component B，那么直接在 A 的 Configuration 应该直接 imports 里指定 B，这个时候肯定能拿到 B 的服务实例
- 2、如果 component A 弱依赖 component B，那么这个时候 A 是不知道 B 是否被业务引入，可以简单的通过标记来实现。

比如 

app.setAttr('BExist', true);
app.getAttr('BExist') => true

**Comment by roy2an** [comment]
`setAttr` 和 `getAttr` 的确可以解决我现在的问题了。
那 `isAsync` 是如何使用的？

**Comment by czy88840616** [comment]
isAsync是内部判断是否用getAsync还是get方法，我理解跟你的需求不是一回事。

**Comment by roy2an** [comment]
好的。非常感谢。

**Comment by roy2an** [comment]
抱歉，另外有个问题。
`app.getApplicationContext().registry.hasDefinition('xxService')`是否是我理解的那样，判断注入项是否存在。

**Comment by czy88840616** [comment]
hasDefinition 是用来判断定义是否存在，非对象或者实例已创建，一般也是内部使用，用户侧都是直接注入。

**Comment by roy2an** [comment]
谢谢。祝您工作愉快。
