### ISSUE TITLE
[rst ack] in midway

### ISSUE THREAD

**Issue by riskgod** [midwayjs/midway#1267]
Hey, midway server 和服务端连接的时候，服务端突然会爆 502 错误，这个是偶发性的，然后我去抓包 发现了问题，midway 服务 会突然发送一个 [RST ACK]的信息 给服务端。那么问题来了，midway 会在 请求过程中 等待一段时间后 突然去 close() 掉这个connection吗？我在搜谷歌的时候 看到了这个[回答](https://serverfault.com/questions/575650/why-would-a-client-send-a-rst-packet-as-reply-to-a-syn-ack)， 当然 是不是也会存在默认 http 请求 close()的情况？

**Comment by czy88840616** [comment]
框架侧应该不会主动做这个事情。
