### ISSUE TITLE
docker run时候会卡住

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#1276]
```
FROM node:14.5.0-slim
WORKDIR /home
COPY . .
# 如果各公司有自己的私有源，可以替换registry地址
RUN npm install --registry=https://registry.npm.taobao.org
RUN npm run build
# 如果端口更换，这边可以更新一下
EXPOSE 7001
CMD ["npm", "run", "online"]

```
用的是8G的配置，也试过换成cnpm， 但是总是在install结束之后卡住
```
...install结束
added 712 packages from 969 contributors in 16.284s
...按理这边应该打印开始RUN npm run build， 但并没有
```
镜像是node:14.5.0-slim  168M

**Comment by waitingsong** [comment]
试试在外部安装好依赖、编译完成，然后再COPY进去

**Comment by stone-jin** [comment]
那你先试试
```
FROM node:14 AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM node:12-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/bootstrap.js ./
COPY --from=build /app/package.json ./

RUN apk add --no-cache tzdata

ENV TZ="Asia/Shanghai"

RUN npm install --production 

# 如果端口更换，这边可以更新一下
EXPOSE 7001

CMD ["npm", "run", "start"]
```

**Comment by Thetiso** [comment]
> 试试在外部安装好依赖、编译完成，然后再COPY进去

外部安装依赖的话，编译过程会影响其他进程，一旦卡住，其他所有进程就都... 
哎 要是在其他测试服务器上的话，我也就这么干了，至少可以很快定位问题出在编译上还是镜像上。

**Comment by Thetiso** [comment]
> 那你先试试
> 
> ```
> FROM node:14 AS build
> 
> WORKDIR /app
> 
> COPY . .
> 
> RUN npm install
> 
> RUN npm run build
> 
> FROM node:12-alpine
> 
> WORKDIR /app
> 
> COPY --from=build /app/dist ./dist
> COPY --from=build /app/bootstrap.js ./
> COPY --from=build /app/package.json ./
> 
> RUN apk add --no-cache tzdata
> 
> ENV TZ="Asia/Shanghai"
> 
> RUN npm install --production 
> 
> # 如果端口更换，这边可以更新一下
> EXPOSE 7001
> 
> CMD ["npm", "run", "start"]
> ```

我的docker 版本不够 ，  as build直接失败了

**Comment by stone-jin** [comment]
那这种能成功吗？
```
FROM node:12

WORKDIR /app

ENV TZ="Asia/Shanghai"

COPY . .

# 如果各公司有自己的私有源，可以替换registry地址
RUN npm install --registry=https://registry.npm.taobao.org

RUN npm run build

# 如果端口更换，这边可以更新一下
EXPOSE 7001

CMD ["npm", "run", "online"]
```

**Comment by waitingsong** [comment]
> 
> 
> > 试试在外部安装好依赖、编译完成，然后再COPY进去
> 
> 外部安装依赖的话，编译过程会影响其他进程，一旦卡住，其他所有进程就都...
> 哎 要是在其他测试服务器上的话，我也就这么干了，至少可以很快定位问题出在编译上还是镜像上。

外部安装依赖的环境也是在 docker 容器中（ci流程），应该不会卡其它进程吧

**Comment by Thetiso** [comment]
> > > 试试在外部安装好依赖、编译完成，然后再COPY进去
> > 
> > 
> > 外部安装依赖的话，编译过程会影响其他进程，一旦卡住，其他所有进程就都...
> > 哎 要是在其他测试服务器上的话，我也就这么干了，至少可以很快定位问题出在编译上还是镜像上。
> 
> 外部安装依赖的环境也是在 docker 容器中（ci流程），应该不会卡其它进程吧

那应该是我没能准确理解您的意思。  我最终的怀疑落在了docker上  虽然不是很肯定

**Comment by Thetiso** [comment]
> 那这种能成功吗？
> 
> ```
> FROM node:12
> 
> WORKDIR /app
> 
> ENV TZ="Asia/Shanghai"
> 
> COPY . .
> 
> # 如果各公司有自己的私有源，可以替换registry地址
> RUN npm install --registry=https://registry.npm.taobao.org
> 
> RUN npm run build
> 
> # 如果端口更换，这边可以更新一下
> EXPOSE 7001
> 
> CMD ["npm", "run", "online"]
> ```

我最终解决的办法是把所有的run  合并到一起，然后就可以了 。
我尝试在npm install 之前随便输出，npm -v   node -v   echo ..之类的 发现都没问题，但是只要执行npm XXX 就会进入假死

**Comment by waitingsong** [comment]
可以监测下构建过程中内存占用是否存在异常。
我是在 Dockerfile 外部（也是在容器中）执行依赖安装，然后在 Dockerfile 中执行 COPY。 好处是可以利用 ci （比如gitlab）的文件缓存功能—— COPY 这一层镜像是可以缓存的，在重复构建出的镜像可以复用镜像层节省非常多空间的。
我公司的 midway 项目，node14.17 基础镜像 50M，构建后镜像 70-80MB，多出的这20-30M内里面还有接近20M空间是可以缓存的，就是说变化的就 dist 目录和 package.json ，每次构建基本就 2M 的那（一层镜像）容量变化。
