### ISSUE TITLE
关于使用dto来创建swagger

### ISSUE THREAD

**Issue by zerogu** [midwayjs/midway#1284]
定义dto文件
![image](https://user-images.githubusercontent.com/7019507/132704750-3d5a795f-d43b-4fc2-b803-44264d56d816.png)

在Controller的代码里
![image](https://user-images.githubusercontent.com/7019507/132705084-0c35a363-6894-4c36-8f7b-37b98e1c9ed5.png)

最后在生成的swagger里会变成
![image](https://user-images.githubusercontent.com/7019507/132705196-b8a1c116-c899-48f5-82bf-97f54007d966.png)

变成到一个common的键值对对象里
求问大佬,这符合预期么

**Comment by czy88840616** [comment]
试试新版本 1.2.0

**Comment by zerogu** [comment]
> 试试新版本 1.2.0

大佬,我试了下
    "@midwayjs/swagger": "^1.1.0",
    "swagger-ui-dist": "^4.0.0-beta.4",

访问/swagger-ui/json,会报错
(0 , decorator_1.getClassExtendedMetadata) is not a function
```
 at SwaggerMetaGenerator.generateSwaggerDefinition (/Users/zero/www/bili_live/node-mlive/node_modules/@midwayjs/swagger/dist/lib/generator.js:139:64)
```

查了下这个getClassExtendedMetadata,发现大佬并没有定义过...

**Comment by czy88840616** [comment]
decorator 包更新了的。

**Comment by zerogu** [comment]
> decorator 包更新了的。

把包整个更新了下
```
1、清理子包的 node_modules，比如（lerna clean --yes）
2、删除主包的 node_modules（比如 rm -rf node_modules)
3、删除 package-lock.json 或者 yarn.lock
4、重新安装依赖（ npm install && lerna bootstrap）
```

发现swagger页面在展示DTO参数时还是老样子....在一个键值对里

**Comment by czy88840616** [comment]
明天来看，今天实在太忙了。

**Comment by czy88840616** [comment]
我想了下好像不对。。。DTO 现在只支持 BODY 请求，query 请求的确是不支持的。

**Comment by zerogu** [comment]
> 我想了下好像不对。。。DTO 现在只支持 BODY 请求，query 请求的确是不支持的。

好!感谢大佬!现在也已经挺好使的了

**Comment by czy88840616** [comment]
一直想重构下，等3.x的功能差不多了就重写一个新的。
