### ISSUE TITLE
关于midway与nestjs的区别

### ISSUE THREAD

**Issue by liudonghua123** [midwayjs/midway#1290]
你好，我最近通过Rax了解到midway这个js后端框架

> Rax 小程序支持云端一体化应用
  >> 小程序一体化是 Midway.js 团队与 Rax 团队合作的产品，通过 Midway.js 对一体化的支持与 Rax 对小程序的支持，我们可以为小程序带去更好的研发体验。

readme的 [使用装饰器开发 Web 应用](https://github.com/midwayjs/midway#%E4%BD%BF%E7%94%A8%E8%A3%85%E9%A5%B0%E5%99%A8%E5%BC%80%E5%8F%91-web-%E5%BA%94%E7%94%A8) 部分和我之前使用过的 [NestJS](https://github.com/nestjs/nest) 类似，请问一下当时开发midway的初衷以及相比 [NestJS](https://github.com/nestjs/nest) 有什么区别，优缺点？

**Comment by czy88840616** [comment]
https://www.yuque.com/midwayjs/midway_v2/introduction#QJ5RS

**Comment by liudonghua123** [comment]
> https://www.yuque.com/midwayjs/midway_v2/introduction#QJ5RS
>
>> 为什么要有 Midway
>>
>> 社区上也有很多类似的框架，那为什么还需要 Midway ？
>>
>> 原因有三点
>>
>> 1、Midway 是阿里内部一直持续在研发的框架，之前 egg 是作为底层框架，需要有面向应用层面的框架来和集团场景对接
>> 2、全量使用 TypeScript 是未来一段时间的趋势，面向未来去迭代和研发是作为架构组创新的要求
>> 3、虽然社区已经有 nest 这样的框架，但是这些产品的维护、协作、修改都会到商业化产品的制约，也无法做到需求的快速迭代和安全性保障，整体的研发理念也和我们不同，为此，我们需要有一套自研的框架体系

嗯，了解 😄
