### ISSUE TITLE
一体化应用中，mongoose的配置，应该写在哪里

### ISSUE THREAD

**Issue by 18583952605** [midwayjs/midway#1292]

**Comment by 18583952605** [comment]
现在是写在 src/config/default.ts 里没有生效，即使注释掉它也能连上mongoDB，连的数据表是test

**Comment by czy88840616** [comment]
一体化的node根目录是src/apis，所以配置在 src/apis/config/*

**Comment by 18583952605** [comment]
不行呀，还是一样，没用到这个配置，这么写配置有问题吗 @czy88840616 

![image](https://user-images.githubusercontent.com/22405993/133366470-515e2fcf-580c-4216-a074-d82f4c90bb26.png)

**Comment by czy88840616** [comment]
configuration 里 importConfigs 里配了么

**Comment by 18583952605** [comment]
忘记被我注释了，，，现在加上好了，感谢大佬 @czy88840616
