### ISSUE TITLE
[midway:bootstrap] receive signal SIGTERM, closing

### ISSUE THREAD

**Issue by Qiulihui** [midwayjs/midway#1294]
k8s中服务使用NODE_ENV=production node bootstrap.js启动, 启动过程突然收到退出信号, 然后服务挂了, 这是为什么呢?
![image](https://user-images.githubusercontent.com/16460817/133557132-25a04406-b4d8-4859-8b52-47a102398517.png)

**Comment by Qiulihui** [comment]
已解决

**Comment by czy88840616** [comment]
是因为前台启动了？

**Comment by Qiulihui** [comment]
> 是因为前台启动了？

因为启动时连接数据库超时了.   k8s的健康检查发现规定时间内指定端口一直无法访问, 就close了. 
公司部署走k8s, 开始连接数据库用的是serviceName, 但是镜像里面没有支持serviseName的工具,后来改成指定ip连接就好了. 
指定ip的缺点时如果以后ip变化, 需要再修改代码, 不过这个是部署在测试环境的,所以目前可以接受ip.

**Comment by czy88840616** [comment]
哦，环境依赖。
