### ISSUE TITLE
@midwayjs/web中怎么配置才支持history单页应用模式

### ISSUE THREAD

**Issue by Elpmis007** [midwayjs/midway#1298]
在@midwayjs/web中使用了`egg-view-nunjucks`作为模板渲染，但是我不知道该怎么配置history的支持，因为刷新页面就404了，我该怎么做，怎么处理才能达到我想要的效果

* **Node Version**:12
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
单页是前端部分配置，node这边不涉及。
