### ISSUE TITLE
建议：单例模式允许注入请求态对象

### ISSUE THREAD

**Issue by Grapedge** [midwayjs/midway#1303]
## Why
- 单例模式可以复用实例，大部分场景下无需动态创建实例
- 请求实际上是调用控制器的某一方法，因此 ctx 在函数上注入可能更符合直觉（类似于 Nest 的 [Req 装饰器](https://docs.nestjs.com/controllers#request-object)）

## 代码
```ts
@Provide()
@Controller('/')
@Scope(ScopeEnum.Singleton)
export class AppController {
  @Get()
  async home(@EggContext() ctx: Context) {
    const { name } = ctx.query
    ctx.body = `Hello, ${name}`
  }
}
```

**Comment by czy88840616** [comment]
- 1、请求创建实例是和 async_hooks 等 ctx 透传方案性能权衡的结果
- 2、ctx 作为参数是函数式手动透传的方式，当下并没有限制，事实上这里方法的第一个参数就是 ctx，无需注入
