### ISSUE TITLE
框架扩展定义时 ts类型问题

### ISSUE THREAD

**Issue by a1235** [midwayjs/midway#1305]
* **Node Version**: 14.16.0
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我在src/app/extend/request.ts 文件新增了以下内容，编辑器中也有request相关的提示，但是运行项目时报错了，请问这个问题该怎么解决?
```
export default {
  get hello() {
    return 'hello world';
  },
};
```

![image](https://user-images.githubusercontent.com/29188013/134802245-f5b6a46e-1c56-477b-84ee-86b60b43c39e.png)
![image](https://user-images.githubusercontent.com/29188013/134802286-b91dfbda-7983-4841-82d9-d605f048acd0.png)
![image](https://user-images.githubusercontent.com/29188013/134802318-f895b826-e3e9-46aa-8e60-0c47de3d8b64.png)

**Comment by czy88840616** [comment]
https://www.yuque.com/midwayjs/midway_v2/eggjs#d64eeb5d63ec26fee8b070e11c2cac0e
