### ISSUE TITLE
想问一下，prisma2与midway2 怎么结合在一起使用，不知道有文档了吗

### ISSUE THREAD

**Issue by sinianzhiren** [midwayjs/midway#1314]
去年看直播发布2.0, 好像说下一个版本会考虑将两个结合起来，不知道现在进度如何，有没有对应的文章和案例，期待 @midwayjs/prisma 插件

**Comment by xmsz** [comment]
我现在有点不明白 如果prisma已经不支持go了，那用prisma的主要意义是什么？

**Comment by czy88840616** [comment]
prisma 其实不太需要包，咱们还是要理解即使不包插件，也是可以使用的（避免陷入没有插件就不会使用的情况哈）。
