### ISSUE TITLE
[问题] 如何在 midway 中使用 ts 的路径映射

### ISSUE THREAD

**Issue by atzcl** [midwayjs/midway#132]
使 `tsconfig.json` 定义的 `paths ` 路径别名生效，在 `ts-node` 是使用 `tsconfig-paths/register` 来识别的，但是在 `midway` 中应该如何实现呢

**Comment by czy88840616** [comment]
https://eggjs.org/zh-cn/tutorials/typescript.html#%E5%9C%A8-tsconfigjson-%E4%B8%AD%E9%85%8D%E7%BD%AE%E4%BA%86-paths-%E6%97%A0%E6%95%88

**Comment by atzcl** [comment]
@czy88840616 感谢~当时也看过这一篇文档，没注意到，疏忽了😂😂

**Comment by anthhub** [comment]
今天遇到了这个问题 感谢

**Comment by immafrady** [comment]
今天遇到了这个问题

在config/plugins.ts的顶部引入之后，并没有生效
