### ISSUE TITLE
error日志自定义格式化

### ISSUE THREAD

**Issue by liuxing95** [midwayjs/midway#1338]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

一般我们错误的日志都自动在 common-error 中写一份 但是在收集日志的希望 common-error的日志格式按照规定的格式来 能够进行正则匹配出来对应的字段 来收集日志  但是在https://www.yuque.com/midwayjs/midway_v2/logger#OYRgn 这个文档的时候 我是想通过 this.app.createLogger('error', ,...) 设置 printFormat 希望error 按照我自定义的格式来报错

**Comment by czy88840616** [comment]
3.x 已实现。
