### ISSUE TITLE
VSCODE如何进行调试

### ISSUE THREAD

**Issue by anthhub** [midwayjs/midway#135]

**Comment by anthhub** [comment]
运行 npm run debgger 有以下输出, 请问应该怎样进行断点调试呢?

Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.
0.0.1:9999/__ws_proxy__

**Comment by czy88840616** [comment]
直接使用 eggjs 的方案 https://eggjs.org/zh-cn/core/development.html#%E4%BD%BF%E7%94%A8-vscode-%E8%BF%9B%E8%A1%8C%E8%B0%83%E8%AF%95

**Comment by anthhub** [comment]
可以了 谢谢! 新年快乐!

**Comment by czy88840616** [comment]
新年快乐🎉

**Comment by jidanji** [comment]
**问问热无**
