### ISSUE TITLE
请教下 TaskLocal改怎么理解？

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#1354]
请教下 TaskLocal改怎么理解？
这里的Local是指开发环境的local吗？ 还是相对分布式Task来说，单机的应用使用TaskLocal?

**Comment by czy88840616** [comment]
单机单进程的定时任务

**Comment by Thetiso** [comment]
> 单机单进程的定时任务，我理解大部分分布式系统应该都不会使用它，少部分只有单机器（或者只跑一个进程的，测试场景）特殊需求会用。

OK  那我就可以理解为 **尽可能使用task**来写任务，考虑到后续服务拓展之类的场景，
**除非是非常肯定的只有单应用单进程**

**Comment by czy88840616** [comment]
是的 。TaskLocal 后面会拓展到单机执行（一个应用只执行一次），但是也是限制于单机器，在分布式场景也不适用。
