### ISSUE TITLE
官网页面微服务分类下有 grpc 和 consul 的介绍, 那有这两者结合的最佳实践吗?

### ISSUE THREAD

**Issue by crossz** [midwayjs/midway#1356]
如题, midway + grpc + consul, 是否有最佳实践的 demo?

如果没有 demo 或不推荐这种组合, 那么 @midwayjs/grpc, 和 @midwayjs/consul 哪个是未来日后维护的核心或重点 package 呢?

**Comment by czy88840616** [comment]
@midwayjs/grpc 是 grpc 的协议包扩展(server 和 client），consul 是分布式的服务发现，我理解如果要做分布式微服务，这两者需要同时配套使用。和 grpc 对应的 http/dubbo 等协议，和 consul 对应的应该是 nacos/zoomkeeper 等。

**Comment by crossz** [comment]
好的，那我来用这两个拼一个 demo 吧。
主要看到 @midwayjs/consul 感谢了网友推送，我担心这不是你们的重点方向，因为我看你们在做 nacos 的 sdk 了。。。所以，万一上了这一条船，日后你们弃了，我这边改起来麻烦。哈哈

**Comment by czy88840616** [comment]
nacos后面肯定会有的。另外concul模块是用户提供的，虽然我们没在用，但是我们的原则是合进来就会统一维护/发布，即使没有新需求也会更新基础的能力。

**Comment by crossz** [comment]
那什么时候nacos大概放出？我们可以再等等把nodejs这条线升级为微服务架构的。

**Comment by czy88840616** [comment]
包 nacos 很简单，只是我想把 nacos node sdk 升级用 ts 重写。。

**Comment by crossz** [comment]
好的，不急。等你，哈哈
