### ISSUE TITLE
3.x progress

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#1357]
## 3.x 目标

- 1、让项目可以 bundle 化，更符合 serverless 的轻量化
- 2、让注入写法更明确，清晰简单
- 3、中间件能力的自建和增强

## 阶段

- [x] development
- [x] 回归旧单测 - beta.1
- [x] 新功能单测，修复问题, beta2...n
- [x] 性能测试
- [x] 文档 ing
- [x] 正式发布

## 当前/计划版本

- [x] 3.x beta.1 
	- #1254 
- [x] 3.x beta.2 
	- #1366
- [x] 3.x beta3
	- #1367
- [x] 3.x beta4 
	- #1370 
	- #1371 
	- #1372
	- #1375
- [x] 3.x beta5
	- #1383 
	- #1384
- [x] 3.x beta6
	- #1387
- [x] 3.x beta7
	- #1388
	- #1389
	- #1395
- [x] 3.x beta8
	- #1343 
	- #1358
	- #1403
	- #1405
	- #1399
	- #1364
- [x] 3.x beta9
	- #1413 
- [x] 3.x beta10
	- #1409 
	- #1422 
	- #1427 
	- #1420 
	- #1426 
- [x] 3.x beta11
	- #1431 
- [x] 3.x beta12
	- #1444 
	- #1439 
	- #1438
	- #1440
- [x] 3.x beta13
	- #1465
	- #1477 
- [x] 3.x beta14
	- #1515
	- #1484
- [x] 3.x beta15
	- #1524
	- #1493
	- #1525
	- #1530 
	- #1531 
- [x] 3.x beta16
   - #1548 
   - #1532

## 新功能

- [x] 1、支持模块化打包（bundle）
- [x] 2、装饰器部分
	- [x] @Init, @Destory 装饰器继承
	- [x] @Plugin, @App, @Logger, @Config 装饰器继承
	- [x] 规范自定义装饰器
- [x] 3、请求参数基础类型转化
- [x] 4、自定义 Validate
- [x] 5、全新的过滤器
- [x] 6、全局的路由前缀
- [x] 7、全新的 swagger
- [x] 8、重新设计了框架（Framework）的概念，并提供组件化使用方式
	- [x] 框架通过组件形式引入
	- [x] 多重框架/组件的测试方式
- [x] 9、错误的规范化
- [x] 10、全新的生命周期
	- [x] 对象系列生命周期
	- [x] 服务启动生命周期
- [x] 11、全新的中间件设计
- [x] 12、单例调用请求作用域时需要用户显式声明可调
- [x] 13、组件包配置定义
- [x] 14、新增 @midwayjs/validate
- [ ] 15、提供通用的返回格式
- [x] 16、提供了 info 组件
	- [x] 考虑内置，路由，中间件等 
- [x] 17、提供了 i18n 组件
	- [x]  joi 错误汉化	
- [ ] 18、默认链路追踪方案
- [x] 19、upload
- [x] 20、koa/express 默认集成 session, bodyparser

### 通用

- 移除不再使用的 midway 和 midway-schedule 包，midway-schedule 旧版本依旧可用，但是不会再更新
- 使用 uuid 替代原有的字符串查找模块，提升模块查找性能和可靠性
- importsConfigs 不再支持相对路径
- 重构 Configuration 加载逻辑，使用模块加载机制加载
- 移除了不再使用的构造器注入的功能
- 移除 Configuration 上的 importObjects 功能
- Configuration 上提供了一套对象创建和销毁的生命周期 hook
- 重构 listModule, saveModule，使其和 decoratorManager 分离，和 container 容器绑定，不再需要缓存清理
- 新增 @midwayjs/validate 组件（原 validate )
- 新增 @midwayjs/info 组件

### @midwayjs/decorator

- 移除 rule 和 validate 装饰器（joi）
- 移除无用的  @Func @Handler @Async @Autoware @Priority 装饰器
- 移除构造器注入能力，该能力不再提供
- 移除 2.x 中废弃的 saveMethodDataToClass，attachMethodDataToClass，getMethodDataFromClass, listMethodDataFromClass, saveMethodMetadata, attachMethodMetadata, getMethodMetadata 方法
- 属性注入的元数据结构进行了调整
- saveClassMetadata 新增了一个参数，可以指定是否和原数据合并
- 提供了 createCustomPropertyDecorator 自定义属性装饰器的方式
- 增加 @Middlware 装饰器
- 一些顶层装饰器无需再次声明 @Provide()

### @midwayjs/core

- 移除通过字符串包名加载 component 的兼容代码
- 移除 containerLoader 的兼容代码
- 移除代理 decorator 包中的 listModule 等方法，两者包功能完全分开
- 移除原有组件 registerObject 会自动增加命名空间的逻辑
- BaseApplicationContext 和 MidwayContainer 进行了合并
- 移除 IMidwayCoreApplication 定义
- 移除 containerUtil 上的两个创建容器的方法
- 移除了 container 上的  getDebugLogger 方法
- 移除 container 上的下列方法
	- getConfigService(): IConfigService;
  	- getEnvironmentService(): IEnvironmentService;
  	- getInformationService(): IInformationService;
  	- setInformationService(service: IInformationService): void;
  	- getAspectService(): IAspectService;
  	- getCurrentEnv(): string;
- 提供了全新的 MidwayFrameworkService 类，用于加载组件中的框架，以及注入之前的 App/Logger/Config 等属性装饰器
- 提供了全新的 MidwayLifeCycleService 类，用于控制整个代码的生命周期
- 提供了全新的 MidwayDecoratorService 类，用于自定义装饰器的实现

### @midwayjs/faas

- 框架组件化
- 移除 faas 包代理小写装饰器的兼容代码
- 废弃 app.generateMiddleware 方法
- 增加中间件/错误处理支持

### @midwayjs/bootstrap

- 移除 beforeHandler，现在的异步配置加载已经能满足诉求
- 移除 load 方法，框架组件化加载后现在不再需要

### @midwayjs/mock

- 移除 egg-mock 的包加载和兼容
- 移除 bootstrap 的依赖，现在研发启动不再需要 bootstrap
- 移除 createBootstrap 方法

### @midwayjs/koa

- 框架组件化
- 增加中间件/错误处理支持
- 增加 koa 相关配置
- 移除 app.generateController 和 app.generateMiddleware 方法
- 增加全局前缀配置

### @midwayjs/express

- 框架组件化
- 增加中间件/错误处理支持
- 原 ctx 的值，变更为 request 对象
- 移除 app.generateController 和 app.generateMiddleware 方法
- 增加全局前缀配置

### @midwayjs/ws

- 框架组件化
- 增加中间件/错误处理支持

### @midwayjs/socketio

- 框架组件化
- 增加中间件/错误处理支持

### @midwayjs/grpc

- 框架组件化
- 增加中间件/错误处理支持
- 增加 grpcServer 相关配置

### @midwayjs/rabbitmq

- 框架组件化
- 增加中间件/错误处理支持

### @midwayjs/web

- 框架组件化
- 移除 prioritySortRouters（老 egg 路由信息生成）的兼容
- 增加中间件/错误处理支持
- 由于提供了默认日志配置的原因，无法兼容 egg logger 的情况，调整为只能使用 midway logger，只兼容 customLogger 的部分配置
- 使用 egg 相关的环境变量的目录调整，比如 EGG_LOG 和 EGG_HOME 可能会出现一些不可预知的问题，比如日志目录不正确
- 移除 app.generateController 方法
- 增加全局前缀配置

### @midwayjs/egg-layer

- 支持了 midway v3，使用了新的 bootstrap 方式来启动

### @midwayjs/task

- 配置的 key 从 taskConfig 改为 task

### @midwayjs/passport

- 简单重构了一下，代码更加精简

**Comment by luoxiao-xy** [comment]
@czy88840616  希望midway可以提供knex.js支持。大家可以选择用typeorm还是knex。orm基于模型对于复杂事务很难。而knex基于数据库表的，更容易处理事务，也更简单。

**Comment by abnerCrack** [comment]
@czy88840616 jwt相关的文档 demo补充下吧，我看了下3.0移除了jwt的package 并且 2.x版本jwt的package也没有发布,调用的时候失败了。

**Comment by czy88840616** [comment]
@abnerCrack 不是移除，是2.x还在改，确定了之后会同步到 3.x

**Comment by abnerCrack** [comment]
@czy88840616 赞，最近刚好一直在用7写点小东西，那我等发布吧。

**Comment by SuGod** [comment]
@czy88840616 `@Query` 注解 在`swagger`中无法设置默认值,例如:
```typescript
@Get('/getPage')
getPage(@Query('pageNumber') pageNumber:number = 1){
   console.log(pageNumber)    // NaN
}
```
1. 在`swagger`中不会设置默认值
2. 文档中也没有描述如何设置参数为必填
3. `eslint`也会提示可自动推导类型

**Comment by czy88840616** [comment]
@SuGod 
- 1、 = 1的默认值是运行时执行的默认值，swagger的默认值通过 @Api 系列装饰器的 example 字段，不是一回事
- 2、参数为必填，走的是校验逻辑，参考校验章节
- 3、eslint 规定，如果赋值是基本类型，number/string/boolean，无需指定 type

**Comment by czy88840616** [comment]
Release Now.
