### ISSUE TITLE
Midway.JS可以直接部署到OpenFaaS吗

### ISSUE THREAD

**Issue by challengingcheng** [midwayjs/midway#1360]
我们用K8S + OpenFaaS自己搭建了一个简单的Serverless平台，我们可以将Midway.JS创建出来的函数部署到OpenFaaS吗？

MidWay.JS 和 [Serverless Framework ](https://github.com/serverless)是不是类似的框架？  还是说 MidWay.JS 是在 Serverless Framework之上的？

**Comment by czy88840616** [comment]
我理解 serverless framework并非传统意义上的框架，更像是为了适配不同平台的 cli 工具，本身更多的是面向不同平台的部署能力。midway更偏向用户开发本身，组织用户代码，提供能力的传统框架。
