### ISSUE TITLE
单元测试报错

### ISSUE THREAD

**Issue by yinhaixiang** [midwayjs/midway#1361]
* **Node Version**: 16.13.0
* **Egg Version**: 2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我按照官网说明
npm init midway -- --type=web my_midway_app
npm install
然后运行单元测试api.test.ts或者home.test.ts
都会直接报错
![image](https://user-images.githubusercontent.com/10047441/141125386-bd0da8b4-fd2f-4c51-9db3-c8743aef1c46.png)

**Comment by czy88840616** [comment]
egg特殊，需要在 idea 调试的时候加上 `--require=ts-node/register` 
![image](https://user-images.githubusercontent.com/418820/141126682-600204d5-2558-4d1c-bdbc-3645bd26ad72.png)

**Comment by captainIT** [comment]
隐藏太深了

**Comment by czy88840616** [comment]
这个是egg内部的隐藏逻辑。。我已经踩了很多次坑了

**Comment by captainIT** [comment]
> 

我本来可以正常测试，但是加了plugin.ts 就不行了，
debug 看到不是js 直接返回了buffer，
   // if not js module, just return content buffer
      const extname = path.extname(filepath);
      if (extname && !Module._extensions[extname]) {
        return fs.readFileSync(filepath);
      }
在 idea 调试的时候加上 --require=ts-node/register 这个就管用了
Module._extensions[extname] 变成false了所以才管用了

是不是 用plugin的方式不对？

**Comment by captainIT** [comment]
Module._extensions  本来.js.json.node
在加了你说的参数后多了一个.ts
所以没问题了
