### ISSUE TITLE
NODE_ENV=production的情况下POST请求都返回403

### ISSUE THREAD

**Issue by soul0932** [midwayjs/midway#1362]
用的官方脚手架生成的项目。
在npm run dev的情况下可以http://127.0.0.1:7001/api/get_user请求到数据，用npm run start后get请求正常，post全部返回403

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/eggjs#%E9%BB%98%E8%AE%A4%E7%9A%84-csrf-%E9%94%99%E8%AF%AF
