### ISSUE TITLE
本地还是会存在这个问题，orm配置加载会默认加上name为‘0’，需要自己手动去修改掉这个name值，才不会出现下面的问题

### ISSUE THREAD

**Issue by CanDouDaShu** [midwayjs/midway#1363]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
什么问题。。。需要提供更多详细的内容。

**Comment by CanDouDaShu** [comment]
Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session. AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.

**Comment by czy88840616** [comment]
是没用 default 配置吧，自建了两个其他的连接？

**Comment by czy88840616** [comment]
这个应该是之前数据源错乱的问题了，新版本已经规避了这个问题。
