### ISSUE TITLE
如何修改默认ctx.logger的输出目录dir？

### ISSUE THREAD

**Issue by AodaZhang** [midwayjs/midway#1369]
我希望可修改默认的日志输出目录，发现文档上的示例只有@midway/egg的项目才能配置，而我的项目是基于@midway/koa搭建的，请问有什么好办法吗？http://www.midwayjs.org/docs/logger#%E5%85%BC%E5%AE%B9%E9%85%8D%E7%BD%AE

**Comment by czy88840616** [comment]
在启动的时候 bootstrap 中传递一个自定义 logger 即可，现阶段因为配置和 egg 有冲突暂时没做。下一版本 v3 可以直接通过配置进行简单的处理。

**Comment by AodaZhang** [comment]
非常感谢!
