### ISSUE TITLE
请问demo-plugin-egg-graphql这个demo要怎样才能运行graphql那个测试界面？

### ISSUE THREAD

**Issue by qgqceo** [midwayjs/midway#137]
文档里面没有提到这点。
我在浏览器中运行http://127.0.0.1:7001/graphql和http://127.0.0.1:7001/graphiql都是404 Not Found。

**Comment by czy88840616** [comment]
这个demo...当初好像就没解决，还留了个issue，原因是我们都对graphql不太熟🤦‍♂️

**Comment by qgqceo** [comment]
> 这个demo...当初好像就没解决，还留了个issue，原因是我们都对graphql不太熟🤦‍♂️

技术大大现在可以解决吗？

**Comment by czy88840616** [comment]
我先看下。。搞不定就找个了解 graphql 的同事。。

**Comment by czy88840616** [comment]
貌似给 demo 加了中间件就出来了。

![image](https://user-images.githubusercontent.com/418820/52545912-2bb50880-2df6-11e9-9ab9-249e5cc35547.png)

**Comment by czy88840616** [comment]
其他的就看 #29 吧。
