### ISSUE TITLE
表单验证错误需要提供默认的响应处理

### ISSUE THREAD

**Issue by ghostoy** [midwayjs/midway#1373]
* **Node Version**: 14
* **Egg Version**: 2.32.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Linux
* **Mini Showcase Repository**:

通过装饰器`@Validate()`产生的验证错误没有提供默认的错误处理（例如返回422和相应的错误内容），而是直接报了500错误。

现在暂时只能通过配置`config.x.ts`里的`onerror`来处理，这带来了几个问题：
1. 要根据响应类型区分处理，例如json还是html
2. Midway没有暴露`joi`的`isError`函数，直接引用`isError`判断错误是表单验证错误会报lint错误`node/no-extraneous-import`

**Comment by czy88840616** [comment]
存了 status，中间件再自行判断处理？

**Comment by ghostoy** [comment]
这个pr主要是默认返回422，而不是更严重的500错误，这样应该跟egg的行为一致了。

**Comment by czy88840616** [comment]
这个只是设置到了error.status 上了吧，这个是 egg-onerror 会处理设置到 ctx.status ?

**Comment by ghostoy** [comment]
@czy88840616 会的。Egg的`Context.throw()`（Koa也是）会生成带`status`属性的`Error`对象，在`egg-onerror`（也是`koa-onerror`）里根据`status`来这是。这部分具体实现在`koa-onerror`里 https://github.com/koajs/onerror/blob/master/index.js#L63-L68。

**Comment by czy88840616** [comment]
看着好像没大问题，我特地研究了下状态码为什么是 422 而不是 412，事实上有一些关于这个的[讨论](https://github.com/FriendsOfCake/crud/issues/337)。

关于当前的 pr

- 1、需要 ci 过，最好有个 test case
- 2、状态码的问题，其实是 breaking 的，最好可以有个配置，方便回退逻辑

比如

```ts
export const validate = {
  errStatus: 422
}
```

**Comment by ghostoy** [comment]
@czy88840616 在@midway/decorator下怎么获取应用的配置项呢？

**Comment by czy88840616** [comment]
我看了下。。的确是没法读，我在 3.x 中加吧。

**Comment by ghostoy** [comment]
这样改你看下行不行：

在validate.ts
```typescript

interface ValidateOptions {
  isTransform?: boolean;
  errorStatus?: number;
}

export function CustomValidate(opt: ValidateOptions) {
  return (customOpt: ValidateOptions = {}) =>
    Validate({ ...opt, ...customOpt });
}

export function Validate(opt: boolean | ValidateOptions = true) {
//...
}
```

使用的时候
```typescript
const Validate = CustomValidate({ errorStatus: 422 });

class SomeController {
  @Validate()
  foo(bar: BarDTO) {
    // ...
  }
}
```

使用默认的Validate函数不设置status，与原来的行为保持一样，使用`CustomValidate`定制的可以统一修改默认值。

**Comment by czy88840616** [comment]
好的

**Comment by czy88840616** [comment]
我在 3.x 里提供了全局配置和装饰器配置两套，并且默认返回了 422。
