### ISSUE TITLE
Database（TypeORM)不支持mongodb吗?

### ISSUE THREAD

**Issue by 1054114709** [midwayjs/midway#1378]
我的数据库是mongodb,用了Database（TypeORM),写数据正常,能写按照官网这个例子
![image](https://user-images.githubusercontent.com/56641124/143051202-239241c2-1487-4c2b-a8b8-3ced89412001.png)写了代码
![image](https://user-images.githubusercontent.com/56641124/143051993-c472c5cd-58b9-4982-b626-a8ff9a5159b4.png)会报错
![image](https://user-images.githubusercontent.com/56641124/143052068-bbcfd406-1fac-4ff2-8216-3cbd2a347ffd.png)是不是mongodb得用Typegoose 不能使用Database（TypeORM)

**Comment by czy88840616** [comment]
是的，typeorm对mongo支持不好，一般用typegoose或者mongoose组件

**Comment by monyee** [comment]
在用 读写没问题

**Comment by 1054114709** [comment]
大佬,能简单贴一下,您读数据库的代码吗?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 中午11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [midwayjs/midway] Database（TypeORM)不支持mongodb吗? (Issue #1378)






在用 读写没问题

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by 1054114709** [comment]
> 在用 读写没问题

大佬,能简单贴一下,您读数据库的代码吗?

**Comment by monyee** [comment]
读的写法一样的 你看下model怎么定义的

**Comment by 1054114709** [comment]
我按照官网上写的,不过官网数据库是mysql,我的是mongodb




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [midwayjs/midway] Database（TypeORM)不支持mongodb吗? (Issue #1378)





 
读的写法一样的 你看下model怎么定义的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by czy88840616** [comment]
在上一个版本 typeorm 文档里写着支持 mongodb 属于 preview 状态，不建议在线上使用，不过我现在去看找不到了。

**Comment by 1054114709** [comment]
谢大佬,我换typegoose吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harry ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [midwayjs/midway] Database（TypeORM)不支持mongodb吗? (Issue #1378)





 
在上一个版本 typeorm 文档里写着支持 mongodb 属于 preview 状态，不建议在线上使用，不过我现在去看找不到了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
