### ISSUE TITLE
@midwayjs/task windows环境手动触发会报redis 底层 evalsha错误

### ISSUE THREAD

**Issue by jimmywangzhiping** [midwayjs/midway#1381]
* **Node Version**:v14.17.0
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**: @midwayjs/task": "^2.13.4"
* **Platform**: win10
* **Mini Showcase Repository**:

 Midway Starting [ Midway ] 
  ReplyError: ERR Error running script (call to f_861a68c53fd5ffc59654877019b25298f921a75e): @user_scri: 39: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at tript in order to switch to single commands replication mode.
      at parseError (\node_modules\redis-parser\lib\parser.js:179:12)
      at parseType (\node_modules\redis-parser\lib\parser.js:302:14)

ite commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode.
    at parseError (\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      '861a68c53fd5ffc59654877019b25298f921a75e',
      '8',
      '{midway-task}:ExcuteSyncContactTask:execute:active',
      '{midway-task}:ExcuteSyncContactTask:execute:wait',
      '{midway-task}:ExcuteSyncContactTask:execute:delayed',
      '{midway-task}:ExcuteSyncContactTask:execute:paused',
      '{midway-task}:ExcuteSyncContactTask:execute:completed',
      '{midway-task}:ExcuteSyncContactTask:execute:failed',
      '{midway-task}:ExcuteSyncContactTask:execute:priority',
      '{midway-task}:ExcuteSyncContactTask:execute:limiter',
      '{midway-task}:ExcuteSyncContactTask:execute:',
      '*',
      '18'
    ]
  }
}

[ Midway ] start error: ERR Error running script (call to f_861a68c53fd5ffc59654877019b25298f921a75e): @user_script:39: @user_script: 39: Write commands not allowed after non determ

**Comment by czy88840616** [comment]
mac 似乎也有

**Comment by jimmywangzhiping** [comment]
@czy88840616  你那边有复现这个问题吗？那部署到docker或者vm会有这个问题吗

**Comment by czy88840616** [comment]
像是 https://midwayjs.org/docs/task#evalsha-%E9%94%99%E8%AF%AF

**Comment by jimmywangzhiping** [comment]
@czy88840616  也尝试用这种方式来配置taskconfig，但是依然会出现evalsha错误。

**Comment by czy88840616** [comment]
mac上配了就好了，windows就不知道了。。
