### ISSUE TITLE
[QUESTION]如何跳过第三方库类型检查

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1385]
背景
- 有个第三方库 *.ts 里有ts错误，例如某些变量引导但是没使用
- skipLibCheck:true 没有效果还是报错

需求
- 如何跳过这部分检查

**Comment by czy88840616** [comment]
我理解 skipLibCheck:true 就够了，检查的也不是第三方库的 ts 吧，而是 d.ts。

**Comment by xmsz** [comment]
> 我理解 skipLibCheck:true 就够了，检查的也不是第三方库的 ts 吧，而是 d.ts。

类似这个问题 https://github.com/microsoft/TypeScript/issues/38538

我引用一个第三包，他是*.ts里有ts的错误
然后我build的时候，因为这些错误中断了


我设置skipLibCheck:true，没有效果，因为只是忽略了检查*.d.ts，并没有忽略检查*.ts

我不清楚为什么会去检查ts

**Comment by czy88840616** [comment]
看起来是 ts 自己的问题，https://github.com/microsoft/TypeScript/issues/38538#issuecomment-892555422 这个 workround 可以试试。

**Comment by xmsz** [comment]
> 看起来是 ts 自己的问题，[microsoft/TypeScript#38538 (comment)](https://github.com/microsoft/TypeScript/issues/38538#issuecomment-892555422) 这个 workround 可以试试。再不行就只能推进包开发去解决了。

ok
