### ISSUE TITLE
关于@Task的疑问

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#1386]
我在远程服务器上跑的corn是  repeat: { cron: '0 */10 * * * *' },
然后本地跑的cron是 repeat: { cron: '0 */5 * * * *' },

同时观察两边的日志发现，后启动的本地服务影响到了线上的服务，两者都变成了5分钟一次task

ps: 用的同一个redis

**Comment by Thetiso** [comment]
关掉本地服务之后.... 线上服务的task不跑了.....

**Comment by czy88840616** [comment]
本地和线上不能用同一个redis的，必然会影响。

**Comment by stone-jin** [comment]
@Thetiso @czy88840616  可以通过task.prefix隔离。相当于本地和预发操作的redis的key不一样。

**Comment by Thetiso** [comment]
> @Thetiso @czy88840616 可以通过task.prefix隔离。相当于本地和预发操作的redis的key不一样。

OK  感谢~
