### ISSUE TITLE
[QUESTION]如何处理[ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1416]
背景
- 我引用了一个包，提示
```

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js
require() of ES modules is not supported.
require() of /node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js from /Users/chenshijian/code/act/act-20211123/shared/package/p-limit/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> shared/package/p-limit/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/node_modules/.pnpm/ts-node@8.10.2_typescript@4.5.2/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/node_modules/.pnpm/ts-node@8.10.2_typescript@4.5.2/node_modules/ts-node/src/index.ts:861:12) {
  code: 'ERR_REQUIRE_ESM'
}

```

- 来自于ts-node的错，大概原因就是我引用的包的type是module
- 然后我看到https://github.com/TypeStrong/ts-node/issues/935#issuecomment-913179458
这个回复 大概感觉是覆盖了ts-node的编译，如果这样解决会不会产生其他问题，有没有其他办法解决

**Comment by czy88840616** [comment]
不支持 esm 规范的包，选支持 commonjs的

**Comment by xmsz** [comment]
> 不支持 esm 规范的包，选支持 commonjs的

ok 太蛋疼了

这次涉及的包是
- p-limit
- yocto-queue

**Comment by waitingsong** [comment]
midway/egg 运行环境的加载器目前只加载 cjs 不支持 esm 。

**Comment by czy88840616** [comment]
esm 的话，看起来框架需要导出不同的入口。

**Comment by waitingsong** [comment]
> esm 的话，看起来框架需要导出不同的入口。

midway v3 (v4?) 统一输出为 ESM 可行不

**Comment by czy88840616** [comment]
ts 对 esm 从 4.5 才开始，看起来还不是很健全。

**Comment by waitingsong** [comment]
> ts 对 esm 从 4.5 才开始，看起来还不是很健全。

推迟了

> Since our beta release post and RC release post, 4.5 has gone through a few changes.
>
> The biggest change we’ve made since the beta is that ECMAScript module support for Node.js 12 has been deferred to a future release, and is now only available as an experimental flag in nightly releases. This was not an easy decision, but our team had a combination of concerns around ecosystem readiness and general guidance for how/when to use the feature. We felt it would be better to smooth out the user experience instead of releasing something that would ultimately be too frustrating for most people. In the meantime though, you can still use the new support for --module nodenext and --moduleResolution nodenext as experimental features in nightly builds of TypeScript. If you try to use these settings in TypeScript 4.5, you’ll receive an error message directing you to use a nightly build instead.

**Comment by bobohuochai** [comment]
> 不支持 esm 规范的包，选支持 commonjs的

不是很理解为什么要做这个限制

**Comment by waitingsong** [comment]
> > 不支持 esm 规范的包，选支持 commonjs的
> 
> 不是很理解为什么要做这个限制

不是限制，而是框架本身以及相关工具尚不支持ESM。所以对于纯ESM模块是不支持的。

**Comment by theshying** [comment]
已经2023年了， 还没支持么

**Comment by twinkle77** [comment]
同

**Comment by zb634009861** [comment]
【自动回复】邮件我已收到，谢谢！

**Comment by huanshiwushuang** [comment]
已经2023年了， 还没支持么

**Comment by siegaii** [comment]
已经2023年了， 还没支持么

**Comment by mirari** [comment]
我也遇到这个问题了，chatgpt-api没法导入

**Comment by SeasonXue** [comment]
2025 年了，社区很多包都仅支持 ESM。
