### ISSUE TITLE
嗨，我发现  isTsMode 这个参数无法设置为false， 疑是源码存在错误

### ISSUE THREAD

**Issue by Topgt** [midwayjs/midway#1417]
当我修改 编译输出目录 为 build 后
```
// bootstrap.js
const { join } = require('path');
const { Bootstrap } = require('@midwayjs/bootstrap');
const WebFramework = require('@midwayjs/web').Framework;

const web = new WebFramework().configure({
  port: 7001,
});
web.isTsMode = false;

Bootstrap.configure({
  baseDir: join(__dirname, 'build'),
  appDir: join(__dirname, 'build'),
})
  .load(web)
  .run();
```
**isTsMode** 这个参数无法设置为false，排查源码发现了这行代码可能有问题。
![image](https://user-images.githubusercontent.com/16378073/145359137-7372778d-474e-4f85-b100-05a615537ec9.png)

https://github.com/midwayjs/midway/blob/b3dc5e27f4d611880e9525a3b798b99b349c3dd5/packages/web/src/framework/singleProcess.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L79

**Comment by czy88840616** [comment]
目的是什么

**Comment by Topgt** [comment]
> 目的是什么，这个参数为真，是为了中途开启，否则就走js模式（js模式是内部使用的egg js版本）。

- 我要运行的就是编译之后的js文件

- 我有注意到这是一个私有属性，我确实不应该修改它，但是我在[“ 编译目录的修改”](http://www.midwayjs.org/docs/change_start_dir#bootstrap-%E5%90%AF%E5%8A%A8)
```
// tsconfig.json
{
  "compileOnSave": true,
  "compilerOptions": {
    // ...
    "outDir": "build"
  },
}
```
```
// bootstrap.js
const { join } = require('path');
const { Bootstrap } = require('@midwayjs/bootstrap');

//...

// 需要用 configure 方法配置 baseDir
Bootstrap.configure({
  baseDir: join(__dirname, 'build'),
})
  .load(web)
  .run();
```
只配置baseDir 项目无法启动，因为它一定会到dist目录下查找egg的文件，紧接着设置了appDir，但
https://github.com/midwayjs/midway/blob/b3dc5e27f4d611880e9525a3b798b99b349c3dd5/packages/web/src/utils.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L22
还是会去把 ‘dist’ 目录拼上，当设置isTsMode = false 时， 我的路径才是正确的编译后的build路径

**Comment by czy88840616** [comment]
这个配置应该是用来开启 midway支持的，走src还是dist，应该是判断了当前是否在 ts 环境，你这是要改编译后的目录，过于hack了。

**Comment by Topgt** [comment]
> Bootstrap.configure(

**Comment by pronebel** [comment]
> // tsconfig.json
> {
>   "compileOnSave": true,
>   "compilerOptions": {
>     // ...
>     "outDir": "build"
>   },
> }



修改输入目录 outDir,
然后基于 bootstrap.js  运行程序，必须需要修改baseDir。不然编译的运维代码只能是dist存放再能执行。

这是一个很正常的需求，一点不是hack的问题。这个需求非常正常。



另外：
isTsMode: this.isTsMode||true   代码是恒true的，那就是问题。

我也是这个需求，今天一直在debug midway 跟踪问题所在，还没查到根本原因。

**Comment by czy88840616** [comment]
是指方式hack，而不是需求，需求没问题。
