### ISSUE TITLE
有什么模块化开发的好点子么

### ISSUE THREAD

**Issue by 13526557907** [midwayjs/midway#1419]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by 13526557907** [comment]
midway和依赖注入模式可以在任意class内注入，可以像nest那样用模块管理起来么，如果没有模块声明不允许模块内的服务被注入到其他地方

**Comment by czy88840616** [comment]
机制不一样，nest是完全隔离，靠ts类型做的，本质上没有中心化的容器。而midway是靠中心化的容器去管理所有的类，类似inversify的方式，原因是有全局的app，config等对象，这也更符合现状，以及java spring的使用方式。
