### ISSUE TITLE
如何通过命令行启动任务并在任务完成后退出

### ISSUE THREAD

**Issue by ghostoy** [midwayjs/midway#1424]
我们想通过K8S的定时任务来处理一些事务，这些任务功能不同，定时方法不同，希望在一次启动的时候时候只调用某一个任务。Midway能不能通过命令行参数来触发某一个任务的启动，并且在任务完成后退出呢？

**Comment by ghostoy** [comment]
这个应用同时也是web应用

**Comment by czy88840616** [comment]
你可以写不同的bootstrap入口，启动不同类型的服务，但是复用同一套代码。

**Comment by ghostoy** [comment]
> 可以写不同的bootstrap入口，启动不同类型的服务，但是复用同一套代码。

有什么参考示例或者文档吗？

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/multi_framework_start#%E5%A4%9A%E4%B8%AA%E6%A1%86%E6%9E%B6%E5%90%AF%E5%8A%A8%E6%96%87%E4%BB%B6%E4%B8%BB%E5%89%AF%E6%A1%86%E6%9E%B6

这个和你本地的bootstrap 文件是一样的，多个入口，无非是多建几个文件。

**Comment by ghostoy** [comment]
我看到`@midwayjs/mock`里有`createApp`和`close`，能不能直接用它们来实现这样的入口。

**Comment by czy88840616** [comment]
不能..mock包是用来测试的..不是为了线上运行。
