### ISSUE TITLE
faas 上传

### ISSUE THREAD

**Issue by mal-fullmoon** [midwayjs/midway#1425]
![image](https://user-images.githubusercontent.com/88432411/145930515-7b4690e0-93c1-4e08-a0b5-056d01c4597a.png)
语雀中faas上传的例子，为啥这块会出现类型不对的问题

**Comment by czy88840616** [comment]
可以先把参数加个 any，这里的定义有点问题。

**Comment by czy88840616** [comment]
已经修复。
