### ISSUE TITLE
使用redis方式缓存（Cache）提示报错

### ISSUE THREAD

**Issue by f2905885** [midwayjs/midway#1429]
<img width="618" alt="微信截图_20211217140228" src="https://user-images.githubusercontent.com/14341507/146497046-c0c62f9b-86eb-463f-b40b-d81833de8639.png">
* **Node Version**: v16.13.1
* **Egg Version**: 
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在config.local.ts配置文件加个redis缓存的配置
// eslint-disable-next-line node/no-unpublished-import
import * as redisStore from 'cache-manager-ioredis';

// eslint-disable-next-line node/no-unpublished-import
export const cache = {
  store: redisStore,
  options: {
    host: '127.0.0.1',
    port: 6379,
    password: '123456',
    db: 2,
    keyPrefix: 'cache:',
    ttl: 600,
  },
};

提示：导出的变量“cache”具有或正在使用外部模块“"D:/Code/Laifaxin/center-server/node_modules/@types/cache-manager-ioredis/index"”中的名称“CacheManagerIORedis.RedisStoreConstructor”，但不能为其命名。
功能使用的正常，但是无法build，提示如上

**Comment by czy88840616** [comment]
可以先在 tsconfig里开skipLibcheck，晚点我看看为啥，估计是三方包typing变了
