### ISSUE TITLE
被apache代理转发后，返回404

### ISSUE THREAD

**Issue by linchenhuicn** [midwayjs/midway#1430]
前面套了一层apache做代理转发。
![image](https://user-images.githubusercontent.com/21193805/146513669-ffb48eca-8f42-40de-8ce2-5314baeac980.png)
访问/api 目录(midway 2.14.0)一直报404。
后面在该项目上加了@Get('/*') 空方法后，所有请求又可以正常响应回去

* **Node Version**: 16.*
* **Platform**: 2.14.0
* **Mini Showcase Repository**:

**Comment by echosoar** [comment]
请问你的目的是要将访问 `example.com/api/xxx` 的请求代理到 `127.0.0.1:10001/xxx` 上？ 还是要代理到 `127.0.0.1:10001/api/xxx` ?

如果是前者，尝试下看看：
```
<Location /api>
   ProxyPass http://127.0.0.1:10001/
   ProxyPassReverse http://127.0.0.1:10001/
</Location>
```

如果是后者，那需要配置 ProxyPass 的地址为 `http://127.0.0.1:10001/api/` ,例如
```
ProxyPass /api/ http://127.0.0.1:10001/api/
ProxyPassReverse /api/  http://127.0.0.1:10001/api/
```

**Comment by linchenhuicn** [comment]
> 请问你的目的是要将访问 `example.com/api/xxx` 的请求代理到 `127.0.0.1:10001/xxx` 上？ 还是要代理到 `127.0.0.1:10001/api/xxx` ?
> 
> 如果是前者，尝试下看看：
> 
> ```
> <Location /api>
>    ProxyPass http://127.0.0.1:10001/
>    ProxyPassReverse http://127.0.0.1:10001/
> </Location>
> ```
> 
> 如果是后者，那需要配置 ProxyPass 的地址为 `http://127.0.0.1:10001/api/` ,例如
> 
> ```
> ProxyPass /api/ http://127.0.0.1:10001/api/
> ProxyPassReverse /api/  http://127.0.0.1:10001/api/
> ```
我是要把api目录去掉的
你说的Location这个配置我也试过，但还是404.
但后面实在没办法，才在项目里了一个加了一个处理/*请求，想看看转发进来的路径有没问题；但加上去后，又能被处正常理掉，这个方法反而都没调用

**Comment by echosoar** [comment]
![image](https://user-images.githubusercontent.com/14832743/146529478-1e2435da-3c2d-49dc-bfd1-bd80c2f07488.png)
实测需要使用 `/api/`
```
<Location /api>
   ProxyPass http://127.0.0.1:10001/
   ProxyPassReverse http://127.0.0.1:10001/
</Location>
```
