### ISSUE TITLE
midway2.x 修改node端代码触发了egg-webpack执行

### ISSUE THREAD

**Issue by shawon1220** [midwayjs/midway#1433]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

midway2.14.0 修改node端代码触发了egg-webpack执行，导致编译很慢

**Comment by czy88840616** [comment]
我理解是 egg-webpack 监听了 ts 文件的变化？这个要它忽略的吧
