### ISSUE TITLE
[ 文档 ] 官方文档不够详细

### ISSUE THREAD

**Issue by atzcl** [midwayjs/midway#144]
刚刚想提一个 issue: 是否能提供 request、app、ctx 等对象的装饰器， 然后在翻看源码的时候，发现框架底层已经把 `ctx` 对象注册到了容器内了，只要
```ts
@inject()
ctx: Context;
``` 
即可注入使用。

所以官方是否能把由框架底层注册的容器都列出来呢？

另外想问下，框架是否可以提供 `request`、`query` 、`helper`、`params` 等等挂载在 `ctx` 中的常用对象所对应的参数装饰器 or 属性装饰器呢？

**Comment by czy88840616** [comment]
目前只有 `ctx` 和 `logger` 两个，都是请求作用域的。其他应该没有了。。
https://github.com/midwayjs/midway/blob/master/packages/midway-core/src/requestContainer.ts#L20

**Comment by atzcl** [comment]
期待更新~
