### ISSUE TITLE
[QUESTION]如何避免生成CRLF的类型/如何设置生成的文件是LF

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#1443]
背景
- 每次运行`npm run dev`的时候，都会生成typings下的文件
- 而这些文件的类型是CRLF
- 但我们git设置的是LF

需求
- 希望可以设置生成的文件换行符类型是LF

**Comment by czy88840616** [comment]
https://juejin.cn/post/6844904069304156168

**Comment by xmsz** [comment]
> https://juejin.cn/post/6844904069304156168

嗯 我现在就是手动IDE切换 然后下次不提交这个文件夹 但是每次新项目都要操作一次有点麻烦
