### ISSUE TITLE
egg.js里默认打印的请求日志。midway里面怎么设置？

### ISSUE THREAD

**Issue by zhump** [midwayjs/midway#145]
咨询一下xx-web.log日志文件里，怎么设置打印请求日志？
![image](https://user-images.githubusercontent.com/7962067/52697533-9c9e2100-2fac-11e9-8254-134faaa6d1e0.png)

**Comment by czy88840616** [comment]
具体指的是？

egg 打的请求日志使用的是 ContextLogger，在 midway 里是一样的。

```ts
export class Service {
  @inject()
  logger;
}
```

在请求作用域下这个 logger 就是 contextLogger。

**Comment by zhump** [comment]
不好意思 我描述的不太清楚 我误认为了egg.js会自动打印请求日志到web.log文件中。 
`level - traceid -ip - time - method - path - params`
其实不管midway还是egg.js都是得自己写中间件去实现这个功能。多谢回复🙏

**Comment by zhump** [comment]
midway 使用类似依赖注入来 分离 service、controller 和一些注入的对象，这样会导致编辑器的提示不出来这写对象的方法和属性。这个是不是目前的遗憾呀？比如这个logger应该有info\warn...等等方法，编辑器是无法提示的。

**Comment by czy88840616** [comment]
我加一个基类机制

**Comment by atzcl** [comment]
自己加上类型注解就好啦 `logger: Logger `

**Comment by czy88840616** [comment]
@zhump @atzcl 我导几个日志类型，看看应该够用了吧

**Comment by zhump** [comment]
嗯嗯 多谢。不过现在有个用法问题 ，请教一下，我在使用egg.js时会给业务controller集成一个baseController,放一下公共的方法。我还可以把 logger等等公共对象， inject在baseController中，业务controller直接this.xxx即可。
例如：
```
import { inject } from 'midway';
export default class BaseController {
  @inject()
  logger

  @inject()
  ctx

  get user() {
    return this.ctx.session;
  }
}

```
其实 这个 ctx 上下文对象 我也想有 提示的。：）

而且官方的例子中，ctx从路由方法的参数的去拿，也是没有任何代码提示的，其实编码的体验是不太好。

![image](https://user-images.githubusercontent.com/7962067/52914774-4eb84e80-3307-11e9-8a82-03e50feab385.png)

有办法解一下吗 我尝试从egg导出一个context作为基类 好像不行 。。

**Comment by czy88840616** [comment]
不会有问题，未来也会逐步倾向这种方式。

**Comment by czy88840616** [comment]
另外，大多数你需要的定义都可以在 midway 上 [找到](https://github.com/midwayjs/midway/blob/master/packages/midway/src/index.ts#L4)。

**Comment by zhump** [comment]
好的 多谢了
