### ISSUE TITLE
graphql 无法build生成文件夹

### ISSUE THREAD

**Issue by hodgevk** [midwayjs/midway#147]
@czy88840616 直接使用graphql的Demo测试，执行npm run build后，在dist文件夹里未生成graphql的相关代码

**Comment by czy88840616** [comment]
应该是用了js，ts 不会自动拷贝到 dist 目录。可以用 midway-bin 的增强语法。
https://midwayjs.org/midway/tool_set.html#build-%E5%91%BD%E4%BB%A4

**Comment by czy88840616** [comment]
加一句这个就行了。
```
  "midway-bin-build": {
    "include": [
      "app/graphql"
    ]
  }
```
