### ISSUE TITLE
计划分离外部定义

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#148]
由于未来会启动 @midwayjs group，serverless framework，以及装饰器，最后都会逐步放到 @midwayjs/decorator, @midwayjs/midway-serverless 这些类似的包名下。

随着越来越多的定义从 midway 上导出，变的不太容易维护，计划将定义也放到 @midwayjs/definition 下，通过类似 module 的机制来引用。

比如。

```ts
import { egg } from '@midwayjs/definition';

const logger: egg.EggLogger = midway.getLogger();
```

ps：同时也解决了内外包引用相同资源，不好覆盖维护的问题。

**Comment by kurten** [comment]
这类break change还是需要谨慎操作 :)

**Comment by czy88840616** [comment]
@midwayjs/definition的定义暂时不动，内部包有这个需求，egg 的定义依旧在 midway-web 导出，midway 可用，不做修改。
