### ISSUE TITLE
本地定时任务立即执行时 提示getLocalTask 方法不存在

### ISSUE THREAD

**Issue by Alter-lyh** [midwayjs/midway#1517]
![1641294697(1)](https://user-images.githubusercontent.com/23023794/148050733-a5d17f12-5839-4359-a756-340b17ed3594.png)
![1641294713(1)](https://user-images.githubusercontent.com/23023794/148050768-e775d6a8-b674-4458-9188-dc36f5f99796.png)
如图所示获取分布式任务的方法是存在的，但是获取本地任务的代码提示不存在。代码是直接copy官网的，不是知道是否是我哪里配置有误呢？
node 版本 12.16.2
其他的版本如图所示
![1641294845(1)](https://user-images.githubusercontent.com/23023794/148051043-2dc1b70c-c20a-4af3-adc8-9ca95a78f0cc.png)

**Comment by czy88840616** [comment]
我仔细读了一下，QueueService 是分布式定时任务的队列服务，本地的任务应该没有 getLocalTask 方法。

**Comment by Alter-lyh** [comment]
> 我仔细读了一下，QueueService 是分布式定时任务的队列服务，本地的任务应该没有 getLocalTask 方法，应该是文档不对。

谢谢，我刚看了确实没有getLocalTask 方法，可能是之前有这个功能，后来删了吧

**Comment by czy88840616** [comment]
文档已删除。
