### ISSUE TITLE
聚合部署， serverless run deploy 命令行乱码，且无法正常部署

### ISSUE THREAD

**Issue by GreatAuk** [midwayjs/midway#1547]
* **Node Version**: 16.8.0
* **Midway Version(Decorator/Core)**: ^2.3.0
* **Component Name/Version**:
* **Platform**: Mac OS(M1)
* **Mini Showcase Repository**:

参考 https://www.midwayjs.org/docs/serverless_aggr 新增项目并运行部署命令

```
npm init midway -- --type=faas-aggr my_midway_app

npm install

npm run deploy
```
![image](https://user-images.githubusercontent.com/20253809/148726098-6b3b7d29-cd9e-489b-a1cd-b07efceb1c20.png)

**Comment by echosoar** [comment]
colorjs 的问题，正在处理中

**Comment by GreatAuk** [comment]
应该是因为这个问题 https://github.com/Marak/colors.js/issues/294 😂， 我先关了，明天试试

**Comment by czy88840616** [comment]
其实是 fun 工具依赖的 color 问题，我们计划将其迁移到 serverless devs。
