### ISSUE TITLE
希望可以在打包后的serverless.yml 文件, 可以注入.env 的环境变量

### ISSUE THREAD

**Issue by LuckyRyan-web** [midwayjs/midway#1549]
服务商为腾讯云

对于数据库账号密码之类的数据, 我用 dotEnv 这个库, 用 .env 文件里面定义数据库的变量

但是servereless 环境中, 无法识别到 .env 文件的内容, 即便是在 package.include 了 .env 文件

如果是要在 f.yml 文件里面把 .env 的变量定义到 environment 的话, f.yml 的数据库信息就会进入 git的版本提交了

有没有办法在生成 .serverless 的时候, 可以有个方法可以替换 serverless.yml 的内容吗

![image](https://user-images.githubusercontent.com/28999580/148746237-79989cfd-ed5d-4df8-9f75-51326cd8748c.png)

**Comment by czy88840616** [comment]
可以用环境变量 https://midwayjs.org/docs/serverless_environment#yml-%E5%8F%98%E9%87%8F%E5%A1%AB%E5%85%85
