### ISSUE TITLE
我用阿里的midway自动安装到函数计算,显示成功但在服务及函数并没显示.是不是不支持海外版澳大利亚

### ISSUE THREAD

**Issue by cpen5** [midwayjs/midway#1580]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

我用阿里的midway自动安装到函数计算,显示成功但在阿里云的服务及函数并没显示.是不是不支持海外版澳大利亚

**Comment by czy88840616** [comment]
海外版应该是不支持吧，到不是框架的问题，而是阿里云发布sdk的关系。如果 Serverless devs 支持，那也是可以的。

**Comment by czy88840616** [comment]
可以试试在 f.yml 里配置 region

```
provider:
	region: xxxx
````
