### ISSUE TITLE
请问build可以改成用esbuild吗？

### ISSUE THREAD

**Issue by pigLoveRabbit520** [midwayjs/midway#1592]
* **Node Version**: v16.13.0
* **Midway Version(Decorator/Core)**: v2.14.3
* **Component Name/Version**: 
* **Platform**: Ubuntu
* **Mini Showcase Repository**:

现在还是感觉npn run build太慢了（慢的主要原因应该是tsc吧），想加快构建速度。

**Comment by echosoar** [comment]
目前仅在dev命令下面提供了esbuild选项：midway-bin dev --ts --fast=esbuild

build/package 目前没有提供，后面会尝试集成swc进行构建

**Comment by echosoar** [comment]
esbuild在我们的测试过程中发现由于egg配置动态合并等会导致一些不兼容的情况，所以目前没有提供
