### ISSUE TITLE
NotFoundError: orm:decoratorService in class OrmConfiguration is not valid in current context

### ISSUE THREAD

**Issue by Tim2011** [midwayjs/midway#1604]
按文档初始化的项目，能正常运行.
然后按文档安装了typeorm和pg
`npm i @midwayjs/orm@2 typeorm --save`

配置也添加了
![image](https://user-images.githubusercontent.com/1234976/150310102-2aa8c13e-2ecf-40e3-a939-649b3241ab12.png)

config.default.ts
![image](https://user-images.githubusercontent.com/1234976/150310193-e25981cc-0d7c-4a0a-9f1c-33dc70b20ae7.png)

运行的时候报错
![image](https://user-images.githubusercontent.com/1234976/150310029-901da1f6-5b59-4632-963a-4a189fb3125c.png)

依赖的版本
![image](https://user-images.githubusercontent.com/1234976/150310549-71b9b661-ef28-4ef0-bbef-82e8a75c8b31.png)

请问是还需要配置其他内容吗

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/150311445-f9ec2326-7bf8-4400-8362-b207364f6fd1.png)

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/150311697-d158f65b-e0d3-4b32-b6d2-04a729df71bf.png)

用 2
