### ISSUE TITLE
midway cos组件创建cos实例时入参太少并且找不到其他修改方式

### ISSUE THREAD

**Issue by 4xii** [midwayjs/midway#1629]
![image](https://user-images.githubusercontent.com/73146951/150944160-31608cb5-eddc-480d-b6a5-5dd39a4ab7f7.png)
只能传SecretId，SecretKey

导致无法传入私有云的参数如ServiceDomain

![image](https://user-images.githubusercontent.com/73146951/150944625-d317eb26-d4a3-4c52-bfe2-3043b9df2035.png)
是否可以根据这些cos入参再拓展一下

**Comment by czy88840616** [comment]
可以pr下，把整个参数传进去
