### ISSUE TITLE
60690bf61537e537888e3593f0edb748 in class UserService in class UserController is not valid in current context

### ISSUE THREAD

**Issue by wangyaxinone** [midwayjs/midway#1633]
![image](https://user-images.githubusercontent.com/23171959/151140635-5e11d7ab-16cd-41b1-ad8e-3f74c4fcdbcc.png)

**server**
![image](https://user-images.githubusercontent.com/23171959/151141435-e6fba8cc-4b64-4599-bf9a-6d0a72d43712.png)
`
**controller**
![image](https://user-images.githubusercontent.com/23171959/151141340-54e7324d-97ee-4155-b76e-aab7abe98c17.png)
之前开发一直没有这个问题，再删除依赖包重新安装后出现的问题，看了官网关于这个bug的解决，但是无效
![image](https://user-images.githubusercontent.com/23171959/151140935-43d68d48-69bc-4800-9d8b-2fabbed58279.png)

**Comment by czy88840616** [comment]
这个错误是userService里某个属性注入的东西找不到定义吧，截图的几个属性检查下，你还得看看继承的里面的。

**Comment by wangyaxinone** [comment]
> 错误是用户几个服务里检查某些属性的东西还找不到定义吧，截图的属性下，你得看看继承的里面的东西。

感谢大佬，继承组件的class 内部注入的服务和 业务服务命名一样 冲突了
