### ISSUE TITLE
swagger 对全局api前缀支持判断失效

### ISSUE THREAD

**Issue by demon-dy** [midwayjs/midway#1654]
https://github.com/midwayjs/midway/blob/6e356071bcef1a90d01738c6f409d0b01043cca8/packages/swagger/src/swaggerExplorer.ts#L189

此处是否应该添加判断存在全局路由属性时，添加前缀
```
// todo： URL赋值，打补丁
if (this.swaggerConfig.basePath) {
    url = this.swaggerConfig.basePath + url;
}
```

**Comment by czy88840616** [comment]
感觉这里应该走 webCollector，那边是直接处理好路由了

**Comment by kurten** [comment]
在新版的 swagger spec 里面前缀只能通过配置 servers 来处理，这个 basePath 没用了。
