### ISSUE TITLE
关于文档提个小建议(3.0::多环境配置)

### ISSUE THREAD

**Issue by ljybill** [midwayjs/midway#1672]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

hi,感谢提供高效的框架提高我们的开发效率。
我在查阅文档时候发现3.0的文档中没有多环境配置的章节，我切换到2.0才看到。
由于我是直接从3.0入坑的，所以建议3.0的文档中也补上多环境配置章节

**Comment by czy88840616** [comment]
有的呀。。https://www.midwayjs.org/docs/env_config

**Comment by ljybill** [comment]
抱歉
