### ISSUE TITLE
关于gRPC错误：13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error

### ISSUE THREAD

**Issue by wissyang** [midwayjs/midway#1679]
* **Node Version**:v16.13.2
* **Midway Version(Decorator/Core)**:^3.0.0
* **Component Name/Version**:@midwayjs/grpc: ^3.0.2
* **Platform**:
* **Mini Showcase Repository**:

我使用npm init midway建立的koa-V3标准化项目，然后100%按照官方手册架设gRPC服务，单元测试也是复制官网文档内容。

第一次测试，index.test.ts报`TypeError: Cannot read properties of undefined (reading 'useMiddleware')`错误，注释这个中间件；

第二次测试，index.test.ts报`14 UNAVAILABLE: No connection established`错误，将gRPC端口由默认的6565修改成7001；

第三次测试，index.test.ts仍然报`14 UNAVAILABLE: No connection established`错误，先npm run dev启动项目；

第四次测试，index.test.ts报`13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error`错误，至此未找到解决办法。

下面我贴上我的关键代码，请大神指点。

>proto/helloworld.proto

    syntax = "proto3";

    package helloworld;

    // 服务的定义
    service Greeter {
      // Sends a greeting
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }

    // 服务的请求参数
    message HelloRequest {
      string name = 1;
    }

    // 服务的响应参数
    message HelloReply {
      string message = 1;
    }

>src/domain/helloworld.ts

    import * as grpc from '@midwayjs/grpc';

    /* package helloworld start */
    export namespace helloworld {
      // 服务的定义
      export interface Greeter {
        // Sends a greeting
        sayHello(data: HelloRequest): Promise<HelloReply>;
      }
      /**
       * Greeter client interface
       */
      export interface GreeterClient {
        // Sends a greeting
        sayHello(options?: grpc.IClientOptions): grpc.IClientUnaryService<HelloRequest, HelloReply>;
      }
      // 服务的请求参数
      export interface HelloRequest {
        name?: string;
      }
      // 服务的响应参数
      export interface HelloReply {
        message?: string;
      }
    }

>src/provider/greeter.ts

    import {
        MSProviderType,
        Provider,
        Provide,
        GrpcMethod,
      } from '@midwayjs/decorator';
      import { helloworld } from '../domain/helloworld';
  
      /**
       * 实现 helloworld.Greeter 接口的服务
       */
      @Provide()
      @Provider(MSProviderType.GRPC, { package: 'helloworld' })
      export class Greeter implements helloworld.Greeter {
  
        @GrpcMethod()
        async sayHello(request: helloworld.HelloRequest) {
          return { message: 'Hello ' + request.name };
        }
      }

>src/configuration.ts

    import { Configuration, App } from '@midwayjs/decorator';
    import * as koa from '@midwayjs/koa';
    import * as validate from '@midwayjs/validate';
    import * as info from '@midwayjs/info';
    import * as grpc from '@midwayjs/grpc';
    import { join } from 'path';
    // import { DefaultErrorFilter } from './filter/default.filter';
    // import { NotFoundFilter } from './filter/notfound.filter';
    // import { ReportMiddleware } from './middleware/report.middleware';

    @Configuration({
      imports: [
        koa,
        validate,
        grpc,
        {
          component: info,
          enabledEnvironment: ['local'],
        },
      ],
      importConfigs: [join(__dirname, './config')],
    })
    export class ContainerLifeCycle {
      @App()
      app: koa.Application;

      async onReady() {
        // add middleware
        // this.app.useMiddleware([ReportMiddleware]);
        // add filter
        // this.app.useFiter([NotFoundFilter, DefaultErrorFilter]);
      }
    }

>test/index.test.ts

    import { createApp, close } from '@midwayjs/mock';
    import { Framework, createGRPCConsumer } from '@midwayjs/grpc';
    import { join } from 'path';
    import { helloworld } from '../src/domain/helloworld';

    describe('test/index.test.ts', () => {

      it('should create multiple grpc service in one server', async () => {
        const baseDir = join(__dirname, '../');
    
        // 创建服务
        const app = await createApp<Framework>(baseDir, {
          services: [
            {
              protoPath: join(baseDir, 'proto', 'helloworld.proto'),
              package: 'helloworld',
            },
          ],
        });

        // 调用服务
        const service = await createGRPCConsumer<helloworld.GreeterClient>({
          package: 'helloworld',
          protoPath: join(baseDir, 'proto', 'helloworld.proto'),
          url: 'localhost:7001'
        });

        const result = await service.sayHello().sendMessage({
          name: 'harry'
        });

        expect(result.message).toEqual('Hello harry');
        await close(app);
      });

    });

>src/config/config.default.ts

```
import { MidwayConfig } from '@midwayjs/core';

export default {
  // use for cookie sign key, should change to your own and keep security
  keys: '1644328748167_9415',
  koa: {
    port: 7001,
  },
} as MidwayConfig;
```

**Comment by czy88840616** [comment]
文档已更新，可以参考最新的文档。

**Comment by czy88840616** [comment]
v3 的文档还在更新中。

**Comment by hbsjmsjwj** [comment]
照着文档grpc，测试跑不过

**Comment by Tenodec** [comment]
> 照着文档grpc，测试跑不过

而且要用node boostrap.js 启动不要 dev

**Comment by czy88840616** [comment]
v3 dev 已经没问题的了

**Comment by ddzyan** [comment]
@czy88840616 我这在写grpc服务调用的时候也遇到了同样的问题，我看上面也没具体说到怎么解决，有空帮忙看下吗？ ` Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error` 和下面这个问题
![image](https://user-images.githubusercontent.com/9130123/182785479-fb7a6598-6c82-4d5d-94db-9c572d2517f3.png)

代码仓库：https://github.com/ddzyan/midway-practice.git
分支：feat/grpc

**Comment by ddzyan** [comment]
> @czy88840616 我这在写grpc服务调用的时候也遇到了同样的问题，我看上面也没具体说到怎么解决，有空帮忙看下吗？ ` Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error` 和下面这个问题 ![image](https://user-images.githubusercontent.com/9130123/182785479-fb7a6598-6c82-4d5d-94db-9c572d2517f3.png)
> 
> 代码仓库：https://github.com/ddzyan/midway-practice.git 分支：feat/grpc

在执行 test/service/email.test.rs 的时候

**Comment by czy88840616** [comment]
你只写了个 client，没写 grpc server。

**Comment by ddzyan** [comment]
> 你只写了个 client，没写 grpc server。

server 在另外一个项目上，单元测试全部通过了

**Comment by jkbody** [comment]
> > 你只写了个 client，没写 grpc server。
> 
> server 在另外一个项目上，按照示例上的使用说明单元测试全部通过了
问题解决了吗？我也遇到了这个报错
