### ISSUE TITLE
vscode启动调试后，无法正常启动服务，无法断点debug调试

### ISSUE THREAD

**Issue by SilverLeaves** [midwayjs/midway#169]
参照 #135 的指引进行操作后，服务没有run起来，发送请求无响应

![图片](https://user-images.githubusercontent.com/31165554/54096173-a9643800-43e5-11e9-8463-ceb0401b3263.png)
![图片](https://user-images.githubusercontent.com/31165554/54096199-c8fb6080-43e5-11e9-9683-a5616aa6b261.png)

**Comment by czy88840616** [comment]
大概率是egg的调试方案坏了，待会儿我给个新的配置看看

**Comment by czy88840616** [comment]
```json
{
  // 使用 IntelliSense 了解相关属性。
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Debug",
      "runtimeExecutable": "tnpm",
      "runtimeArgs": ["run", "debug"],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "auto",
      "port": 9229,
      "autoAttachChildProcesses": true
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Test",
      "runtimeExecutable": "tnpm",
      "runtimeArgs": ["run", "test"],
      "console": "integratedTerminal",
      "protocol": "auto",
      "port": 9229,
      "autoAttachChildProcesses": true
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Attach to remote",
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "/usr/src/app",
      "address": "localhost",
      "protocol": "auto",
      "port": 9999
    }
  ]
}
```
试试这个。

**Comment by SilverLeaves** [comment]
我把`tnpm`改为`npm`咯。

**Comment by czy88840616** [comment]
恩恩，tnpm 是内部产品。

**Comment by SilverLeaves** [comment]
`tnpm`最后更新于3年前？这是干什么
![图片](https://user-images.githubusercontent.com/31165554/54097209-f64a0d80-43e9-11e9-9ab5-d55ca355f00d.png)

**Comment by SilverLeaves** [comment]
好的吧！

**Comment by czy88840616** [comment]
外部应该是没这个包的，放一个假的包，避免内部用户误装。

**Comment by SilverLeaves** [comment]
服务是起来了，但是断点处不会停下来，直接请求处理完了
![图片](https://user-images.githubusercontent.com/31165554/54097295-65bffd00-43ea-11e9-975f-d42b32af675e.png)

**Comment by czy88840616** [comment]
我研究一下。。主要是我一般用的 idea 调试。。vscode 不太常用。

**Comment by SilverLeaves** [comment]
什么IDEA? VS Studio?

**Comment by czy88840616** [comment]
https://www.jetbrains.com/idea/

**Comment by SilverLeaves** [comment]
哦，想得通，阿里java攻城狮转战node

**Comment by czy88840616** [comment]
只是 WebStorm 开发太卡了，所以换了。

**Comment by SilverLeaves** [comment]
看下这个，问题应该出在这里
![图片](https://user-images.githubusercontent.com/31165554/54098635-593ea300-43f0-11e9-9254-4b2199412af7.png)

**Comment by czy88840616** [comment]
我生成下了 sourcemap，似乎也没有读到

**Comment by SilverLeaves** [comment]
egg下我改了，调试显示是这样的
![图片](https://user-images.githubusercontent.com/31165554/54099403-14b50680-43f4-11e9-9652-d10c56b3104b.png)

**Comment by czy88840616** [comment]
跟提供配置的开发反馈了一下，他说之前是能直接调试的。。现在不知为何需要重启下才能断到了。

![image](https://user-images.githubusercontent.com/418820/54099693-8477c100-43f5-11e9-8e25-aecd24a83c24.png)


![image](https://user-images.githubusercontent.com/418820/54099698-880b4800-43f5-11e9-9d30-68895e8d7892.png)

重启了之后 egg 进程就出来了。

**Comment by SilverLeaves** [comment]
真神奇！！！
如果你觉得解决了，就可以关了这个ISSUE。

我觉得这个`技巧`需要写到文档里面去。

**Comment by czy88840616** [comment]
egg 那边我看到也有相同的问题，由于这块我们没有涉猎，也可以等 egg 那边修复。

**Comment by SilverLeaves** [comment]
@czy88840616 2019/5/17  vscode中，配置好后可以直接调试了。

**Comment by waitingsong** [comment]
@SilverLeaves   我用这个可以断点，并且修改ts文件后自动重启调试进程后断点也正常
 e50aa2f3d06bf
