### ISSUE TITLE
this.redisService.on is not a function

### ISSUE THREAD

**Issue by Richard-Choooou** [midwayjs/midway#1709]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/23492006/154220805-eef89ba9-bb62-4585-a937-a0f903742b25.png)

ioredis 继承了 [EventEmitter](http://nodejs.org/api/events.html#events_class_events_eventemitter)
这回方法没有把继承的方法拷贝，导致 缺失了 ioredis 的部分方法。

**Comment by Richard-Choooou** [comment]
![image](https://user-images.githubusercontent.com/23492006/154221306-d363429e-6c3c-4950-abf4-c9abdd058caa.png)

**Comment by czy88840616** [comment]
呃，的确，eventEmitter的没有代理
