### ISSUE TITLE
midway Serverless 部署到阿里云FC报错，求解

### ISSUE THREAD

**Issue by wangyaxinone** [midwayjs/midway#1710]
![image](https://user-images.githubusercontent.com/23171959/154234798-d58f81ba-fb20-4767-ad3d-d941fff32688.png)
AccessKeyId和AccessKeySecret 都填写对的了，但是还是报错，换台机子就能成功，求解

**Comment by echosoar** [comment]
使用 `--resetConfig` 重设参数的时候，第一个输入的是一个 `access alias`，可以输入 `default`，然后再输入ak 和 secret。

如果 `access alias` 不想设置为 `default`，可以在执行 `midway-bin deploy` 的时候通过 `--access` 参数设置你自定义的 access alias，例如  `midway-bin deploy --access=default-2`
