### ISSUE TITLE
期望在midway-bin dev 时，tsx 文件的变更可以自动编译测试

### ISSUE THREAD

**Issue by shinku** [midwayjs/midway#1715]
尝试在midway中构建react 的ssr 应用，不免会用到tsx文件，但在执行 
`‘cross-env ets && cross-env NODE_ENV=local midway-bin dev --ts’ `
的情况下，tsx文件的变更并没在本地有热更新。希望在后期版本中集成相关功能。

**Comment by czy88840616** [comment]
tsx 基本归属于前端页面侧的文件了，如有需要，可以通过 watchExt 自行增加。
