### ISSUE TITLE
WebMiddleware不见了

### ISSUE THREAD

**Issue by SilverLeaves** [midwayjs/midway#172]
![图片](https://user-images.githubusercontent.com/31165554/54167668-d415c580-44a5-11e9-8f70-a0f093956e7a.png)

**Comment by czy88840616** [comment]
删了lock文件，重装试一下，

Silver·湫澲 <notifications@github.com>于2019年3月12日 周二上午9:04写道：

**Comment by czy88840616** [comment]
我的错，漏导出了。   https://github.com/midwayjs/midway/pull/173

**Comment by czy88840616** [comment]
原因是，本来这个接口在 @midwayjs/decorator 这个包，上一次重构玩，我们判断只会在 web 场景用到，就移到了 midway-web 的 interface 里，但是 index 没有导出 interface，造成了这个问题。

**Comment by SilverLeaves** [comment]
兄die，你这回复效率很高鸭

**Comment by czy88840616** [comment]
已经修改测试用例，避免再造成这个问题。

**Comment by czy88840616** [comment]
已发布 v1.4.10
