### ISSUE TITLE
全局的middleware只能使用egg.js的方式使用吗？

### ISSUE THREAD

**Issue by zhump** [midwayjs/midway#174]
目前看demo和文档,middleware只应用于单个controller和路由。如何通过midway声明一个全局的middleware?

**Comment by czy88840616** [comment]
额，可以看看我们的讨论的过程，https://github.com/midwayjs/midway/issues/82。

主要是 egg 已经提供了全局了中间件，目前就跳过这块的支持。不过为了代码统一和依赖注入的特性，可能还是会提供这个功能。

**Comment by zhump** [comment]
好滴 期待解决方案 ：）

**Comment by xluos** [comment]
> 额，可以看看我们的讨论的过程，[https://github.com/midwayjs/midway/issues/82。](https://github.com/midwayjs/midway/issues/82%E3%80%82)
> 
> 主要是 egg 已经提供了全局了中间件，目前就跳过这块的支持。不过为了代码统一和依赖注入的特性，可能还是会提供这个功能。

egg中是约定在`app/middleware` 目录下的单独文件，然后在config中引入名称，midway中也能这样用吗？我尝试了一下无法直接在config中使用IoC注入的插件，可以提供一个例子吗？比如CORS中间件。

另外在CORS中间件使用过程中发现每个路由都要额外添加一个`@options`装饰器，有没有什么方法可以配一个全局相应的`@options`请求，或者有没有什么别的比较方便的解决方案。

谢谢！

**Comment by ZQun** [comment]
@xluos https://github.com/midwayjs/midway/issues/170#issuecomment-471468304

**Comment by czy88840616** [comment]
config中的名字是egg规定的，只能配置中间件的名字。
ZQun <notifications@github.com>于2019年3月14日 周四上午10:21写道：

**Comment by czy88840616** [comment]
@xluos

> egg中是约定在app/middleware 目录下的单独文件，然后在config中引入名称，midway中也能这样用吗？我尝试了一下无法直接在config中使用IoC注入的插件，可以提供一个例子吗？比如CORS中间件。

全局中间件是一样的，例子 https://github.com/midwayjs/midway-examples/blob/master/demo-extended-koa/src/app/middleware/trace.ts

或者直接使用 egg-cors.


> 另外在CORS中间件使用过程中发现每个路由都要额外添加一个@options装饰器，有没有什么方法可以配一个全局相应的@options请求，或者有没有什么别的比较方便的解决方案。

没太明白，@get/@post 这些装饰器就类似于使用 koa-router 以前写的 `app.get()、app.post()`，以前写一句就对应现在的一个装饰器。

**Comment by xluos** [comment]
@czy88840616 我的意思是跨域的时候浏览器不是有个options预查请求嘛，如果对应路由不加上`@options()`装饰器，这个预查就会返回404。如果都写了又有点儿麻烦。midway里有没有什么方法可以像在Nginx里配置那样匹配所有的路由的options请求返回204

**Comment by czy88840616** [comment]
那可以写个全局的中间件吧。。。

```js
if(method === 'OPTIONS') {
  this.status = 204
}
```

这种？

**Comment by xluos** [comment]
> 那可以写个全局的中间件吧。。。
> 
> ```js
> export default function(options: any, app: any): any {
>   return async (ctx: any, next: any) => {
>     if(method === 'OPTIONS') {
>      this.status = 204
>     }
>     await next();
>   };
> }
> ```
> 
> 这种？

是噢，一直在想怎么弄一个通配的路由，忽略了还有这种操作 :joy: ，还是自己太菜了。。抱歉哈

**Comment by SilverLeaves** [comment]
这真令人迷惑。

**Comment by czy88840616** [comment]
主要还是egg提供了这个能力，midwya要提供另一种全局中间件的方式就势必得修改到loadMiddleware方法了，比较hack了。

**Comment by waitingsong** [comment]
对于 OPTION 我在 egg 用的方法，可供参考：
1. 方法一 使用插件
config/plugin.ts
```ts
export default {
  cors: {
    enable: true,
    package: 'egg-cors',
  },
  // security: false, // 禁用全部安全检查
}
```

2. 方法二 使用中间件
app/middleware/header.ts
```ts
import { Context } from 'egg'

export default (ttl: number) => {
  return async (ctx: Context, next: () => Promise<void>) => {
    await next()
    // OPTIONS 预检有效期
    ctx.res.setHeader('Access-Control-Max-Age', ttl)
  }
}
```

然后在路由 router.ts 中调用 
```ts

export default (app: Application) => {
  const { controller, router } = app
  const setHeader = app.middleware.header(3600)
}
```

**Comment by yolo2013** [comment]
有个问题，以egg的形式定义的中间件不是class类型，怎么注入 service 呢？那么就必须要把service放在app目录下了吗？

**Comment by czy88840616** [comment]
https://midwayjs.org/midway/guide.html#context-%E6%89%A9%E5%B1%95

使用 `await ctx.requestContext.getAsync('xxx')`

**Comment by czy88840616** [comment]
新版本已经处理全局中间件问题。
