### ISSUE TITLE
添加全局中间件后无法访问路由的求解

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#176]
如图，当我试图添加一个test.js的全局中间件，访问路由时提示not found， 而当我删除时，一切又恢复正常。请问如何解决这个问题？谢谢。
![pic](https://user-images.githubusercontent.com/40480550/54504208-a204d780-496d-11e9-90ea-13ab5a080e34.png)

**Comment by czy88840616** [comment]
得在中间件里 await next() 吧？

**Comment by linzelong95** [comment]
@czy88840616 
真是不好意思，确实如大神所言。
