### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#177]
我用midway-init创建了项目，昨天运行一切顺利，但今早打开项目时，vscode提示找不到midway module。于是我用cnpm  install midway --save重新做了安装。但安装完毕后，npm run dev 启动报错，如图。系统是win 10.请问该如何操作，才能正常使用。谢谢。
![info](https://user-images.githubusercontent.com/40480550/54572576-42690380-4a23-11e9-8444-da849a23e927.png)

**Comment by czy88840616** [comment]
我们来查一下

**Comment by czy88840616** [comment]
等等...

应该是删了 node_modules，重新cnpm install吧，单独装一个可能有问题的。

另外，要把lock文件先删了。

**Comment by linzelong95** [comment]
@czy88840616 嗯，全部重新装可以使用
