### ISSUE TITLE
hey,可否提供一个passport-local在midway的实例，egg文档的那个，似乎没能整明白，谢谢。

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#178]

**Comment by czy88840616** [comment]
是 https://github.com/eggjs/egg-passport 这个插件？

**Comment by linzelong95** [comment]
@czy88840616 
是这个，但好像没怎么看明白，不太清楚怎么在midway上应用。貌似passport-local介绍得有点少？

**Comment by czy88840616** [comment]
看上去就是个 outh 的验证器来着。。。提供了 middleware。。

**Comment by linzelong95** [comment]
@czy88840616 好的，谢谢。

**Comment by linzelong95** [comment]
@czy88840616 
hey,我看到网上的例子，都是校验成功或者失败后重定向到某个路由，那如果不重定向，而是以json的形式响应回前台（restful形式），该怎么配置呢？
<img width="1154" alt="info" src="https://user-images.githubusercontent.com/40480550/54614974-45eaa200-4a98-11e9-9c9d-13114d74d69a.png">

**Comment by czy88840616** [comment]
这个插件应该是强制重定向的吧。。。

**Comment by alongite** [comment]
嗨，我也没明白怎么在midway里面使用passport，有demo吗
