### ISSUE TITLE
midway3 用依赖注入的方式定义日志 transport有问题

### ISSUE THREAD

**Issue by fflrichard** [midwayjs/midway#1780]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* 3.0.13
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

下面是官网的示例：<br>
```
@Configuration()
export class AutoConfiguration {
  @Inject()
  loggerService: MidwayLoggerService;
  @Inject()
  customTransport: CustomTransport;
  async onReady() {
    const appLogger = this.loggerService.getLogger('customLogger');
    appLogger.add(this.customTransport);
  }
}
```

这里的`MidwayLoggerService.getLogger`的返回值是：`ILogger`，而不是`IMidwayLogger`，所以没有`add`这个方法

**Comment by czy88840616** [comment]
对的，故意的， ILogger  最为常用，只提供了几个特定的方法定义，也方便和其他日志对象做转换（比如 console），如果明确要用 midway logger 的add，需要显式声明类型

const appLogger = this.loggerService.getLogger('customLogger') as IMidwayLogger;

**Comment by fflrichard** [comment]
好的，谢谢
