### ISSUE TITLE
Validate的Rule装饰器能否加个参数翻译

### ISSUE THREAD

**Issue by LinFeng1987** [midwayjs/midway#1784]
很多时候往往希望将dto中的错误信息可以直接返回到业务，目前的Rule规则仅仅支持返回如下格式："\"password\" 长度必须小于或等于 16 个字符长"，而不能返回一个password参数被单独翻译后的message

**Comment by czy88840616** [comment]
文档有写啊
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/418820/156929391-7c7265bd-d646-4f69-bb53-de749b35cc33.png">

**Comment by LinFeng1987** [comment]
.error我目前就是用的这个，但还是感觉不是很方便，我是不是没救了😂

**Comment by czy88840616** [comment]
错误就几种

- 1、符合某个属性中单条规则的校验错误，比如一个属性字符串有校验超长的，也有校验不够位数的
- 2、某类规则报错的复写，比如所有字符串超过长度的错误文案覆盖
- 3、完全的自定义，比如某个字段不管报什么错，都统一返回一个 ”xxx 字段不对“

- 对于 1，如果默认的文案的不符合，你可以对单条属性中的单条规则做错误覆盖，比较麻烦

麻烦到什么程度呢，要单独定义这么大一串。。我觉得你应该不会接受的。。

```ts
export class UserDTO {
	@Rule(RuleType..string().max(10)
		  .message('{{#label}} data max over 10')
          .error(errors => {
            errors.forEach(err => {
              switch (err.code) {
                case 'any.empty':
                  err.message = 'Value should not be empty!';
                  break;
                case 'number.min':
                  err.message = `Value should have at least ${err} characters!`;
                  break;
                case 'number.max':
                  err.message = `Value should have at most ${err.code} characters!`;
                  break;
                default:
                  break;
              }
            });)
	name: string;
}
```

- 对于 2，使用 i18n 的规则覆盖，文档有描述
- 对于 3，直接使用 new Error

我理解应该够能覆盖场景了。。

**Comment by LinFeng1987** [comment]
感谢大佬指点
