### ISSUE TITLE
3.0 移除了createBootstrap 方法 但cli中自定义entryFile导致错误

### ISSUE THREAD

**Issue by Nawbc** [midwayjs/midway#1787]
* **Node Version**:
* **Midway Version(Decorator/Core)**: 3.0.13
* **Component Name/Version**: cli, mock
* **Platform**: Windows
* **Mini Showcase Repository**:

见 https://github.com/midwayjs/cli/blob/0f50734decf8613076b357a3cd7bfacf4bf171da/packages/cli-plugin-dev/src/child.ts#L43

**Comment by czy88840616** [comment]
3 应该不需要 entryFile 了，这是给 2 用的。

**Comment by yxmg** [comment]
请教下 3.0 不用entryFile的话 怎么在`midway-bin dev --ts`添加前置脚本
类似等价于 `egg-scripts start --node-options--require ./tracing.js`（前置启动 tracing.js）

**Comment by czy88840616** [comment]
dev 只是给开发用的，没法添加 node -r。
