### ISSUE TITLE
midway包报错的问题

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#179]
如图，昨晚一切顺利，今早打开项目，提示我controller等has no exported member
（这两天的早上，打开项目，怎么老是报错，这是昨天早上提交的issue [npm run dev报错](https://github.com/midwayjs/midway/issues/177) ）
![info](https://user-images.githubusercontent.com/40480550/54650718-c1753f00-4aea-11e9-9019-86f3a4f9b5ec.png)

**Comment by czy88840616** [comment]
感觉还是npm安装的问题，毕竟我们已经有快一周没有发布了.....

**Comment by czy88840616** [comment]
还有就是vscode本身的索引，你可以用命令行试试启动，如果可以，那就是vscode的问题了。

**Comment by linzelong95** [comment]
@czy88840616 
刚学这些不久，我不太清楚怎么用命令行启动。用了笨方法，删除node_modules，再安装，就可以正常使用了。

**Comment by czy88840616** [comment]
就是执行下 npm run dev...如果能跑..那就是vscode本索引的问题了...

**Comment by linzelong95** [comment]
@czy88840616 
早上那个错，好像执行npm run dev也报错吧
（我忘了我有没有试着启动，回想不起来）
