### ISSUE TITLE
日志logger 自定义根目录的问题

### ISSUE THREAD

**Issue by kkaaddff** [midwayjs/midway#1790]
* **Node Version**:14.17
* **Midway Version(Decorator/Core)**:3.1.0
* **Component Name/Version**:
* **Platform**:*
* **Mini Showcase Repository**:*
[在文档中](http://www.midwayjs.org/docs/logger#%E6%97%A5%E5%BF%97%E8%B7%AF%E5%BE%84%E5%92%8C%E6%96%87%E4%BB%B6
)
本地的日志根目录为 ${app.appDir}/logs/项目名 目录下
目录地址可以自定义

``` 
const logsPath = path.join(process.cwd(), 'logs')
config.midwayLogger = {
    default: {
      dir: logsPath,
    },
  }
```
但是错误日志以及其他日志会被记录到 roots 中，初步查看代码发现是`this.configService.getConfiguration('midwayLogger')`返回的
暂时修改配置:
```
const logsPath = path.join(process.cwd(), 'logs')
  config.midwayLogger = {
    // fix: 错误以及其他日志会被记录到 roots 中
    default: {
      dir: logsPath,
      auditFileDir: path.join(logsPath, '.audit'),
      errorDir: logsPath,
    },
  }
```
不知道是特性，还是bug，如果是feature的话是否需要修改文档

**Comment by czy88840616** [comment]
应该是bug。

**Comment by czy88840616** [comment]
我又调整了一下，最新的 pr 不再需要单独设置 auditFileDir 和 errorDir 了，会跟随 dir 自动判断。 #1791

**Comment by kkaaddff** [comment]
> 我又调整了一下，最新的 pr 不再需要单独设置 auditFileDir 和 errorDir 了，会跟随 dir 自动判断。 #1791

这样很符合使用习惯和预期
