### ISSUE TITLE
@midwayjs/swagger3.0.13不同接口之间参数覆盖的问题

### ISSUE THREAD

**Issue by ctq123** [midwayjs/midway#1806]

**Comment by ctq123** [comment]
![image](https://user-images.githubusercontent.com/12124169/157797142-ee920b4a-980b-4da1-9f00-099cb5da5f75.png)

**Comment by ctq123** [comment]
![image](https://user-images.githubusercontent.com/12124169/157797205-9a7c4c1b-3066-4dce-a509-5969b3732ba8.png)

**Comment by ctq123** [comment]
其实它们应该是不一样才对

版本如下：
@midwayjs 3.0.13
@midwayjs/swagger 3.0.13
@midwayjs/koa 3.0.13
nodejs v14.17.3

**Comment by czy88840616** [comment]
提供一个复现代码吧

**Comment by kurten** [comment]
body的 class 是不是重名了，swagger 不识别重名类，会覆盖掉的
