### ISSUE TITLE
关于更改项目目录名导致npm run dev报错的疑问

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#181]
hey,我更改了目录名，比如项目A更改成项目B，npm run dev时报错如图，请问哪些地方需要做相应的修改，谢谢。

![info](https://user-images.githubusercontent.com/40480550/54807710-0949c100-4cb9-11e9-907e-9ee57ab864ac.png)

**Comment by czy88840616** [comment]
改了项目名？无所谓吧。。。你这是 node_modules 又坏了吧。

ps: 你这是 windows。。。错误了多重装下依赖吧。。

**Comment by linzelong95** [comment]
@czy88840616 
我对项目重新命名，就报错。
如果我把项目名更改回原来的那个，就又可以使用。
所以是不是某些配置跟项目名关联上了。。。

**Comment by czy88840616** [comment]
并不会啊。。用户代码不会跟最顶层目录有关系啊。。你要不重装下依赖看看。。。也许是依赖里有跟根目录相关的部分，windows 体系可能比较奇怪，写的全路径什么的。

**Comment by linzelong95** [comment]
@czy88840616 
好吧，我重装依赖。谢谢。
