### ISSUE TITLE
在midway如何优雅地写中间

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#182]
hi，又要打扰了。。
自定义中间件，如何在midway优雅地写呢？
如图，这是一个koa-passport的中间件的使用，写出来的代码看起来很“原生”，感觉跟精心封装的midway有点“格格不入”，请问是否有更优雅的写法？
可否指点一二，谢谢。

![info](https://user-images.githubusercontent.com/40480550/54861348-9d239780-4d62-11e9-98a7-43aa84784cbc.png)

**Comment by czy88840616** [comment]
这就要看看怎么设计全局中间件支持了....

**Comment by czy88840616** [comment]
等我设计完...

**Comment by linzelong95** [comment]
@czy88840616 
ok. thanks
