### ISSUE TITLE
@midwayjs/redis 怎样做能支持 RedisJSON？

### ISSUE THREAD

**Issue by YSHIDM** [midwayjs/midway#1820]
* **Node Version**: v16.13.2
* **Midway Version(Decorator/Core)**: 3.0.0
* **Component Name/Version**: egg 1.2.1
* **Platform**: ubuntu20
* **Mini Showcase Repository**:"@midwayjs/redis": "^3.1.1"

请问 @midwayjs/redis 怎样做能支持 RedisJSON？ redis 已经安装好，RedisJSON 可用，但@types/ioredis 不支持 JSON 的 api。

**Comment by czy88840616** [comment]
ioredis 好像不支持 json api，可以选择其他的库。 https://oss.redis.com/redisjson/

**Comment by luin** [comment]
可以使用 `redis.call()` 方法。参考：https://github.com/luin/ioredis/blob/main/examples/module.js。@types/ioredis 可能没有提供相关声明，不过 ioredis v5 自带了官方的 TypeScript 声明。

**Comment by czy88840616** [comment]
作者说的对。

**Comment by YSHIDM** [comment]
但是 midway 的 redis ts 提示里没有 call 方法

**Comment by luin** [comment]
> 但是 midway 的 redis ts 提示里没有 call 方法

目前可以用 `// @ts-expect-error` 暂时忽略类型检查，等待 Midway 升级 ioredis 到 v5。cc @czy88840616

**Comment by czy88840616** [comment]
已升级
