### ISSUE TITLE
midway3控制器中的方法不是async的话获取不到req.Body内容,请问是正常的吗?

### ISSUE THREAD

**Issue by wgcairui** [midwayjs/midway#1831]
上面是方法没加async的,下面加了async
2022-03-18 09:35:23,588 INFO 45367 [midway:socketio] Socket.io server start success and attach to web server
2022-03-18 09:35:23,589 INFO 45367 [midway:ws] WebSocket server find shared http server and will be attach.
[ Midway ] Auto reload. [change] controller/open.ts
{
  data: {
    request: { method: 'POST', url: '/api/open/crc', header: [Object] },
    response: {
      status: 404,
      message: 'Not Found',
      header: [Object: null prototype]
    },
    app: { subdomainOffset: 2, proxy: false, env: 'local' },
    originalUrl: '/api/open/crc',
    req: '<original node req>',
    res: '<original node res>',
    socket: '<original node socket>'
  }
}
undefined
[ Midway ] Pre Process Force Exit.
2022-03-18 09:35:48,379 INFO 45396 [midway:socketio] Socket.io server start success and attach to web server
2022-03-18 09:35:48,379 INFO 45396 [midway:ws] WebSocket server find shared http server and will be attach.
[ Midway ] Auto reload. [change] controller/open.ts
{
  data: { pid: 1, instructN: '03', address: 0, value: 0, protocolType: 1 }
}
`
`

实际代码
`
/**
   * 生成crc校验码
   * @param param0
   * @returns
   */
  @Post('/crc')
  async crc(@Body() data: any) {
    console.log({ data });

    const { pid, instructN, address, value } = data;
    const c = Buffer.allocUnsafe(2);
    c.writeIntBE(address, 0, 2);
    const start = c.slice(0, 2).toString('hex');

    const d = Buffer.allocUnsafe(2);
    d.writeIntBE(value, 0, 2);
    const end = d.slice(0, 2).toString('hex');

    return {
      code: 200,
      data: this.Util.Crc16modbus(pid, instructN + start + end),
    };
  }
`

midway版本
`
"@midwayjs/bootstrap": "^3.1.1",
    "@midwayjs/core": "^3.1.1",
    "@midwayjs/decorator": "^3.0.4-beta.1",
    "@midwayjs/info": "^3.1.1",
    "@midwayjs/koa": "^3.1.1",
    "@midwayjs/logger": "^3.0.0-beta.13",
    "@midwayjs/oss": "^3.1.1",
    "@midwayjs/socketio": "^3.1.1",
    "@midwayjs/swagger": "^3.1.1",
    "@midwayjs/task": "^3.1.1",
    "@midwayjs/typegoose": "^3.1.1",
    "@midwayjs/validate": "^3.1.1",
    "@midwayjs/ws": "^3.1.1",
`

**Comment by czy88840616** [comment]
logger 用2（和2公用），decorator 也用正式

**Comment by wgcairui** [comment]
好的
