### ISSUE TITLE
midway3.15 TaskLocal本地定时任务无法获取ctx上到扩展方法?

### ISSUE THREAD

**Issue by li305263** [midwayjs/midway#1835]
`@TaskLocal(FORMAT.CRONTAB.EVERY_DAY)
  async updateMany() {
    console.log(this.ctx.helper);
}`
获取context上的扩展方法也是undefined
获取this.ctx.helper也是undefined

**Comment by czy88840616** [comment]
没错的，midway组件的ctx是midway的逻辑，只包含midway自己的标准接口，跟egg无关。

**Comment by li305263** [comment]
> 没错的，midway组件的ctx是midway的逻辑，只包含midway自己的标准接口，跟egg无关。

谢谢回复
如果想获取egg的ctx的话应该怎么做呢？用老的@Schedule 装饰器吗？

**Comment by czy88840616** [comment]
对，只有这一种方式。

**Comment by czy88840616** [comment]
文档已更新 https://midwayjs.org/docs/extensions/egg#%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1

**Comment by li305263** [comment]
> 文档已更新 https://midwayjs.org/docs/extensions/egg#%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1

好的感谢

**Comment by li305263** [comment]
> 文档已更新 https://midwayjs.org/docs/extensions/egg#%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1

以下为升级前的src/schedule 目录下的定时任务的日志， 是不是还有什么配置没改呢
2022-03-20 11:44:34,485 WARN 23464 [Job#16477478744821972533199836001] undefined#updateClass unknown task

**Comment by czy88840616** [comment]
的确，这里v3的兼容有点问题 https://github.com/midwayjs/midway/pull/1836

**Comment by czy88840616** [comment]
已修复，可以重装依赖。

**Comment by li305263** [comment]
> 已修复，可以重装依赖。
感谢，可以了
