### ISSUE TITLE
midway v3.1.5 上传获取不到原来2.X的流数据

### ISSUE THREAD

**Issue by li305263** [midwayjs/midway#1838]
底层web 使用的egg.
获取不到this.ctx.getFileStream()

**Comment by czy88840616** [comment]
是正常的，为了文档统一，midway新版本关闭了egg大部分插件而改为使用 midway 自己的组件，如需使用egg的内容，可以单独开启 egg-multipart 插件。

**Comment by li305263** [comment]
好谢谢。 确实在文档里又写
