### ISSUE TITLE
typegoose InjectEntityModel后拿到的model为undefined

### ISSUE THREAD

**Issue by Jeepeng** [midwayjs/midway#1840]
* **Node Version**: v16.14.0
* **Midway Version(Decorator/Core)**: @midwayjs/decorator@3.0.10 / @midwayjs/core@3.1.5
* **Component Name/Version**: @midwayjs/typegoose@3.1.5
* **Platform**: MacOS
* **Mini Showcase Repository**: [git@github.com:Jeepeng/midway-showcase.git](https://github.com/Jeepeng/midway-showcase)

按照文档 https://www.midwayjs.org/docs/extensions/mongodb 引入typegoose，```this.userModel``` 为```undefined```：
```ts
import { Provide } from '@midwayjs/decorator';
import { InjectEntityModel } from '@midwayjs/typegoose';
import { ReturnModelType } from '@typegoose/typegoose';
import { User } from '../entity/user';

@Provide()
export class TestService {
  @InjectEntityModel(User)
  userModel: ReturnModelType<typeof User>;

  async getTest() {
    // create data
    const { _id: id } = await this.userModel.create({
      name: 'JohnDoe',
      jobs: ['Cleaner'],
    } as User); // an "as" assertion, to have types for all properties

    // find data
    const user = await this.userModel.findById(id).exec();
    console.log(user);
  }
}
```

报错信息：
```
TypeError: Cannot read properties of undefined (reading 'create')
```

**Comment by czy88840616** [comment]
检查是否漏做
![image](https://user-images.githubusercontent.com/418820/159229059-3154a271-128c-45f8-8a74-78ab303ca0de.png)

**Comment by Jeepeng** [comment]
@czy88840616 没有漏
<img width="600" alt="image" src="https://user-images.githubusercontent.com/3993655/159229577-24a63d7e-4cb9-402e-b2fb-bf468c55e54d.png">

**Comment by czy88840616** [comment]
光这样我看不出来，提供一个复现仓库？

**Comment by Jeepeng** [comment]
@czy88840616 
git@github.com:Jeepeng/midway-showcase.git

**Comment by czy88840616** [comment]
初步判定是由于 ts 文件被加载了两次，装饰器被执行了两次造成的，奇怪的是同一个文件 require 没有被缓存，还在排查原因（编译后是好的）。

**Comment by czy88840616** [comment]
已查到问题，原因如下：

mac 对大小写不敏感，而 ts 加载文件又是大小写敏感的。

由于你的 entity/User.ts 是大写的，但是 在 service/user.ts 中 import 的代码是小写的，导致框架require 时和 import require 时加载了不同的 user 文件，导致内存里生成了两份不同的 User 实例。

解法：
统一用小写文件。

**Comment by Jeepeng** [comment]
已解决，感谢

**Comment by czy88840616** [comment]
推荐在 tsconfig 中增加 forceConsistentCasingInFileNames 的配置，可以规避该问题，我们也将在脚手架中增加该项。

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "inlineSourceMap":true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "stripInternal": true,
    "skipLibCheck": true,
    "pretty": true,
    "declaration": true,
    "forceConsistentCasingInFileNames": true,
    "typeRoots": [ "./typings", "./node_modules/@types"],
    "outDir": "dist"
  },
  "exclude": [
    "dist",
    "node_modules",
    "test"
  ]
}
```
