### ISSUE TITLE
@midwayjs/validate dynamic key

### ISSUE THREAD

**Issue by leozhang007** [midwayjs/midway#1844]
@midwayjs/validate 校验包的动态 key 应该怎么写呢？翻了文档及 issus 没找到，感谢。

**Comment by czy88840616** [comment]
什么叫动态key？有示例么？

**Comment by leozhang007** [comment]
@czy88840616 
export class ComponentsDTO {

  @Rule(RuleType.string().required())
  [key: string]: string;
}

类似这种

**Comment by czy88840616** [comment]
[key: string]: string; 是定义，并不是实际的代码，编译完就没了，没法做key。

**Comment by leozhang007** [comment]
用 joi 的写法可以，借鉴地址：https://github.com/sideway/joi/issues/1745
不过类型推断没了，改下接口结构吧
