### ISSUE TITLE
@midwayjs/orm 动态链接数据库

### ISSUE THREAD

**Issue by jiege1** [midwayjs/midway#1845]
请问一下，@midwayjs/orm 有办法动态链接数据库么？
目前我们不同用户之间的数据，通过数据库做了数据隔离。
我想自己管理一批数据库连接，根据客户端传入的用户标识选择链接对应的数据库。

**Comment by czy88840616** [comment]
我搜了一下，https://github.com/typeorm/typeorm/issues?q=Dynamic+Table+ typeorm 没有特别好的动态创建表去管理的功能，总的来说 orm 都不太适合。。

**Comment by jiege1** [comment]
好的，谢谢。目前我直接使用的typeorm，没有通过@midwayjs/orm的配置。自己管理了一个数据库连接池，将连接池作为全局唯一的依赖注入到应用实现了。
