### ISSUE TITLE
Swagger的@ApiResponse注解中的schema参数没有效果

### ISSUE THREAD

**Issue by dpzxsm** [midwayjs/midway#1847]
例如这样
```
  @ApiResponse({
    status: 200,
    schema: {
      type: 'object',
      properties: {
        data: {
          $ref: getSchemaPath(SysUser),
        },
      },
    },
  })
 async current() {
}
```

**Comment by kurten** [comment]
必须要有 content type，不然不知道返回具体什么类型，导致 swagger 不识别。

```
  @ApiResponse({
    status: 200,
    content: {
      'application/json': {
        schema: {
          properties: {
            data: { '$ref': getSchemaPath(Cat)}
          }
        }
      }
    }
  })
```

**Comment by dpzxsm** [comment]
@kurten  使用getSchemaPath(SysUser) 还是会报一个错误，无法生成schema
```
Resolver error at paths./user/current.get.responses.200.content.application/json.schema.properties.data.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/class SysUser {
} does not exist in document
```

**Comment by czy88840616** [comment]
新版本我还未发，等发布了再试试。

**Comment by jiege1** [comment]
@czy88840616 您好，请问一下。在使用ApiProperty注解标记users时，items.$ref 并没有发生任何作用？  比如下面这段


@ApiProperty({
    description: '关联的用户列表',
    required: false,
    type: 'array',
    items: { $ref: getSchemaPath(User.name) },
  })
  @ManyToMany(type => User, user => user.tags)
  @JoinTable({
    name: 'user_tag',
    joinColumns: [{ name: 'tag_id' }],
    inverseJoinColumns: [{ name: 'user_id' }],
  })
  users: User[];

**Comment by jiege1** [comment]
@czy88840616 您好，请问一下。在使用ApiProperty注解标记users时，items.$ref 并没有发生任何作用？ 比如下面这段

`  @ApiProperty({
    description: '关联的用户列表',
    required: false,
    type: 'array',
    items: { $ref: getSchemaPath(User.name) },
  })
  @ManyToMany(type => User, user => user.tags)
  @JoinTable({
    name: 'user_tag',
    joinColumns: [{ name: 'tag_id' }],
    inverseJoinColumns: [{ name: 'user_id' }],
  })
  users: User[];`

**Comment by jiege1** [comment]
@czy88840616 您好，在ApiProperty中使用items.$ref好像并没有起作用，比如下面这段，swagger.json就无法生成 对应的ref指向

`
  @ApiProperty({
    description: '关联的用户列表',
    required: false,
    type: 'array',
    items: { $ref: getSchemaPath(User.name) },
  })
  @ManyToMany(type => User, user => user.tags)
  @JoinTable({
    name: 'user_tag',
    joinColumns: [{ name: 'tag_id' }],
    inverseJoinColumns: [{ name: 'user_id' }],
  })
  users: User[];
`

**Comment by jiege1** [comment]
`

 @ApiProperty({
    description: '关联的用户列表',
    required: false,
    type: 'array',
    items: { $ref: getSchemaPath(User.name) },
  })

  @ManyToMany(type => User, user => user.tags)

  @JoinTable({
    name: 'user_tag',
    joinColumns: [{ name: 'tag_id' }],
    inverseJoinColumns: [{ name: 'user_id' }],
  })

  users: User[];
`

**Comment by jiege1** [comment]
@czy88840616  您好，ApiProperty注解使用items.$ref没有任何效果，并没有生成对应的$ref。比如下图这样

![image](https://user-images.githubusercontent.com/31118673/159851491-f49fd83d-59e4-4f33-b836-05370bc75504.png)

**Comment by jiege1** [comment]
swagger生成出来的json文件显示为：
{
  "users": {
  "type": "array",
  "items": {},
  "description": "关联的用户列表",
  "required": false
}

**Comment by czy88840616** [comment]
试试v3.2.0

**Comment by dpzxsm** [comment]
@czy88840616  你好，我刚刚已经升级到v3.2.1了，但是发现还是有这个问题，虽然swagger的json格式对了，但是swagger中没有自动生成相关的Schema
```
@ApiResponse({
    status: 200,
    content: {
      'application/json': {
        schema: {
          properties: {
            data: { $ref: getSchemaPath(SysUser) },
          },
        },
      },
    },
  })
```
swaager会报错 Could not resolve reference: Could not resolve pointer: /components/schemas/SysUser does not exist in document

**Comment by kurten** [comment]
确定一下你的 SysUser 有没有生成 schema。并不是随便一个 $ref 就生效的，需要保证你的 schema 中有 SysUser，即 SysUser 有加 @ApiProperty 描述所有字段。
不过这里建议直接使用 type: SysUser。

**Comment by dpzxsm** [comment]
@kurten  确定有@ApiProperty 描述的字段，用
```
  @ApiResponse({
    type: SysUser,
  })
```
这种类型就可以生成schema，如果当前控制器都是用getSchemaPath，就不会生成schema了

**Comment by kurten** [comment]
> @kurten 确定有@ApiProperty 描述的字段，用
> 
> ```
>   @ApiResponse({
>     type: SysUser,
>   })
> ```
> 
> 这种类型就可以生成schema，如果当前控制器都是用getSchemaPath，就不会生成schema了

getSchemaPath 的前提是之前 SysUser 已经被当作参数或者Body被扫描出来了，这样你可以直接生成一个 ref，不然你生成的ref没有 schema 引用的。
你的情况就是直接拼ref，但是 SysUser 前面都没有使用到。

**Comment by dpzxsm** [comment]
@kurten 这种方式不适合那种统一返回体的结构，相当于每个接口都要定义个返回类，这样工作量太大了。还是建议使用getSchemaPath的时候，可以自动加入到Schema，或者暴露出一个方法，可以手动加入shemale。

**Comment by jiege1** [comment]
我在使用 ApiProperty 时，当我定义一个array类型时，生成的schemas type为Array，导致swagger识别不了。
我尝试加上type: 'array'时，发现定义的 items.$ref 为空了？
请问有什么解决办法么？
代码如下图
![image](https://user-images.githubusercontent.com/31118673/160598015-ab9151db-7348-4343-aaca-bdb0f1998a6b.png)

注释掉type生成的schemas
`{
    "tags": {
        "type": "Array",
        "description": "用户标签列表",
        "required": false,
        "items": {
            "$ref": "#/components/schemas/Tag"
        }
    }
}
`

不注释则是
`{
    "tags": {
        "type": "array",
        "items": {},
        "description": "用户标签列表",
        "required": false
    }
}`

**Comment by czy88840616** [comment]
@jiege1 单独issue吧，合并在一个问题下不好追踪的。

**Comment by dpzxsm** [comment]
@ApiExtraModels  注解我试过已经没有问题了
