### ISSUE TITLE
midway 类型编译出错：TS2322 

### ISSUE THREAD

**Issue by Realzzz1874** [midwayjs/midway#1849]
* **Node Version**: v16.13.1
* **Midway Version(Decorator/Core)**: decorator: 2.14.0 / core: 2.14.6
* **Component Name/Version**:
* **Platform**: Windows
* **Mini Showcase Repository**:

在非 midway 的项目中，这种字典转换的写法是 OK 的，但是 midway 项目中***有些字典偶尔***会出现编译不通过的情况。

```javascript
export enum ModerationTargetType {
  userNickname = 1,
  articleContent = 2,
  groupIntro = 3,
  comment = 4,
}

export const moderationTargetTypeList: DictList<typeof ModerationTargetType> = [
  [ModerationTargetType.userNickname, '用户昵称'],
  [ModerationTargetType.articleContent, '文章正文'],
  [ModerationTargetType.groupIntro, '小组简介'],
  [ModerationTargetType.comment, '评论'],
];

// 其中 DictList 函数为：
export type DictList<E, U = UnionToTuple<keyof E>> = {
  [n in keyof U]: [U[n] extends keyof E ? E[U[n]] : never, string];
};
```

编译报错为：

```bash
error TS2322: Type 'ModerationTargetType.userNickname' is not assignable to type 'ModerationTargetType.comment'.
error TS2322: Type 'ModerationTargetType.articleContent' is not assignable to type 'ModerationTargetType.userNickname'.
error TS2322: Type 'ModerationTargetType.groupIntro' is not assignable to type 'ModerationTargetType.articleContent'.
error TS2322: Type 'ModerationTargetType.comment' is not assignable to type 'ModerationTargetType.groupIntro'.

```

**Comment by czy88840616** [comment]
不是很完整啊，https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwLIQCbCgQxgEsJEAVfKAc2BjIE8xg4BvAKDjmQGc8A5IgGMA1onypmAXjgBGADQc4lYoIA2wAMKkYSeNIBMCzlSgRkYAJKIYpuNIDMRuIIioJ1u3AAsCgL5s2UEhYZ1JueFQcPEISckoaOkZgABkicIAuOAARIRhU8IAeGCSIADNMKIJiUgpqWgYmAD5PAG1FFqxcKtjahIbgADoefiFRcWA5OAByQApXQHYjQFYzQAfPKYBdJw7KmJr4+qSB5SF1LWtdSanAcNNAA69AY2sLtY3O6Oq4usSmAZMzS2tTc8B4HUAI36AAO9ANNyD3aT26Oze-QGLjcZ2mgBHowBd0RDVgBuAIAehxcEAboqAWjlsrl8vBAL+KgAdTQBccoAsf8C4Gg8GKTFJgjyaRgBQAopMAKqefmIHoQMjmdQFYTAehlOA8xrNaTsTgtRBwIjq6Wy8r81aZFr8tWrBAgHSIbDcODauU8uAAfnlhuNJsyiGAADc8JNwlBNVQsWxfJigA

在playground先跑下吧。

**Comment by Realzzz1874** [comment]
@czy88840616 sorry，漏了 UnionToTuple 的定义
```javascript
type UnionToTuple<T> = (
    (T extends any ? (t: T) => T : never) extends infer U
      ? (U extends any ? (u: U) => any : never) extends (v: infer V) => any
        ? V
        : never
      : never
  ) extends (_: any) => infer W
    ? [...UnionToTuple<Exclude<T, W>>, W]
    : [];
```

另外，在 playground 中加入 UnionToTuple 之后没有报错。
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwLIQCbCgQxgEsJEAVfKAc2BjIE8xg4BvAKDjmQGc8A5IgGMA1onypmAXjgBGADQc4lYoIA2wAMKkYSeNIBMCzlSgRkYAJKIYpuNIDMRuIIioJ1u3AAsCgL5s2UEhYZ1JueFQcPEISckoaOkZgABkicIAuOAARIRhU8IAeGCSIADNMKIJiUgpqWgYmAD5PAG1FFqxcKtjahIbgADoefiFRcWA5OAByQApXQHYjQFYzQAfPKYBdJw7KmJr4+qSB5SF1LWtdSanAcNNAA69AY2sLtY3O6Oq4usSmAZMzS2tTc8B4HUAI36AAO9ANNyD3aT26Oze-QGLjcZ2mgBHowBd0RDVgBuAIAehxcEAboqAWjlsrl8vBAL+KgAdTQBccoAsf8C4Gg8GKTFJgjyaRgBQAopMAKqefmIHoQMjmdQFYTAehlOA8xrNaTsTgtRBwIjq6Wy8r81aZFr8tWrBAgHSIbDcODauU8uAAfnlhuNJsyiGAADc8JNwlBNVQsWxfNjOKzmMLReKwJKyEq4AAKRSceNkU3my1KRD0B0JmCZMgASjszVTbs9eCLoHTVs1pTwcH5Sc4OfjgqrSAz+CzLeQmX5RckzS72bLXqglbNHat8Y9mVr9YAagOh1mm82cwu183R3gtzuoIoJ9WEwB9TLD5caxB1qBwADqTcdLQGL4jNTFEuAvJAamQuAKZCTHeipAasTYGliQA

**Comment by czy88840616** [comment]
我试了v3没有问题，v2的话，估计是typescript/ts-node 版本太低了吧。

**Comment by Realzzz1874** [comment]
@czy88840616 感谢帮助排查！
但奇怪的是，项目中用了很多这种字典转换，大部分的时候它都可以正常运行，偏偏这个出了问题。
PS: ts-node 的版本是 9.0.0

**Comment by czy88840616** [comment]
我在 v2 似乎也没出现问题。。

**Comment by Realzzz1874** [comment]
@czy88840616 
这也是我纠结的点，因为很多字典都是通过这种方式来定义转换。之前也出现过这个问题，改改变量名字换个位置也能编译通过，但是经常出现很令人头疼，而且又只在 midway 的这个项目中出现，所以想了解一下是否是 midway 在编译的时候有做一些特殊处理。

**Comment by czy88840616** [comment]
midway 用的是 mwcc（包裹了tsc），你可以试试直接用纯 tsc。

**Comment by Realzzz1874** [comment]
@czy88840616 
好的，感谢帮助！
我抽空去研究一下这个问题。

**Comment by waitingsong** [comment]
enum 类型比较麻烦，有时候得先编译下相关 enum 类型，引用到这个类型的地方才正常。

如果LZ对于变量类型校验不那么严格可以直接用 ENUM 作为泛型参数
- 如果枚举值带有数字，那么无法严格约束值
- 如果采用字符串枚举，可以完美实现强约束并且底层类型不会那么复杂（ `UnionToTuple` 属于骚操作，容易出问题。我现在不使用了）

[PLAY](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwLIBUsCY4DeAUHHMgM7BQByAlgMYDWiAhqsHALxwCMANCTgtYDADbAAwhEQwk8brgGkA5lAjIwASRlqucAMxK49CKnYy9AFgEBfIvdCRYx6eXipcALjgARBjAAebDwAPj0AbUFw4NwAOgoqOiZWdj44AHJACldAdiNAVjNAB890gF0jaJw44RgxSWlZGTT0wHDTQAOvQGNrRuLSmNjVdS0dCAbAeB1AEb9AAO9AablOqO6TMzkGwBHowC7o6dJwgFYNhv1dztIAegO4AIBac7hAWDlALHlASHNAbx9AaPVAIH1ADj0iIoBuB3BoeBgAJ5gDh+eiBLBhbgAJQgAHcAhDwkUiI4-nBAcC4DD4QBpSFwcI4tJuKC0RDKZE-JzwJBoTA4QiCBI0BjMNgcbjpZlJNnsdJGSrVKQyOR6dKC+jiYV1GD8wS9DTaGC6TkK-rKiBy0hzczyDI6uRauBHOAAMwgED0hjgAEIroBfgMAZHq3QAOpoB1bUAPApEOwo37OEyINxwVAwGDeUGBYL4yLrYLxSgs5Lsho5AprAlxiVS2oLDItdrpspYHpqRUDYbjKYlGY4WIG+oZFaF9L12UNU37Y3HM6nOBPQCYqYB76Ki+msGQ7RUO3YuA+HRSAA)

**Comment by Realzzz1874** [comment]
@waitingsong 感谢答疑！
想请教一下，为什么 enum 相关类型需要先编译一下呢，对这块知识有些欠缺，想了解一下原理。

**Comment by waitingsong** [comment]
> @waitingsong 感谢答疑！ 想请教一下，为什么 enum 相关类型需要先编译一下呢，对这块知识有些欠缺，想了解一下原理。

enum 和 Clase 相同，既是类型也是值。对于 monorepo（比如 lerna 管理）项目，如果 A子包定义并导出枚举类型，然后 B子包引入使用这个枚举类型，那么当修改了这个枚举类型之后，B包中能并不能自动感知到类型的变化，必须把 A 编译一次（生成了js以及 d.ts）之后才会正常。而对于 interface、type 类型就不用额外编译了，自动就感知到了。

**Comment by Realzzz1874** [comment]
@waitingsong 多谢大佬解惑，thx！
