### ISSUE TITLE
Windows平台Powershell和Cmd还是无法创建项目，要不就是跑不起来

### ISSUE THREAD

**Issue by yzbgyq** [midwayjs/midway#185]
![image](https://user-images.githubusercontent.com/32931212/55147975-5549a980-5182-11e9-8952-a918462f8ae5.png)

**Comment by czy88840616** [comment]
windows的环境变量设置得换一下...

yzbgyq <notifications@github.com>于2019年3月28日 周四下午8:19写道：

**Comment by yzbgyq** [comment]
对windows这么不友好吗？关键是项目也拉不下来

**Comment by czy88840616** [comment]
😢，windows 的 cmd 问题实在是很诡异，之前有说 git bash 运行脚手架可以使用。

另外，windows 的环境变量需要做一些修改，[文档里也有列出](https://midwayjs.org/midway/guide.html#windows-%E6%94%AF%E6%8C%81)。

```
{
  "dev": "set NODE_ENV=local && midway-bin dev --ts"
}
```

**Comment by yzbgyq** [comment]
谢谢，在windows上跑起来了，但是不知道后续开发在windows上还有哪些坑？不敢用啊

**Comment by czy88840616** [comment]
目前看来除了脚手架生成会卡住，环境变量设置的不一致外，其他的问题还没发现，最大的问题还是相关的库的兼容性，只要 ts-node/node/typescript 能保证兼容性，其他的问题不是特别大。
