### ISSUE TITLE
使用npm run start_build打包并运行项目， 如下报错该如何解决？

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#186]
hi, 打扰了，请教个问题。
我使用start_build （npm run build && set NODE_ENV=development && midway-bin dev）打包并运行项目，出现了错误，请问如何解决这个问题。谢谢。
（已知在直接使用npm run dev直接运行的情况下并无报错。）

![info](https://user-images.githubusercontent.com/40480550/55532248-bd970e80-56df-11e9-9008-f54e8018cab2.png)

**Comment by czy88840616** [comment]
恩。。这是我的bug。。原因是因为执行start_build 的时候走了 js 模式，但是内部判断又加载了 ts。

**Comment by linzelong95** [comment]
@czy88840616 
也就是不影响线上的启动？

**Comment by czy88840616** [comment]
恩，线上不会走这个，这个之前只是为了本地测试用。

**Comment by linzelong95** [comment]
@czy88840616 
好的，谢谢

**Comment by linzelong95** [comment]
@czy88840616 

hello， 我尝试着用egg-scripts的方式把项目部署到线上，但我访问时，程序报错“please set config.keys first”，如图。
这个config.keys是config.default.js里的配置吗？
（默认地，config.keys = appInfo.name + '_1552632441524_9669'）

我该做何修改，才能不报错？谢谢。

![info](https://user-images.githubusercontent.com/40480550/55542604-f93ed200-56f9-11e9-9216-4754194d0800.png)

**Comment by czy88840616** [comment]
得先 npm run build。

**Comment by linzelong95** [comment]
@czy88840616 

我已经在本地执行了npm run build ,然后将项目上传至服务器（除去node_modules），在服务器的项目里使用npm install --production，然后npm start（egg-scripts start）启动。访问时就报set  config.keys first。 so  how to deal  with  it ....

**Comment by czy88840616** [comment]
dist 目录上传了吗？

**Comment by linzelong95** [comment]
@czy88840616 
除了node_modules,其他的包括dist都上传了。

![info](https://user-images.githubusercontent.com/40480550/55543512-c0076180-56fb-11e9-9b82-f6ed3052558e.png)

**Comment by czy88840616** [comment]
这种可能有：

- 1、在根目录中除了 src 外，还有其他的目录包含 ts 文件，这个要看下 dist 目录里的结构
- 2、这个app目录是啥。。

**Comment by linzelong95** [comment]
@czy88840616 
1. dist结构如图一。
2. tsconfig.json如图二。
3. 根目录的app目录，是我在客户端访问url自动生成的，里边只有一个空的public文件夹

![dist](https://user-images.githubusercontent.com/40480550/55544400-994a2a80-56fd-11e9-85b8-1788bb59f235.png)

![tsconfig](https://user-images.githubusercontent.com/40480550/55544415-9cddb180-56fd-11e9-9caa-6034db01397a.png)

**Comment by czy88840616** [comment]
看上去没有什么大问题，能给我开个权限看看么

**Comment by linzelong95** [comment]
@czy88840616 
原谅我不知道怎么开权限，毕竟是真小白。
这是代码地址，包含dist文件夹  ，[project](https://github.com/linzelong95/blog_system/tree/master/blog_server_midway)

**Comment by czy88840616** [comment]
我知道问题了

- 1、主要问题是，start 命令没有传递 framework，参考[这里](https://github.com/midwayjs/midway/blob/master/packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json#L26)
- 2、次要问题，貌似你用的代码脚手架是我们用于创建 demo 的脚手架，并不是真正的项目。。里面的依赖有很多不同，可以对照一下。

**Comment by linzelong95** [comment]
@czy88840616 
hi， 添加了--framework=midway，还是报错？

![info](https://user-images.githubusercontent.com/40480550/55692196-2f20d680-59d8-11e9-9fe1-971b20a15169.png)

**Comment by czy88840616** [comment]
看起来还是走到了 ts 的逻辑，难道 windows 判断不一样。。我去装个 windows 看看。。

**Comment by linzelong95** [comment]
@czy88840616 
hi,请问这个报错问题，现在有什么解决思路呢？谢谢。

**Comment by czy88840616** [comment]
我的 windows又被回收了，虚拟机镜像还在从 icloud 慢慢拉。。。

大概率是出在判断 typescript 的地方，根路径识别错误了。midway 有几个判断是否是 typescript 的地方。

- webLoader，判断是读取 src，还是 dist，[这里](https://github.com/midwayjs/midway/blob/master/packages/midway-web/src/loader/webLoader.ts#L101)
- agent/worker 加载 ts-node 的地方，[这里](https://github.com/midwayjs/midway/blob/master/packages/midway/cluster/agent_worker.js#L5)

可以帮我定位下-。-

**Comment by linzelong95** [comment]
@czy88840616 
水平太次，只得以看个大概。有一处不解，为何图中exports.isTypeScriptEnvironment()的判断要取反？

![info](https://user-images.githubusercontent.com/40480550/56108429-7d0c8000-5f7e-11e9-85c2-e217b8790b71.png)

**Comment by czy88840616** [comment]
不在ts环境的，才去加载 ts-node.

**Comment by czy88840616** [comment]
我发了个新版 midway@1.5.1，把 ts-node 依赖删了，你测测看，。

**Comment by linzelong95** [comment]
@czy88840616 
谢谢啦，
现在报unexpected token export。
我想过段时间再来瞧瞧。。。

**Comment by czy88840616** [comment]
行，有问题可以开新 issue。已经close的很难被发现。。
