### ISSUE TITLE
请问websocket这部分大概要多久能调整完成？

### ISSUE THREAD

**Issue by rxxcy** [midwayjs/midway#1864]

**Comment by czy88840616** [comment]
现有的不改，只是要加中间件的支持。

**Comment by biuuu** [comment]
@czy88840616 请问 SocketIO 组件有对应的函数式写法吗？

**Comment by czy88840616** [comment]
没有的

**Comment by shadowyun** [comment]
怪不得中间件一直不生效

**Comment by czy88840616** [comment]
是的，socket是事件机制，中间件支持特别困难

**Comment by shadowyun** [comment]
现在socket这边是支持aspect的吗？需要自己实现一下auth

**Comment by czy88840616** [comment]
支持。

**Comment by cc4dogman** [comment]
我为了支持socketio2.x版本都是直接把最新源码copy到内部去改了,直接写一个framework太麻烦了

**Comment by czy88840616** [comment]
差不多了，上周刚把 socket的中间件加了。。最近是在太忙了。

**Comment by huanshiwushuang** [comment]
this.socketApp.useMiddleware([AuthMiddleware]);  一直不生效，连 resolve 方法都没进去到。你们会这样吗？
"dependencies": {
    "@midwayjs/bootstrap": "^3.0.0",
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/decorator": "^3.0.0",
    "@midwayjs/info": "^3.0.0",
    "@midwayjs/koa": "^3.0.0",
    "@midwayjs/logger": "^2.14.0",
    "@midwayjs/socketio": "3",
    "@midwayjs/static-file": "3",
    "@midwayjs/validate": "^3.0.0",
    "@socket.io/admin-ui": "^0.5.1",
    "@socket.io/redis-adapter": "^8.1.0",
    "bcryptjs": "^2.4.3",
    "cross-env": "^6.0.0",
    "ioredis": "^5.3.1"
  },
  "devDependencies": {
    "@midwayjs/cli": "^2.0.0",
    "@midwayjs/mock": "^3.0.0",
    "@types/jest": "^29.2.0",
    "@types/koa": "^2.13.4",
    "@types/node": "14",
    "jest": "^29.2.2",
    "mwts": "^1.0.5",
    "socket.io-client": "^4.6.1",
    "ts-jest": "^29.0.3",
    "dayjs": "^1.11.7",
    "typescript": "~4.8.0"
  },
