### ISSUE TITLE
中间件的ignore方法里面，获取不到config装饰器的配置信息

### ISSUE THREAD

**Issue by xqh-jason** [midwayjs/midway#1867]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/75606017/160525774-20e96079-a956-4277-adae-b5345ccaa6ab.png)
this.routeWhiteList  undefined

**Comment by daixiongsheng** [comment]
中间件里面没有this，可以从ctx上取

<img width="552" alt="image" src="https://user-images.githubusercontent.com/28498805/160638218-612e2413-5c5d-4e63-a777-9205b2377555.png">

**Comment by czy88840616** [comment]
这里是this丢了，要有的。

注意：ctx.app 并不是标准 api，：）
