### ISSUE TITLE
希望 npm init midway 能支持聚合部署v3版本

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#1877]
https://midwayjs.org/docs/serverless/serverless_aggr

按照官方文档装完才发现是v2的

**Comment by czy88840616** [comment]
聚合部署在代码和逻辑层面和标准项目差异都不大，所以我们想如果一个函数要多个路由，就干脆直接用标准项目代替了。

**Comment by pilaoda** [comment]
明白了，那我用koa-v3，就可以直接deploy了是吧？还需要再做额外的聚合相关的配置吗？

**Comment by pilaoda** [comment]
https://midwayjs.org/docs/serverless/migrate_midway

是按这个来吗？如果是的话，希望能提供一个模板，方便把这个文档里的配置都提前配好。感谢

**Comment by czy88840616** [comment]
对。

**Comment by pilaoda** [comment]
好的，或者指点一下这个生成模板的代码在哪一块，如果我研究好看看能不能提个pr

**Comment by czy88840616** [comment]
这种能组合的我们一般就不做模版了，一是模版多了很难维护，二是聚合物部署不算是在serverless主推的模式（感觉不太好）

**Comment by czy88840616** [comment]
大多数的聚合的需求为中后台或者小流量http服务，不是说不好用，而是和应用上serverless同质化了，这点上用户也很难理解其中的区别，所以保留一种即可。
