### ISSUE TITLE
请问如何同时部署多地域阿里云FC

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#1878]
例如我有一个日志采集服务，想部署到全球各个地域的阿里云函数计算，怎样部署才是最佳实践呢？
目前配置f.yml没有发现能同时发布多个地域的机制

**Comment by czy88840616** [comment]
是阿里云 sls ？

**Comment by pilaoda** [comment]
不是sls，只是我一个日志的中转服务器，想在各个地区都部署一台中转服务器，然后再写入各个地区的sls。
因为我的客户端应用并不能用sdk直接采集日志，只能通过http发给我的中转服务器

**Comment by czy88840616** [comment]
我理解一下，你想通过各个地域的函数搭建一个给前端用的日志服务，前端发送打点到函数，函数来记录到各地的 sls 服务？

**Comment by pilaoda** [comment]
目前我想到一个办法，就是在f.yml里，通过环境变量指定地域，把npm run deploy改成
` NODE_ENV=hangzhou mw deploy & NODE_ENV=shenzhen mw deply`

**Comment by czy88840616** [comment]
额yml本身好像也不支持多个region配置，如果 serverless devs 支持的话，也可以直接用，进 .serverless 里发布即可。

**Comment by pilaoda** [comment]
好吧，多谢
