### ISSUE TITLE
如何拿到 raw 类型的 request body 数据?

### ISSUE THREAD

**Issue by zhenxiedd01** [midwayjs/midway#190]
请问如何拿到 raw 类型的 request body 数据?

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
`ctx.request.rawBody`，参考https://github.com/koajs/bodyparser

**Comment by zhenxiedd01** [comment]
谢谢 @czy88840616 回复，刚用我们这个midway，不太熟悉，再多问一下：
我们的parser是用的koajs/bodyparser么？怎么ctx.request里没提示有rawBody这个属性呢？还是我需要另行配置这个koajs/bodyparser。

**Comment by czy88840616** [comment]
提示？是指 ts 提示么，这个大概率没有，自己标下或者 any 吧。

koa-bodyparser 这个是 egg 引入的。 https://github.com/eggjs/egg/blob/master/app/middleware/body_parser.js

**Comment by zhenxiedd01** [comment]
ok，try it tomorrow，thanks。

**Comment by zhenxiedd01** [comment]
change to `ctx` type `any`, ctx.request.rawBody work fine 
thanks @czy88840616

**Comment by czy88840616** [comment]
```
import { Context } from 'midway';
```

context 的定义是有从 egg 导出的，但是我不确定 egg 是否有包含 bodyparser 的定义。

**Comment by zhenxiedd01** [comment]
大概看了下，egg里并没有导出完整的bodyparser定义，选择导出了大多数定义，但不是全部。

**Comment by czy88840616** [comment]
额。。那只能 any 了。。
