### ISSUE TITLE
如何对ValidationError 统一处理 返回

### ISSUE THREAD

**Issue by riskgod** [midwayjs/midway#1902]
hey 遇到个问题 dto 校验的时候 会有 ValidationError，想对这些 ValidationError在中间件 做个统一处理，请问如何 catch 这一类型的err

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/extensions/validate#2%E5%A4%84%E7%90%86%E6%A0%A1%E9%AA%8C%E9%94%99%E8%AF%AF
