### ISSUE TITLE
疑问，依赖注入会存储类本身，是直接存储到内存中么，这样会不会造成，项目过大时占用内存过多，为什么不存储类的文件路径 需要创建时动态加载，

### ISSUE THREAD

**Issue by yuntian001** [midwayjs/midway#1904]
**下面是文档中的原文：**
依赖注入原理
我们以下面的伪代码举例，在 Midway 体系启动阶段，会创建一个依赖注入容器（MidwayContainer），扫描所有用户代码（src）中的文件，将拥有 @Provide 装饰器的 Class，保存到容器中。

这里的依赖注入容器类似于一个 Map。Map 的 key 是类对应的标识符（比如 类名的驼峰形式字符串），Value 则是 类本身。

**疑问：**
1.依赖注入会存储类本身，是直接存储到内存中么，这样有没有项目过大时占用内存过多的可能。
2.为什么不采用存储类的文件路径 需要创建时动态加载的方式以避免内存占用过多。

**Comment by czy88840616** [comment]
- 1、本身 node 所有的代码都是需要 require 的，这部分一直在内存中，不管 midway 存不存，都只是个引用关系
- 2、文件路径在 require 之后，都是无法获取到的信息，如果存文件路径，那就属于动态 require，会对类型分析造成巨大的干扰，内存问题，同1，另外，也有不同的打包模式（比如 ncc）合并为一个文件之后没有路径的信息，也就无法做这种行为

**Comment by yuntian001** [comment]
如果是在初次运行时进行类型分析，每个引用的类型分析完成后后立即释放掉对应的引用 或者 将其放在build命令中，将分析结果和引用路径关系缓存到特定的json文件中，需要实例化的时候再根据路径动态require，是不是可以规避内存问题。

打包默认为一个文件 确实无法做这种行为。

是否可以透露目前阿里内部成熟的项目启动后占用内存大约多大，以便于看是否需要过于纠结文件内存加载问题。

**Comment by czy88840616** [comment]
价值很小，而且会破坏现有标准的 node 模块体系。首先你无法精确区分到底哪些是需要动态引用的，所有的模块都会直接或者简单在代码中被依赖到（除非有一些废代码，完全不用），比如一开始就要初始化路由，分析，拿到实际的方法，这个时候必须是要类本身的，同时因为类代码里必然会注入某个对应的类，这个时候依赖，以及依赖的依赖都会 require 在内存中的。

纯 require 的代码内存并不大，除非加载特定的大资源，否则无需纠结内存问题。

**Comment by czy88840616** [comment]
一般 node 项目，正常的内存都在 200m 以内（100-200 动态）。
