### ISSUE TITLE
swagger中,ApiBody,ApiQuery,ApiParam用法拓展.

### ISSUE THREAD

**Issue by developeryvan** [midwayjs/midway#1905]
![image](https://user-images.githubusercontent.com/47513562/163101138-3528b18c-7ad2-44a7-a845-a5ed26e29abc.png)
目前ApiBody,ApiQuery,ApiParam必须配合@Body,@Query,@Param才有效果,请教下,单独使用ApiBody,ApiQuery,ApiParam,可否也支持下类型获取,如图所示.

**Comment by kurten** [comment]
这样不支持，拿不到参数哦

**Comment by developeryvan** [comment]
![image](https://user-images.githubusercontent.com/47513562/163102949-84f089b0-27e9-479d-af0d-1a676688d27f.png)
这里是拿不到函数的参数,但感觉应该可以根据metaForMethods扩展下.

**Comment by developeryvan** [comment]
![image](https://user-images.githubusercontent.com/47513562/163420656-f8498fa0-92ba-4630-a75d-0d89b1bc94fa.png)
大概思路就是没有WEB_ROUTER_PARAM_KEY的时候再添加下metaForMethods的类型参数,老哥帮忙看看能不能实现?

> 这样不支持，拿不到参数哦

**Comment by kurten** [comment]
> ![image](https://user-images.githubusercontent.com/47513562/163420656-f8498fa0-92ba-4630-a75d-0d89b1bc94fa.png) 大概思路就是没有WEB_ROUTER_PARAM_KEY的时候再添加下metaForMethods的类型参数,老哥帮忙看看能不能实现?
> 
> > 这样不支持，拿不到参数哦

组件实现上面是独立的，只用 swagger 的装饰器，router 是不会执行相关逻辑的。
