### ISSUE TITLE
 "loggerService"报错

### ISSUE THREAD

**Issue by Tmamasay** [midwayjs/midway#1917]
错误截图：
![image](https://user-images.githubusercontent.com/31384364/163553290-a9625b3e-25fd-4625-9a32-c016f2255ab6.png)

描述：node版本为^14时,运行没有问题，升级到^16后，重新安装依赖，运行报错

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/how_to_update_midway#%E6%99%AE%E9%80%9A%E9%A1%B9%E7%9B%AE%E6%9B%B4%E6%96%B0

主要是 lock。

**Comment by Tmamasay** [comment]
感谢🙇‍，可以了
