### ISSUE TITLE
一体化项目，文件上传一半，断开后导致程序崩溃

### ISSUE THREAD

**Issue by tianming-1986** [midwayjs/midway#1918]
![lQLPDhtVdtde5o_NAb_NAoawTMtKVWwGeSkCXLKhbMBvAA_646_447](https://user-images.githubusercontent.com/97207423/163555564-d5a28fcb-64ce-4401-8e26-99a0dc102bc8.png)

**Comment by echosoar** [comment]
fixed: https://github.com/midwayjs/cli/pull/292
