### ISSUE TITLE
项目内的tsx文件如何不被导出？

### ISSUE THREAD

**Issue by shinku** [midwayjs/midway#1920]
目前在项目中用到了一个邮件功能，邮件内的html文件通过tsx文件编写，用了react-dom 的 renderToString，方便数据导入，以及后期维护。但是在build完成之后在dist目录下也包含tsx文件，导致了start 的时候出现模块解析的问题。
现在的方案是在导出的时候不需要到处 这个tsx 文件，这种情况下可以避免run的时候文件解析出现问题，即可以正常运行。
所以现在的问题是，如何在我build的时候不用到导出这个tsx 文件。谢谢～

**Comment by czy88840616** [comment]
我理解可以在 tsconfig 里 ignore 掉这个文件，如果不希望被 midway 加载，可以参考 https://midwayjs.org/docs/container#%E8%87%AA%E5%8A%A8%E7%BB%91%E5%AE%9A
