### ISSUE TITLE
写API时，提供较好的API文档支持

### ISSUE THREAD

**Issue by topwood** [midwayjs/midway#193]
```
@get('/:name')
  async getProductByName(ctx): Promise<void> {
    const name: string = ctx.params.name;
    const product = await this.service.get(name);
    ctx.body = {success: true, message: 'OK', data: product};
  }
```
例如以上代码，可以对该方法做一些注释（例如JSdoc格式），在package.json中提供相应的命令，生成对应的api文档，最终样子类似Swagger那种

**Comment by zhenxiedd01** [comment]
关注

**Comment by Lvison** [comment]
关注

**Comment by czy88840616** [comment]
我们内部也是使用 tsdoc 来生成文档，如果有把装饰器的修饰，再生成文档做成一种能力，也不错。

**Comment by skmdev** [comment]
可以增加類似 fastify 驗證request body 的decorator 
https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md
然後再生成swagger doc

**Comment by czy88840616** [comment]
我研究下 swagger doc，😄

**Comment by Lvison** [comment]
egg-swagger-doc 这个插件

> 我研究下 swagger doc，😄

egg-swagger-doc 这个插件还不错感觉，不过我研究了下 好像不支持midway，如果支持也是不错的

**Comment by czy88840616** [comment]
插件我理解只要没有特别针对后缀做处理的话吗，应该都是支持的。

**Comment by Lvison** [comment]
> 插件我理解只要没有特别针对后缀做处理的话，应该都是支持的。

我的问题，另外一个插件影响到

**Comment by anthhub** [comment]
> > 插件我理解只要没有特别针对后缀做处理的话，应该都是支持的。
> 
> 我的问题，另外一个插件影响到

egg-swagger-doc  所以这个是可以用的吗

**Comment by Lvison** [comment]
是可以用的，另外我有一些特别的需求，自己fork下来改到本地了

**Comment by anthhub** [comment]
> 是可以用的，另外我有一些特别的需求，自己fork下来改到本地了

好的 多谢

**Comment by csjiabin** [comment]
> egg-swagger-doc 这个插件
> 
> > 我研究下 swagger doc，😄
> 
> egg-swagger-doc 这个插件还不错感觉，不过我研究了下 好像不支持midway，如果支持也是不错的

只能在开发环境用

**Comment by czy88840616** [comment]
已经有 swagger 组件了。
