### ISSUE TITLE
需求:能否让热更新文件夹自定义可以支持多个文件夹进行热更新

### ISSUE THREAD

**Issue by yuntian001** [midwayjs/midway#1933]
比如我想用以下目录结构开发自定义组件
|---package1
|---src
我期望热更新监听src和package1两个文件夹
这样开发package1组件时热更新也会生效

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/tool/cli#dev-%E5%91%BD%E4%BB%A4

**Comment by yuntian001** [comment]
感谢。

**Comment by yuntian001** [comment]
--watchFile 支持模糊或正则匹配么
 如midway-bin dev --ts --watchFile=./package1/*/src

**Comment by echosoar** [comment]
支持 picromatch 规则，参考：https://github.com/micromatch/picomatch

**Comment by yuntian001** [comment]
经测试 使用 cross-env NODE_ENV=local midway-bin dev --ts  --watchFile=./test/*/controller 并未生效
使用cross-env NODE_ENV=local midway-bin dev --ts  --watchFile=./test/src/controller 时自定义监听是生效的
目录结构
![image](https://user-images.githubusercontent.com/43692243/164679071-feae6fa2-a5f2-41b4-bf84-0c02894c08e0.png)

@echosoar

**Comment by yuntian001** [comment]
![image](https://user-images.githubusercontent.com/43692243/164679711-6989712d-1649-41c8-9a87-2b4177b13c41.png)
z这里watchFile对进行检测时并没有应用 [micromatch/picomatch](https://github.com/micromatch/picomatch)规则，应该是在这里排除掉了

**Comment by echosoar** [comment]
@yuntian001 我看看，下一版本 cli 修复下

**Comment by echosoar** [comment]
> @echosoar 大约什么时间可以修复。

最新版本的已经修复了
