### ISSUE TITLE
midway 3.x 接口swagger  description，summary属性不生效

### ISSUE THREAD

**Issue by f2905885** [midwayjs/midway#1934]
midway版本：
![image](https://user-images.githubusercontent.com/14341507/164720242-9c6bfda6-19ad-4ec9-85a3-2a7adc2ed7a0.png)
代码：
![image](https://user-images.githubusercontent.com/14341507/164720369-bbd62ca8-367f-40fa-9f42-96db9f4e6d77.png)
结果：
![image](https://user-images.githubusercontent.com/14341507/164720500-2cfbb406-f6cc-4503-a5a9-81d7588f0713.png)

@Controller 中的description是生效的
`@Controller('/account', {
  middleware: [UserMiddleware],
  description: '用户账号信息相关，需要登录',
})`
@Post @Get 中的description、summary都不生效
`@Get('/current', { description: 'ddddd', summary: 'sssss' })
  @Post('/current', { description: '232323', summary: '323xxxx' })`

**Comment by kurten** [comment]
不支持，可以使用 @ApiOperation

**Comment by f2905885** [comment]
已用@ApiOperation解决
