### ISSUE TITLE
redis 空密码问题

### ISSUE THREAD

**Issue by wy2022** [midwayjs/midway#1935]
![bfa27ea839dede7fd5ede8352a9d3fb](https://user-images.githubusercontent.com/40479235/164876309-6e3fdd0d-13c8-48bd-b115-9fe50db9c9b5.png)

![13b189c1a2589d7e426298425a7761a](https://user-images.githubusercontent.com/40479235/164876355-d5c31aab-bd11-4b78-a99e-e91a339846ae.png)
 删除password字段或者"" 都不行 

config.prod.ts

import { MidwayConfig } from '@midwayjs/core';
import { join } from 'path';
import { createRedisAdapter } from '@midwayjs/socketio';
export default {
  // use for cookie sign key, should change to your own and keep security
  keys: '1648881068753_6284',
  koa: {
    port: 9000,
  },
  orm: {
    /**
     * 单数据库实例
     */
    type: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    username: 'zthb_2',
    password: '123456',
    database: 'zthb_2',
    synchronize: false,     // 如果第一次使用，不存在表，有同步的需求可以写 true
    logging: true,
    dateStrings: true,
  },
  jwt: {
    secret: 'zhongtianhuanbao', // fs.readFileSync('xxxxx.key')
    expiresIn: '2d',  // https://github.com/vercel/ms
  },
  passport: {
    session: false,
  },
  cache: {
    store: 'memory',
    ttl: 60 * 60,  //秒
  },
  redis: {
    client: {
      port: 6379, // Redis port
      host: "127.0.0.1", // Redis host
      password: "auth",
      db: 0,
    },
  },
  socketIO: {
    adapter: createRedisAdapter({ host: '127.0.0.1', port: 6379, password: "auth", db: 1 } as any),
    cors: {
      origin: '*',
    }
  },
  task: {
    redis: {
      port: 6379,
      host: '127.0.0.1',
      password: 'auth',
      db: 2,
    },
    prefix: 'midway-task',                      // 这些任务存储的 key，都是 midway-task 开头，以便区分用户原有redis 里面的配置。
    defaultJobOptions: {
      repeat: {
        tz: "Asia/Shanghai"                     // Task 等参数里面设置的比如（0 0 0 * * *）本来是为了0点执行，但是由于时区不对，所以国内用户时区设置一下。
      },
    },
  },
  upload: {
    // mode: UploadMode, 默认为file，即上传到服务器临时目录，可以配置为 stream
    mode: 'file',
    // fileSize: string, 最大上传文件大小，默认为 10mb
    fileSize: '10mb',
    // whitelist: string[]，文件扩展名白名单
    // whitelist: uploadWhiteList.filter(ext => ext !== '.pdf'),
    // tmpdir: string，上传的文件临时存储路径
    tmpdir: join(process.cwd(), 'public', 'files'),
    // cleanTimeout: number，上传的文件在临时目录中多久之后自动删除，默认为 5 分钟
    cleanTimeout: 5 * 60 * 1000,
  },

  cors: {
    credentials: false,
  },
  validate: {
    validationOptions: {
      allowUnknown: true,       // 全局生效
    }
  }

} as MidwayConfig;

package.json

{
  "name": "my-midway-project",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "dependencies": {
    "@midwayjs/bootstrap": "^3.0.0",
    "@midwayjs/cache": "^3.2.2",
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/cross-domain": "^3.2.2",
    "@midwayjs/decorator": "^3.0.0",
    "@midwayjs/info": "^3.0.0",
    "@midwayjs/jwt": "^3.2.2",
    "@midwayjs/koa": "^3.0.0",
    "@midwayjs/logger": "^2.14.0",
    "@midwayjs/orm": "^3.2.2",
    "@midwayjs/passport": "^3.2.2",
    "@midwayjs/redis": "^3.3.2",
    "@midwayjs/socketio": "^3.3.2",
    "@midwayjs/static-file": "^3.2.2",
    "@midwayjs/task": "^3.3.2",
    "@midwayjs/upload": "^3.2.2",
    "@midwayjs/validate": "^3.2.2",
    "@types/cache-manager-ioredis": "^2.0.2",
    "cache-manager": "^3.6.0",
    "dayjs": "^1.11.0",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "node-xlsx": "^0.21.0",
    "passport": "^0.5.2",
    "passport-jwt": "^4.0.0",
    "typeorm": "^0.3.4",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@midwayjs/cli": "^1.2.90",
    "@midwayjs/mock": "^3.0.0",
    "@types/cache-manager": "^3.4.3",
    "@types/ioredis": "^4.28.10",
    "@types/jest": "^26.0.10",
    "@types/koa": "^2.13.4",
    "@types/node": "14",
    "@types/passport": "^1.0.7",
    "cross-env": "^6.0.0",
    "jest": "^26.4.0",
    "mwts": "^1.0.5",
    "ts-jest": "^26.2.0",
    "typescript": "^4.0.0"
  },
  "engines": {
    "node": ">=12.0.0"
  },
  "scripts": {
    "start": "NODE_ENV=production node ./bootstrap.js",
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "test": "midway-bin test --ts",
    "cov": "midway-bin cov --ts",
    "lint": "mwts check",
    "lint:fix": "mwts fix",
    "ci": "npm run cov",
    "build": "midway-bin build -c"
  },
  "midway-bin-clean": [
    ".vscode/.tsbuildinfo",
    "dist"
  ],
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "anonymous",
  "license": "MIT"
}

**Comment by wy2022** [comment]
我测试出来了是   默认携带了密码 
socketIO: {
    adapter: createRedisAdapter({ host: '127.0.0.1', port: 6379, db: 1 } as any),
    cors: {
      origin: '*',
    }
  },

**Comment by qq296565890** [comment]
> 我测试出来了是 默认携带了密码 socketIO: { adapter: createRedisAdapter({ host: '127.0.0.1', port: 6379, db: 1 } as any), cors: { origin: '*', } },
=====================================

socketIO: {
    cors: {
      origin: "*",
      methods: ["GET", "POST"]
    },
    adapter: createRedisAdapter({ 
      host: 'password@biz.redis.com',
      port: 6379,
    } as any),
  }

**Comment by czy88840616** [comment]
后续版本，不再默认提供 redisAdapter 包裹，可以自己传一个，这样就不会出现这个问题了（文档已先行更新，兼容等过几个版本再移除）。
