### ISSUE TITLE
ctx 上下文 使用不是很方便

### ISSUE THREAD

**Issue by desonyuan** [midwayjs/midway#1937]
我使用登录验证 passport组件后  想拿到注入给ctx.state.user  每个controller 都要注入 ctx，抽离一下也需要集成一个基类，感觉稍微麻烦了点，能不能增加通过@Controller装饰器传参注入进去？还是有更好的方法？

**Comment by czy88840616** [comment]
ctx 是每个请求独立的，注定了不可能挂载全局静态类或者静态方法。

几种拿法：

- 1、@inject() ctx，标准做法
- 2、在基类 @inject ctx，提供一个 getUser() 方法拿 user，价值不大，还多了继承
- 3、通过自定义属性装饰器，比如写个 @User()，或者参数装饰器 @User，参考自定义装饰器
- 4、我还没想到。。
