### ISSUE TITLE
midway 3.3.4 中swagger 中 @body不生效

### ISSUE THREAD

**Issue by zybieku** [midwayjs/midway#1938]
* **Node Version**: v16.14.0
* **Midway Version(Decorator/Core)**: 3.3.4
* **Component Name/Version**:swagger 3.34
* **Platform**: win10
* **Mini Showcase Repository**:
* 
midway 3.3.4 中swagger 中 @body不生效,不会生成参数文档

![image](https://user-images.githubusercontent.com/15903330/165031284-8ce748e9-92d7-4796-a83c-e5d1798a9444.png)
![image](https://user-images.githubusercontent.com/15903330/165031400-09b264f4-5ee3-4112-8e07-6d2e4961a630.png)

![image](https://user-images.githubusercontent.com/15903330/165031462-4ae7621e-4091-48dc-870e-5d4cf323f73e.png)

对应swagger ui的参数中没有内容
![image](https://user-images.githubusercontent.com/15903330/165031610-81afd575-562c-4984-b64a-323ddb53f747.png)

但是schemas对象已经有了

**Comment by czy88840616** [comment]
Get 请求，不认 body

**Comment by zybieku** [comment]
nice, 回答真快, 直接复制的get_Info方法, 没注意改上面  注解 了

**Comment by zybieku** [comment]
OmitDto PickDto 基础的dto ,swagger无法识别嘛
![image](https://user-images.githubusercontent.com/15903330/165034659-05dd05b5-9b21-4146-a167-2f36a054824c.png)

**Comment by czy88840616** [comment]
继承应该可以吧

**Comment by zybieku** [comment]
直接extends 可以,  如果用**pickDto,OmitDto**等, DTO的 schemas只会**显示子类的字段**(当然这个问题不大),  Rules校验到生效
