### ISSUE TITLE
开发的组建没有在项目启动时没有调用组件createClient

### ISSUE THREAD

**Issue by helloHT** [midwayjs/midway#1950]
我是照着redis组件来开发的，然后发布npm包，在引入我的midway项目时发现没有调用组件的createClient方法
以下是我打印出来的组件内容
![image](https://user-images.githubusercontent.com/31006740/166176611-c5907369-60be-42a9-a73d-f8b0bff735fb.png)

**Comment by czy88840616** [comment]
需要提供更详细的代码示例，像是没读配置

**Comment by helloHT** [comment]
> 需要提供更详细的代码示例，像是没读配置

你好，这是我的组件所有代码
![image](https://user-images.githubusercontent.com/31006740/166180279-78232c0e-fc58-45e1-aa4e-f1371050370e.png)

**Comment by czy88840616** [comment]
看着好像没大问题，得看用的地方的 apollo 配置怎么写的吧。

**Comment by helloHT** [comment]
> 看着好像没大问题，得看用的地方的 apollo 配置怎么写的吧。服务工厂的配置有特定格式的，参考https://midwayjs.org/docs/service_factory

谢谢，我找到原因了，是配置中我没有用client或者clients
