### ISSUE TITLE
构建单文件，然后npm run bundle_start启动 报错

### ISSUE THREAD

**Issue by tuohuang** [midwayjs/midway#1952]
* **Node Version**: 16.14.0
* **Midway Version(Decorator/Core)**:3.0.0
* **Component Name/Version**:
* **Platform**:Windows
* **Mini Showcase Repository**:

构建单文件，然后npm run bundle_start启动 报错：Error: ENOENT: no such file or directory, open 'D:\Program\package.json' 我的项目的目录是D:\Program\midway\。需要在项目上一层目录创建一个package.json才可以

**Comment by czy88840616** [comment]
需要给我更详细的事例。

**Comment by tuohuang** [comment]
> 需要给我更详细的事例。

升级下包就没有问题了
