### ISSUE TITLE
在Axios的拦截器中。通过this.ctx获取到的上下文信息是空的。请教一下如何获取到ctx的信息

### ISSUE THREAD

**Issue by biggod-ck** [midwayjs/midway#1954]
1. 按照该https://midwayjs.org/docs/extensions/axios成功集成了axios
2.
 `
httpService.interceptors.response.use(

      response=> {

       // 期望再这里可以获取到 ctx的信息。可以拿到请求相关的信息，用于日志的输出。

        console.log(this.ctx); // 输出的是一个 {}

        return config;

      },

      error => {

        // Do something with request error

        return Promise.reject(error);

      }
    );
`

**Comment by czy88840616** [comment]
interceptors 都是在请求之外注册的，所以拿不到 ctx。

**Comment by biggod-ck** [comment]
> interceptors 都是在请求之外注册的，所以拿不到 ctx。

那有其他方案可以获取到对应的ctx吗？大佬指点一下~

**Comment by czy88840616** [comment]
有呀，app上挂 ctx 会串的，核心就是因为取不到 ctx。

**Comment by biggod-ck** [comment]
第一步 自定义 contextLoggerFormat。这个里面可以获取到CTX。
第二步 再axios的拦截器里面通过this.logger进行输出。发现根本没走自定义的contextLoggerFormat。这个是什么原因导致没走呢？大佬可以解释一下吗。非常感谢🙏

**Comment by czy88840616** [comment]
onReady是启动阶段执行的，那个时候没有 ctx，所以 logger 和 ctx 不绑定，你拿到的 axios 实例也是单例，所以没有办法和 ctx 关联。

**Comment by biggod-ck** [comment]
好的 感谢大佬！非常感谢
