### ISSUE TITLE
inject无法注入

### ISSUE THREAD

**Issue by zt123123** [midwayjs/midway#196]
官方的demo-sequelize-typescript使用factory生成provider
我想在Model使用@provide提供model
在Service使用@inject注入model
例如：
PostModel.ts
```ts
@provide('postModel')
export class PostModel extends Model<PostModel> { ......}
```
--------------------------------------------------------------------
PostService.ts
```ts
export class PostService implements IPostService {
  @inject('postModel')
  PostModel: IPostModel;
  async list(options: IPostListOptions): Promise<IPostListResult> {
     await this.PostModel.findAll();
```
--------------------------------------------------------------------
这样就会提示 this.PostModel.findAll is not a function
不明原因，请大神赐教

**Comment by kurten** [comment]
* 在一个request作用域下，默认通过getAsync获取到对象实例，返回的是一个promise，需要使用await context.getAsync('postModel') 才能获取到真正的对象实例
