### ISSUE TITLE
swagger 不支持 Date 类型

### ISSUE THREAD

**Issue by Ttou** [midwayjs/midway#1960]
使用 Date 定义 DTO 的属性时，报错 `Unknown Type: Date`

```ts
import { ApiPropertyOptional } from '@midwayjs/swagger'

import { SysUserEntity } from '../../../entity'

/** 查找用户数据 */
export class FindUserDTO implements Partial<SysUserEntity> {
  @ApiPropertyOptional({ description: '用户账号' })
  userName: string

  @ApiPropertyOptional({ description: '创建时间' })
  createTime: Date
}
```

![image](https://user-images.githubusercontent.com/4298437/167119064-d011cd1f-2d45-4acf-afb6-5b6bbfba23eb.png)

* **Node Version**: v16.14.2
* **Midway Version(Decorator/Core)**: v3.3.5
* **Component Name/Version**: @midwayjs/swagger v3.3.5
* **Platform** :Windows
* **Mini Showcase Repository**:

**Comment by kurten** [comment]
是的，swagger 本身标准就不支持

**Comment by Ttou** [comment]
@kurten 在 nest 里是可以的
![image](https://user-images.githubusercontent.com/4298437/167750127-8e68e61f-257a-47c7-8cc5-06f16d6fdf49.png)

**Comment by kurten** [comment]
> @kurten 在 nest 里是可以的 ![image](https://user-images.githubusercontent.com/4298437/167750127-8e68e61f-257a-47c7-8cc5-06f16d6fdf49.png)

你可以在装饰器里面声明 @ApiProperty{type: string, format: 'date'})

**Comment by Ttou** [comment]
@kurten  确实可以，用 @ApiProperty({ format: 'date-time' }) 就行
