### ISSUE TITLE
task Error: Validation error, cannot resolve alias "und"

### ISSUE THREAD

**Issue by dydwang** [midwayjs/midway#1961]
[ Midway ] (node:92388) UnhandledPromiseRejectionWarning: Error: Validation error, cannot resolve alias "und"
    at F:\分享\2022.4-nodets框架\test_midway\node_modules\cron-parser\lib\expression.js:169:17
    at String.replace (<anonymous>)
    at Function._parseField (F:\分享\2022.4-nodets框架\test_midway\node_modules\cron-parser\lib\expression.js:163:21)
    at parse (F:\分享\2022.4-nodets框架\test_midway\node_modules\cron-parser\lib\expression.js:866:36)
    at Function.parse (F:\分享\2022.4-nodets框架\test_midway\node_modules\cron-parser\lib\expression.js:919:10)
    at Function.parseExpression (F:\分享\2022.4-nodets框架\test_midway\node_modules\cron-parser\lib\parser.js:41:25)
    at getNextMillis (F:\分享\2022.4-nodets框架\test_midway\node_modules\bull\lib\repeatable.js:214:29)
    at Queue.nextRepeatableJob (F:\分享\2022.4-nodets框架\test_midway\node_modules\bull\lib\repeatable.js:38:24)
    at F:\分享\2022.4-nodets框架\test_midway\node_modules\bull\lib\queue.js:737:19
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

[ Midway ] (node:92388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handle
d with .catch(). (rejection id: 1)
(node:92388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dydwang** [comment]
async onReady(container: IMidwayContainer, app?: IMidwayBaseApplication<Context>) {
    // add middleware
    this.app.useMiddleware([ReportMiddleware]);
    // add filter
    // this.app.useFilter([NotFoundFilter, DefaultErrorFilter]);
    // Task这块的启动后立马执行
    const result: any = await container.getAsync(QueueService);
    const taskJob: Queue = await result.getQueueTask(`QueueTaskService`, 'taskQue') // 此处第一个是你任务的类名，第二个任务的名字也就是装饰器Task的函数名
    taskJob.add({}, {delay: 0}) // 表示立即执行。
  }

**Comment by czy88840616** [comment]
看堆栈是 cron 表达式的错误

**Comment by Yuliang-Lee** [comment]
按文档用 `repeat: { cron: FORMAT.CRONTAB.EVERY_DAY_ONE_FIFTEEN },` 也会报同样的错

**Comment by czy88840616** [comment]
这货的 cron 表达式好像不一样。。

**Comment by Yuliang-Lee** [comment]
。。所以这是框架 bug 吗

**Comment by Yuliang-Lee** [comment]
[启动就触发](https://midwayjs.org/docs/extensions/task#%E5%90%AF%E5%8A%A8%E5%B0%B1%E8%A7%A6%E5%8F%91 ) 配置上这个就报错了

**Comment by Yuliang-Lee** [comment]
我发现问题在于启动就触发这里，任务如果以定时执行是没问题的

**Comment by czy88840616** [comment]
我试试

**Comment by czy88840616** [comment]
我跟了下 bull，可能是他们改过参数了，现在可以使用 `job.add({}, {delay: 0, repeat: null})` 来触发。

**Comment by Yuliang-Lee** [comment]
> 我跟了下 bull，可能是他们改过参数了，现在可以使用 `job.add({}, {delay: 0, repeat: null})` 来触发。

这样可以了。这个最好也改下文档

**Comment by czy88840616** [comment]
文档已改。
