### ISSUE TITLE
MidwayDefinitionNotFoundError: MidwayWebFramework is not valid in current context

### ISSUE THREAD

**Issue by steady-join** [midwayjs/midway#1965]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

基于docker打包后构建错误
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/29935583/167375521-aa1073d9-1d8f-484f-8ae0-892338bdaf57.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/29935583/167375671-e1f25c1c-fe2b-48d6-98cf-9a8b252030dc.png">

**Comment by czy88840616** [comment]
没 build 吧

**Comment by steady-join** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
