### ISSUE TITLE
Context接口类型添加session属性

### ISSUE THREAD

**Issue by ckvv** [midwayjs/midway#1966]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

现在设置`this.ctx.session`缺少TS提示https://www.midwayjs.org/docs/controller#session
是遗漏了还是故意这样?
https://github.com/midwayjs/midway/blob/main/packages/core/src/interface.ts#L360-L380

**Comment by czy88840616** [comment]
看了下，只有 egg 下出不来。。koa 和 express 的 session 是 midway 组件自己提供的，是有 session 定义的，egg的是复用了 egg 的定义，还得额外看看。

**Comment by czy88840616** [comment]
我创建了一个egg自己的ts项目，他们自己就没有 session 定义

![image](https://user-images.githubusercontent.com/418820/167533362-42713971-9c4a-44ae-a6ab-07584174c729.png)

**Comment by ckvv** [comment]
@czy88840616 
我使用`npm init midway`创建的是默认的`koa-v3 - A web application boilerplate with midway v3(koa)`也是没有的提示的
<img width="654" alt="截屏2022-05-10 12 43 31" src="https://user-images.githubusercontent.com/30174970/167544192-82539c5c-4b92-49f2-b611-17fc52629283.png">

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/167564595-84a3aba8-c368-4b91-8bed-72a99eab4379.png)

没发现问题。。

**Comment by ckvv** [comment]
> ![image](https://user-images.githubusercontent.com/418820/167564595-84a3aba8-c368-4b91-8bed-72a99eab4379.png)
> 
> 没发现问题。。

我是存在这个问题的，我把代码上传到了github 
+ npm init midway
+ 使用默认的koa-v3 - A web application boilerplate with midway v3(koa)模版创建
https://github.com/ckvv/midway-project/blob/main/src/controller/api.controller.ts#L15

**Comment by czy88840616** [comment]
已复现该问题，原因为 ts 不解析二级依赖中 index.d.ts 导出的定义。
