### ISSUE TITLE
生成的swagger-ui/index.json中数据类型Array应该修改为array

### ISSUE THREAD

**Issue by BEIBEI123** [midwayjs/midway#1967]
发现导出的 swagger-ui/index.json ，导入至其他软件比如apifox里面，这个array字段没识别，后来才发现导出的是Array，但是OpenAPI定义的是array，而不是Array，希望能修改
"@midwayjs/swagger": "^3.1.6",

**Comment by kurten** [comment]
贴一下你的参数类型

**Comment by kurten** [comment]
我大概知道你的问题了，因为 ts 本身的原因，范型的具体类型是获取不到的，你必须在装饰器中声明 type

https://midwayjs.org/docs/extensions/swagger#%E7%B1%BB%E5%9E%8B%E5%92%8C%E5%8F%82%E6%95%B0

**Comment by BEIBEI123** [comment]
``js
public async index(
    @Query('timerange[]') timerange?: Array<string>
  ) {
    const result = await this.LogService.log_list(
      timerange
    );
    return this.success(result);
  }

``

**Comment by kurten** [comment]
> ```js
> public async index(
>     @Query('timerange[]') timerange?: Array<string>
>   ) {
>     const result = await this.LogService.log_list(
>       timerange
>     );
>     return this.success(result);
>   }
> ```
> 
> 这是这里，Array，修改成array时ts报错，不修改的话导出的 swagger-ui/index.json的话OpenAPI错误

用 string[] 不要用 Array<string>
