### ISSUE TITLE
如何将定义好的数据库模型同步到数据库中呢？

### ISSUE THREAD

**Issue by tan1444** [midwayjs/midway#197]
![微信截图_20190418204503](https://user-images.githubusercontent.com/16314475/56361710-a47f7900-621a-11e9-9ff9-48bdfed6e7ba.png)
我按照例子定义好了user表，但如何把它同步到我的数据库中去呢？

**Comment by czy88840616** [comment]
这个..没这个功能啊……

**Comment by tan1444** [comment]
只能手码吗？项目里打一遍，再到数据库里手动创建一下？

**Comment by czy88840616** [comment]
等等..sequelize有个sync 方法的，可以同步表结构的

**Comment by tan1444** [comment]
在midway框架下如何实现呢，有没有demo？

**Comment by zt123123** [comment]
sequeze是orm框架  orm简化了sql操作前提是，把实体类映射到数据库的表字段，你不自己定义Model，框架不知道怎么处理  。在Java中heberlate也是需要配置文件的，同时也要建立相应的bean，定义类的属性与方法，来映射到数据库。然后就可以用orm框架来简化sql语句，用对应的api来操作数据。

**Comment by czy88840616** [comment]
这个属于 sequelize 的用法，具体看同步这页。。http://docs.sequelizejs.com/manual/models-definition.html#database-synchronization
