### ISSUE TITLE
@midwayjs/http-proxy配置代理规则将其转发到页面地址，返回多余字段

### ISSUE THREAD

**Issue by cpxGithub** [midwayjs/midway#1970]
1. 按照文档下载组件@midwayjs/http-proxy@3
2. 配置代理转发，如配置/main/转发到百度地址
```
httpProxy: {
      default: {
        // 一些每个策略复用的值，会和底下的策略进行合并
      },
      strategy: {
        main: {
          match: /^\/main\/$/,
          target: 'https://www.baidu.com/',
        },
      },
}
```
3. 访问改地址发现返回多余字段 OK， 如下图
![t1](https://user-images.githubusercontent.com/20429937/167627555-daf7ffb7-db92-44ea-8a5c-44c434423b9f.png)
![t2](https://user-images.githubusercontent.com/20429937/167627641-3a771a6e-c5cd-4760-9f9c-a9e661cf5137.png)

* **Node Version**: v16.15.0
* **Midway Version(Decorator/Core)**: ^3.0.0
* **Component Name/Version**: "@midwayjs/http-proxy": "^3.3.5",
* **Platform**: macOs
* **Mini Showcase Repository**:

**Comment by echosoar** [comment]
fixed: https://github.com/midwayjs/midway/pull/1973
