### ISSUE TITLE
[BUG] @midwayjs/i18n 在未安装和启用状态会设置 cookie 

### ISSUE THREAD

**Issue by tianfanfan** [midwayjs/midway#1971]
如题
在纯净的 midwayjs 应用中，会设置 local为 zh-cn

npm init midway

选择 koa-v3

npm run dev

可以看见 被设置了local为 zh-cn 的 cookie

**Comment by czy88840616** [comment]
i18n 是 validate 组件所依赖的，validate是脚手架中已经自带的。

**Comment by tianfanfan** [comment]
> i18n 是 validate 组件所依赖的，validate是脚手架中已经自带的。
以下几个问题：

1. validate 后，i18n 无法剔除了。
2. 这个 cookie 的 key (local) 无法修改为其他 key。
3. cookie 的值也是 通过 header Accept-Language 获取，无法自定义获取方式。
除非手动调用 saveRequestLocale 否则无法修改。写法也无法用普通中间件，必须用 @Scope(ScopeEnum.Request)
否则会报：
Middleware with singleton scope can't implicitly inject MidwayI18nService with request scope directly。

**Comment by czy88840616** [comment]
如果不希望 i18n 写入 cookie，可以设置 i18n 的 writeCookie 配置 为 false，如果想修改读取的 cookie key，可以修改 resolver 的 cookie Field。
