### ISSUE TITLE
typeorm如何通过entity文件把结构同步到数据库生成数据表

### ISSUE THREAD

**Issue by MineFurjiko** [midwayjs/midway#1972]
文档的typeorm章节，说了设置synchronize: true。
我在config/config.default.ts 中的orm配置了
 orm: {
    type: 'mysql',
    host: '192.168.10.3',
    port: 3306,
    username: 'vm',
    password: '0815',
    database: 'test',
    synchronize: true, // 如果第一次使用，不存在表，有同步的需求可以写 true
    logging: true,
    entities: ['../entity/entity_mysql/*.ts'],
  }
然而，并没有效果。
请问该如何设置，在midway中

**Comment by czy88840616** [comment]
- 1、启用组件
- 2、启动应用

**Comment by MineFurjiko** [comment]
> 

实在抱歉哈，在同个应用中测试了typegoose 和 typeorm。
再调试typegoose时把configuration.ts 中orm组件的启用给注释调了。
刚刚要测试orm时，忘记打开了。
