### ISSUE TITLE
DTO继承时@ApiProperty只能继承一次的问题

### ISSUE THREAD

**Issue by heyongsheng** [midwayjs/midway#1976]
```
class baseDTO {
  @ApiProperty({
    example: '17755556666',
    description: '11位手机号码',
  })
  @Rule(RuleType.string().required().length(11))
  phone: string;

  @ApiProperty({
    enum: ['sport', 'question'],
    example: 'sport',
    description: '产品线',
  })
  @Rule(RuleType.string().required().valid('sport', 'question'))
  site: string;
}
export class CodeLoginDTO extends baseDTO {
  @ApiProperty({
    example: '0000',
    description: '验证码',
  })
  @Rule(RuleType.string().required().length(4))
  code: string;

  @ApiProperty({
    example: 'xxxx',
    description: '随机数',
  })
  @Rule(RuleType.string().required().length(100))
  uuid: string;
}

export class LoginDTO extends baseDTO {
  @ApiProperty({
    example: 'xxx',
    description: '密码',
  })
  @Rule(RuleType.string().required().min(6).max(30))
  password: string;
}
```

这里的 LoginDTO  和 CodeLoginDTO 都继承于 baseDTO ，他们的验证规则也正确的继承了，但是在swagger中展示的时候，只有排在前面的路由可以展示baseDTO 中的字段描述和示例
![image](https://user-images.githubusercontent.com/18118447/168118202-2cd46e00-d93b-4f77-87a1-975a6be3e2b8.png)

![image](https://user-images.githubusercontent.com/18118447/168118021-21c6d5de-7583-4c67-87b2-8816fe9d417d.png)
![image](https://user-images.githubusercontent.com/18118447/168118136-1b5d8e71-77ba-41c2-8a04-4490785d3305.png)

**Comment by kurten** [comment]
baseDTO 加个 export 试试呢

**Comment by bobohuochai** [comment]
> baseDTO 加个 export 试试呢
一样的， 第二个 **example Value** 没有继承，**schema** 继承了。

**Comment by bobohuochai** [comment]
调试了下代码， 在 swaggerExplorer.ts 文件中 parseClzz 方法有问题。
![image](https://user-images.githubusercontent.com/22309079/173490407-2b72f2ee-1df5-4751-af73-8ffe52cfd6e5.png)
这个删除example 属性，会影响到第二次获取基类getClassExtendedMetadata 的props,里面的example 会丢失。
@czy88840616

**Comment by czy88840616** [comment]
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/418820/174071200-e762dfc3-b859-415b-bf83-43893c4c2e42.png">

好像没问题啊。
