### ISSUE TITLE
怎么获得组件实例化后的对象？

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#1983]
怎么样才能获得图中  @midwayjs/sequelize 组件 sequelize 实例化后的 instance 呢？
![image](https://user-images.githubusercontent.com/9130123/168421138-ada96808-4cff-4140-b41a-24cad125d6de.png)

现在考虑的是下面类似的代码，有更好的解决方案吗？
```ts
const t = this.entity.sequelize.transaction;
```

**Comment by ddzyan** [comment]
https://github.com/midwayjs/midway/issues/1600 
这个问题有后续的解决方案吗？

**Comment by ddzyan** [comment]
为什么这个插件不会 `@midwayjs/redis` 的使用一致呢？

**Comment by czy88840616** [comment]
这个组件没有做多实例处理，也基本也没包什么东西，和redis不一样。

**Comment by ddzyan** [comment]
> 这个组件没有做多实例处理，也基本也没包什么东西，和redis不一样。

那暂时除了我上面的使用方法以外，有其他方式推荐吗

**Comment by ddzyan** [comment]
![image](https://user-images.githubusercontent.com/9130123/168424702-16ad9231-1b80-4bad-9cd0-a3d7e742ec60.png)

**Comment by ddzyan** [comment]
为了获取实例化后的 sequelize 对象，并且支持多实例化，我提交了这个 pr ，麻烦看下是否可行，已经兼容老版本的创建 https://github.com/midwayjs/midway/pull/2023 @czy88840616
