### ISSUE TITLE
koa3 logger 生产环境的日志不能输出,在开发环境的时候可以输出

### ISSUE THREAD

**Issue by qaz63700** [midwayjs/midway#1985]
自定义日志logger 在npm run start生产环境的不能输出日志,在运行开发环境的时候可以输出日志,

const { Bootstrap } = require('@midwayjs/bootstrap');
Bootstrap.run();

**Comment by czy88840616** [comment]
本地开发和服务器部署时的 日志路径 和 日志等级 不同，具体请参考 [配置日志根目录](https://midwayjs.org/docs/logger#%E9%85%8D%E7%BD%AE%E6%97%A5%E5%BF%97%E6%A0%B9%E7%9B%AE%E5%BD%95) 和 [框架的默认等级](https://midwayjs.org/docs/logger#%E6%A1%86%E6%9E%B6%E7%9A%84%E9%BB%98%E8%AE%A4%E7%AD%89%E7%BA%A7)。
