### ISSUE TITLE
[问题] egg-scripts

### ISSUE THREAD

**Issue by atzcl** [midwayjs/midway#199]
请教大佬，如何在 `midway` 中给 `egg-scripts` 传递 `NODE_OPTIONS` 环境变量，尝试了在 `midway-server-options` 定义 `node-options` 无效

**Comment by atzcl** [comment]
或者可以在 `midway-examples` 里整一个例子吗？😂😂

**Comment by czy88840616** [comment]
https://github.com/eggjs/egg/issues/2623

查了下..

**Comment by atzcl** [comment]
@czy88840616 当时也看过这个 issue 了，不过不是很明白，，对这块不熟悉😂😂我去看下源码，，现在用 pm2 也可以了，但是还是想全家桶一起上，之后也方便 `docker` 交付，，
