### ISSUE TITLE
ServerLess 部署

### ISSUE THREAD

**Issue by imohuan** [midwayjs/midway#1993]
## 耗时
每一次 `npm run deploy` 都会在这 `Install production dependencies` 卡很长一段时间

``` text
Install layers...
 - Layers install complete
Install production dependencies...
 - Dependencies install complete
```

### 我认为这是没有必要的，我是用的是腾讯云，我把对应的依赖已经打包上传到层中（下图）
![image](https://user-images.githubusercontent.com/41279222/169494310-97f5121e-c8eb-452d-9f7e-cac04cad3a47.png)
## 一： 配置 `layers`
``` yml
layers:
  test:
    path: npm:@midwayjs/egg-layer@latest
```

## 二： 扩展cli 
https://midwayjs.org/docs/tool/cli#1-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E6%89%A9%E5%B1%95

#### 很可惜，我都失败了
# 问题一:  自动为云函数绑定 层
> 配置`layers` 我无法绑定层， 因为我根据官网的layers配置项，完全不能理解该如何绑定上传后的层
![image](https://user-images.githubusercontent.com/41279222/169495236-f93fb08f-36a5-46c8-84cd-d701154bda5d.png)

# 问题二： 跳过midway deploy安装依赖这个环节，直接打包上传服务器

**Comment by czy88840616** [comment]
可以尝试直接 tsc 构建，这样框架+代码没问题，但是缺少一个平台的入口文件（xxx.js），入口文件可以拿之前同名的加一个，这样组合完的是没有依赖的。

**Comment by imohuan** [comment]
也就是说 脚手架没有实现 取消安装依赖这个功能，部署到腾讯云我想直接使用cli提供

**Comment by czy88840616** [comment]
当前没有，一直没这个需求，不过我觉得既然有几个skip，加一个跳过安装依赖问题也不大。

**Comment by imohuan** [comment]
配置 layers ，绑定到腾讯云可行吗

**Comment by czy88840616** [comment]
我们没有尝试过。

**Comment by imohuan** [comment]
目前你们会做写方面的更新吗

**Comment by czy88840616** [comment]
我们在尝试ncc打包的方案，但是还会有些限制。

**Comment by imohuan** [comment]
嗯嗯，这个问题都可以通过手动或者等待来完成，但我也希望未来可以解决，还是不要来的太晚

**Comment by czy88840616** [comment]
serverless现在对框架来说最大的问题是对接部署平台的成本，每个平台的sdk都不同，对接十分吃力，如果不对接，也很难搞。

**Comment by imohuan** [comment]
如果是这样的化，可以先解决 取消安装依赖 这个选项功能把

**Comment by czy88840616** [comment]
对，我理解这个做做快的，下周评审做了就行。

**Comment by imohuan** [comment]
好嘞，这些都无关大雅，我目前有个大问题，如果有空可以帮忙解决一下
https://github.com/midwayjs/midway/issues/1996

**Comment by echosoar** [comment]
有 --skipInstallDep 参数，可以跳过依赖安装

**Comment by imohuan** [comment]
感谢，skipInstallDep 有效
