### ISSUE TITLE
图片上传空白

### ISSUE THREAD

**Issue by imohuan** [midwayjs/midway#1996]
# 图片上传之后，图片无法访问
![image](https://user-images.githubusercontent.com/41279222/169512835-62e17073-fa43-4cc2-b7eb-5a66a6a10cef.png)

[serverless-test.zip](https://github.com/midwayjs/midway/files/8738772/serverless-test.zip)

# `f.yml` 配置问题
# 配置为阿里云的时候正常，可以访问  `provider:name: aliyun` 

# 可是变成 tencent之后就无法访问
``` yml
provider:
  name: tencent
```

**Comment by czy88840616** [comment]
我理解文件太大了，超过2m，函数网关就会随机截断了。

**Comment by imohuan** [comment]
通过测试，不是文件大小问题

测试使用的是同一张图片
![image](https://user-images.githubusercontent.com/41279222/169784190-c0ebcdc5-c88b-4dc2-9a43-4c5d6071b76c.png)

**Comment by imohuan** [comment]
hello， 不要忘了哦

**Comment by imohuan** [comment]
以近半个月了，请问目前是什么情况，是在修复还是其他》

**Comment by czy88840616** [comment]
一是函数这块有些变化，我们一直在做新版本的事情，二是腾讯云最近做价格调整，现在更难调试了。

**Comment by echosoar** [comment]
问题已经定位了，是因为腾讯云的apigw在处理multipart-formdata的时候，默认是直接把 body toString了，导致一些二进制编码没有了。
根据腾讯云的文档，上传需要在apigw开启base64编码，这样上传的请求body就会把二进制数据编码成base64，这需要 @midwayjs/upload 支持一下 base64 编码的解析。https://cloud.tencent.com/document/product/583/52991

下面是临时改造之后，上传之后的效果：
![image](https://user-images.githubusercontent.com/14832743/172520003-5b4000e3-17d5-44fa-b85a-964dac3a1642.png)

会在 @midwayjs/upload 的下一个版本里面支持（预计这两天发布），发布之后在这个issue会同步相关使用信息。

**Comment by imohuan** [comment]
好嘞，感谢

**Comment by czy88840616** [comment]
v3.3.12
