### ISSUE TITLE
middleware格式化返回值，controller返回falsy不执行

### ISSUE THREAD

**Issue by pengxingwang** [midwayjs/midway#2012]
* **Node Version**: 16.40
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**: mac
* **Mini Showcase Repository**:

![lQLPJxZbfohx9ILNB77NCsaw0xU6231DvmIClvhznED5AA_2758_1982](https://user-images.githubusercontent.com/26086540/171080505-81dd3173-da30-496f-8596-677867abd41e.png)

按照官网的例子用middlware 格式化返回值，但是当controller 返回null时 ， FormatMiddleware 不执行return。 postman响应体里body为空， 虽然接口是成功了。

**Comment by bobohuochai** [comment]
+1, 返回false, result 也会变undefined。。。

**Comment by czy88840616** [comment]
恩，618之后会改。

**Comment by bobohuochai** [comment]
https://github.com/midwayjs/midway/issues/1976 大佬 这个什么时候改，swagger dto不能继承写起来太烦了。
