### ISSUE TITLE
Swagger @ApiProperty type 数组写法不支持复杂类型

### ISSUE THREAD

**Issue by bobohuochai** [midwayjs/midway#2015]
* **Node Version**:12
* **Midway Version(Decorator/Core)**:^3
* **Component Name/Version**:@midwayjs/swagger^3.3.8
* **Platform**: mac
* **Mini Showcase Repository**:https://github.com/bobohuochai/test-swagger

dto 写法
![image](https://user-images.githubusercontent.com/22309079/171322955-fb33b083-1149-4923-95d8-e80a876ab902.png)

swagger-ui
![image](https://user-images.githubusercontent.com/22309079/171323003-0b3ad6cd-ac6e-4040-b797-c4ca277ee6e0.png)

如果是对象展示正常：type:OssUploadResponseDataDto
![image](https://user-images.githubusercontent.com/22309079/171323288-4835d3af-c857-4da2-b556-ba61d1c29d3c.png)

**Comment by kurten** [comment]
提取ApiProperty最后逻辑判断的把 items 覆盖了，现在已经修复 哈

**Comment by czy88840616** [comment]
已发布。
