### ISSUE TITLE
Socket.io 单元测试 timeout

### ISSUE THREAD

**Issue by bobohuochai** [midwayjs/midway#2029]
* **Node Version**:12
* **Midway Version(Decorator/Core)**:^3
* **Component Name/Version**:@midwayjs/socketio^3
* **Platform**:mac
* **Mini Showcase Repository**:https://github.com/bobohuochai/midwayjs-demo

1.按照 这篇文章 搭建socket.io 服务，https://midwayjs.org/docs/extensions/socketio#%E5%B8%B8%E8%A7%81-api
2.运行单元测试报错
![image](https://user-images.githubusercontent.com/22309079/172341163-570b4561-5e0d-46c9-9382-208adbbbf238.png)
3.关于socketio path 的配置疑问
![image](https://user-images.githubusercontent.com/22309079/172341620-b6b86efd-4af9-4438-8a38-1b150233217b.png)

**Comment by czy88840616** [comment]
https://github.com/bobohuochai/midwayjs-demo/blob/master/src/config/config.default.ts#L3

socketio client 也要配端口。

**Comment by bobohuochai** [comment]
> https://github.com/bobohuochai/midwayjs-demo/blob/master/src/config/config.default.ts#L3
> 
> socketio client 也要配端口。

确实，但是不是应该读取的config.unittest.ts 的配置嘛；

![image](https://user-images.githubusercontent.com/22309079/172350340-ff899973-7807-4fd4-abde-91ce0df2760e.png)

**Comment by czy88840616** [comment]
截图只是 server 的配置，client和 server 没什么关系，只是用来测试的，需要自行指定。

**Comment by bobohuochai** [comment]
> 截图只是 server 的配置，client和 server 没什么关系，只是用来测试的，需要自行指定。

client 的端口咋配置，socketIO:{port:3000} ,这个是服务端的端口配置吧。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/172361241-a792690c-a5dd-4082-8276-ec7c7f508375.png)

**Comment by bobohuochai** [comment]
不纠结 port 的问题了，啥也不改现在也通过了...
在config 里配置了socketIO:{
  port:3000.
  path:'/socketio'
}
第三个问题，关于path **,用createSocketIOClient  不能传path 参数**。
直接用 socket.io-client 包，
import * as socketIOClient from 'socket.io-client'
 const client = await socketIOClient.connect({
      port: 3000,
      path:'/socketio'
    });
这样写会报timeout

**Comment by czy88840616** [comment]
这里有我们的测试用例，简单来说就是
1、端口要对上
2、path 要对上
3、namespace 要对上

你以为的 path 不一定是 path（可能是namespace）
参考：https://midway.alibaba-inc.com/docs/next/extensions/socketio#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%B2%A1%E8%BF%9E%E4%B8%8A%E6%B2%A1%E5%93%8D%E5%BA%94

**Comment by bobohuochai** [comment]
第三点path 不能传递应该和ts 有关，类型声明没有继承，文档上已经写的很清楚path 和 namesapce 的区别了。关于类型为什么没有继承，我再找找

**Comment by czy88840616** [comment]
没装 socket.io-client 的定义吧。
