### ISSUE TITLE
官网关于swagger内容的地址打不开

### ISSUE THREAD

**Issue by Last-Order-Wsk** [midwayjs/midway#2031]
https://midwayjs.org/midway
我想看看关于这部份 但是显示Page Not Found
![image](https://user-images.githubusercontent.com/73875874/172588656-a37d100f-3476-406b-877a-bbab2182db94.png)

**Comment by Last-Order-Wsk** [comment]
从这里链接过去的 
![image](https://user-images.githubusercontent.com/73875874/172589205-7b93be00-4ce1-4fbd-b9c0-4f24e8ef9889.png)

**Comment by czy88840616** [comment]
子包readme属于历史未改，实际都在组件中。https://www.midwayjs.org/docs/extensions/swagger

**Comment by Last-Order-Wsk** [comment]
thanks
