### ISSUE TITLE
【Feature】异常处理 filter 优化

### ISSUE THREAD

**Issue by Yuliang-Lee** [midwayjs/midway#2032]
* **Node Version**: v16+
* **Midway Version(Decorator/Core)**: @Catch
* **Component Name/Version**: 
* **Platform**:
* **Mini Showcase Repository**:

filter 的实现支持一类错误的捕获，而不是指定一个错误的捕获。

https://github.com/midwayjs/midway/blob/main/packages/core/src/common/filterManager.ts#L81

这一行的代码改为类似

```js
err instanceof SomeError
```

实际场景是，比如我想捕获所有 `TypeORM` 抛出来的异常进行处理，但是 `TypeORM` 可能抛出的错误有几十个，每个都继承自 `TypeORMError`

<img width="940" alt="image" src="https://user-images.githubusercontent.com/6936358/172781556-a5abd237-9b15-4e91-8d8d-0f00190a3139.png">

按现在的写法需要把所有错误以数组形式传到 `@Catch([])` 中，比较不方便

**Comment by czy88840616** [comment]
感觉可以，不过子类这个处理可能要额外加参数了。

**Comment by Yuliang-Lee** [comment]
如何处理比较好？我可以看看有时间的话改下

**Comment by czy88840616** [comment]
这个处理简单的，主要是涉及到core的发布，没那么快。

**Comment by czy88840616** [comment]
已实现。
