### ISSUE TITLE
使用身份验证的 jwt策略出错

### ISSUE THREAD

**Issue by Last-Order-Wsk** [midwayjs/midway#2035]
当我按照官网给出的示例，发送请求获取token的值是ok的，但是使用midwar中间价验证信息的时候出错，
![image](https://user-images.githubusercontent.com/73875874/172989206-35216ca8-2a85-439b-bad8-0e9abc5c7d02.png)

**Comment by czy88840616** [comment]
使用passport 0.5.x版本，新版本将在后续兼容。

**Comment by Last-Order-Wsk** [comment]
我试着降了版本到0.5.3 于是有了新的错误
Error: Failed to serialize user into session

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/extensions/passport#1failed-to-serialize-user-into-session
这是个正常错误。

**Comment by Last-Order-Wsk** [comment]
thanks
