### ISSUE TITLE
ERROR 23556 Error [unhandledRejectionError]: [logger]: Please set fileLogName when enable file log

### ISSUE THREAD

**Issue by x1911** [midwayjs/midway#2036]
ERROR 23556 Error [unhandledRejectionError]: [logger]: Please set fileLogName when enable file log

my code:
```const { Bootstrap } = require('@midwayjs/bootstrap');
const WebFramework = require('@midwayjs/koa').Framework;

const web = new WebFramework().configure({
    port: 7001,
    
    
});

Bootstrap.configure().load(web).run();```

after install those npm modules, it shows error

<img width="643" alt="image" src="https://user-images.githubusercontent.com/8219031/173006766-2a2cde8f-6d2d-406a-910e-7b53c03d16fe.png">

here is package.json


```
{
    "private": true,
    "name": "xxx",
    "version": "1.0.0",
    "scripts": {
        "build": "midway-bin build -c",
        "start": "cross-env NODE_ENV=production node ./bootstrap.js",
        "serve": "cross-env NODE_ENV=local midway-bin dev --entryFile=./bootstrap.js --ts --fast"
    },
    "dependencies": {
        "@alicloud/pop-core": "1.7.10",
        "@linrna/midway": "3.1.23",
        "@linrna/midway-orm": "3.1.23",
        "@linrna/midway-oss": "1.2.2",
        "@midwayjs/decorator": "2.13.2",
        "@midwayjs/mock": "2.13.2",
        "@midwayjs/task": "2.13.2",
        "exceljs": "^4.3.0",
        "koa-send": "^5.0.1",
        "mysql": "^2.18.1",
        "node-wx-jssdk": "^1.0.6"
    },
    "devDependencies": {
        "@midwayjs/cli": "^1.0.0",
        "@types/node": "14",
        "cross-env": "^6.0.0",
        "typescript": "^4.0.0"
    },
    "engines": {
        "node": ">=12.0.0"
    }
}

```

<!--
Thank you for reporting an issue.

1. It's RECOMMENDED to submit PR for typo or tiny bug fix.
2. If this's a FEATURE request, please provide: details, pseudo codes if necessary.
3. If this's a BUG, please provide: course repetition, error log and configuration. Fill in as much of the template below as you're able.
4. It will be nice to use `egg-init --type=simple bug` to provide a mini GitHub repository which can reproduce the issue.

感谢您向我们反馈问题。

1. 提交问题前，请先阅读文档，善用搜索
2. 我们推荐如果是小问题（错别字修改，小的 bug fix）直接提交 PR。
3. 如果是一个新需求，请提供：详细需求描述，最好是有伪代码实现。
4. 如果是一个 BUG，请提供：复现步骤，错误日志以及相关配置，并尽量填写下面的模板中的条目。
5. 如果可以，请使用 `midway-init` 提供一个最小可复现的代码仓库，方便我们排查问题。
6. 扩展阅读：[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)
-->

* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

<!-- Enter your issue details below this comment. -->

**Comment by czy88840616** [comment]
你把堆栈隐藏了。。从堆栈往回找，logger创建的时候没传 fileLogName
