### ISSUE TITLE
Upgrade default Node.js version from v8 to v10

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#204]
https://github.com/nodejs/Release

4.30 是 6.x LTS 的最后一天，而 8.x 也将于年底完成它的使命，midway 计划将于近期把默认的 node 版本从 8 升级到 10。

**Comment by waitingsong** [comment]
可同时把 tsconfig.json 的 target 提示为 es2018 。反正 2019也过半了。

**Comment by czy88840616** [comment]
这个貌似还不急。。可以再等等吧。

**Comment by meteorlxy** [comment]
```md
Node.js >= 10.16.0 required.
```

这个不是已经写在 README 里面了吗 2333

**Comment by waitingsong** [comment]
@meteorlxy  10.16.0 的要求是脚手架里面的，midway 主框架还是 8.

**Comment by czy88840616** [comment]
正好升级 midway2，从 v12 起步。

**Comment by waitingsong** [comment]
v12 起步挺好.
