### ISSUE TITLE
文档中配置 server https 部分好像有问题

### ISSUE THREAD

**Issue by boguan** [midwayjs/midway#2058]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/3226538/174968534-f758a652-f8aa-4025-812b-9c911d2ddad4.png">

图中 readFileSync 好像不能加
因为 safeRequire 方法中 会对 koa.key 做 readFileSync

**Comment by boguan** [comment]
配置 https
按照如下配置，启动会报错：
https://midwayjs.org/docs/extensions/koa#https-%E9%85%8D%E7%BD%AE

解决方案是：文档中
koa: {
    key: readFileSync(join(__dirname, '../ssl/ssl.key'), 'utf8'),
    cert: readFileSync(join(__dirname, '../ssl/ssl.pem'), 'utf8'),
  },
改成
koa: {
    key: join(__dirname, '../ssl/ssl.key'),
    cert: join(__dirname, '../ssl/ssl.pem'),
  },

**Comment by boguan** [comment]
原因是 safeRequire 方法中 会对 koa.key 做 readFileSync
详见 https://github.com/midwayjs/midway/blob/main/packages/core/src/util/index.ts#L39

**Comment by czy88840616** [comment]
感谢，已经更新。
