### ISSUE TITLE
没有办法使用自定义的外部session存储(没办法设置sessionStore)，会报type error

### ISSUE THREAD

**Issue by sfesh2012** [midwayjs/midway#206]
**没有办法使用自定义的外部session存储(没办法设置sessionStore)，会报
TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute
详情见showcase代码：./src/app/extend/application.ts** 

步骤：
1. midway init初始化
2. plugin.ts中启用内部egg-session插件
3. config中配置egg-session插件
4. 通过extend扩展插件外部存储

* **Node Version**: 11.1.0
* **Egg Version**: 
* **Plugin Name**: egg-session
* **Plugin Version**: 
* **Platform**: mac os
* **Mini Showcase Repository**: https://github.com/sfesh2012/midway-session-test.git

**Comment by sfesh2012** [comment]
我遇到了一个bug？ @czy88840616 这里有没有修复计划或者建议方案？
session是个基础功能，影响比较大。

**Comment by czy88840616** [comment]
我刚在看。。。

**Comment by sfesh2012** [comment]
赞一个高效，等你好消息！ ：）

**Comment by czy88840616** [comment]
看起来是直接在 `./src/app/extend/application.ts` 里定义了扩展 sessionStore，这样就和 egg-session 扩展冲突了。

**Comment by czy88840616** [comment]
egg-session 扩展外部 store 的方式是比如在 app.js(src/app.ts) 中写，而不是直接在 app/extend 中。

![image](https://user-images.githubusercontent.com/418820/57187483-2a413b00-6f22-11e9-8d37-12e238ecac8b.png)

**Comment by sfesh2012** [comment]
哦，app.ts已经被我改成了 app boot hook的方式了，我试试再willReady里看看能不能工作吧。

![image](https://user-images.githubusercontent.com/3196516/57187521-c79c6f00-6f22-11e9-84cf-666eebcacb3d.png)

**Comment by sfesh2012** [comment]
@czy88840616 不管是hook方式，还是代码例子里的方法， 都没有成功， 只是不报错了。
代码已经上传到bug示例的git上了，麻烦再看看？

**Comment by czy88840616** [comment]
got

**Comment by czy88840616** [comment]
app.ts是放在 `src/app.ts`，对应根目录，而不是在 `src/app/app.ts`

**Comment by sfesh2012** [comment]
@czy88840616 感谢， 收到。
在 hook方式下， 要再configWillLoad里面写才可以生效。
