### ISSUE TITLE
3.0 Bootstrap.before is not a function

### ISSUE THREAD

**Issue by yyshengfan** [midwayjs/midway#2068]
// 使用
const { Bootstrap } = require('@midwayjs/bootstrap');
Bootstrap.before(async container => {
  // 读取远程配置
  web = createKoaweb(container.getConfigService().getConfiguration());
  await container.getAsync('remoteConfigKey');
})
  .configure({
    baseDir: path.join(__dirname, '/dist'),
    preloadModules: getFiles(path.join(__dirname, '/dist')),
  })
  .load(() => {
    return web;
  })
  .run();

// 报错
Bootstrap.before(async container => {
          ^

TypeError: Bootstrap.before is not a function
    at Object.<anonymous> (/Users/sh07047ml/hui/risk-components-control/bootstrap.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by waitingsong** [comment]
```ts
export declare class Bootstrap {
    private static starter;
    private static logger;
    private static configured;
    private static applicationContext;
    /**
     * set global configuration for midway
     * @param configuration
     */
    static configure(configuration?: IMidwayBootstrapOptions): typeof Bootstrap;
    private static getStarter;
    static run(): Promise<void>;
    static stop(): Promise<void>;
    static reset(): void;
    /**
     * on bootstrap receive a exit signal
     * @param signal
     */
    private static onSignal;
    /**
     * on bootstrap process exit
     * @param code
     */
    private static onExit;
    private static uncaughtExceptionHandler;
    private static unhandledRejectionHandler;
    static getApplicationContext(): IMidwayContainer;
}
```

没有 `before()` 这个方法啊

**Comment by czy88840616** [comment]
恩，3.x 去掉了，在已经有 [onConfigLoad](https://midwayjs.org/docs/lifecycle) 之后这个方法已经没什么作用了。
