### ISSUE TITLE
context被注入到service时，行为不一致？

### ISSUE THREAD

**Issue by sfesh2012** [midwayjs/midway#207]
使用inject方式将context注入到service中：
在 controller 中访问service的成员方法，可以正常获得上下文ctx对象
在 webmiddleware 中访问service的成员方法不能正常获得上下文ctx对象

示例代码：
参考service/user.ts 12行
访问 http://localhost:7001/user/1
经过 apiMiddleware和不经过apiMiddleware的行为不一致。

* **Node Version**: 11.1.0
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: mac os
* **Mini Showcase Repository**:  https://github.com/sfesh2012/midway-session-test

**Comment by czy88840616** [comment]
是的，middleware比较特殊，他不属于请求上下文内，无法注入ctx等，也无法获取请求作用域的对象，如果要获取请求上下文的对象，可以直接从参数获取。

**Comment by sfesh2012** [comment]
哦，暂时改入参了，这里能改进吗？不太优雅:)

**Comment by czy88840616** [comment]
middleware 比较特别，他是在一开始框架组装的时候就被实例化了，没法跟现有的上下文服务关联，只能注入单例的服务。

但是可以通过 ctx.requestContext.getAsync 的方式获取上下文服务，这样就属于链路的一部分，就能取到 ctx 了。


```ts
import { WebMiddleware, provide, inject } from 'midway';

@provide()
export class ApiMiddleware implements WebMiddleware {

  resolve() {
    return async (ctx, next) => {
      const userService = await ctx.requestContext.getAsync('userService');
      await userService.getUser({ id: 1 });
      await next();
    };
  }

}
```

**Comment by sfesh2012** [comment]
这样也不错， 我试试看

**Comment by sfesh2012** [comment]
可以了，这个方法相对优雅一些! 👍
