### ISSUE TITLE
v3-egg版本grpc报错

### ISSUE THREAD

**Issue by hbsjmsjwj** [midwayjs/midway#2072]
FAIL  test/index.test.ts (10.474 s)
  test/index.test.ts
    × should create multiple grpc service in one server (7270 ms)

  ● test/index.test.ts › should create multiple grpc service in one server
-------------------------------------------------------------------------------------
按照文档建demo，然后写grpc，单元测不通过

**Comment by czy88840616** [comment]
请提供更详细的 demo。。。

**Comment by hbsjmsjwj** [comment]
非常抱歉，要和文档一模一样就可以了，grpc默认6565，之前忽略了这点
