### ISSUE TITLE
worker 偶尔会挂掉

### ISSUE THREAD

**Issue by Yuliang-Lee** [midwayjs/midway#2086]
* **Node Version**: v16.13.0
* **Midway Version(Decorator/Core)**: 3.3.5
* **Component Name/Version**: 
* **Platform**: linux
* **Mini Showcase Repository**:

项目运行在 K8S 上，偶尔 worker 会突然死掉，
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/6936358/176867528-74d1a4f8-7fc5-4e28-b530-ae1393e5409f.png">

common-error 没有错误日志，看不出是什么引起的，这种问题有办法定位吗？

**Comment by czy88840616** [comment]
如果没有其他日志的话，这一点 egg-cluster 是定位不出来的。

ps：看着像是 worker 太多了。。少起几个试试。

**Comment by waitingsong** [comment]
看看资源方面有异常没。比如内存泄露

可以考虑改成 koa 单进程模式，估计日志能捕捉到异常。

**Comment by Yuliang-Lee** [comment]
好像还真是 worker 起多了或者说内存不够了导致的。最近优化资源成本，调小了pod 内存占用。。感谢
