### ISSUE TITLE
bull task 新需求

### ISSUE THREAD

**Issue by sy296565890** [midwayjs/midway#2090]
期望：
1. 支持更多的queue常用方法及更友好的提示
![image](https://user-images.githubusercontent.com/85245446/177084375-f79ca458-3621-4058-9d3f-6ceadeb9abae.png)

    job.pause();
    job.resume();

    pause(jobIds, 暂停处理任务or暂停计时器, 是否返回任务数据)

    jobIds = pauseAll(暂停处理任务or暂停计时器, 是否返回任务数据)
    jobOkIds = resumeAll(jobIds)

2. 更多的实用代码块
      e.g. clearBull 
                async clearBull (queue) {
                    // 核心关键问题查看github issues
                    // https://github.com/OptimalBits/bull/issues/83
                    await queue.empty();
                    await queue.clean(0, 'active');
                    await queue.clean(0, 'completed');
                    await queue.clean(0, 'delayed');
                    await queue.clean(0, 'failed');
                  }

**Comment by ddzyan** [comment]
可以本地安装下 npm i @types/bull -D

**Comment by sy296565890** [comment]
> 可以本地安装下 npm i @types/bull -D

非常感谢哥们的解答，我在安装依赖之后，新的问题又来了，还请哥们再帮忙看一下
![image](https://user-images.githubusercontent.com/85245446/177455397-21bd2ee4-ddb3-43bb-a478-c6d83240ec40.png)
![image](https://user-images.githubusercontent.com/85245446/177456031-e333ae23-2b7f-4f22-9eef-65f7397f4e81.png)

**Comment by ddzyan** [comment]
你可以上传一个项目到github上，方便看些
