### ISSUE TITLE
@midwayjs/bootstrap Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by lqsong** [midwayjs/midway#2096]
* **Node Version**: node 14
* **Midway Version(Decorator/Core)**: ^3.0.0
* **Component Name/Version**:^3.0.0
运行 `cross-env NODE_ENV=production node ./bootstrap.js` ,因为项目 js 有 import，请问有什么解决方案

**Comment by czy88840616** [comment]
如果项目下有前端文件，可以忽略目录，参考 https://midwayjs.org/docs/container#%E8%87%AA%E5%8A%A8%E7%BB%91%E5%AE%9A

**Comment by lqsong** [comment]
> 目下有前端文件，可以忽略目录，参考
是需要引入这个，所以有什么办法吗 ， 不用`@midwayjs/bootstrap`启动，自定义可以吗？或者其他方法。

**Comment by czy88840616** [comment]
你只有两个办法：

- 1、不要把前端目录放到 src 下
- 2、如果一定要放，参考上面链接。

**Comment by lqsong** [comment]
不在src 下，另外的目录，只是引入读取了这个文件，里面有import,所以`@midwayjs/bootstrap`不考虑支持解析`import`吗

**Comment by czy88840616** [comment]
不建议混引，如果只是类型，可以用 import type 语法，bootstrap.js 使用 js 放在根目录也是有原因的，在 node es module 没成熟前，不会支持其他编译方式。

**Comment by czy88840616** [comment]
不建议混引，如果只是类型，可以用 import type 语法，bootstrap.js 使用 js 放在根目录也是有原因的，在 node es module 没成熟前，不会支持其他编译方式。

**Comment by lqsong** [comment]
不用@midwayjs/bootstrap启动，自定义启动可行？有没有自定义`bootstrap`的样列

**Comment by waitingsong** [comment]
> 不建议混引，如果只是类型，可以用 import type 语法，bootstrap.js 使用 js 放在根目录也是有原因的，在 node es module 没成熟前，不会支持其他编译方式。

> 在 node es module **没**成熟前

“没”？  😄

**Comment by czy88840616** [comment]
bootstrap 就是干启动的事情。。不用它还能用谁。。
