### ISSUE TITLE
引用 cherrio 编译失败

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#2119]
编译报错如下
```shell
> crypto-mint@1.0.1 build
> npm run clear && midway-bin build -c


> crypto-mint@1.0.1 clear
> rm -rf ./logs ./run ./dist

   - Copy config/locales/en_US.json
   - Copy config/locales/zh_CN.json
   - Copy Complete
node_modules/cheerio-select/lib/index.d.ts:1:15 - error TS1005: ',' expected.

1 import { type Options as CSSSelectOptions } from "css-select";
                ~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:2:23 - error TS1005: ',' expected.

2 export { Parser, type ParserOptions };
                        ~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:10:27 - error TS1005: ',' expected.

10 export { DomHandler, type DomHandlerOptions };
                             ~~~~~~~~~~~~~~~~~

node_modules/htmlparser2/lib/index.d.ts:47:10 - error TS1005: ',' expected.

47     type Callbacks as TokenizerCallbacks
            ~~~~~~~~~





Error! You can try adding the -V parameter for more information output.
```

查询 midway-bin 编译源代码，并且查询相关资料，负责编译的模块包@midwayjs/mwcc把typescripte的版本号进行小版本限定 ` "typescript": "~4.2.4"`，error TS1005 错误为 ts 版本过低，语法不兼容，这块有考虑升级到最新版本吗？

**Comment by waitingsong** [comment]
` import { type Options as CSSSelectOptions } `  这种语法 ts 需要 4.7.2 以上。
mwcc 的依赖还在 4.2.4

如果你项目的 tsconfig.json 里面没有使用 paths，那么可以使用 `tsc` 替代 `midway-bin build` 作为编译命令。

**Comment by ddzyan** [comment]
> `import { type Options as CSSSelectOptions }` 这种语法 ts 需要 4.7.2 以上。 mwcc 的依赖还在 4.2.4
> 
> 如果你项目的 tsconfig.json 里面没有使用 paths，那么可以使用 `tsc` 替代 `midway-bin build` 作为编译命令。

嗯，我现在临时的解决方也是直接使用 `tsc` 替代，想了解下的是这个编译模块以后不做升级了吗？

**Comment by waitingsong** [comment]
mwcc 这个模块应该是会废弃的。 midway-cli 模块已经更新到 v2 不过还没发布，应该就解决 ts 版本问题了

**Comment by ddzyan** [comment]
最新版本编译出问题，这个模块是做了升级吗？ ts版本过低导致高版本语法不支持的问题，已经在安排升级的路上了吗
<img width="940" alt="image" src="https://user-images.githubusercontent.com/9130123/180428929-23e1d5e6-f1cb-4f7f-bf47-5a90ebd22ec0.png">

**Comment by czy88840616** [comment]
cli 现在只依赖到4.6的ts，如果有库特别激进，那就可能编译不了，可以用tsc替代
