### ISSUE TITLE
日志输出格式化了2次

### ISSUE THREAD

**Issue by ghostoy** [midwayjs/midway#2128]
* **Node Version**: 18.5.0
* **Midway Version(Decorator/Core)**: 3.3.6
* **Component Name/Version**: @midwayjs/logger@2.16.3
* **Platform**: 
* **Mini Showcase Repository**:

```typescript
logger.info('%s', '%Y-%m-%d')
// 应该输出
// %Y-%m-%d
// 实际输出
// %Y-%m-NaN
```
在@midwayjs/logger中使用`util.format`对`%s`部分格式化一遍，然后到了`winston`里又被`splat`格式化了一遍，导致日志中输出错误。

**Comment by ghostoy** [comment]
@midwayjs/logger上也提交了[相同的issue](https://github.com/midwayjs/midway/issues/2128)

**Comment by czy88840616** [comment]
好像不支持这种，%的变量的话，只能在第一个参数。

**Comment by ghostoy** [comment]
> 日志里要打 % 格式的内容？

是的

**Comment by ghostoy** [comment]
@czy88840616 你们会修复吗，我提交了PR (midwayjs/logger#63)

**Comment by waitingsong** [comment]
需要用 % 在后续日志中继续解析？ 会不会有安全问题（好比 log4j 那种）

**Comment by czy88840616** [comment]
@ghostoy 我把单测修了下，可以先 rebase 下master
