### ISSUE TITLE
[RFC] midway aop feature

### ISSUE THREAD

**Issue by kurten** [midwayjs/midway#213]
针对一个 function 执行的生命周期来说，我们期望可以在 function 执行之前、执行之后、抛出异常时做一些事情。比如参数验证权限，记录 function 执行耗时，以及异常返回结果封装等等。

我们定义一个 interpreter 接口，实现该接口的如下几个方法：

```TypeScript
import { InterceptorCycle } from 'midway';

@provide()
@interceptor()
@priority(-1) 
export class InterceptorCycleImpl implements InterceptorCycle {
  @inject()
  xxxService;  // 注入的必须为单例

  before(ctx) {
    // TODO this.xxxService.checkParams(ctx.params...);
    // ctx.return = true; 标记直接返回，不需要继续执行方法体
    ctx.time = Date.now();
  }
  
  after(ctx) {
    console.log(Date.now() - ctx.time);
  }

  catch(e, ctx) {
    console.error(e.stack, ctx);
  }
}
```

那么使用该 interpreter 方式如下：

```TypeScript
@provide()
export class HelloService {
  // 这里顺序可以使用 InterceptorCycle 中声明 priority 来指定具体顺序
  @intercept(['interceptorCycleImpl'])
  async test(a: string, b: boolean) {
      // TODO logic
  }
}
```

**Comment by justquanyin** [comment]
是需要在每个function前都加上 @intercept 么？调用function之前，如果鉴权失败，是不是应该可以直接返回报错信息，function的方法应该不需要再执行了

**Comment by kurten** [comment]
> 是需要在每个function前都加上 @intercept 么？调用function之前，如果鉴权失败，是不是应该可以直接返回报错信息，function的方法应该不需要再执行了

是的，需要显示的在 function 上加上 @intercept 来声明。关于提前返回，我是想在 ctx 中提供 return 标记来声明方法需要提前返回。

**Comment by justquanyin** [comment]
一个函数上支持多个 @intercept 的写法么？多个写法的话，是否有先后关系(类似于洋葱圈逻辑)？

**Comment by czy88840616** [comment]
里面是数组的话，就有顺序了。

**Comment by justquanyin** [comment]
那数组中每个InterceptorCycleImpl对象的 before 和 after函数的执行顺序是怎样的呢？

**Comment by kurten** [comment]
> 那数组中每个InterceptorCycleImpl对象的 before 和 after函数的执行顺序是怎样的呢？

* 执行顺序是 before -> 具体 function -> after，如果抛出异常，则执行 catch
* 数组顺序按照 ```@intercept``` 配置的顺序来定

**Comment by justquanyin** [comment]
> > 那数组中每个InterceptorCycleImpl对象的 before 和 after函数的执行顺序是怎样的呢？
> 
> * 执行顺序是 before -> 具体 function -> after，如果抛出异常，则执行 catch
> * 数组顺序按照 `@intercept` 配置的顺序来定

例如 `@intercept`数组中有 [a,b,c]
* 执行顺序是 a.before -> b.before -> c.before -> 具体function -> c.after -> b.after -> a.after 的话，那就是和洋葱圈的模式一致的呗？
* 如果是按照上面的顺序执行的话，catch的捕获，是不是也是洋葱圈的层级关系？

**Comment by kurten** [comment]
> > > 那数组中每个InterceptorCycleImpl对象的 before 和 after函数的执行顺序是怎样的呢？
> > 
> > 
> > 
> > * 执行顺序是 before -> 具体 function -> after，如果抛出异常，则执行 catch
> > * 数组顺序按照 `@intercept` 配置的顺序来定
> 
> 例如 `@intercept`数组中有 [a,b,c]
> 
> * 执行顺序是 a.before -> b.before -> c.before -> 具体function -> c.after -> b.after -> a.after 的话，那就是和洋葱圈的模式一致的呗？
> * 如果是按照上面的顺序执行的话，catch的捕获，是不是也是洋葱圈的层级关系？

是的

**Comment by justquanyin** [comment]
期待实现

**Comment by lichenhao** [comment]
建议参考 spring的 

我的一个简单实现如下：

```typescript
// 可复制到 https://www.typescriptlang.org/play/ 执行即可。
class Aspect {
    static around(aroundAspect:Function) { 
        return function (target: any, method: string, options: any): void {
            const handler = options.value; 
            options.value = function (...args): any {
                return aroundAspect(handler, this, args);
            };
        }
    }
}
class Throwable {
    static around(handler:Function, context:any, args:any[]):any {
        try {
            return handler.apply(context, args);
        } catch (e) {
            return {
                code: 9999,
                message: 'system error'
            };
        }
    }
}

class Action {
    @Aspect.around(Throwable.around)
    method(name: string): any {
        throw new Error('c'); 
        return {code: 200, message: "hello " + name };
    }
}

const result = new Action().method("test");
alert(JSON.stringify(result));
```

**Comment by kurten** [comment]
> 建议参考 spring的
> 
> 我的一个简单实现如下：
> 
> ```ts
> // 可复制到 https://www.typescriptlang.org/play/ 执行即可。
> class Aspect {
>     static around(aroundAspect:Function) { 
>         return function (target: any, method: string, options: any): void {
>             const handler = options.value; 
>             options.value = function (...args): any {
>                 return aroundAspect(handler, this, args);
>             };
>         }
>     }
> }
> class Throwable {
>     static around(handler:Function, context:any, args:any[]):any {
>         try {
>             return handler.apply(context, args);
>         } catch (e) {
>             return {
>                 code: 9999,
>                 message: 'system error'
>             };
>         }
>     }
> }
> 
> class Action {
>     @Aspect.around(Throwable.around)
>     method(name: string): any {
>         throw new Error('c'); 
>         return {code: 200, message: "hello " + name };
>     }
> }
> 
> const result = new Action().method("test");
> alert(JSON.stringify(result));
> ```

这个也是一个不错的实现方式，而且是和框架无关的实现

**Comment by lichenhao** [comment]
> > 建议参考 spring的
> > 我的一个简单实现如下：
> > ```ts
> > // 可复制到 https://www.typescriptlang.org/play/ 执行即可。
> > class Aspect {
> >     static around(aroundAspect:Function) { 
> >         return function (target: any, method: string, options: any): void {
> >             const handler = options.value; 
> >             options.value = function (...args): any {
> >                 return aroundAspect(handler, this, args);
> >             };
> >         }
> >     }
> > }
> > class Throwable {
> >     static around(handler:Function, context:any, args:any[]):any {
> >         try {
> >             return handler.apply(context, args);
> >         } catch (e) {
> >             return {
> >                 code: 9999,
> >                 message: 'system error'
> >             };
> >         }
> >     }
> > }
> > 
> > class Action {
> >     @Aspect.around(Throwable.around)
> >     method(name: string): any {
> >         throw new Error('c'); 
> >         return {code: 200, message: "hello " + name };
> >     }
> > }
> > 
> > const result = new Action().method("test");
> > alert(JSON.stringify(result));
> > ```
> 
> 这个也是一个实现方式，而且是和框架无关的实现。但是依旧无法解决多个aop函数执行的问题，而且加入有多个aop函数需要执行的话，顺序优先级、以及编写方式不是很优雅。

1. 顺序问题应该可以提供一些最佳实践来解决
2. 调试问题目前应该是整个Node生态的问题，不仅仅是框架问题，而且目前还没找到像Java生态一样非常好的调试能力，包括异常信息，堆栈信息等。

**Comment by czy88840616** [comment]
2.x 已提供拦截器。
