### ISSUE TITLE
ctx.query 解析与express v4 的差别

### ISSUE THREAD

**Issue by SmartOrange** [midwayjs/midway#2162]
类似一下 url
http://127.0.0.1:7001?mixFlowInstIds%5B%5D=108015365&flowInstIds%5B%5D=103137222

express 解析：
![image](https://user-images.githubusercontent.com/15233745/181458015-b64a59df-ddf3-4f56-aba2-8f6f44bc35d8.png)

midway：
![image](https://user-images.githubusercontent.com/15233745/181458099-6117a020-571a-40b7-a664-823c7db21986.png)

**Comment by waitingsong** [comment]
express 和 php 差不多，传递 数组字段名。 midway 默认是直接识别为字段名，然后重名的覆盖（可以设置为解析为数组）

**Comment by kurten** [comment]
依赖库的处理逻辑上有差异，我看看能不能抽象一下可配直化的逻辑出来

**Comment by czy88840616** [comment]
我让觅九提的...不要慌

**Comment by kurten** [comment]
> 我让觅九提的...不要慌

好吧，其实替换一下 koa request 中的 query parse 就行了，不过就是比较麻烦。
[qs](https://github.com/ljharb/qs/blob/main/test/parse.js#L9 ) 这个是支持这类复杂query参数处理的。

**Comment by czy88840616** [comment]
koa 我看是正确的，不正确的是 egg 吧。。

**Comment by czy88840616** [comment]
是egg的特性，我加了个参数 https://midwayjs.org/docs/extensions/egg#query-%E6%95%B0%E7%BB%84%E8%A7%A3%E6%9E%90
