### ISSUE TITLE
Class constructor ApiMiddleware cannot be invoked without 'new'

### ISSUE THREAD

**Issue by SilverLeaves** [midwayjs/midway#217]
* **Node Version**: 10.15.3
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

//src/app/middleware/verfiy.ts
```ts
@provide()
export default class ApiMiddleware implements WebMiddleware {
  resolve() {
    return async (ctx:Context, next) => {
      if (ctx.headers.Authorization) {
        console.log(ctx.headers.Authorization)
      }
      await next();
    };
  }
//
```
//config/config.default.ts
```ts
...
  config.middleware = ["verify"];
...
```

![图片](https://user-images.githubusercontent.com/31165554/57837635-c6f2bb00-77f5-11e9-8780-aed5fdec0ef2.png)

**Comment by czy88840616** [comment]
这个是没办法放在config里用的，也就是说这个方式不支持全局 middleware，只支持单路由上的。同 #174
