### ISSUE TITLE
swagger在body存在多个单独取值的时候 swagger中不显示该条

### ISSUE THREAD

**Issue by jiumengs** [midwayjs/midway#2170]
* **Node Version**: v16.13.2
* **Midway Version(Decorator/Core)**: 3.3.6
* **Component Name/Version**: "swagger-ui-dist": "^4.13.0" "@midwayjs/swagger": "^3.4.5"
* **Platform**: macos

<img width="979" alt="image" src="https://user-images.githubusercontent.com/39983417/182005882-f52daa78-d360-4c8b-8020-ab39ec3506cf.png">

<img width="979" alt="image" src="https://user-images.githubusercontent.com/39983417/182005924-16673ca6-28d1-485f-8e80-423c664d2c80.png">

**Comment by czy88840616** [comment]
swagger下不建议body取特定属性，会导致数据不全，这样写的话需要带上@ApiProperty

**Comment by jiumengs** [comment]
好的 感谢
