### ISSUE TITLE
框架层面支持一个插件可加载多个插件实例

### ISSUE THREAD

**Issue by SilverLeaves** [midwayjs/midway#218]
* **Node Version**:10.15.3
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在使用中有些插件是需要多个实例的，但是插件本身并未实现多实例配置。
用例：
`egg-dingtalk`默认是单实例配置，可是我这里有两个dingtalk开发需求，他们业务重叠，所以我共用了同一后端，所以需要配置两个dingtalk实例。

**Comment by czy88840616** [comment]
这个没办法。。midway 的 @plugin() 也只是简单的从 app 上取属性，具体的多实例还是要插件来实现的。

**Comment by czy88840616** [comment]
egg-dingtalk 并没有提供什么特殊的能力。。

- 1、https://github.com/eggjs/egg-dingtalk/blob/master/app/extend/application.js#L7 貌似留了口子，可以在 app.ts 里手动创建多个实例，然后塞到 ioc 里
- 2、直接用 node-dingtalk 客户端就行了，加上 @config 装饰器，体验也差不多

**Comment by SilverLeaves** [comment]
egg的底层koa也出ts版本的了，[tkoa https://github.com/tkoajs/tkoa](https://github.com/tkoajs/tkoa)，
