### ISSUE TITLE
定义路由的方式

### ISSUE THREAD

**Issue by yuu2lee4** [midwayjs/midway#219]
现在有这么一个需求，我的路由根据提供方式有很多种类型，有对内的，有给前端的，有的是openapi，我再controller下面建立了三个文件夹,inward、zuul、open，希望inward下面的路由前面统一有个/inward的前缀，以此类推，目前就只能在每个controller文件里手写前缀，很不优雅，希望就是按照文件夹自动加上前缀或者说能通过某种方式自己定义

**Comment by czy88840616** [comment]
所以说你的 `controller/inward` 文件夹下有很多 controller 文件？

**Comment by kurten** [comment]
> 所以说你的 `controller/inward` 文件夹下有很多 controller 文件？

我的理解，应该是自动带上目录，作为url路径的prefix

**Comment by czy88840616** [comment]
@kurten 不好吧，这样就和目录有关系了，到时候拆文件出来就有影响了。

**Comment by Lellansin** [comment]
可以写个 util 根据 __dirname 在每个文件开头算一个前缀

**Comment by yuu2lee4** [comment]
不知道业界是怎么弄得，反正现在这种是很麻烦

**Comment by zhou-xin-undefined** [comment]
在文件的第一行定义一个URL路径, 后面的继承这个路径

**Comment by zhou-xin-undefined** [comment]
加个中间层进行路由分发

**Comment by a1235** [comment]
有好的解决方法了吗

**Comment by waitingsong** [comment]
> 
> 
> > 所以说你的 `controller/inward` 文件夹下有很多 controller 文件？
> 
> 我的理解，应该是自动带上目录，作为url路径的prefix

如果实现了这个需求，那么接下来的自动路由需求将会是 `/目录名/文件名（不包含扩展名）`  哈哈

**Comment by czy88840616** [comment]
这就越来越。。后面应该会提供动态注册路由的 API，比如 app.registerRouter(UserController, { group: 'xxx', prefix: '/v1'}); 这样，不过头疼的就是 swagger 那边怎么取。

**Comment by czy88840616** [comment]
已经提供了动态增加路由的 API。
