### ISSUE TITLE
[组件] TypeORM 配置 key

### ISSUE THREAD

**Issue by dongdongcpk** [midwayjs/midway#2191]
最新版本 README 中与实际代码片段中的 key 并不一致，对比见下：

- README：https://github.com/midwayjs/midway/tree/main/packages/typeorm#configuration
- 代码：https://github.com/midwayjs/midway/blob/main/packages/typeorm/index.d.ts#L7

具体应以哪个为准？

**Comment by czy88840616** [comment]
定义漏改了，以文档为准。

**Comment by dongdongcpk** [comment]
官网也同步更新一下吧，看的一头雾水

**Comment by czy88840616** [comment]
官网好像没错，都是对的样子。
