### ISSUE TITLE
swagger Responses schema 显示问题

### ISSUE THREAD

**Issue by doublekai** [midwayjs/midway#2199]
![image](https://user-images.githubusercontent.com/40791509/183019361-feb2203a-5c5a-48ae-944c-32cd021e4493.png)
这是返回定义的schema
![image](https://user-images.githubusercontent.com/40791509/183019445-2cc661a7-830c-4280-a6cd-4835f6c227ab.png)
![image](https://user-images.githubusercontent.com/40791509/183019506-e11667db-2958-4e5c-a95b-edb48bd843e4.png)
![image](https://user-images.githubusercontent.com/40791509/183019605-3138118e-6322-42a3-aa43-a8ea4f8c3d5a.png)

**Comment by kurten** [comment]
TypeScript 范型继承拿不到类型信息的，ApiProperty 里面指定类型试试

**Comment by czy88840616** [comment]
@kurten https://docs.nestjs.com/openapi/operations#advanced-generic-apiresponse

**Comment by kurten** [comment]
> @kurten https://docs.nestjs.com/openapi/operations#advanced-generic-apiresponse

midway swagger 也支持这么搞的

**Comment by czy88840616** [comment]
你给个文档示例吧。。他说没试出来。

**Comment by doublekai** [comment]
这样可以![image](https://user-images.githubusercontent.com/40791509/183337896-98e37d6d-d1ca-45cc-8f04-6a4fcff8dc5c.png)
![image](https://user-images.githubusercontent.com/40791509/183338022-cd6401a4-a1c0-4264-8862-984e760534d6.png)

我想实现
![image](https://user-images.githubusercontent.com/40791509/183337951-13e07e28-c48c-47e4-bb9c-fd404922fcfc.png)
不知道这样有什么方法

**Comment by doublekai** [comment]
> 你给个文档例子吧。。他说没试出来。
现在query还不支持对象吗
![image](https://user-images.githubusercontent.com/40791509/183359870-6783dfda-7999-4d27-b75b-a2fe9a193250.png)

**Comment by Sinmere** [comment]
官方swagger测试案例 '/test5/{aa}       @ApiResponse({
        type: OssMultipleUploadResponseDto
    })
swagger API都显示不了   望修复

**Comment by czy88840616** [comment]
@Sinmere 有问题提到单独的issue中，提供更完整的内容。

**Comment by czy88840616** [comment]
已经处理。
