### ISSUE TITLE
怎样在midway中container的dumpDependency功能？

### ISSUE THREAD

**Issue by sfesh2012** [midwayjs/midway#220]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问在midway中怎样使用container的dumpDependency功能呢？
怎样获得container？ 文档中并没有提到呢。
@czy88840616

**Comment by czy88840616** [comment]
这个midway里是自动的，会生成在run/ 目录下，每个进程都会生成一个....

**Comment by sfesh2012** [comment]
看到了， 感谢！
