### ISSUE TITLE
当mock的Service对象没有使用缺省 export "default" class 的时(即只使用export class)， mockService 会找不到需要mock的方法名。

### ISSUE THREAD

**Issue by phiner** [midwayjs/midway#221]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by phiner** [comment]
错误信息为:
AssertionError [ERR_ASSERTION]: property list in original object must be function

**Comment by kurten** [comment]
可以使用 app.mockClassFunction ，直接使用 mockService 和midway框架的IoC机制不兼容

**Comment by phiner** [comment]
> 可以使用 app.mockClassFunction ，直接使用 mockService 和midway框架的IoC机制不兼容

噢，是这样，多谢。
