### ISSUE TITLE
midway/koa3 怎么接入skywalking

### ISSUE THREAD

**Issue by hbsjmsjwj** [midwayjs/midway#2215]
* **Node Version**:14.18.1
* **Midway Version(Decorator/Core)**:3.0.0
* **Component Name/Version**:Platform
* **Platform**: 
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
我还在研究。skywalking 是 apache 的产品，midway是支持 OpenTelemetry 的，理论上是支持不同的产品。比如：/istio/readme/#deploying-opentelemetry-collector

**Comment by czy88840616** [comment]
看着 https://github.com/apache/skywalking-nodejs 是兼容 koa 的，直接在 bootstrap.js 里引用启动就行了吧。

**Comment by hbsjmsjwj** [comment]
--bootstrap.js------------------------------------------------------
const { Bootstrap } = require('@midwayjs/bootstrap');
const { default:agent } = require('skywalking-backend-js')
agent.start({
  serviceName: 'mw_service',
  serviceInstance: 'mw_service',
  collectorAddress: 'xxxxx',
});
Bootstrap.run();
--启动命令----------------------------------------------------------
    "dev-bootstrap": "cross-env NODE_ENV=local midway-bin dev --ts --entryFile=bootstrap.js",
-报错------------------------------------------------------------------------
{
  file: 'D:\\develop\\apimanage-mw-mock-server\\node_modules\\skywalking-backend-js\\lib\\agent\\protocol\\grpc\\clients\\HeartbeatClient.js',
  code: 12,
  details: 'Method not found: skywalking.v3.ManagementService/reportInstanceProperties',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [ 'application/grpc' ] },
    options: {}
  },
  level: 'error',
  message: 'Failed to send heartbeat 12 UNIMPLEMENTED: Method not found: skywalking.v3.ManagementService/reportInstanceProperties',
  stack: 'Error: 12 UNIMPLEMENTED: Method not found: skywalking.v3.ManagementService/reportInstanceProperties\n' +
    '    at Object.callErrorFromStatus (D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\call.ts:81:17)\n' +
    '    at Object.onReceiveStatus (D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\client.ts:352:36)\n' +
    '    at Object.onReceiveStatus (D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\client-interceptors.ts:462:34)\n' +
    '    at Object.onReceiveStatus (D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\client-interceptors.ts:424:48)\n' +
    '    at D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\call-stream.ts:330:24\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:77:11)\n' +
    'for call at\n' +
    '    at ServiceClientImpl.makeUnaryRequest (D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\client.ts:324:26)\n' +
    '    at ServiceClientImpl.reportInstanceProperties (D:\\develop\\apimanage-mw-mock-server\\node_modules\\@grpc\\grpc-js\\src\\make-client.ts:189:15)\n' +     
    '    at Timeout._onTimeout (D:\\develop\\apimanage-mw-mock-server\\node_modules\\skywalking-backend-js\\src\\agent\\protocol\\grpc\\clients\\HeartbeatClient.ts:75:36)\n' +
    '    at listOnTimeout (internal/timers.js:557:17)\n' +
    '    at processTimers (internal/timers.js:500:7)'
}

不理解

**Comment by czy88840616** [comment]
这是你 skywalking 的服务没返回心跳吧，这个已经不是框架侧的问题了。

**Comment by hbsjmsjwj** [comment]
# 记录
### 安装 npm i skywalking-backend-js
### bootstrap.js配置
```javascript
try {
  const { default: agent } = require("skywalking-backend-js");//"skywalking-backend-js": "^0.5.1"   "skywalking-backend-js": "^0.3.0"
  agent.start({
    serviceName: "dev-mw-Agent",
    serviceInstance: "dev-mw-Agent",
    collectorAddress: "xxx.xxx.xxx:11800", //skywalking 默认上报端口（rpc）（12800 http）
  });
} catch (error) {
  console.log('skywalking error========================================',error)
}

const { Bootstrap } = require('@midwayjs/bootstrap');
Bootstrap.run();

```
##### 踩坑笔记
可能因为公司网络和skywalking服务不稳定，会报一些错误
然后 尝试低版本  skywalking-backend-js 0.3.0 ，成功了，但大多时候或安装的时候失败报错（原因是 里面依赖的grpc包太老了被废弃），偶尔也会成功，但大多时候报错
```shell
 grpc@1.24.11 install E:\开源\新建文件夹\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library
```
这个直接npm i skywalking-backend-js  新版本

##### 自己搭一个skywalking 避免环境和网络的问题(docker安装)

```shell
# 服务端
sudo docker run --name oap --restart always -p 1234:1234 -p 11800:11800 -p 12800:12800 -d apache/skywalking-oap-server:8.5.0-es6
# UI端
sudo docker run --name oap-ui --restart always -p 18080:8080 --link oap:oap -e SW_OAP_ADDRESS=oap:12800 -d apache/skywalking-ui:8.5.0
```
然后按照上面的配置，调用接口 ，在 http://xxxxxxxxx:18080/  (ui)查看信息

**Comment by Yuliang-Lee** [comment]
现在 skywalking 的 mongoose instrument 有 bug，如果用了 mongoose 的还不能接 skywalking https://github.com/apache/skywalking/issues/10253
