### ISSUE TITLE
升级到v3之后OPTIONS请求变成了404

### ISSUE THREAD

**Issue by immzz** [midwayjs/midway#2216]
* **Node Version**: v14.x
* **Midway Version(Decorator/Core)**: 3.4.9
* **Component Name/Version**: midways faas
* **Platform**: aliyun FC
* **Mini Showcase Repository**:

从2.x升级到3.4.9后，所有的非GET请求（如POST请求）之前的OPTIONS请求结果都变成了404，导致原请求被当做CORS error处理。
使用的是midwayjs/faas，函数定义如下：

```
@ServerlessTrigger(ServerlessTriggerType.HTTP, {
    path: '/some/api',
    method: 'post',
  })
  @Validate()
  async handleRequest(@Body(ALL) payload: RequestRule) {
  }
```

**Comment by czy88840616** [comment]
yml 有变化吗。

**Comment by andantei** [comment]
找到原因了：
在f.yml中我们原来一直使用的是：
```
...
custom:
  customDomain:
    domainName: false
...
```
这样部署的时候不会每次都覆盖手动配置好的custom domain。
升级到新版本后由于必须设置domainName，于是我们就加上了具体的domainName，但部署之后发现trigger methods里面自动去掉了OPTIONS: https://tinyurl.com/2lzqxr99 。

这样导致OPTIONS变成了404。感觉应该是serverless-devs的问题，但看了一下文档并不支持triggers的OPTIONS method：

https://docs.serverless-devs.com/fc/yaml/triggers#http%E8%A7%A6%E5%8F%91%E5%99%A8

所以我们现在临时的解决方法是直接去掉customDomain配置，这样不会影响到我们手动设置的自定义域名，但每次部署的时候还是会自动生成一个域名。

**Comment by echosoar** [comment]
应该是这个设置：
```yaml
custom:
  customDomain: false
```
