### ISSUE TITLE
Request for reproducible benchmarks

### ISSUE THREAD

**Issue by oraluben** [midwayjs/midway#2229]
* **Node Version**: v16.15.1
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

We're evaluating the performance of node frameworks, but the benchmark(s) of midway seems to lack document (there's `benchmark/` and `scripts/benchmark.sh`) and bounded to specific node version (only run benchmark CI with node 14).

While the `benchmark/` seems updated, I cannot get a valuable result from it. It runs without error but returns a zero qps.
The `scripts/benchmark.sh` is used by Github Actions CI but I cannot run it with node 16. I made some dirty updates trying to get it working, but not all issues are solved: #2228.

It would be nice to have a stable benchmark with step-by-step instruction.

**Comment by czy88840616** [comment]
We set this action to avoid memory leak and will be fix it soon.

**Comment by oraluben** [comment]
> While the `benchmark/` seems updated, I cannot get a valuable result from it. It runs without error but returns a zero qps.

Actually, I can get a positive QPS on some of my dev envs, and zero on other dev envs and my local env. Do you have any idea about this?
I also pushed some updates about `benchmark/readme.md` that you may find useful.

**Comment by czy88840616** [comment]
> > While the `benchmark/` seems updated, I cannot get a valuable result from it. It runs without error but returns a zero qps.
> 
> Actually, I can get a positive QPS on some of my dev envs, and zero on other dev envs and my local env. Do you have any idea about this? I also pushed some updates about `benchmark/readme.md` that you may find useful.

maybe have some error when project start.  You can got real qps after build and run with `npm run start`.

**Comment by oraluben** [comment]
ok it's still not working...
the benchmark quit instantly after startup:
```
$ npm run start

> midway-sample@1.0.0 start
> node bootstrap.js

2022-08-12 17:15:33,524 INFO 54924 [midway:bootstrap] current app started
2022-08-12 17:15:33,527 INFO 54924 [midway:bootstrap] exit with code:0
$ curl localhost:7001                       
curl: (7) Failed to connect to localhost port 7001 after 7 ms: Connection refused
```
Sometimes it seems to work because some stale server is listening on 7001 and returns result, it's not the benchmark server.

**Comment by czy88840616** [comment]
npm i & npm run build & npm run start

**Comment by oraluben** [comment]
thanks, it worked!
