### ISSUE TITLE
如何动态获取注入对象的实例

### ISSUE THREAD

**Issue by im3ott** [midwayjs/midway#2237]
* **Node Version**: 16.13.0
* **Midway Version(Decorator/Core)**: 3.0.0
* **Component Name/Version**: koa/3.0.0
* **Platform**: web
* **Mini Showcase Repository**:

比如在代码中注入了一个 A 的对象(单例作用域)，通过 this.a 获取到的是个 Proxy 的对象实例，如何能获取 A 的对象实例？

@Scope(ScopeEnum.Singleton)
class A {
}

@Inject()
a: A;

@Init()
async init() {
    this.a   // a is Proxy {__is_proxy__: true, __target_id__: '57c006d971715f8ca42121a2ed4c569a'}
}

**Comment by czy88840616** [comment]
你拿到的就是，变成这样是因为循环依赖了。

**Comment by im3ott** [comment]
> 

循环依赖是指在 class A 中注入了 class B， class B 中 也注入了 class A 么？ 例如这样

@Scope(ScopeEnum.Singleton)
class A {
    @Inject()
    b: B
}

@Scope(ScopeEnum.Singleton)
class B {
    @Inject()
    a: A
}

**Comment by im3ott** [comment]
#https://github.com/midwayjs/midway/issues/2237#issuecomment-1214144813

循环依赖是指在 class A 中注入了 class B， class B 中 也注入了 class A 么？ 例如这样

https://github.com/scope(ScopeEnum.Singleton)
class A {
@Inject()
b: B
}

https://github.com/scope(ScopeEnum.Singleton)
class B {
@Inject()
a: A
}

**Comment by im3ott** [comment]
> 你拿到的就是，变成这样是因为循环依赖了。

谢谢，有个新的问题不知道是bug还是写法的问题

我在 class B 的 init 函数中获取到 class A 的对象（通过listModule获取）然后通过 this.applicationContext.getAsync 获取 class A的对象实例时会死循环（因为getAsync没有实例，在getAsync函数中又createAsync了，然后又走到了 init 中）大概代码如下

```
export const CustomDecorator = (): ClassDecorator => (target: any) => {
    saveModule('mycustomDecorator', target);
    Provide()(target);
}

@CustomDecorator()
@Scope(ScopeEnum.Singleton)
class A {
    ....
}

@Scope(ScopeEnum.Singleton)
class B {

    @ApplicationContext()
    applicationContext: IMidwayContainer;

    @Init()
    async init() {
        let temp = listModule('mycustomDecorator');
        if (!temp.length) return;
        for (const e of temp) {
            let instance = await this.applicationContext.getAsync(e);    // 这里就死循环了，会再次进入 init
        }
    }
}
```

打断点调试看的话，是因为 getAsync 时通过 id 找不到对应的实例从而最后又执行了 createAsync

```
    async getAsync(identifier, args, objectContext) {
        var _a;
        args = args !== null && args !== void 0 ? args : [];
        objectContext = objectContext !== null && objectContext !== void 0 ? objectContext : { originName: identifier };
        if (typeof identifier !== 'string') {
            objectContext.originName = identifier.name;
            identifier = this.getIdentifier(identifier);
        }
        if (this.registry.hasObject(identifier)) {
            return this.registry.getObject(identifier);
        }
        const definition = this.registry.getDefinition(identifier);
        if (!definition && this.parent) {
            return this.parent.getAsync(identifier, args);
        }
        if (!definition) {
            throw new error_1.MidwayDefinitionNotFoundError((_a = objectContext === null || objectContext === void 0 ? void 0 : objectContext.originName) !== null && _a !== void 0 ? _a : identifier);
        }
        return this.getManagedResolverFactory().createAsync({ definition, args });
    }

```

```
    hasObject(identifier) {
        var _a;
        identifier = (_a = this.identifierRelation.getRelation(identifier)) !== null && _a !== void 0 ? _a : identifier;
        return this.has(PREFIX + identifier);    // 加了这个 PREFIX 所以找不到，但 identifier 对应的结果是有的
    }

```

我这样获取实例是有问题的吗？

**Comment by czy88840616** [comment]
getAsync 一般都是在类之外（比如初始化声明周期 onReady里）做的，不会在类本身里面执行，你在 init 里做就等价于 inject，这两个时机是一样的，proxy 就是用来解决循环依赖的，所以拿到proxy对象，依旧是可以正常使用的，没必要动态再去拿。

**Comment by im3ott** [comment]
> getAsync 一般都是在类之外（比如初始化声明周期 onReady里）做的，不会在类本身里面执行，你在 init 里做就等价于 inject，这两个时机是一样的，proxy 就是用来解决循环依赖的，所以拿到proxy对象，依旧是可以正常使用的，没必要动态再去拿。

好的，我明白了，谢谢；动态获取的目的是为了解决 this 指向，我再考虑一下结构设计吧，谢谢

**Comment by waitingsong** [comment]
>  let instance = await this.applicationContext.getAsync(e);    // 这里就死循环了，会再次进入 init

可以在这儿排除掉 B 自己应该就不会走回来了，比如给 B 加个 symbol 属性值
