### ISSUE TITLE
仓库在本地怎么完成依赖安装和单元测试呢

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/midway#2238]
现在遇到下载仓库后，在本地运行 `npm run clear` 和 `npm run bootstrap ` ，内部的一些依赖还是存在报错未引用的情况，有什么办法解决吗？之前没有遇到，可以顺利在本地完成依赖安装和单元测试

**Comment by czy88840616** [comment]
npm i & npm  run bootstrap & npm run cov ?

**Comment by ddzyan** [comment]
嗯，是的，在执行 npm run cov 就报错了
![image](https://user-images.githubusercontent.com/9130123/185021567-8a309c39-740e-4401-9eb0-7880634b5c01.png)

**Comment by ilyydy** [comment]
> 嗯，是的，在执行 npm run cov 就报错了 ![image](https://user-images.githubusercontent.com/9130123/185021567-8a309c39-740e-4401-9eb0-7880634b5c01.png)

npm run build 再试试。因为 "typings": "dist/index.d.ts"，依赖编译后的 index.d.ts

![image](https://user-images.githubusercontent.com/8614566/185022825-509a4f15-6835-41c6-9b6d-e7e875b38335.png)

**Comment by czy88840616** [comment]
哦，是的，npm i & npm run bootstrap & npm run build & npm run cov ?

**Comment by ddzyan** [comment]
可以，解决了
