### ISSUE TITLE
任务调度 3 个装饰器的参数都是 any，有计划补全吗

### ISSUE THREAD

**Issue by ilyydy** [midwayjs/midway#2246]
https://github.com/midwayjs/midway/blob/a8ff82caa59ef214bed97ad6e09ff1487ed8e389/packages/decorator/src/decorator/task/task.ts#L4

https://github.com/midwayjs/midway/blob/a8ff82caa59ef214bed97ad6e09ff1487ed8e389/packages/decorator/src/decorator/task/queue.ts#L7

https://github.com/midwayjs/midway/blob/a8ff82caa59ef214bed97ad6e09ff1487ed8e389/packages/decorator/src/decorator/task/taskLocal.ts#L7

**Comment by czy88840616** [comment]
老的不想动了，会重写。
