### ISSUE TITLE
[Question] `experimentalDecorators：true`压不住啦?

### ISSUE THREAD

**Issue by SilverLeaves** [midwayjs/midway#225]
* **Node Version**:10.15.3
* **midway Version**:1.5.2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:windows 10

 `"experimentalDecorators": true,`已经设置啦（下载模板，我就没改过），今天莫名其妙的蹦出来装饰器的提示，用了装饰器的ts文件都飘红了。
![图片](https://user-images.githubusercontent.com/31165554/58464476-568a5900-8168-11e9-9e95-c5c147c45513.png)
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "inlineSourceMap":true,
    "noImplicitThis": true,
    "stripInternal": true,
    "pretty": true,
    "declaration": true,
    "outDir": "dist",
    "lib": ["es2017", "dom"]
  },
  "exclude": [
    "app/public",
    "app/views",
    "dist",
    "node_modules",
    "test"
  ]
}
```

**Comment by czy88840616** [comment]
像是 vscode 索引不对，重新打开试试？或者重新安装依赖。

**Comment by SilverLeaves** [comment]
删除重装依赖，重打开，不行。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/58469253-b76a5f00-8171-11e9-8a0c-82d4836a40c1.png)

重装了依赖。。没有炸。。

**Comment by SilverLeaves** [comment]
我重装下vscode试试，今天vscode特别抽风。

**Comment by czy88840616** [comment]
😢

**Comment by SilverLeaves** [comment]
重装vscode也不行，造孽啊
![图片](https://user-images.githubusercontent.com/31165554/58470276-e41f7600-8173-11e9-957f-6584be3433f7.png)

**Comment by czy88840616** [comment]
看看是不是配置的影响，比如.vscode 目录什么的。。

**Comment by SilverLeaves** [comment]
周末重装看看
