### ISSUE TITLE
引入了ESM的包, 已经升级TypeScript到最新，为什么dev模式下正常，build会有这个错误？

### ISSUE THREAD

**Issue by ckvv** [midwayjs/midway#2261]
> my-midway-project@1.0.0 build
> midway-bin build -c

   - Copy Complete
error TS4124: Compiler option 'moduleResolution' of value 'nodenext' is unstable. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'.

* **Node Version**:  v16.16.0
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
TypeScript 对 ems 支持的不是很好吧，不推荐用。

**Comment by waitingsong** [comment]
midway 目前不支持 ESM，所以 tsconfig.json 固定这两个参数就行：
```
    "module": "commonjs",
    "moduleResolution": "node",
```

**Comment by waitingsong** [comment]
> TypeScript 对 ems 支持的不是很好吧，不推荐用。

nodejs v16 ESM 支持是 stable， TypeScript 从 4.7 开始对 ESM 支持也很不错了。
我现在的 nodejs 轮子都编译为 ESM + CJS， 单测是用 ESM 模式跑，都正常 
`cross-env TS_NODE_PROJECT=test/tsconfig.json mocha --loader=ts-node/esm`

10月份 v18 就进入 LTS， midway 可以考虑把对 ESM （编译）的支持排上日程了

**Comment by czy88840616** [comment]
没那么简单， esm 固化变量的特性，在测试，监控等场景大量的包是不支持的。
