### ISSUE TITLE
Passport 登录后，用户信息反序列化函数里，依赖注入的数据库操作对象为空

### ISSUE THREAD

**Issue by chenyuncai** [midwayjs/midway#2262]
Passport 登录后用户信息反序列化函数里，依赖注入的数据库操作对象为空
* **Node Version**: 16.11.0
* **Midway Version(Decorator/Core)**: 3.4.10
* **Component Name/Version**:
* **Platform**: windows
* **Mini Showcase Repository**:

您好，按照文档尝试集成passport做用户登录时，

```
@CustomStrategy()
export class LocalStrategy extends PassportStrategy(Strategy) {
  @InjectEntityModel(UserEntity)
  userModel: Repository<UserEntity>;
  async validate(username: string, password) {}
  serializeUser(user: UserEntity, done) {}
  async deserializeUser(username: string, done) {}
}
```

在validate函数中可以正常使用this.userModel进行数据库查询，但在deserializeUser里userModel为undedined。不能调用其下的数据库查询方法，validate与deserializeUser函数的执行机制有什么区别吗？

**Comment by czy88840616** [comment]
可能 this 丢了。。

**Comment by chenyuncai** [comment]
是的，反序列化里打印this，this为undefined
