### ISSUE TITLE
task启动就触发 在 K8S 上多 POD 时，会触发多次

### ISSUE THREAD

**Issue by Yuliang-Lee** [midwayjs/midway#2263]
* **Node Version**: 16
* **Midway Version(Decorator/Core)**: 3
* **Component Name/Version**: 3
* **Platform**: linux
* **Mini Showcase Repository**:

task启动就触发 在 K8S 上多 POD 时，会触发多次。看表现看起来哪怕不是在 K8S 上，在普通机器上部署多套，也会触发多次？

有办法在不额外引入一个分布式锁的情况下做到只在一个服务实例上执行吗？

**Comment by czy88840616** [comment]
都得有个锁吧，不管是文件锁还是分布式锁
