### ISSUE TITLE
請問有更好的方法去取消自動掃描某些路徑?

### ISSUE THREAD

**Issue by skmdev** [midwayjs/midway#227]
看了源代碼後, 發現可以加以下config 去取消自動掃描某些路徑, 但有更好的方法去設置嗎?

```
  config.container = {
    ignore: '**/client/**', // ignore path in midway auto scan
  };
```

**Comment by czy88840616** [comment]
目前留的口子就是这个配置，一般情况下我们希望 src 下的内容都是 typescript 代码，并且能被 ioc 所扫描到，其他的文件尽可能放到 src 目录外。
