### ISSUE TITLE
手动实现typeorm数据库实体实现迁移到数据库中

### ISSUE THREAD

**Issue by liangyuan1** [midwayjs/midway#2274]
如何根据代码中创建的实体，执行一个命令实现数据库的整体迁移工作

**Comment by czy88840616** [comment]
可以使用 https://orkhan.gitbook.io/typeorm/docs/migrations，但是非常不建议在代码层面做，尽可能使用数据库工具（cli，数据库管理工具，云数据库管理工具 dms 等）。
