### ISSUE TITLE
关于swagger的exampleValue的显示

### ISSUE THREAD

**Issue by qq295823929** [midwayjs/midway#2286]
![image](https://user-images.githubusercontent.com/38320579/188045757-c1ce038e-ab68-49c1-95ec-33b9730bdaad.png)
![image](https://user-images.githubusercontent.com/38320579/188045783-ebebdd22-a23f-4ad4-8458-5599ab6b1482.png)
![image](https://user-images.githubusercontent.com/38320579/188045812-c8f260b8-5035-4606-9930-ebb2d490fd11.png)
![image](https://user-images.githubusercontent.com/38320579/188046758-66dcad69-f5ec-4801-a059-4938f7974034.png)

就是有一个通知的model,规定项目中返回的数据结构统一要为{code:0,message:'',data:data},这样的模式,然后在分页中,这个data数据为
{count:999,rows:[{id:1,title:"一个通知标题"}]},我按照图上面的写法,得到的exampleValue是这样的,也就是data并没有exampleValue,但是scheme里面显示是可以识别的
![image](https://user-images.githubusercontent.com/38320579/188046997-3d7434b2-9c19-431a-a7e8-b57170894c0d.png)

![image](https://user-images.githubusercontent.com/38320579/188046247-7904c269-03b3-4af1-a74e-1c5c23f9f535.png)
这个data的example怎么才能按照我写好的显示?
另外还有一个问题,我看其他框架,比如java,.net里面的swagger貌似都是如下图自动生成的?
![image](https://user-images.githubusercontent.com/38320579/188046358-5f5f3795-67bf-4dc3-95cf-460644e23674.png)
midway可不可以做到这一点?不同每个都必须要写example,而是根据类型自动导出,因为这个exampleValue更多的是一眼看出数据格式是什么样的吧?本身具体是什么其实并不重要吧?

**Comment by qq295823929** [comment]
没人回答我就再说一下吧.其实简化来说就是嵌套的数据格式里面的exampleValue我没有在midwayswagger里面找到合适的编写方式.必须要给所有的字段编写exampleValue,否则在swaggerUi里面的exampleValue就不显示.这个真的很蛋疼

**Comment by czy88840616** [comment]
你的问题是，希望不写 example的默认值，确希望 swagger 依旧能展示一个 ？

**Comment by qq295823929** [comment]
> 你的问题是，希望不写 example的默认值，确希望 swagger 依旧能展示一个 ？

是的呢,就比如我的返回格式是{code:0,message:'',data:User},这个user是一个用户信息,但是我并不想在每个返回结果里面都写上这个data的example,而是根据引用的UserDto的类型,自动生成一个example?我看了nest.js都是可以做到的.

**Comment by qq295823929** [comment]
> 你的问题是，希望不写 example的默认值，确希望 swagger 依旧能展示一个 ？

就如同我最开始提的那样,虽然我在scheme里面可以看到返回的结构了,但是,一旦我没有给data的ApiProperty注解的example给一个值,那么data将不会出现在example Value这个选项中(但是在scheme里面还是可以完整地看出来整个数据格式的),不知道是我哪里有问题还是并没有提供这个功能呢?

**Comment by czy88840616** [comment]
容我研究一下。

**Comment by qq295823929** [comment]
> 容我研究一下。

好的,辛苦了,小公司目前选型,之前是用egg.很想使用midway

**Comment by qq295823929** [comment]
> 容我研究一下。

今天又捣鼓了一整天,最后发现好像用我最开始的那种写法,生成的json数据是不对的,
![image](https://user-images.githubusercontent.com/38320579/188595359-79295ad1-7cbe-49b0-9e7b-230631478df8.png)
dao导致我直接用apifox导入的时候,并不能识别MainUserInfoRes,
![image](https://user-images.githubusercontent.com/38320579/188596191-7feedb49-ce61-43de-b236-77493876f664.png)
我手动将json件中的'/'补全后,重新导入到apifox,发现可以正确识别了
![image](https://user-images.githubusercontent.com/38320579/188596586-2c3e5b26-2121-41a0-9c6d-263f5fe01c00.png)
这应该是是一个bug吧?

**Comment by qq295823929** [comment]
![image](https://user-images.githubusercontent.com/38320579/188600295-2300e1c6-78a2-465b-8ca6-a1e74f0274c5.png)
我把这里的'#components/schemas/',修改为'#/components/schemas/'之后,json数据可以正常导出到apifox.能确认下吗?
另外,exampleValue出不来的问题我也大概找出来了?是因为这里如果没有写example的话,就默认给了一个example的对象,我没有明白之前这样做的目的,但是我将它注释掉之后,发现,一起如我想要的那样了.
![image](https://user-images.githubusercontent.com/38320579/188601653-4d65f3f4-0e57-4d34-a619-db4d3df645c7.png)

**Comment by qq295823929** [comment]
![image](https://user-images.githubusercontent.com/38320579/188600295-2300e1c6-78a2-465b-8ca6-a1e74f0274c5.png)
我把这里的'#components/schemas/',修改为'#/components/schemas/'之后,json数据可以正常导出到apifox.能确认下吗?
另外,exampleValue出不来的问题我也大概找出来了?是因为这里如果没有写example的话,就默认给了一个example的对象,我没有明白之前这样做的目的,但是我将它注释掉之后,发现,一起如我想要的那样了.
![image](https://user-images.githubusercontent.com/38320579/188601653-4d65f3f4-0e57-4d34-a619-db4d3df645c7.png)

**Comment by czy88840616** [comment]
是的，我昨天发现了少了个 /
