### ISSUE TITLE
关于编译打包的问题

### ISSUE THREAD

**Issue by waitingsong** [midwayjs/midway#230]
对于编译打包的疑问：
1. 执行 `npm i --prod` 安装依赖
2. 执行 `npm run build` 

如下错误提示
> 'midway-bin' 不是内部或外部命令，也不是可运行的程序或批处理文件。
...
...

执行 `npm i --prod midway-bin ` 安装失败。

能否介绍下你们的编译、打包、部署流程是怎样的？  

另，我在 egg 项目的一个处理是把  `@types/node` 放在 `dependencies` 中，这样通过 `npm i --prod` 安装的依赖在执行 build 的时候才不会报错（缺少类型）。

**Comment by czy88840616** [comment]
因为midway-bin，tyoescript等都是开发期依赖，所以需要先 npm i，再执行 midway-build，然后删除node_modules，重新执行 npm i —production

**Comment by waitingsong** [comment]
原来如此。没想到。。
为了减小 typescript 占用的开发空间(大概45M)，我是安装全局的版本然后做个软连接，这样每个项目开发目录就省了不少空间。 然后把 eslint 等等开发包也用同样方式处理大概还能省几十M ，项目多了还是可观的。 不过对于把 typescript 写到dep 依赖中且限制了版本的包就没办法了。。
我的 egg 用这个方式就只需要 npm i --prod 装一次依赖就可以打包了。
midway 可以考虑这种方式。

**Comment by czy88840616** [comment]
可以尝试用 lerna 管理所有应用，类似 https://github.com/midwayjs/midway-examples 的方式，使用 --hoist 模式安装，这样依赖只在最上层，所有应用统一一份。
