### ISSUE TITLE
请问midway怎么集群部署

### ISSUE THREAD

**Issue by hbsjmsjwj** [midwayjs/midway#2311]
线上需要两台机器，采用集群部署方式

**Comment by waitingsong** [comment]
docker-compose ?

**Comment by hbsjmsjwj** [comment]
以后会用k8s，目前不会，暂定用nginx负载，想有没有更好的方式

**Comment by waitingsong** [comment]
简单就  docker-compose + nginx

**Comment by hbsjmsjwj** [comment]
部门只有几个试点项目上容器+k8s，现在就简单部两台，然后由nginx upstream
