### ISSUE TITLE
组件&扩展中JWT配置说明没有引入JwtMiddleware来源

### ISSUE THREAD

**Issue by zhoucswift** [midwayjs/midway#2325]
import { Configuration } from '@midwayjs/decorator';
import { IMidwayContainer } from '@midwayjs/core';
import * as jwt from '@midwayjs/jwt';

@Configuration({
  imports: [
    // ...
    jwt,
  ],
})
export class MainConfiguration {
  async onReady(applicationContext: IMidwayContainer): Promise<void> {
    // 添加中间件
    this.app.useMiddleware([
      // ...
      JwtMiddleware,
    ]);
  }
}

**Comment by czy88840616** [comment]
往下看，有示例。
