### ISSUE TITLE
部署报错的问题

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#233]
hi，时隔两月，我又回来咨询部署报错的问题了。
[曾经关于部署的咨询](https://github.com/midwayjs/midway/issues/186)
我在package.json设置midway版本号为1.5.6，build后部署到云服务器上，报错如图：

<img width="1073" alt="QQ20190610-222433@2x" src="https://user-images.githubusercontent.com/40480550/59202468-19de4900-8bcf-11e9-90b5-249f5615a363.png">

请问，如何才能部署成功？谢谢！

**Comment by czy88840616** [comment]
看上去像是启动走了ts模式，用的启动脚本是哪个？

**Comment by linzelong95** [comment]
@czy88840616 
我使用nom run build 打包，上传至云服务器，再安装依赖npm i --production.
使用的pm2启动项目，按照midway的教程，引入了一个server.js。
然后pm2 start server.js
但是报错了。

**Comment by czy88840616** [comment]
加个NODE_ENV=production看看

**Comment by linzelong95** [comment]
@czy88840616 
请问是在build的时候加入吗？如下：
"build": "set NODE_ENV=production && midway-bin build -c"
我尝试着这样做，用pm2启动后，依然报同样的错。
如果不是这样处理，那NODE_ENV=production该加在哪儿呢？谢谢

**Comment by czy88840616** [comment]
呃我是指在执行pm2的时候

**Comment by linzelong95** [comment]
@czy88840616 
我配置了pm2的相关参数，如图。然后使用pm2 start ecosystem.config.js --env production运行项目，在日志里依然看到报同样的错。

<img width="499" alt="QQ20190611-121418@2x" src="https://user-images.githubusercontent.com/40480550/59243488-e937f700-8c42-11e9-81bd-cb3aca3011af.png">

**Comment by czy88840616** [comment]
目前我使用 https://github.com/midwayjs/midway-examples/tree/master/demo-pm2 这个demo，执行 npm run build 之后，本地执行 node index.js 能成功，删除 dist 目录后报错，说明走的是 js 模式，没有问题。

安装 pm2，执行 pm2 start index.js 似乎也没问题。。
![image](https://user-images.githubusercontent.com/418820/59283754-a6efd380-8c9d-11e9-8c14-eaeb954244b3.png)

**Comment by czy88840616** [comment]
理论上，服务器上也只需要 dist、node_modules、package.json，其他的都可以不需要。
