### ISSUE TITLE
[有偿1000] 有大佬可以把 midway & umi 结合起来吗？

### ISSUE THREAD

**Issue by 18583952605** [midwayjs/midway#2341]
需要了解 midway 这个框架的，就知道我说的结合是什么意思~~~
就是midway前后端一体化的那种

可以的大佬联系下，这个比较难，有偿(500 - 1000)求
ps: 我自己搞了好久，没有搞定
希望大佬们帮帮忙~

**Comment by czy88840616** [comment]
可以去微信群里问。

**Comment by 18583952605** [comment]
@czy88840616 大佬有时间搞下不~~~

**Comment by czy88840616** [comment]
这个。。暂时没有呢

**Comment by 18583952605** [comment]
@czy88840616 大佬 加不了群  
钉钉群满 100 人进不去了   
微信拉群机器人不通过好友

**Comment by czy88840616** [comment]
钉钉2 群可以加，微信也可以先加我 czy88840616

**Comment by vanness30214** [comment]
同求最新版本midway3与umi4结合
