### ISSUE TITLE
关于 'NODE_ENV' 不是内部或外部命令，也不是可运行的程序 或批处理文件 的一点小建议

### ISSUE THREAD

**Issue by muzaisimao** [midwayjs/midway#235]
在**Windows**系统上使用`NODE_ENV=xxx` 会出现 " 'NODE_ENV' 不是内部或外部命令，也不是可运行的程序 或批处理文件"的错误 , 这种设置环境变量的方式在powershell和cmd中都不被支持.

有个兼容Mac, Linux, Windows的解决方案, 可以使用 [cross-env](https://github.com/kentcdodds/cross-env)  设置环境变量.

package.json:
```json
  "scripts": {
    "start_build": "npm run build && cross-env NODE_ENV=development midway-bin dev",
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "debug": "cross-env NODE_ENV=local midway-bin debug --ts",
    "build": "midway-bin build -c"
  }
```
希望可以整合在`midway`中, 用Windows的程序员还是(wo)挺(jiu)多(shi)的😂😂
😂

**Comment by czy88840616** [comment]
😢，本来是计划 windows 生成的脚手架稍微调整下。。然后发现不是很好改。。。

**Comment by czy88840616** [comment]
测了下，好像没问题，可以加。

**Comment by czy88840616** [comment]
已经修改发布，可以试试：）

**Comment by muzaisimao** [comment]
好的, 下午试试😁
