### ISSUE TITLE
官方提供的例子启动报错

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#236]
使用midway-init下载了midway-ts样例，安装依赖后，用npm run dev启动报错如图

<img width="1165" alt="QQ20190611-190910@2x" src="https://user-images.githubusercontent.com/40480550/59267421-d04c3780-8c7c-11e9-975b-2f001b9c2b47.png">

**Comment by czy88840616** [comment]
咦。。。我还想回的。。。

貌似是因为加了严格模式，可以加下面的配置，也可以把strict 相关的去掉先。。我想想怎么搞。


```json
  "compilerOptions": {
    "strictPropertyInitialization": false,
```
