### ISSUE TITLE
如何让midwayjs使用永久的腾讯key进行ci/cd部署

### ISSUE THREAD

**Issue by Xishang7707** [midwayjs/midway#2360]
按照教程在.env文件中配置了key和secret，但是部署时一直要扫码，无法进行自动部署。

**Comment by czy88840616** [comment]
这个我们做不到呢。。部署的行为是腾讯云自己决定的。

**Comment by Xishang7707** [comment]
> 这个我们做不到呢。。部署的行为是腾讯云自己决定的。

是使用serverless framework进行部署的吗？

**Comment by czy88840616** [comment]
是老的 serverless framework 的一个 plugin，但是现在腾讯云似乎不更新了。
