### ISSUE TITLE
疑问：git 已经默认已经对换行符进行了转换，如果我关闭eslint中换行符的检查，本地windows使用CRLF 对系统运行会不会有影响。

### ISSUE THREAD

**Issue by yuntian001** [midwayjs/midway#2365]
1.git 已经默认已经对换行符进行了转换
默认情况下
core.autocrlf 为 true  在提交时将CRLF转换为LF，在拉取（检出checkout）时将UNIX换行符（LF）替换成CRLF。
为什么还在eslint 中进行检查?
2. 如果我eslint中关闭换行符的检查，本地使用CRLF 对系统运行会不会有影响。

**Comment by czy88840616** [comment]
1、默认的项目是以 mac 作为基础，.editorconfig 中配置的换行是 LF
2、这个时候如果 autocrlf 为 true，在windows 下就像你说，代码是  CRLF 会有问题，所以最简单的就是 autocrlf 为 false，保持win/mac 一致
3、以团队工作为准，可以自行调整

**Comment by waitingsong** [comment]
可以规定检出检入全部都是 LF （autocrlf: false, safeCrlf: blank）.
