### ISSUE TITLE
BUG: @Get 等路由注解中的 summary 或者 description 不生效

### ISSUE THREAD

**Issue by yuntian001** [midwayjs/midway#2366]
以下用法
```
 @Get('/info',{ summary: 'test',description:'测试'})
  async getUser(@Query('uid') uid) {
    return { success: true, message: 'OK', data: { aa: 1 } };
  }
```
拿到的的swagger  json中没有summary和description
![image](https://user-images.githubusercontent.com/43692243/194807586-638967da-a59e-4eec-9154-abbd64d06260.png)

使用@ApiOperation 则可以拿到
```
 @Get('/info',{ summary: 'test',description:'测试'})
  @ApiOperation({summary:'test',description:'测试'})
  async getUser(@Query('uid') uid) {
    return { success: true, message: 'OK', data: { aa: 1 } };
  }
```
![image](https://user-images.githubusercontent.com/43692243/194807882-2848d705-c0ee-43d9-a628-34dafe1fff85.png)

**Comment by czy88840616** [comment]
pr 已经合进去了，发了就能用了。

**Comment by yuntian001** [comment]
> pr 已经合进去了，发了就能用了。
