### ISSUE TITLE
swagger 无法解析循环依赖的对象数组

### ISSUE THREAD

**Issue by Ttou** [midwayjs/midway#2370]
* **Node Version**: 16.17.0
* **Midway Version(Decorator/Core)**: 3.5.3
* **Component Name/Version**: Swagger@3.5.3
* **Platform**: Windows11
* **Mini Showcase Repository**: https://github.com/Ttou/midway-swagger-demo

![image](https://user-images.githubusercontent.com/4298437/195010877-cbcc4121-357e-4e28-ad5d-d156cf84b31a.png)

**Comment by czy88840616** [comment]
这种模块互相引用是没有办法的，甚至都不在框架层面。。node 本身 require 拿到的就是 undefined，碰到这种情况最好吧两个放到同一个文件中。
