### ISSUE TITLE
@midwayjs/typegoose 报Operation `*.findOne()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by wgcairui** [midwayjs/midway#2374]
* **Node Version**: v18
* **Midway Version(Decorator/Core)**:3.6.0
* **Component Name/Version**:@midwayjs/typegoose ^3.6.0
* **Platform**: mac
* **Mini Showcase Repository**:

当我有一个default默认数据库配置,mongoose.connections中有两个连接,此时任何请求操作都导致Operation `*.findOne()` buffering timed out after 10000ms 超时,但是我把mongoose.connections[0]中的连接配置调整为default之后,工作都正常了,我从midway V2版本更新上来的,是不是哪里没有配置? 之前core@3.1.6版本还好的

config.default.ts配置
```
export default {
  mongoose: {
    dataSource: {
      default: {
        uri: `mongodb://${
          process.env.NODE_Docker === 'docker' ? 'mongo' : '127.0.0.1'
        }:27017/test`,
        options: {
          useNewUrlParser: true,
          useUnifiedTopology: true,
        } as ConnectOptions,
        // 关联实体
        entities: ['**/entity/*.ts'],
      },
    },
  },
}
```

我的补救措施
```
import { Autoload, Init, Provide, Scope, ScopeEnum } from '@midwayjs/decorator';
import mongoose from 'mongoose';
import config from '../config/config.default';

@Provide()
@Scope(ScopeEnum.Singleton)
@Autoload()
export class MongooseDataSource {
  @Init()
  async init() {
    await mongoose.connect(
      config.mongoose.dataSource.default.uri,
      config.mongoose.dataSource.default.options
    );
  }
}
```

**Comment by czy88840616** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/418820/195128076-3033ba23-7535-4878-a137-3213325ae2da.png">
这个删了么

**Comment by wgcairui** [comment]
没有使用EntityModel
<img width="675" alt="image" src="https://user-images.githubusercontent.com/12164036/195224526-b6953fbb-34d5-4cc3-ad80-aa14d6a21eee.png">

entity
```
import { modelOptions, prop, Ref } from '@typegoose/typegoose';
import { Schema } from 'mongoose';

class Devprotocol {
  @prop({ enum: [485, 232], default: 485 })
  public Type: number;

  @prop()
  public Protocol: string;
}

/**
 * 设备信息
 */
@modelOptions({ schemaOptions: { collection: 'device.types' } })
export class DevType {
  @prop()
  public Type!: string;

  @prop()
  public DevModel!: string;

  @prop({ type: () => Devprotocol })
  public Protocols: Devprotocol[];
}
```

// 关联实体
        `entities: ['**/entity']`
后戳改了也一样

**Comment by czy88840616** [comment]
@wgcairui  给我一个可复现的最小 demo ？

**Comment by wgcairui** [comment]
不好弄,我连了五六个服务,不好拆分,先这样用吧,我mongo也没有多库的需求,后面自己新建一个v3的demo看看
