### ISSUE TITLE
mysql在大量insert的时候，连接出现`Error: Pool is closed.`，服务直接中断

### ISSUE THREAD

**Issue by chenzhaozheng** [midwayjs/midway#2376]
* **Node Version**: 12.22.7
* **Midway Version(Decorator/Core)**: 2.3.0
* **Component Name/Version**:未知
* **Platform**: linux
* **Mini Showcase Repository**: 
####  2. 服务会出现如下异常
![image](https://user-images.githubusercontent.com/5388869/195231720-491c7754-14d1-45b8-9bae-7fe93042df32.png)

**Comment by stone-jin** [comment]
是不是你数据库被你压力搞的很大？导致连接被断了？这时候是不是优化一下客户端的写法，例如使用批插入方式？

**Comment by chenzhaozheng** [comment]
> 是不是你数据库被你压力搞的很大？导致连接被断了？这时候是不是优化一下客户端的写法，例如使用批插入方式？

数据库是压力有点大，但是其实连接上去操作啥的是可以的，还是可以访问的，而node服务的话就直接中断了。客户端的写法是要优化的，只是我在想能不能有方式能让服务不会中断掉，只是说访问的时候去等待或者说有个超时，有类似的情况可以等压力减低后让服务自动恢复起来。

**Comment by czy88840616** [comment]
这种是连接池被耗完了，如果要精细来做的话，得自己维持连接池去创连接了，以及对每个请求做限制等等。
