### ISSUE TITLE
打包时，如何自动将存放静态资源的public文件夹复制一份到dist

### ISSUE THREAD

**Issue by linzelong95** [midwayjs/midway#238]
嗨，我打包的时候，生产的dist没有包含public文件夹，请问如何配置，才能自动将存放静态资源的public文件复制一份到dist？或者，怎样处理dist里的文件跟src的public之间的关系？
谢谢。

<img width="1398" alt="QQ20190612-172614@2x" src="https://user-images.githubusercontent.com/40480550/59340855-604fb700-8d39-11e9-88b2-5824f5d8e78e.png">

**Comment by czy88840616** [comment]
https://midwayjs.org/midway/tool_set.html#build-%E5%91%BD%E4%BB%A4

可以用 build 命令的配置部分。

**Comment by linzelong95** [comment]
@czy88840616 
谢谢
