### ISSUE TITLE
controller的参数如果是class类型，目前是需要加@Validate()注解才能实现自动类型转换，希望能做个统一配置

### ISSUE THREAD

**Issue by Hank360** [midwayjs/midway#2381]
* **Node Version**: 16.x
* **Midway Version(Decorator/Core)**:3.6.0
* **Component Name/Version**: -
* **Platform**: - 
* **Mini Showcase Repository**: -

controller的参数如果是class类型，目前是需要加@Validate()注解才能实现自动类型转换，希望能做个统一配置；

像我们的项目100%都需要类型转换，几乎每个controller方法都需要加@Validate()注解，习惯了spring的自动转换，希望midway也能有个全局的配置；

**Comment by StringKe** [comment]
可以自己包裹一下注解
