### ISSUE TITLE
mongo, saas系统， 数据需要用database级别隔离， 即每个租户都创建一个database给他用， 请问支持吗？用的是mongoose跟@typegoose/typegoose

### ISSUE THREAD

**Issue by huangapple** [midwayjs/midway#2392]
mongo, saas系统， 数据需要用database级别隔离， 即每个租户都创建一个database给他用， 请问支持吗？用的是mongoose跟@typegoose/typegoose

**Comment by czy88840616** [comment]
一个系统动态连接所有数据库？

**Comment by huangapple** [comment]
对， 想法是这样的。   有新租户要进来时， 就动态创建一个数据库， 该数据库下有一整套的业务表。
后面这个租户的所有操作都是操作这个数据库下的。  跟别的租户是数据库级别隔离的。

**Comment by czy88840616** [comment]
动态连接数据库是很简单的，理论上每个租户数据独立，只要结构相同，用不同的连接去做就行了。

动态创建数据库，肯定是不会在同一份代码中来做的，这种拿其他脚本来做更好。

**Comment by huangapple** [comment]
谢谢指导。
