### ISSUE TITLE
libs下面的service文件修改保存后不会自动重启midway

### ISSUE THREAD

**Issue by huangyanyang** [midwayjs/midway#240]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

libs下面的service文件修改保存后不会自动重启midway

**Comment by czy88840616** [comment]
可以参考这个。https://github.com/midwayjs/midway/pull/24/files#diff-6d5a47204caab757fba3d8c4fbd82f9cR11
