### ISSUE TITLE
midway日志配置了，个别项不生效

### ISSUE THREAD

**Issue by zhengrz** [midwayjs/midway#2403]
node版本：16.17.0
npm版本：8.19.2

"@midwayjs/bootstrap": "^3.0.0",
"@midwayjs/core": "^3.0.0",
"@midwayjs/decorator": "^3.0.0",
"@midwayjs/info": "^3.0.0",
"@midwayjs/koa": "^3.0.0",
"@midwayjs/logger": "^2.14.0",
"@midwayjs/validate": "^3.0.0"

// config.default.ts
import { MidwayConfig } from '@midwayjs/core';

export default {
  keys: ['idata'],
  koa: {
    port: 7001,
  },
  midwayLogger: {
    default: {
      dir: './logs',
      maxSize: '100m',
      maxFiles: '3d',
      datePattern: 'YYYY-MM-DD.log',
      format: info => {
        return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.labelText}${info.message}`;
      },
    },
    clients: {
      coreLogger: {
        fileLogName: 'core',
      },
      appLogger: {
        fileLogName: 'app',
      },
    },
  },
} as MidwayConfig;

使用this.ctx.logger.info('asdasdas');

目前遇到问题是：输出的日志格式不对
2022-10-18 12:32:49,181 INFO 9902 [-/::1/-/17ms GET /api/get_user] asdasdas

**Comment by czy88840616** [comment]
你这个是上下文日志的格式，https://midwayjs.org/docs/logger#%E9%85%8D%E7%BD%AE%E4%B8%8A%E4%B8%8B%E6%96%87%E6%97%A5%E5%BF%97%E8%BE%93%E5%87%BA%E6%A0%BC%E5%BC%8F

**Comment by zhengrz** [comment]
> 你这个是上下文日志的格式，https://midwayjs.org/docs/logger#%E9%85%8D%E7%BD%AE%E4%B8%8A%E4%B8%8B%E6%96%87%E6%97%A5%E5%BF%97%E8%BE%93%E5%87%BA%E6%A0%BC%E5%BC%8F

import { MidwayConfig } from '@midwayjs/core';

export default {
  keys: ['idata'],
  koa: {
    port: 7001,
  },
  midwayLogger: {
    default: {
      dir: './logs',
      maxSize: '100m',
      maxFiles: '3d',
      datePattern: 'YYYY-MM-DD.log',
      format: info => {
        return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.message}`;
      },
      contextFormat: info => {
        return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.message}`;
      },
    },
    clients: {
      coreLogger: {
        fileLogName: 'core',
        format: info => {
          return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.message}`;
        },
        contextFormat: info => {
          return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.message}`;
        },
      },
      appLogger: {
        fileLogName: 'app',
        format: info => {
          return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.message}`;
        },
        contextFormat: info => {
          return `${info.timestamp} ${info.LEVEL} ${info.pid} ${info.message}`;
        },
      },
    },
  },
} as MidwayConfig;


我直接粗暴用这样日志配置，日志输出依然是：2022-10-18 17:08:52,884 INFO 23615 [-/::1/-/11ms GET /api/get_user] asdasdas

**Comment by czy88840616** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/418820/196462234-e64ea90a-99b2-490d-8dd1-ba107f0be494.png">
请参考文档进行适配。

**Comment by zhengrz** [comment]
已经处理好了，谢谢
