### ISSUE TITLE
弱弱的问一下，为什么midway又做起了全栈

### ISSUE THREAD

**Issue by WangHansen** [midwayjs/midway#241]
话说淘宝前端发布了很多前后端分离的博客，介绍到了midway构架
印象里midway构架通过nodejs做ssr实现了“大前端”解决了前后端分离
记得大前端的概念很厉害，网上有很多讨论，大家都一致认为很先进
可是现在midway开源了之后却变成了一个全栈框架，请问大佬可以讲解一下为什么吗
还有就是全栈的话怎么take advantage of容器技术呢，我现在看到的industry standard好像都是前后端分离，前端SPA部署到static hosting，后台可以用docker来做，加上k8s还可以自由伸缩
全栈怎么看都感觉不是在进步啊😂
我是小白，求不喷🤣

**Comment by czy88840616** [comment]
前后端分离是比较早的概念，是将原本的模板层独立部署，到了今天，演进为了 BFF，前端基本上都是 React or Vue 来完成，Node 端用来提供接口或者 SSR，midway 最开始做的就是这层工作。但是光做这层是不够的，web 层已经有 koa/express/egg 等体系来完成了，本质上没有太大的区别，而全栈体系在开发的过程中其实缺少很多能力，在大体系上 Node.js 是缺失的。

目前集团大多数应用都是对内的中台，基本上都是前端来 own 整个项目，全栈一方面是开拓了前端的视野和能力，另一方面也是业务本身的需要。另一方面，你现在看到的 midway 只是 midway for egg，是 midway 体系的一部分。

**Comment by WangHansen** [comment]
不好意思回复的晚 我还是没有看懂 所以全栈相比于之前大前端有什么优势么 而且全栈不是会更不方便做microservice结构

**Comment by czy88840616** [comment]
我理解全栈更像是一个不确定的概念，不是说做了数据库或者缓存就是全栈了，应该有更大的定义。

微服务，faas等，你都可以看成全栈的一个延伸，并不是说传统场景才有全栈。

优势的话
1、独立解决更让复杂的问题
2、可以拓展前端的边界职能，寻求更多新场景
