### ISSUE TITLE
npm run deploy没有正常运行

### ISSUE THREAD

**Issue by hugyu** [midwayjs/midway#2419]
* **Node Version**:16.00.0
* **Midway Version(Decorator/Core)**:3.0.0
我在执行npm run deploy时 没有像文档那样部署到阿里云FC而是在生成一个新的文件夹和压缩包
![image](https://user-images.githubusercontent.com/92319342/196855815-c4a31551-4e78-4271-9c4e-9c80240f6a11.png)

**Comment by czy88840616** [comment]
发下package.json ?

**Comment by hugyu** [comment]
{
  "name": "midway_faas_project",
  "private": true,
  "version": "1.0.0",
  "description": "Midway Serverless for the Serverless environment",
  "main": "index.js",
  "license": "MIT",
  "keywords": [
    "serverless",
    "midway"
  ],
  "scripts": {
    "dev": "cross-env NODE_ENV=local midway-bin dev --ts",
    "test": "cross-env midway-bin test --ts",
    "deploy": "midway-bin deploy",
    "lint": "mwts check",
    "lint:fix": "mwts fix"
  },
  "dependencies": {
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/decorator": "^3.0.0",
    "@midwayjs/faas": "^3.0.0",
    "@midwayjs/hooks": "^3.0.1",
    "@midwayjs/koa": "^3.6.0",
    "@midwayjs/typeorm": "^3.6.0",
    "@midwayjs/validate": "^3.6.0",
    "mysql2": "^2.3.3",
    "typeorm": "^0.3.10"
  },
  "devDependencies": {
    "@midwayjs/cli": "^1.2.90",
    "@midwayjs/cli-plugin-faas": "^1.2.90",
    "@midwayjs/fcli-plugin-fc": "^1.2.90",
    "@midwayjs/mock": "^3.0.0",
    "@midwayjs/serverless-app": "^3.0.2",
    "@midwayjs/serverless-fc-starter": "^3.0.2",
    "@midwayjs/serverless-fc-trigger": "^3.0.2",
    "@types/jest": "^26.0.10",
    "@types/node": "14",
    "cross-env": "^6.0.0",
    "jest": "^26.4.0",
    "mwts": "^1.0.5",
    "ts-jest": "^26.2.0",
    "typescript": "~4.6.0"
  }
}

**Comment by hugyu** [comment]
> 发下package.json ?

{
"name": "midway_faas_project",
"private": true,
"version": "1.0.0",
"description": "Midway Serverless for the Serverless environment",
"main": "index.js",
"license": "MIT",
"keywords": [
"serverless",
"midway"
],
"scripts": {
"dev": "cross-env NODE_ENV=local midway-bin dev --ts",
"test": "cross-env midway-bin test --ts",
"deploy": "midway-bin deploy",
"lint": "mwts check",
"lint:fix": "mwts fix"
},
"dependencies": {
"@midwayjs/core": "^3.0.0",
"@midwayjs/decorator": "^3.0.0",
"@midwayjs/faas": "^3.0.0",
"@midwayjs/hooks": "^3.0.1",
"@midwayjs/koa": "^3.6.0",
"@midwayjs/typeorm": "^3.6.0",
"@midwayjs/validate": "^3.6.0",
"mysql2": "^2.3.3",
"typeorm": "^0.3.10"
},
"devDependencies": {
"@midwayjs/cli": "^1.2.90",
"@midwayjs/cli-plugin-faas": "^1.2.90",
"@midwayjs/fcli-plugin-fc": "^1.2.90",
"@midwayjs/mock": "^3.0.0",
"@midwayjs/serverless-app": "^3.0.2",
"@midwayjs/serverless-fc-starter": "^3.0.2",
"@midwayjs/serverless-fc-trigger": "^3.0.2",
"@types/jest": "^26.0.10",
"@types/node": "14",
"cross-env": "^6.0.0",
"jest": "^26.4.0",
"mwts": "^1.0.5",
"ts-jest": "^26.2.0",
"typescript": "~4.6.0"
}
}

**Comment by echosoar** [comment]
输出的日志可以把最后面的一部分截图截一下吗

**Comment by hugyu** [comment]
> 输出的日志可以把最后面的一部分截图截一下吗

![image](https://user-images.githubusercontent.com/92319342/196860200-17b811ea-bdae-442a-a82c-915af8fe9b45.png)

**Comment by echosoar** [comment]
这个看起来是阿里云的 serverless-devs 发布有点问题，我找一台 windows 电脑拉阿里云的同学一起排查下

**Comment by hugyu** [comment]
> 这个看起来是阿里云的 serverless-devs 发布有点问题，我找一台 windows 电脑拉阿里云的同学一起排查下

谢谢

**Comment by hugyu** [comment]
> 这个看起来是阿里云的 serverless-devs 发布有点问题，我找一台 windows 电脑拉阿里云的同学一起排查下
大佬，怎么解决呀

**Comment by echosoar** [comment]
![image](https://user-images.githubusercontent.com/14832743/197108495-182cc8a4-acfe-46c2-aa43-9a62f97abc78.png)
我们新建了一个 midway faas v3 的项目 deploy 没有复现出来问题，你方便吧你的代码打个zip包发我一下吗，我用你的代码再排查下。
可以发我邮箱 soar.gy@alibaba-inc.com，如果你在我们的钉钉群里，可以群里@我

**Comment by hugyu** [comment]
> ![image](https://user-images.githubusercontent.com/14832743/197108495-182cc8a4-acfe-46c2-aa43-9a62f97abc78.png) 我们新建了一个 midway faas v3 的项目 deploy 没有复现出来问题，你方便吧你的代码打个zip包发我一下吗，我用你的代码再排查下。 可以发我邮箱 [soar.gy@alibaba-inc.com](mailto:soar.gy@alibaba-inc.com)，如果你在我们的钉钉群里，可以群里@我
谢谢，我重启了一个新的fass项目，可以了，谢谢大佬
