### ISSUE TITLE
执行start_build报错

### ISSUE THREAD

**Issue by hcYu168** [midwayjs/midway#242]
![image](https://user-images.githubusercontent.com/29545462/59491221-f65e1b80-8eb8-11e9-93ce-237d4e9e8cdb.png)

**Comment by czy88840616** [comment]
midway-bin dev --ts

**Comment by hcYu168** [comment]
> midway-bin dev --ts

 midway-bin dev --ts这个可以运行，但是npm runn start的时候就会报错，这是为什么？

**Comment by czy88840616** [comment]
`midway-bin dev --ts` 用于本地开发，会自动 require('ts-node/register')，执行 *.ts 文件不会报错。

npm run start 应该走了 egg-scripts，本身只会走 js 模式，会使用 dist/xxx 来启动，不过看报错貌似是 typeorm 的 ioc 走到了 ts 文件，可以看看是不是 typeorm 引起的。
