### ISSUE TITLE
升级3.6版本后，upload文件上传报错

### ISSUE THREAD

**Issue by kooriookami** [midwayjs/midway#2429]
* **Node Version**:
* 16.15.1
* **Midway Version(Decorator/Core)**:
* 3.6.0
* **Component Name/Version**:
* @midwayjs/upload 3.6.1
* **Platform**:
* Win11 x64
* **Mini Showcase Repository**:

之前使用3.5.x版本的文件上传没有问题，今天@midwayjs/upload升级到3.6.1后，文件上传会报错，提示Invalid update file name xxx, please check it，不知道这个是不是一个break change

**Comment by czy88840616** [comment]
应该是 bug。

**Comment by czy88840616** [comment]
已经修复，@midwayjs/upload 使用 3.6.2
