### ISSUE TITLE
请问可以把midway-example里面的demo-sequelize项目的sequelize升级到5.x版本吗

### ISSUE THREAD

**Issue by qgqceo** [midwayjs/midway#243]
如题所示。麻烦技术大大有空升级一下这个demo项目的sequelize版本。想看看在新版本下的技术实现。
感谢。

**Comment by czy88840616** [comment]
sequelize@5 有什么新特性么。。。没怎么关注。。

**Comment by qgqceo** [comment]
> sequelize@5 有什么新特性么。。。没怎么关注。。

我实现了这个需求。感谢。

**Comment by czy88840616** [comment]
能帮我们修改下 demo 么 ?
