### ISSUE TITLE
引入官方 axios 库导致 jest test 报错

### ISSUE THREAD

**Issue by TimonPeng** [midwayjs/midway#2438]
仅引入后就使得 jest raise

```
TypeError: Cannot read properties of undefined (reading 'getApplication')

> 12 |       app = await createApp<Framework>();
```

```typescript
// ...
import * as axios from '@midwayjs/axios';
// ...

@Configuration({
  imports: [
    // ...
    axios
    // ...
  ],
  // ...
})
```

**Comment by czy88840616** [comment]
@TimonPeng 目前看起来是 axios 新版本使用的 exports 的逻辑，在低版本 jest 下支持不是很好的样子，我这里把 jest 升级到了 29，直接用 jest 运行似乎没问题了。

**Comment by TimonPeng** [comment]
@czy88840616 我是最新的 29.2.1 问题还是存在。。

**Comment by czy88840616** [comment]
是的，直接用 jest，midway-bin 里内置的 jest 是26 版本，是有问题的。

**Comment by TimonPeng** [comment]
好的，我尝试了一下强制拉平（yarn 的 resolutions，pnpm 的 overrides）也不行。

看来没办法还是上游适配最好，patch 文件太麻烦了~ 先直接 `jest` 用吧~谢谢~！

```bash
must export a `process` or `processAsync` or `createTransformer` function.
```

**Comment by czy88840616** [comment]
如果搞不定，下个版本我就要把axios 固定回 0.x 了

**Comment by czy88840616** [comment]
新版本 cli 中已经移除了 jest 的固定版本依赖，现在已经可以自行升级 jest 到 v28 了，脚手架也会同步更新。
