### ISSUE TITLE
build failed because of type-check fail

### ISSUE THREAD

**Issue by WJayWJay** [midwayjs/midway#2462]
* **Node Version**:
* **Midway Version(Decorator/Core)**: 3.7
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

### when using typescript strict mode,  building project will fail! error is show below:

![image](https://user-images.githubusercontent.com/3736332/198979372-7f8fe2dd-9951-4fe5-aef5-6ecb2d6a7e94.png)

this is an accepted error or others ??

**Comment by czy88840616** [comment]
We will check it.

**Comment by czy88840616** [comment]
The midway package is built in non-strict mode, so if you use strict mode, you may get an error. Turning on skipLibCheck in tsconfig.json can solve this problem.

**Comment by WJayWJay** [comment]
why not adapt strict mode ? have any extra consideration？？ @czy88840616

**Comment by czy88840616** [comment]
We use the base typescript + mwts + eslint + Prettier to solve the problem of checking and formatting. We do not want to open the strict mode of ts to affect the efficiency of the entire encoding.
