### ISSUE TITLE
cache组件的ttl配置失效

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#2471]
我的本地依赖是

"@midwayjs/cache": "^2.14.6",
"@types/cache-manager": "^4.0.0",

是最近node-cache-manager升级了吗? 之前设置 {ttl : null} 是可以禁止过期的，现在即使设置为-1 或者 0 或者null 都是10秒默认值，
但是设置其他数值是有效的

![微信图片_20221103175803](https://user-images.githubusercontent.com/8968567/199692297-04c8852a-9a25-466b-ab28-cbd042defc63.png)

**Comment by czy88840616** [comment]
cache-manager版本是什么，nodw_modules里的

**Comment by Thetiso** [comment]
![image](https://user-images.githubusercontent.com/8968567/199872886-16800a1e-c33e-46b7-8970-754f96c98ede.png)
cache-manager是3.6.3版本

然后我还发现个奇怪的事情  本地居然有两个tpyes_cache_manager版本  一个是3.4.3  一个是4.0.2
前者是 midwayjs/cache引入的   后者是按照官网教程引入的   

![image](https://user-images.githubusercontent.com/8968567/199873117-a2aae379-9229-4186-99c8-d8f441fec524.png)

**Comment by Thetiso** [comment]
![image](https://user-images.githubusercontent.com/8968567/199873342-3355bb44-1e9f-4117-8813-470e2c715bac.png)

**Comment by czy88840616** [comment]
@types 只是定义，不影响使用。

**Comment by czy88840616** [comment]
试试不自己装 cache-manager 依赖？

**Comment by czy88840616** [comment]
看了下，cache-manager 3 是今年 5 月更新的，我怀疑是另外哪里更新了。

**Comment by echosoar** [comment]
根据 cache-manager@3.6.3 的源码:

https://github.com/node-cache-manager/node-cache-manager/blob/96a814fad67d3ff1c87c05ce04a06a50bec36cff/lib/stores/memory.js#L65-L67

最后塞入 lru cache 的过期时间，如果调用 `set` 方法的时候 `ttl` 传的是 `null`，那就会使用初始化 `cache manager` 的时候传入的 `maxAge` 参数，而 `maxAge` 参数来源于初始化的时候传入的 `ttl`：

https://github.com/node-cache-manager/node-cache-manager/blob/96a814fad67d3ff1c87c05ce04a06a50bec36cff/lib/stores/memory.js#L36

这个 ttl 来源于用户代码的 config 文件中间的 cache 配置与默认的 @midwayjs/cache 组件的配置 `合并后`的配置，默认值是 10。

如果要使得 set的时候 null 生效，那么需要将用户代码的配置中，将 cache 的 options.ttl 设置为 null，例如：
```ts
// src/config/config.default.ts
export const cache = {
    options: {
        ttl: null
    }
}
```

**Comment by Thetiso** [comment]
> 根据 cache-manager@3.6.3 的源码:
> 
> https://github.com/node-cache-manager/node-cache-manager/blob/96a814fad67d3ff1c87c05ce04a06a50bec36cff/lib/stores/memory.js#L65-L67
> 
> 最后塞入 lru cache 的过期时间，如果调用 `set` 方法的时候 `ttl` 传的是 `null`，那就会使用初始化 `cache manager` 的时候传入的 `maxAge` 参数，而 `maxAge` 参数来源于初始化的时候传入的 `ttl`：
> 
> https://github.com/node-cache-manager/node-cache-manager/blob/96a814fad67d3ff1c87c05ce04a06a50bec36cff/lib/stores/memory.js#L36
> 
> 这个 ttl 来源于用户代码的 config 文件中间的 cache 配置与默认的 @midwayjs/cache 组件的配置 `合并后`的配置，默认值是 10。
> 
> 如果要使得 set的时候 null 生效，那么需要将用户代码的配置中，将 cache 的 options.ttl 设置为 null，例如：
> 
> ```ts
> // src/config/config.default.ts
> export const cache = {
>     options: {
>         ttl: null
>     }
> }
> ```
现在遇到个更奇怪的问题   设置ttl的具体时间有问题  
设置了ttl = 7840  结果过了100秒再去get设个cache，发现之前的cache没了

```
2022-11-18 12:00:20,323 INFO 47 BGM: 重新构建bgm_plan => 虞兮叹 (DJ沈念版), 剩余歌曲数量 35, ttl => 7840
2022-11-18 12:03:45,347 INFO 47 BGM: 重新构建bgm_plan => Finzy Kontini - Cha Cha Cha, 剩余歌曲数量 35, ttl => 7733
```


```
    async getCurrentBgm() {
        let current_cache_bgm:any = await this.cache.get(CURRENT_BGM)
        if(!current_cache_bgm) {
            let planed_bgm_list:any = await this.cache.get(BGM_PLAN_CACHE_KEY)
            if(!planed_bgm_list || BGM_PLAN_CACHE_KEY.length == 0) {
                planed_bgm_list = await this._prepareBgmPlans()
                planed_bgm_list = this._randomAll(planed_bgm_list)
                current_cache_bgm = planed_bgm_list.splice(-1)[0]
                let ttl = planed_bgm_list.reduce((sum, bgm)=> {
                    let {duration} = bgm
                    sum += parseInt(duration)
                    return sum
                }, 0)
                await this.cache.set(BGM_PLAN_CACHE_KEY, planed_bgm_list, {ttl: ttl})
				this.logger.info(`BGM: 重新构建bgm_plan => ${current_cache_bgm.title}, 剩余歌曲数量 ${planed_bgm_list.length}, ttl => ${ttl}`)
            } else {
                current_cache_bgm = planed_bgm_list.splice(-1)[0]
				this.logger.info(`BGM: 从缓存的bgm_plan获取新的bgm => ${current_cache_bgm.title}, 剩余歌曲数量${planed_bgm_list.length}`)
            }
            let {duration = 10} = current_cache_bgm
            let st = new Date().getTime()
            current_cache_bgm = Object.assign(current_cache_bgm, {
                st: st,
                et: st + parseInt(duration) * 1000
            })
            await this.cache.set(CURRENT_BGM, current_cache_bgm, {ttl: parseInt(duration)})
            await this.eventService.addEvent({
                x_type: EventType.ChangeBgm,
                payload: current_cache_bgm
            })
        }
        return current_cache_bgm;
    }

```

@czy88840616

**Comment by Thetiso** [comment]
lru-cache是不是有个设定？  如果多少秒没去get, 他就会清空？

**Comment by Thetiso** [comment]
被迫写了一个定时器去轮询cache的各个key , 然后表现符合预期了    [ sad]

> lru-cache是不是有个设定？ 如果多少秒没去get, 他就会清空？

**Comment by Thetiso** [comment]
定时任务刷新cache跑了几个小时 还是出问题了，看来我还是老老实实走redis吧

**Comment by czy88840616** [comment]
LRU 清理还是有逻辑的，要么超出了 size 大小，要么时间到了。

**Comment by Thetiso** [comment]
> LRU 清理还是有逻辑的，要么超出了 size 大小，要么时间到了。

嗯 因为我本地服务其实会比较频繁的去设置cache 所以当我看到这个cache是lru的  也就大概知道为啥会失效了
