### ISSUE TITLE
任务队列 @midwayjs/bull 使 web中间件 失效了！

### ISSUE THREAD

**Issue by kushao** [midwayjs/midway#2494]
[错误复现请看这里](https://github.com/kushao/midway-bull-test)

```
Node: 16.15.1
@midwayjs/bootstrap	3.7.3(^3.0.0)
@midwayjs/bull	3.7.4(^3.7.4)
@midwayjs/core	3.7.0(^3.0.0)
@midwayjs/decorator	3.7.0(^3.0.0)
@midwayjs/info	3.7.3(^3.7.3)
@midwayjs/web	3.7.3(^3.0.0)
egg	2.37.0(^2.0.0)
```

全局中间件没使用bull组件时正常运行，将 bull 组件配置到代码中后，中间件失效。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/201055262-f3346bcb-3790-421c-97a9-e49305220f5c.png)

如果希望把中间件加到 egg 中，把 egg 放第一位。

**Comment by kushao** [comment]
好的，谢谢
