### ISSUE TITLE
v3 egg 能使用 schedule 吗？

### ISSUE THREAD

**Issue by MagicButterfly** [midwayjs/midway#2497]
有没有demo，我按照官网上的一直跑不起来

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/201293674-943eeef8-2571-42d4-bc72-b39ee74a87a8.png)

**Comment by MagicButterfly** [comment]
我试了这个，就是跑不起来，有没有 v3 定时任务的demo，我用的是egg的

**Comment by ZQun** [comment]
@MagicButterfly 试试这个方式，这个是v3版本egg的定时任务

**Comment by ZQun** [comment]
@MagicButterfly 试试这个方式，这个是v3版本egg的定时任务
``` typescript
import { Provide, Inject, Schedule, CommonSchedule } from '@midwayjs/decorator';
import { Context } from '@midwayjs/web';
import { AdminService } from '../modules/admin/Service.admin';

@Provide()
@Schedule({
    cron: '0 0 0 * * *',
    type: 'worker', // 指定某一个 worker 执行
})
export class ClearPriceCron implements CommonSchedule {

    @Inject()
    ctx: Context;

    @Inject()
    admin: AdminService

    // 定时执行的具体任务
    async exec() {
        await this.admin.clearPrice()
    }
}

```

**Comment by MagicButterfly** [comment]
我把这个也试了一下，还是不太行，是不是需要一些配置之类的东西？

**Comment by czy88840616** [comment]
https://github.com/czy88840616/midway-test-component/blob/master/src/schedule/report.ts

**Comment by shinima** [comment]
我这边遇到了这个问题，安装 midway-schedule  2.14.7  版本后可以正常跑了。

midway-schedule 的版本有点混乱，lastest 指向 1.x，而最大的版本号是 3.x ，结果生效的版本是 2.14.7...
