### ISSUE TITLE
reload worker 问题

### ISSUE THREAD

**Issue by ZQun** [midwayjs/midway#25]
lib目录/service/文件更改之后无法监听到文件变化
src/interface.ts 文件更改也不会监听到文件变化

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
应该是 egg-development 插件只监听了 app 目录，这个是可以配置的 https://github.com/eggjs/egg-development

ps：可以帮忙提个 mr，增加一下默认配置。
