### ISSUE TITLE
models下面的文件如何自动生成？

### ISSUE THREAD

**Issue by tan1444** [midwayjs/midway#250]
![QQ截图20190626140324](https://user-images.githubusercontent.com/16314475/60154946-753d4780-981b-11e9-9c38-76170cb83bd7.png)
models下面的数据实体文件要手动一个个新建不是很麻烦吗，没有自动生成的方法吗？

**Comment by czy88840616** [comment]
目前没有这个能力😢

**Comment by tan1444** [comment]
好吧，那就手动建了

**Comment by zhou-xin-undefined** [comment]
谁写个 node-mybatis

**Comment by czy88840616** [comment]
我们内部有个 fastrecord，比较像。。但是木有人有动力维护，就没放出来了。。

**Comment by waitingsong** [comment]
楼上这个是query builder？

**Comment by waitingsong** [comment]
@zhou-z-xin  `kmore` 这个 ？
