### ISSUE TITLE
midway创建 faas-v3 类型项目出错

### ISSUE THREAD

**Issue by ssmoon** [midwayjs/midway#2513]
OS: Windows 11
Node: 16.16
npm: 8.11.0

重现步骤：
 npm init midway
选择：faas-v3 - A serverless application boilerplate with midway v3(faas) 后出错
选择:   koa-v3 - A web application boilerplate with midway v3(koa) 可以成功创建项目

出错提示：

> Command failed: npm --registry=https://registry.npm.taobao.org/ i --no-save --legacy-peer-deps
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\projects\mp1\node_modules\@midwayjs\fcli-plugin-fc
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./postinstall
npm ERR! C:\projects\mp1\node_modules\@midwayjs\command-core\dist\npm.js:148
npm ERR!     if (!npm && !argv.skipAutoFindNpm) {
npm ERR!                                      ^
npm ERR!
npm ERR! TypeError: Cannot read properties of undefined (reading 'skipAutoFindNpm')
npm ERR!     at findNpm (C:\projects\mp1\node_modules\@midwayjs\command-core\dist\npm.js:148:23)
npm ERR!     at postInstallModule (C:\projects\mp1\node_modules\@midwayjs\command-core\dist\utils\postInstall.js:34:49)
npm ERR!     at async C:\projects\mp1\node_modules\@midwayjs\fcli-plugin-fc\postinstall.js:15:5

期望：可以正常创建项目

**Comment by echosoar** [comment]
bug fix: https://github.com/midwayjs/cli/pull/306

**Comment by echosoar** [comment]
cli 新版本已经发布，问题已修复
