### ISSUE TITLE
[Question] 如何把引用的js一起打包到dist

### ISSUE THREAD

**Issue by yiescc** [midwayjs/midway#2517]
* **Node Version**: 16
* **Midway Version(Decorator/Core)**:3
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

```
import './a.js';
```

- build之后，a.js并没有一起被打包到dist

**Comment by czy88840616** [comment]
ts 不认 js，如有需要，开启 tsconfig.json中的 allowJS
