### ISSUE TITLE
midway-upgrade  不可用

### ISSUE THREAD

**Issue by BonderTam** [midwayjs/midway#2519]
`npx: the --ignore-existing argument has been removed.
See `npm help exec` for more information
Need to install the following packages:
  midway-upgrade
Ok to proceed? (y) y
The current framework version (koa 3.4) does not support upgrading`

之前误升级，导致一堆不兼容，于是写死了版本
![image](https://user-images.githubusercontent.com/249648/203260356-9a177aee-96d8-48ec-b1da-1750ddeea797.png)
 这次因为需要用到view-ejs , 安装@midwayjs/view-ejs@3.4.7   仍然跑不了。 
 
 索性想升级到3.8， 就想到用midway-upgrade， 结果不支持啊。。。。

**Comment by czy88840616** [comment]
已经是新的了呀，upgrade 是给大版本用的。

**Comment by czy88840616** [comment]
既然你用了写死的版本，那么就得承担写死的代价，可以用 https://www.npmjs.com/package/npm-check-updates 等工具升级。

**Comment by BonderTam** [comment]
> 既然你用了写死的版本，那么就得承担写死的代价，可以用 https://www.npmjs.com/package/npm-check-updates 等工具升级。

感谢。 高效。
