### ISSUE TITLE
如何拿到logger？

### ISSUE THREAD

**Issue by xiongsongsong** [midwayjs/midway#252]
因为typeOrm库要自定义一个Logger，将日志转交给midway来记录，但怎么才能拿到logger对象呢？

![image](https://user-images.githubusercontent.com/342509/60354497-ebe66a80-99fe-11e9-8c1a-e0fc83d18b69.png)

**Comment by atzcl** [comment]
```
import { plugin, EggLogger } from 'midway';

class Test {
  @plugin('logger')
   logger: EggLogger;
   ....
}
```

**Comment by xiongsongsong** [comment]
@atzcl  似乎不行
![image](https://user-images.githubusercontent.com/342509/60405096-bb5e2680-9be0-11e9-83c1-e9aa15288be0.png)

**Comment by yviscool** [comment]
@xiongsongsong  MyCustomLogger 加一个 @provide 的啊

**Comment by atzcl** [comment]
@xiongsongsong 我做了个示例，你看一下
[https://github.com/atzcl/z/blob/457e746b71337f55868a433dea1ea9800b77969e/src/typeorm.ts#L34](https://github.com/atzcl/z/blob/457e746b71337f55868a433dea1ea9800b77969e/src/typeorm.ts#L34)
[https://github.com/atzcl/z/blob/master/src/lib/Other/TypeORMLogger.ts](https://github.com/atzcl/z/blob/master/src/lib/Other/TypeORMLogger.ts)

**Comment by xiongsongsong** [comment]
@yviscool @atzcl 多谢两位，可以了。

**Comment by atzcl** [comment]
@yviscool 单纯给 MyCustomLogger 加 @provide 也是没用的，估计他是按照 typeorm 的文档，直接 `new MyCustomLogger ` 来使用的，并不是用 inject 注入 MyCustomLogger

**Comment by xiongsongsong** [comment]
@atzcl 按照你给出的方法，可以了，我学习下。

**Comment by czy88840616** [comment]
💯
