### ISSUE TITLE
swagger中,get请求,如果是一个对象,无法展示出参数的详情

### ISSUE THREAD

**Issue by qq295823929** [midwayjs/midway#2521]
![image](https://user-images.githubusercontent.com/38320579/203483247-abf271a7-18c5-4c99-9f5c-4c20949b1622.png)
使用官网上面的列子,swagger的界面是这样的
![image](https://user-images.githubusercontent.com/38320579/203483376-989262fb-cfae-4041-9b84-3a64ecde9f38.png)
这样,如果有很多参数,就无法区分这些参数的属性,比如长度,是否毕传等等.

期望能query参数很多的时候,变成
![image](https://user-images.githubusercontent.com/38320579/203483539-d6375067-b853-4aee-b36f-44fb5b3e507d.png)
不知道是否能提供

**Comment by czy88840616** [comment]
对象可以通过加装饰器加 description 来描述的吧。
