### ISSUE TITLE
基于KOA组件的Http应用， 默认是一个进程吗？如果不是的话， 定时器如何控制是单个进程执行， 还是全部都执行？

### ISSUE THREAD

**Issue by huangapple** [midwayjs/midway#2522]
基于KOA组件的Http应用， 默认是一个进程吗？如果不是的话， 定时器如何控制是单个进程执行， 还是全部都执行？

应用场景就是  我有些任务是用来刷新缓存的， 这个缓存是在内存里的。需要每个进程都执行。
有些任务又是真正的任务， 只要执行一次的

**Comment by huangapple** [comment]
任务队列里描述的
http://www.midwayjs.org/docs/extensions/bull

分解可能会阻塞 Node.js 事件循环的单一任务。比如用户请求需要像音频转码这样的 CPU 密集型工作，就可以将此任务委托给其他进程，从而释放面向用户的进程以保持响应。

如果是单进程， 类似CPU这种密集型的， 该卡顿还是卡顿吗？

**Comment by czy88840616** [comment]
框架侧不关心进程模式，进程模型在外面（pm2)，对于框架的进程来说，就是一个单纯的监听 - 执行的过程，如果 cpu 密集型工作，卡顿也只是卡顿这一个进行，而其他的子进程依旧在处理。

**Comment by huangapple** [comment]
任务队列看得有点懵， 有个问题我没找到答案

我启动了两个点， 此时我有两种任务， 
类型1.  刷新进程内存缓存（每个点都需要）
类型2. 一些定时任务， 同时只要一个点执行就好。

这个用  bull 任务队列怎么实现？ 看描述他是 分布式任务管理器 ， 那应该只能处理  类型2的任务？
我这样理解对吗？

**Comment by czy88840616** [comment]
所谓分布式任务，就是任务派发，同时只有一台机器的一个进程在执行，如果你所有进程都要，那无非自己写个 cron 去执行下就好了。

**Comment by huangapple** [comment]
我之前用  @midwayjs/task， 本地任务， 就是类似自己写个cron去执行

然后刚上来看文档， 发现task不推荐了， 推荐用bull了， 然后我就发现， 好像不支持我说的这种场景

**Comment by huangapple** [comment]
那本地任务， 目前只能自己找个地方写个 cron 吗？框架目前是没有提供什么组件来实现（除了过气的@midwayjs/task）,对吧？

**Comment by czy88840616** [comment]
是的，task 会被 bull 替代，不过现在还能用，后面可能会有个单机的任务组件，看需求了。

**Comment by huangapple** [comment]
好的， 感谢指导。

**Comment by huangapple** [comment]
有没有考虑直接把 Task改成单机的本地任务啊， 刚好现在缺少

**Comment by czy88840616** [comment]
没那么快：）

**Comment by huangapple** [comment]
好的好的

**Comment by sy296565890** [comment]
> 没那么快：）

大佬  请教一下  自定义组件 调试是不是必须要 build才能正常引入啊

**Comment by czy88840616** [comment]
对，或者一起测的话参考 https://github.com/midwayjs/midway/tree/main/packages-resource/midway-test-inner-component/src

**Comment by sy296565890** [comment]
> 对，或者一起测的话参考 https://github.com/midwayjs/midway/tree/main/packages-resource/midway-test-inner-component/src

我去试试~先谢谢大佬~
