### ISSUE TITLE
链路追踪  有图表吗？

### ISSUE THREAD

**Issue by huangapple** [midwayjs/midway#2523]
文档里的 http://www.midwayjs.org/docs/extensions/otel

有图表可以看吗？

**Comment by czy88840616** [comment]
otel 只产生数据，可以自行对接图表。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/203583131-323c5fc1-7400-4bdb-8145-51b1a4642901.png)

**Comment by huangapple** [comment]
谢谢大佬
