### ISSUE TITLE
Midway 3 任务队列组件，清除任务历史数据配置无效

### ISSUE THREAD

**Issue by siegaii** [midwayjs/midway#2524]
![image](https://user-images.githubusercontent.com/40651327/203730771-992840af-7351-4785-95b9-e0bd80b515a5.png)  

我在尝试使用 midway3 任务队列方案的时候写了任务队列完成后清除历史任务的配置，代码如下：
```ts
import { Processor, IProcessor } from '@midwayjs/bull';
import { sleep } from '@midwayjs/core';

@Processor('pipelineStatistics', {
  removeOnComplete: 0,
  removeOnFail: 100,
})
export class PipelineStatisticsProcessor implements IProcessor {
  async execute(param: {
    repoId: string;
    appName: string;
    startTime: string;
    endTime: string;
  }) {
    console.log('param: ', param);
    await sleep(100);
  }
}
```

但是在运行 2 次后发现历史的任务数据的 key 在 redis 中并没有被清除。  
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/40651327/203731965-685576f0-534d-47d5-8dc2-152bdbd3b830.png">

请问这个配置是我理解的不对吗，难道不是这个意思

**Comment by siegaii** [comment]
调试了一下基本可以确认是：@Processor 装饰器有问题, 装饰器貌似没有实现相关配置的注入

这边直接对 bull job 进行配置是生效的

```ts
async statisticsPipeline(params: StatisticsPipelineDTO) {
    const apps = await this.findAppService.findDxApps();
    this.pipelineStatisticsQueue.addBulk(
      apps.map(app => ({
        data: {
          repoId: app.gitlab_repo_id,
          appName: app.name,
          ...params,
        },
        opts: {
          removeOnComplete: true,
        },
      }))
    );
  }
```

**Comment by siegaii** [comment]
![image](https://user-images.githubusercontent.com/40651327/203762764-4e356744-b25d-4614-b1ca-340dbb4c346d.png)
这个配置也无效

**Comment by czy88840616** [comment]
不是很确定，因为在 runJob 的地方是传递进去的。https://github.com/midwayjs/midway/blob/main/packages/bull/src/framework.ts#L85

**Comment by czy88840616** [comment]
我之前测试是会删除的，也可能测的不仔细 #2526

**Comment by siegaii** [comment]
> 我之前测试是会删除的，也可能测的不仔细 #2526

可能是 3.8.0 的这个版本有点问题，在退回 3.6.0 后这些配置都生效了

**Comment by czy88840616** [comment]
目前看起来，除了 3.6.1 中将 bull 的版本从 4.10.0 改成了 4.10.1，其他也只有改了类型导出以及定义的变化。

**Comment by czy88840616** [comment]
fixed in #2526
