### ISSUE TITLE
Midway3.8.0：typeorm 配置 entities 路径匹配不生效

### ISSUE THREAD

**Issue by siegaii** [midwayjs/midway#2531]
昨天将 midway 整体升级到了 3.8.0，发现 typeorm 配置 entities 路径匹配不生效。

实测一下在 3.6.0 与 3.7.3 有效，今天整体重新退回到 3.6.0 了
```ts
 typeorm: {
    dataSource: {
      default: {
        type: 'mysql',
        host: ConfigMap.mysql.host,
        port: ConfigMap.mysql.port,
        username: ConfigMap.mysql.username,
        password: ConfigMap.mysql.password,
        database: ConfigMap.mysql.database,
        synchronize: ConfigMap.mysql.synchronize,
        logging: false,
        entities: ['**/**/entity/*.entity.{j,t}s'],
      },
    },
  },
```

**Comment by siegaii** [comment]
使用实体类注册 entities 是有效的

**Comment by zybieku** [comment]
> entities: ['entity'],
不生效,这样配置 扫描规则是啥,  entity文件夹多个

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/203963134-4fecb5cb-3ef9-4226-a56b-a90f5b4f7a5a.png)

**Comment by zybieku** [comment]
如果只有一个目录，就写 entity就行了，如果有多个 entity，那就 **/entity




---原始邮件---
发件人: "Harry ***@***.***&gt;
发送时间: 2022年11月25日(周五) 晚上6:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [midwayjs/midway] Midway3.8.0：typeorm 配置 entities 路径匹配不生效 (Issue #2531)

**Comment by zybieku** [comment]
我把版本锁定成 3.8.0 ,又不生效了

**Comment by czy88840616** [comment]
没有改动更新哦。
