### ISSUE TITLE
如何修改日志输出目录（使用useContext，ctx.logger.warn(), ）

### ISSUE THREAD

**Issue by quixote1304629** [midwayjs/midway#2532]
![image](https://user-images.githubusercontent.com/32378929/203921752-78a2fe6c-0e01-4c2c-9685-325535634ace.png)
按照图里的方法配置后，不生效

**Comment by czy88840616** [comment]
1、一体化检查配置是否目录正确（apis/config/*)
2、检查启动环境变量（比如配在 local，执行却是 development）
3、配置是否在 config 中加载（比如如果对象形式，需要手动 import 文件）

**Comment by quixote1304629** [comment]
1 多谢

**Comment by quixote1304629** [comment]
> 1、一体化检查配置是否目录正确（apis/config/*) 2、检查启动环境变量（比如配在 local，执行却是 development） 3、配置是否在 config 中加载（比如如果对象形式，需要手动 import 文件）
多谢
