### ISSUE TITLE
--fast=swc 报错

### ISSUE THREAD

**Issue by shanelau** [midwayjs/midway#2536]
* **Node Version**: v18.12
* **Midway Version(Decorator/Core)**: 3.7.0
* **Component Name/Version**:
* **Platform**: mac
* **Mini Showcase Repository**:

NODE_ENV=local midway-bin dev --ts --fast=sw

如果存在相互引用的两个包，则项目无法启动

```
ReferenceError: Cannot access 'xxxService' before initialization
```

**Comment by czy88840616** [comment]
原则上不要相互引用，在语言层面上必出问题。

**Comment by Yuliang-Lee** [comment]
typeorm 里如果两个表有外键关系，这里必然出现互相引用。。要怎么处理？

**Comment by waitingsong** [comment]
两个表相互引用外键？

**Comment by Yuliang-Lee** [comment]
> 两个表相互引用外键？

只要有外键必然出现的。。typeorm 就这样

**Comment by Yuliang-Lee** [comment]
https://stackoverflow.com/a/71983552
https://typeorm.io/#relations-in-esm-projects

这个倒是有解决方案，service 互相引用了的话，目前看没办法解决

**Comment by waitingsong** [comment]
> > 两个表相互引用外键？
> 
> 只要有外键必然出现的。。typeorm 就这样

单就数据库设计，不应该出现两张表相互引用外键情况吧（外键通常引用的是主键，两张表主键相互引用……？）

**Comment by Yuliang-Lee** [comment]
> 

不是互相引用，typeorm 就是只要有外键，在两个 entity 里都会有申明，就会互相引用了

**Comment by Yuliang-Lee** [comment]
> > > 两个表相互引用外键？
> > 
> > 
> > 只要有外键必然出现的。。typeorm 就这样
> 
> 单就数据库设计，不应该出现两张表相互引用外键情况吧（外键通常引用的是主键，两张表主键相互引用……？）

不是互相外键，typeorm 就是只要有外键，在两个 entity 里都会有申明，就会互相引用了
