### ISSUE TITLE
k8s部署的worker数

### ISSUE THREAD

**Issue by Thetiso** [midwayjs/midway#2539]
@czy88840616    我这边使用azure-k8s来部署服务，当我在yaml上显示cpu = 2的时候，实际在pod上跑的worker数量默认等于了宿主机的cpu数量。
**是否可以通过类似设置dockerfile ENV的方式来限制worker的数量**？

...我知道可以通过scripts下追加 --workers=4来限制，不过这个指令在构建镜像之前，还得为不同的数量预先配置不同的scripts。感觉不是很合适。

**Comment by czy88840616** [comment]
你说的是 egg-scripts 启动的吧。我理解走 docker file 配置 env 的话，也可以写个 shell，把环境变量拼到命令上。

**Comment by Thetiso** [comment]
> 你说的是 egg-scripts 启动的吧。我理解走 docker file 配置 env 的话，也可以写个 shell，把环境变量拼到命令上。

OKOK  感谢
