### ISSUE TITLE
使用全局 typescript 导致的问题

### ISSUE THREAD

**Issue by waitingsong** [midwayjs/midway#254]
* **Node Version**:  v10.16
* **Egg Version**: 
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

 需求：
删除 `package.json` 中 devDependencies.typescript 条目，使用 `npm link typescript` 创建对全局 typescript 的链接。 从而减小每个项目开发阶段 `node_modules`  目录的体积 （typescript 占用 43M空间）

问题：
1.  通过 `midway-init` 创建一新项目
2. `npm i ` 安装依赖
3. 删除 pkg.devDependencies.typescript
4. 执行 `npm start` 以及 `npm run start_build` 均报错
  ```
  .......\midway-test\src\interface.ts:4
  export interface IUserOptions {
  ^^^^^^
  ```

**Comment by waitingsong** [comment]
1. `npm run start_build` 的问题通过在命令行后追加 `--ts` 参数问题解决
2. `npm start` 问题，通过更新 `cluster/utils.js` 文件额外检测项目根是否存在文件 `tsconfig.json` 来判断

**Comment by czy88840616** [comment]
我理解

- 1、start_build 这个命令是为了在本地能测试编译后的代码（dist），那肯定不能加 --ts
- 2、我们之前觉得，只有本地会执行 ts 源码，会加载 ts-node/register，所以只需要判断 ts 环境即可
- 3、我觉着如果 ts 装到全局，主要还是 npm run build 的时候找不到 tsc 或者 ts 环境报错

所以只要在 build 的时候能找到全局的 tsc，其他问题应该都好办。

**Comment by waitingsong** [comment]
我的意思是项目不用单独安装 ts 而是把全局安装的 ts 软连接到项目内，如此既不影响编译也能节省开发环境下的磁盘空间。
我现在的 egg 项目即采用这种方式，尚未发现不良影响。

**Comment by czy88840616** [comment]
软链应该可以的吧，，相当于就在本地中了，这个本地执行 npm run build 还会报错？

**Comment by waitingsong** [comment]
执行 run build 会报错的 因为传入了 freamwork 参数调用了 midway 的脚本。

**Comment by waitingsong** [comment]
@czy88840616 确认如果先 npm i 然后删除依赖中的 typescript ，则 执行 `npm start` 以及 `npm run start_build` 报错.

**Comment by czy88840616** [comment]
今天有点晚。。我明天跑个demo看看。

**Comment by waitingsong** [comment]
我测试没发现问题。 可能的问题是普通js 项目，依赖中无 typescript 但根目录存在 tsconfig.json， 此时可能不正常。
不过 9102年了，项目该全 ts 化了。

**Comment by waitingsong** [comment]
midway 已默认 ts 。
