### ISSUE TITLE
生产环境， 如何开始 sourcemap ， 让报错报对行？

### ISSUE THREAD

**Issue by huangapple** [midwayjs/midway#2548]
目前上生产是类似这样的
```

FROM registry.cn-hangzhou.aliyuncs.com/kerzhi-libs/node:16  AS build
# RUN npm install -g npm@8.19.2
WORKDIR /app

COPY . .

RUN npm install  --registry=https://registry.npm.taobao.org

RUN npm run build

FROM registry.cn-hangzhou.aliyuncs.com/kerzhi-libs/node:16-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/bootstrap.js ./
COPY --from=build /app/package.json ./
COPY --from=build /app/files ./files


# RUN apk add --no-cache tzdata

ENV TZ="Asia/Shanghai"

RUN npm install --omit=dev  --registry=https://registry.npm.taobao.org

# 如果端口更换，这边可以更新一下
EXPOSE 8080

CMD ["npm", "run", "start"]

```

走的是 npm run build, npm run start
没有了 sourcemap, 报错都对不上了。

想要sourcemap， 正确的方式是什么？ 总不能是npm run dev吧

**Comment by waitingsong** [comment]
sourcemap 是编译的时候生成的。你看看容器镜像里面有没有

**Comment by waitingsong** [comment]
还可以试试在容器中添加变量
```
ENV NODE_OPTIONS="--enable-source-maps"
```

**Comment by huangapple** [comment]
我改成这样， 两处都加了 
```
ENV NODE_OPTIONS="--enable-source-maps"
```

```
FROM registry.cn-hangzhou.aliyuncs.com/kerzhi-libs/node:16  AS build
# RUN npm install -g npm@8.19.2
WORKDIR /app

COPY . .
ENV NODE_OPTIONS="--enable-source-maps"
RUN npm install  --registry=https://registry.npm.taobao.org

RUN npm run build

FROM registry.cn-hangzhou.aliyuncs.com/kerzhi-libs/node:16-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/bootstrap.js ./
COPY --from=build /app/package.json ./
COPY --from=build /app/files ./files


# RUN apk add --no-cache tzdata

ENV TZ="Asia/Shanghai"
ENV NODE_OPTIONS="--enable-source-maps"
RUN npm install --omit=dev  --registry=https://registry.npm.taobao.org

# 如果端口更换，这边可以更新一下
EXPOSE 8080

CMD ["npm", "run", "start"]

```

还是没有， 容器镜像里的是这样的， 
![image](https://user-images.githubusercontent.com/10572028/205443863-a1298d7d-fadf-42f0-b1a7-75971a0988a6.png)

 有.d.ts， 没有 map文件

**Comment by czy88840616** [comment]
tsconfig.json 增加 sourceMap 或者 inlineSource 配置。

**Comment by huangapple** [comment]
原本就已经有了
```
 "inlineSourceMap": true,
```
但还是不行

**Comment by waitingsong** [comment]
> 原本就已经有了
> 
> ```
>  "inlineSourceMap": true,
> ```
> 
> 但还是不行

看看容器 dist 里面有没有 sourcemap 信息（文件或者 inline）

**Comment by huangapple** [comment]
只有d.ts跟.js






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 中午11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [midwayjs/midway] 生产环境， 如何开始 sourcemap ， 让报错报对行？ (Issue #2548)





  
原本就已经有了
  "inlineSourceMap": true,  
但还是不行
  
看看容器 dist 里面有没有 sourcemap 信息（文件或者 inline）

**Comment by huangapple** [comment]
![image](https://user-images.githubusercontent.com/10572028/205540817-100ae3e0-3efa-4844-94ca-8ff69dd996a7.png)

**Comment by waitingsong** [comment]
那多半在编译的时候没有生成 sourcemap 信息。看看 tsconfig.json 配置

**Comment by huangapple** [comment]
文件内容末尾有附加的sorceMap信息
![image](https://user-images.githubusercontent.com/10572028/205577470-0eb31729-98c7-405f-9b61-3044f95395de.png)

解出来是长这样的
![image](https://user-images.githubusercontent.com/10572028/205577600-a4d0f97d-cda7-4d3d-bd28-c18e61ed76bb.png)

 那就是我在打包时， 要把src也给打过去， 对吗？

**Comment by huangapple** [comment]
我还以为生成的.sourceMap也会在dist里面呢

**Comment by waitingsong** [comment]
> 我还以为生成的.sourceMap也会在dist里面呢

不是这个意思。红框里面是源码路径用于解析出实际文件的行列。 你把 tsconfig.json 里面改成 sourceMap: true, inlineSourceMap: false
也会是同样的结果。
因为你是基于 ts 生成的 sourcemap。

**Comment by huangapple** [comment]
可以了， 感谢！
