### ISSUE TITLE
Casbin basic_model.conf 相关问题，以及 isOwn 用处

### ISSUE THREAD

**Issue by Mikasa33** [midwayjs/midway#2550]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/29498153/205481462-98b6bbdd-49af-4dbc-b232-39720e136958.png">

请问这里是不是应该是 g2 呢，还是说我自己理解的有问题？ 😂
```
g2, users_list, user
g2, user_roles, user
g2, user_permissions, user
g2, roles_list, role
g2, role_permissions, role
```

顺便想问一下 `isOwn` 参数一般在什么情况下使用呢？能否举个例子。。
自己去看 `@midwayjs/casbin` 插件的源码，发现 `possession` 为 `AuthPossession.OWN` 或 `AuthPossession.OWN_ANY` 情况下，必须设置 `isOwn: () => true` 才可以通过
```
@UsePermission({
    action: AuthActionVerb.READ,
    resource: Resource.USER_ROLES,
    possession: AuthPossession.OWN
    isOwn: (ctx) => true,
  })
```

**Comment by czy88840616** [comment]
我不确定这个写法，因为我也是从 casbin的示例中拿过来的 https://casbin.org/zh/docs/supported-models

**Comment by Mikasa33** [comment]
好的谢谢！我再研究研究
