### ISSUE TITLE
@midwayjs/sequelize 用了这个插件之后，怎么使用transaction 

### ISSUE THREAD

**Issue by magdsnail** [midwayjs/midway#2554]
@midwayjs/sequelize 用了这个插件之后，怎么使用transaction

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/extensions/sequelize#%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E6%BA%90

https://sequelize.org/docs/v6/other-topics/transactions/

**Comment by magdsnail** [comment]
> https://midwayjs.org/docs/extensions/sequelize#%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E6%BA%90
> 
> https://sequelize.org/docs/v6/other-topics/transactions/
棒极了 谢谢
