### ISSUE TITLE
拦截器 aop 能否实现在 controller 层直接装饰器形式注入

### ISSUE THREAD

**Issue by magdsnail** [midwayjs/midway#2558]
拦截器aop 能否实现在collection层直接装饰器形式注入

**Comment by czy88840616** [comment]
什么 collection。

**Comment by magdsnail** [comment]
> 

不好意思 写错了  是 controller（控制器）层

**Comment by magdsnail** [comment]
@czy88840616 不好意思 写错了 是 controller（控制器）层

**Comment by waitingsong** [comment]
通过 aop 可以实现在 controller 层进行装饰器注入的呀

**Comment by magdsnail** [comment]
> 通过 aop 可以实现在 controller 层进行装饰器注入的呀

@waitingsong 不可以  我意思是定义一个拦截器   在controller里面用，而现在的用法是需要在拦截器头部 具体指明哪些 controller，或者哪些controller中的某些方法，  那么我想弄一个全局的拦截器就实现不了了，最好的方式是放到controller里面，可以在指定的controller 里面使用   还可以在指定的方法里面使用  也可以全局配置  这样是最好的

**Comment by czy88840616** [comment]
拦截器和中间件不一样，拦截器是基于类的结构去拦截，所以必须要有类本身，而中间件是请求通配，实现是不一样的。

**Comment by magdsnail** [comment]
> 
好的 明白了

**Comment by waitingsong** [comment]
> > 通过 aop 可以实现在 controller 层进行装饰器注入的呀
> 
> @waitingsong 不可以 我意思是定义一个拦截器 在controller里面用，而现在的用法是需要在拦截器头部 具体指明哪些 controller，或者哪些controller中的某些方法， 那么我想弄一个全局的拦截器就实现不了了，最好的方式是放到controller里面，可以在指定的controller 里面使用 还可以在指定的方法里面使用 也可以全局配置 这样是最好的

可以自定义装饰器，支持类装饰和类方法装饰
