### ISSUE TITLE
pm2 运行项目启动不了

### ISSUE THREAD

**Issue by magdsnail** [midwayjs/midway#2561]
![image](https://user-images.githubusercontent.com/26218033/206153043-b825917b-0ee3-4500-82a5-d4e10c835680.png)

![image](https://user-images.githubusercontent.com/26218033/206153156-9ea6fa7a-998c-409a-bc2f-d9f0079298ee.png)

![image](https://user-images.githubusercontent.com/26218033/206153266-01aa87fc-d98f-4d6f-accb-778168d4728e.png)

**Comment by czy88840616** [comment]
1、检查是否 npm run build
2、检查端口配置正确性
3、检查日志中的报错信息
