### ISSUE TITLE
一直停留在 collecting boilerplate config...

### ISSUE THREAD

**Issue by chu-han** [midwayjs/midway#257]
* **Node Version**: v 10.16.0
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

# 安装脚手架工具
npm install -g midway-init
# 新建应用
midway-init
提示：? Please select a boilerplate type (Use arrow keys)
# 选择任意模板
出现以下提示：
? Please select a boilerplate type midway-ts - Simple midway application boilerplate by ts
[midway-init] use boilerplate: midway standard typescript template(midway-ts-boilerplate)
[midway-init] collecting boilerplate config...
并一直停留在这个提示界面。

**Comment by ZQun** [comment]
是windows系统 ？   可以用git bash

**Comment by chu-han** [comment]
> 是windows系统 ？   可以用git bash

终端从power shell换到 git bash  是可以的。

**Comment by chu-han** [comment]
> 是windows系统 ？   可以用git bash
 但是git bash 只能使用默认第一个模板，无法选择模板了。这个cli 是不支持powershell 和cmder 终端吗

**Comment by czy88840616** [comment]
头疼，难不成让我重写一个脚手架工具-。-

现在 egg-init 有个 type 参数，可以直接选择某个模板，midway-init 也一样。type 参考 [这里](https://github.com/midwayjs/midway/blob/master/packages/midway-init/boilerplate/boilerplate.json)

```
midway-init [dir] --type=simple
```

**Comment by waitingsong** [comment]
用传参数指定模板名最简单。
我觉得没必要兼容 powershell，有 git-bash 就够了。

**Comment by chu-han** [comment]
> 头疼，难不成让我重写一个脚手架工具-。-
> 现在 egg-init 有个 type 参数，可以直接选择某个模板，midway-init 也一样。type 参考 这里
> midway-init [dir] --type=si
