### ISSUE TITLE
http2 server 服务无响应

### ISSUE THREAD

**Issue by godPaimon** [midwayjs/midway#2578]
浏览器访问127.0.0.1:7001 ： ERR_INVALID_HTTP_RESPONSE

* **Node Version**: v16.14.2
* **Midway Version(Decorator/Core)**: ^3.0.0
* **Component Name/Version**:
* **Platform**: mac os
* **Mini Showcase Repository**: https://github.com/godPaimon/midway-test

**Comment by czy88840616** [comment]
http2 要开 https

**Comment by godPaimon** [comment]
OK
