### ISSUE TITLE
问题：midway一体化 vue模板 打包之后  生产服务器启动 报错 ERROR 23498 ReferenceError: document is not defined

### ISSUE THREAD

**Issue by JiaoZheng** [midwayjs/midway#2579]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/24946849/207007941-452c37d4-d132-45c4-9da6-34067e9bdb23.png">

**Comment by czy88840616** [comment]
参考：https://midwayjs.org/docs/container#%E8%87%AA%E5%8A%A8%E7%BB%91%E5%AE%9A 忽略前端代码。
