### ISSUE TITLE
建议我们用midway框架开发websocket么

### ISSUE THREAD

**Issue by 15998194741** [midwayjs/midway#2593]
最近一直在了解midway框架，也是刚好业务上遇见了一个要使用serverless的需求，感觉大家都在说midway的强大于是便过来想要尝试着使用，但是当我准备开发websocket的时候，发现这方面的文档少之又少。

**Comment by czy88840616** [comment]
serverles的socket是由对应平台提供，传统应用请参考 websocket组件。
