### ISSUE TITLE
如何为 test 指定 tsconfig.json

### ISSUE THREAD

**Issue by waitingsong** [midwayjs/midway#260]
请问在执行 `npm run test` 时如何指定 `tsconfig.json` 路径，比如 `test/tsconfig.json` 。
这样就可以在测试用的配置中放宽一些检查，比如 `compilerOptions.noUnusedLocals`  设置为 `false`，不然写用例的时候很不方便。

**Comment by czy88840616** [comment]
好像之前有个 mr 做了这个事情。

https://github.com/midwayjs/midway/pull/191

**Comment by waitingsong** [comment]
谢谢。
只翻了 issues 没发现，原来是 mr 。
