### ISSUE TITLE
能不能提供类似 @nestjs/swagger 的惰性函数写法，来支持循环依赖

### ISSUE THREAD

**Issue by Ttou** [midwayjs/midway#2601]
* **Node Version**: 16.13.1
* **Midway Version(Decorator/Core)**: 3.9.7
* **Component Name/Version**: @midwayjs/swagger@3.9.3
* **Platform**: macOS
* **Mini Showcase Repository**: [文档说明](https://docs.nestjs.cn/9/recipes?id=%e5%be%aa%e7%8e%af%e4%be%9d%e8%b5%96)

**Comment by czy88840616** [comment]
能。
