### ISSUE TITLE
循环依赖惰性写法无效

### ISSUE THREAD

**Issue by Ttou** [midwayjs/midway#2603]
* **Node Version**: 16.13.1
* **Midway Version(Decorator/Core)**: 3.9.0
* **Component Name/Version**: @midwayjs/swagger@3.9.8
* **Platform**: macOS
* **Mini Showcase Repository**: [示例项目](https://github.com/Ttou/midway-swagger-demo)

使用惰性写法后，swagger-ui 里解析出来的是 string 数组

```typescript
import { ApiProperty, getSchemaPath } from '@midwayjs/swagger';

export class UserVO {
  @ApiProperty()
  userId: number;

  @ApiProperty({
    type: 'array',
    items: { $ref: () => getSchemaPath(RoleVO) },
  })
  roles: RoleVO[];
}

export class RoleVO {
  @ApiProperty()
  roleId: number;

  @ApiProperty({
    type: 'array',
    items: { $ref: () => getSchemaPath(UserVO) },
  })
  users: UserVO[];
}
```

![image](https://user-images.githubusercontent.com/4298437/209752641-923cb599-c4e5-4b78-a10e-4f4e5e6379c0.png)

**Comment by czy88840616** [comment]
额，response 忘了改。

**Comment by czy88840616** [comment]
仔细读了了一下，这种循环引用本身 swagger 已经没法支持展示了（无限引用），生成的 json 已经是完整的， 所以这不是问题。
