### ISSUE TITLE
Bootstrap 可以启动多个么

### ISSUE THREAD

**Issue by Topthinking** [midwayjs/midway#2605]
我想在同一个进程里，运行两个不同端口的应用，一个端口是http服务，一个端口是https服务，不知是否可行

**Comment by Topthinking** [comment]
纯nodejs是可以做到的，使用tcp模型代理即可

**Comment by czy88840616** [comment]
同一个应用？

**Comment by Topthinking** [comment]
是的，同一份代码

**Comment by czy88840616** [comment]
想了一下，当前 http 服务是在一个固定的实例中，而实例在一个容器下只会有一个，同时由于装饰器本身在一个进程里只会加载一次，这几个原因弄上来，在一个进程中跑多次相同代码，应该是不可以的。
