### ISSUE TITLE
注入配置的取值检查

### ISSUE THREAD

**Issue by waitingsong** [midwayjs/midway#262]
注入配置功能当不存在输入参数对应键名的时候不抛异常？

```ts
export default (appInfo: EggAppInfo) => {
  const config = <DefaultConfig> {}

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1559532739675'

  config.welcomeMsg = 'Hello midwayjs!'  // <--------- 这儿

  return config
}

```
```ts
export class HomeController {
  @config('welcomeMsg123')  // 注入了不存在的键名
  hello: string

  @get('/')
  index(ctx: Context) {
    ctx.body = this.hello
  }
}
```

 build, dev, start 都通过。但是项目启动之后访问网站失败（浏览器无任何反应，服务端也无任何异常日子）。 导致如果开发的时候在某处注入了不存在的值（或者之前可行，但某时删除了config中的键名），若无版本控制则排查问题就极其困难了。

**Comment by czy88840616** [comment]
这个当初有过争议，现在的实现是因为 config 本身是对象，所以 config 取不存在的值就是 undefined。一方面 egg 的 app.config 本身是可以修改的，如果在后面动态添加键值，在前期报错的话就变成不给机会了，所以讨论到最后默认还是使用 js 本身的逻辑，返回 undefined。

**Comment by waitingsong** [comment]
我的问题不是 undefined 的问题，而是页面就不可访问了（浏览器一直卡住）。
