### ISSUE TITLE
可以用一体化的方式 使用 @midwayjs/bull 吗？

### ISSUE THREAD

**Issue by quixote1304629** [midwayjs/midway#2623]
我在官方文档中没有看见一体化的用法

**Comment by czy88840616** [comment]
hooks 支持 midway 的组件之一，class 和函数式是可以混用的，如果一体化没有写，那就说明就是用 class 写法。

**Comment by quixote1304629** [comment]
> hooks 支持 midway 的组件之一，class 和函数式是可以混用的，如果一体化没有写，那就说明就是用 class 写法。

@czy88840616 

因为我的项目是使用一体化的方式，如果@midwayjs/bull只能用class的写法的话，那我是不是只能放弃使用@midwayjs/bull，直接使用bull这个库就好了

我有了解到@midwayjs/bull 是在 bull这个库做的一层封装）

**Comment by czy88840616** [comment]
可以，没有限制。
