### ISSUE TITLE
socketio 组件怎么在握手阶段拒绝连接？

### ISSUE THREAD

**Issue by zuozuomuxi** [midwayjs/midway#2627]
* **Node Version**: v18.12.1
* **Midway Version(Decorator/Core)**:  @midwayjs/core@3.9.0
* **Component Name/Version**:  @midwayjs/socketio@3.9.0
* **Platform**: macOS
* **Mini Showcase Repository**:

我使用 `@midwayjs/socketio` 实现了一些逻辑，我想在握手阶段做身份验证，如果验证不通过，就拒绝连接，下面是我的代码：
```typescript
// src/middleware/socket.middleware.ts
import { Middleware, } from '@midwayjs/decorator';
import { httpError } from '@midwayjs/core';
import { Context, NextFunction } from '@midwayjs/socketio';

@Middleware()
export class SocketMiddleware {
  resolve() {
    return async (ctx: Context, next: NextFunction) => {

      if (!isValid(ctx.handshake.headers.token)) {
        // 不起作用，仍然建立了连接
        throw new httpError.UnauthorizedError();
      }
    
      return next();
    }
  }
}

// src/configuration.ts
async onReady() {
  this.socketApp.useConnectionMiddleware(SocketMiddleware);
}
```
但是这段代码并不起作用，客户端仍然会监听到 connect 事件，即使我在中间件里调用 `ctx.disconnect()`，客户端也是先监听到 `connect`，然后监听到 `disconnect`。

如果使用 socket.io 本身的中间件写法，就没有问题，可以给 next 传 error 参数来抛出异常中止连接，客户端也不会监听到 connect 事件，但是这样我没办法在中间件实现里获取我要的各种 service。代码如下：
```typescript
// src/configuration.ts
async onReady() {
  this.socketApp.use((socket, next) => {
    const err = new Error("not authorized");
    next(err);
  });
}
```
有没有什么方法在 midway 的中间件里实现抛出异常，中止掉 ws 连接？

**Comment by czy88840616** [comment]
这个一般是在哪个阶段做的？

**Comment by zuozuomuxi** [comment]
> 这个一般是在哪个阶段做的？

我觉得应该就是在握手阶段做。从另一个角度考虑，midway的中间件至少要覆盖 socketio 中间件本身就有的功能吧。可以看看 [socket.io](https://socket.io/zh-CN/docs/v4/middlewares/#handling-middleware-error) 的文档，用 midway 的中间件写法是没法触发 connect_error 这个事件的

**Comment by zuozuomuxi** [comment]
@czy88840616 我看了下 `@midwayjs/socketio` 的代码，midway 中间件的代码都是在 connect 后才执行的

**Comment by czy88840616** [comment]
可以继续沿用 socket.io的中间件，midway 的中间件和 socket.io自己的中间件不冲突的。
