### ISSUE TITLE
使用midway-init 在途中卡住。

### ISSUE THREAD

**Issue by xixixida** [midwayjs/midway#263]
node v12.3.1
midway-init v1.6.2
windows 10
运行到这一步再也不动了。

PS C:\code\midwayjs\hteweb> midway-init
[midway-init] use registry: https://registry.npmjs.org
[midway-init] target dir is C:\code\midwayjs\hteweb
? Please select a boilerplate type midway-ts - Simple midway application boilerplate by ts
[midway-init] use boilerplate: midway standard typescript template(midway-ts-boilerplate)
[midway-init] collecting boilerplate config...

使用 Ctrl-c 停止不了

**Comment by czy88840616** [comment]
windows么。。用 gitbash 试试。

**Comment by yangdan8** [comment]
现在都还用不了?这进度醉了

**Comment by waitingsong** [comment]
git bash 啊。

**Comment by yangdan8** [comment]
gitbash选不了模板类别

**Comment by waitingsong** [comment]
@yangdan8  
看文档，我添加了示例的 
https://midwayjs.org/midway/guide.html#%E5%88%9B%E5%BB%BA%E6%96%B0%E5%BA%94%E7%94%A8

**Comment by yangdan8** [comment]
加--type,而不是正视这个问题,哎

**Comment by czy88840616** [comment]
已经在修改中，这个进展比较慢，一是因为脚手架每个现在都要增加测试，而是最近大促的确也没什么时间。。我们尽快上线。

**Comment by waitingsong** [comment]
@yangdan8 
我个人是 win7 系统，基本所有需要命令行的操作都是 git-bash 执行的。 cmd 也就用来 ping 下（git-bash 下ping输出乱码）。

**Comment by czy88840616** [comment]
@xixixida @yangdan8 已经改造完了，刚发布了 1.14.0，有一些内部依赖的原因暂时无法直接切到正式版，可以通过 `npm install midway-init@beta -g` 来使用，如果有其他问题可以反馈给我。

**Comment by czy88840616** [comment]
已经切到正式版，支持 windows，如有问题，可以继续提。

**Comment by yangdan8** [comment]
> @yangdan8
> 我个人是 win7 系统，基本所有需要命令行的操作都是 git-bash 执行的。 cmd 也就用来 ping 下（git-bash 下ping输出乱码）。
> 另外，我是TC重度依赖，把 `ctrl+g` 快捷绑定启动 git-bash 上面。要执行命令行可以快速调出来，然后 `ctrl+d` 就退出，非常的方便。

习惯了powershell
