### ISSUE TITLE
tsconfig.json配置中paths编译问题，@midwayjs/cli@2.0.10

### ISSUE THREAD

**Issue by ztl19930409** [midwayjs/midway#2645]
* **Node Version**:16.16.0
* **Midway Version(Decorator/Core)**:3.9.0
* **Component Name/Version**:@midwayjs/cli@2.0.10
* **Platform**:MacOs 13.0.1
* **Mini Showcase Repository**:
使用```npm init midway```初始化项目，```@midwayjs/cli```默认版本为2.0.10。在这个版本下，tsconfig中配置paths，编译不会将别名路径编译成相对路径。
这是在```@midwayjs/cli```2.0.10下编译的结果片段：
![image](https://user-images.githubusercontent.com/17899695/211496397-2c19aa6f-1a2d-4525-938e-5516abb2b8e8.png)

tsconfig.json配置如下：
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "inlineSourceMap": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "stripInternal": true,
    "skipLibCheck": true,
    "pretty": true,
    "declaration": false,
    "forceConsistentCasingInFileNames": true,
    "typeRoots": [
      "./src/typings",
      "./node_modules/@types"
    ],
    "outDir": "dist",
    "paths": {
      "@/*": [
        "src/*"
      ],
      "@api/*": [
        "src/api/*"
      ],
      "@service/*": [
        "src/service/*"
      ],
    }
  },
  "exclude": [
    "dist",
    "node_modules",
    "test"
  ]
}
```
在```@midwayjs/cli```1.3.21下编译会将别名路径转换为相对路径。
这是在1.3.21版本下编译的文件：
![image](https://user-images.githubusercontent.com/17899695/211495977-1f10093c-4f55-4146-808d-eec8fa2f41f5.png)

**Comment by waitingsong** [comment]
在开发依赖中增加依赖 tsc-alias，然后
在编译后执行： `tsc-alias`

example:
```
  "scripts": {
    "build": "midway-bin build && tsc-alias",
}
```

**Comment by ztl19930409** [comment]
>
