### ISSUE TITLE
使用@midwayjs/validate参数验证，无法捕获参数异常

### ISSUE THREAD

**Issue by cliek** [midwayjs/midway#2655]
* **Node Version**: 14.17
* **Midway Version(Decorator/Core)**: 
* **@midwayjs/bootstrap": "^3.0.0",
    "@midwayjs/core": "^3.0.0",
    "@midwayjs/decorator": "^3.0.0",
    "@midwayjs/info": "^3.0.0"
    "@midwayjs/jwt": "3"
    "@midwayjs/koa": "^3.0.0"
    "@midwayjs/logger": "^2.14.0"
    "@midwayjs/typeorm": "3"
    "@midwayjs/validate": "3"
* **Platform**: mac os 12.xx

我按照官网文档【组件】安装了 `@midwayjs/validate` 组件。
项目中使用了过滤器捕获异常：
```
// validate.filter.ts
import { Catch } from '@midwayjs/decorator';
import { MidwayValidationError } from '@midwayjs/validate';
import { Context } from '@midwayjs/koa';

@Catch(MidwayValidationError)
export class ValidateErrorFilter {
	async catch(err: MidwayValidationError, ctx: Context) {
		return {
			status: err.status,
			message: '校验参数错误,' + err.message
		}
	}
}
```
同时配置了`default.filter.ts` 和 `notfound.filter.ts`
在`configuration.ts`文件中：
```
// other code
// 过滤器
import { DefaultErrorFilter } from './filter/default.filter';
import { NotFoundFilter } from './filter/notfound.filter';
import { ValidateErrorFilter } from './filter/validate.filter';



@Configuration({
	imports: [
		koa,
		validate,
		jwt,
		orm,
		{
			component: info,
			enabledEnvironment: ['local'],
		},
	],
	importConfigs: [join(__dirname, './config')],
})
export class ContainerLifeCycle {
	@App()
	app: koa.Application;

	async onReady() {
		// add middleware
		// add filter
		// 这里我加入了过滤器
		this.app.useFilter([ ValidateErrorFilter, NotFoundFilter, DefaultErrorFilter ]);
	}
}

```
在`common.controller.ts`使用验证

```
/// xxx
import { Validate } from '@midwayjs/validate';
import { LoginDTO, userInfoDTO, registerDTO } from '../types/common.controller';

@Provide()
@Controller('/api')
export class CommonController {
        @Post('/register')
	@Validate()
        async register(@Body('userInfo') userInfo: registerDTO ): Promise<{}> {
           return this.userService.createUser(userInfo);
        }
}
```
当前请求`/api/register`时，body中不携带参数，异常不会被`ValidateErrorFilter`捕获，但是可以被`DefaultErrorFilter`捕获，但是得到的Error信息是
![image](https://user-images.githubusercontent.com/29326163/212472144-cd5a80d9-2b36-484a-9522-1fac62928605.png)
我查询过多次文档，写法上没有问题，改配置的地方也看了，百度关于这类问题也是很少。

**Comment by czy88840616** [comment]
你这是 TypeError，不是校验的错误。

**Comment by cliek** [comment]
我看了下，好像还没进方法就报错了；
![image](https://user-images.githubusercontent.com/29326163/212476969-ef2e63e3-2d18-427b-bdce-d342165413e7.png)
好像将接受类型改为`any`就不会报错，但是用了`DTO`就会报如上异常，不管参数是否传对；
我配置的`dot`如下：
![image](https://user-images.githubusercontent.com/29326163/212477008-823745fa-36eb-45f2-b0ec-4002b56d63db.png)

**Comment by cliek** [comment]
我知道问题了，开始定义类型加了`declare`后来改成class加验证没有删掉就导致typeError的错误了
