### ISSUE TITLE
运行 hooks build时候， 为什么程序会执行一遍

### ISSUE THREAD

**Issue by quixote1304629** [midwayjs/midway#2658]
最近在build时候发现了链接redis错误，当时很奇怪，为什么build代码会链接redis。 后面发现build时候程序执行了。
可以请教一下执行程序的目的是什么么，有没有相关的文档看看谢谢谢谢🙏～～

**Comment by quixote1304629** [comment]
另外，在 midwayjs/hooks 中 @midwayjs/hcc 的作用是什么呢，readme没有写

**Comment by czy88840616** [comment]
执行的目的是为了生成路由给前端吧。
