### ISSUE TITLE
Can not get context in the service injected in middleware? 

### ISSUE THREAD

**Issue by Chersquwn** [midwayjs/midway#266]
I find the issue can not get context in service when injecting service into middleware, but i can not find any description in the docs. Is it a bug?

```ts
@provide()
export class ApiMiddleware implements WebMiddleware {
  @inject("baseService")
  baseService: BaseService

  resolve() {
    return async (ctx: Context, next: () => Promise<any>) => {
       console.log(this.baseService)      // { ... ctx: undefined }
    }
  }
}
```

**Comment by czy88840616** [comment]
same issue: #207

**Comment by waitingsong** [comment]
我这儿 ctx 和注入的 userService 都是正常的。 这是什么原因呢？

**Comment by waitingsong** [comment]
service 注册有三种作用域，假如是单例模式，那么
```ts
@provide()
export class ApiMiddleware implements WebMiddleware {
  @inject("baseService")
  baseService: BaseService

  resolve() {
    return async (ctx: Context, next: () => Promise<any>) => {
       console.log(this.baseService)      // { ... ctx: undefined }
    }
  }
}
```
此时  baseService 中的 ctx 应该是啥作用域呢。
对于 service 我认为以 传参方式传入 ctx 比较稳妥。

**Comment by czy88840616** [comment]
这个主要是实现方式了，在绑定 middleware的时候，注入baseService，还没有请求，所以肯定是做不到请求作用域，所以里面的一切都是单例。

**Comment by waitingsong** [comment]
假如有 UserService extends baseService, 可以注册为默认作用域么

**Comment by czy88840616** [comment]
首先，单例没有 ctx，即使写了也是 undefined（貌似为了防止误写还是加了一个空对象）。

其次继承的问题就比较复杂了，建议基类不要写 `@provide` ，这样是不会被 ioc 容器扫描进来，都以子类的作用域为准，比较合理。

**Comment by Chersquwn** [comment]
嗯，现在用`requestContext.getAsync`获取到了，只是文档里面没有说明，有些疑惑。
