### ISSUE TITLE
[需求] faas部署到阿里云， f.yml里面能否支持自定义域名开启https（配置对应证书）功能

### ISSUE THREAD

**Issue by Kntt** [midwayjs/midway#2686]
找了文档和源码，没有发现自定义域名可以配置https的地方。
安全组要求必须开启https
使用midway部署，每次https都会被重置。很不方便
<img width="381" alt="image" src="https://user-images.githubusercontent.com/20291026/215405609-7e69ac92-fb12-4031-981e-9b97631b83c9.png">
想可以得到支持

**Comment by czy88840616** [comment]
要看 serverless devs 是否有该配置。

**Comment by Kntt** [comment]
> 要看 serverless devs 是否有该配置。

里面没有， 那就悬了， 先用http了， 不影响功能
