### ISSUE TITLE
start midway server async

### ISSUE THREAD

**Issue by zhaofeng-shu33** [midwayjs/midway#270]
* **Node Version**: 10.16.0
* **Midway Version**: 1.8.0
* **Platform**: macOS

使用 `require('midway/server')` 可以同步启动 server（阻塞进程），想问下有没有异步的方式？
在 `midway/server.js` 中有提到 `require('midway/server').ready`可以接一个回调函数，但
我试了好像还是同步的方式，没有进入回调函数。

**Comment by czy88840616** [comment]
恩，我看了下 egg-cluster 的 master，貌似也没有留回调函数。。

**Comment by zhaofeng-shu33** [comment]
OK

**Comment by waitingsong** [comment]
服务器启动没必要异步吧。

**Comment by zhengxsFE** [comment]
@waitingsong 有的，比如异步加载配置信息

**Comment by czy88840616** [comment]
这个其实可以用另外的方式解决，比如在 agent.ts 里，手动从 ioc 容器中 get 一个单例，单例的 @init 方法里做执行就行。

**Comment by czy88840616** [comment]
已支持异步配置加载。
