### ISSUE TITLE
解析multipart/form-data格式中的非文件字段

### ISSUE THREAD

**Issue by cxy930123** [midwayjs/midway#2716]
* **Node Version**: v18.12.1
* **Midway Version(Decorator/Core)**: 3.7.0
* **Component Name/Version**: @midwayjs/upload@3.10.7
* **Platform**: Linux
* **Mini Showcase Repository**:

期望能解析 formData 格式中的文本字段，目前似乎只能获取上传的文件，而无法获取其中的非文件字段。

**Comment by czy88840616** [comment]
不是 Fields 里？
