### ISSUE TITLE
midway 3.0一体化项目如何部署访问静态的主文档？

### ISSUE THREAD

**Issue by Amoslb** [midwayjs/midway#2736]
使用一体化项目直接进行一体化部署打包后在本机进行run start，项目启动后台接口可以通过postman访问到。但是路由默认无法访问index.html主文档。
![image](https://user-images.githubusercontent.com/22581560/218994399-b3b4e19d-9122-465f-9adc-a5a861ec4f99.png)
<img width="332" alt="image" src="https://user-images.githubusercontent.com/22581560/218994698-17560eee-b3f1-4828-bf4e-e9333a02e085.png">
这里是打包后的产物，我想通过localHost:3000/index.html 访问_client文件夹下的html文档应该如何做？或者是否应该设置根域名的default 为_client文件下的index.html

**Comment by Amoslb** [comment]
已解决

**Comment by perny** [comment]
> 已解决

请问一下如何解决的？
