### ISSUE TITLE
passport的使用,按照v3的文档的代码配置后,validate方法没有触发

### ISSUE THREAD

**Issue by keepzouba** [midwayjs/midway#2737]
![image](https://user-images.githubusercontent.com/36989930/218997119-446411d4-e5d3-4b3c-b86f-e4a80fed0529.png)
<img width="606" alt="image" src="https://user-images.githubusercontent.com/36989930/218997272-d4d5a84e-0527-4f0e-a5b0-5cc7b8fb7f98.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/36989930/218997335-a4b2cd28-e0d6-48e8-b5b7-ff4576e8ef1d.png">

**Comment by keepzouba** [comment]
能有完整的示例查看吗

**Comment by czy88840616** [comment]
https://github.com/midwayjs/midway/tree/main/packages/passport/test/fixtures
