### ISSUE TITLE
dev模式需要支持符号链接，或子进程支持传入node启动参数

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#2742]
我的项目是一个monorepo
```
- node_modules
    - @midwayjs
        - validate
- packages
    - my-lib
        - my-dto.ts
        - package.json
    - midway-app
        - node_modules
            - my-lib (symblo link)
            - @midwayjs
                - ...
        - ...
        - package.json
- package.json
- lerna.json
```

其中 `my-lib` 是 `midway-app` 的依赖项，而`midway-app`需要打包发布，所以用了 yarn 的 nohoist，将所需依赖都安装在自己的目录下，只有`my-lib`用了link。
`my-lib` 里定义了一些midway需要的DTO，依赖了`@midwayjs/validate`，因此安装了`@midwayjs/validate`并且由 lerna host到根目录。

为了能同时调试`my-lib`，使用了node的`--preserve-symlink`选项
vscode的 launch.json 如下：
```
{
			"name": "Midway Local",
			"type": "node",
			"request": "launch",
			"cwd": "${workspaceRoot}/code",
			"runtimeExecutable": "node",
			"runtimeArgs": [
				"--preserve-symlinks",
				"--preserve-symlinks-main",
				"node_modules/@midwayjs/cli/bin/midway-bin.js",
				"dev",
				"--ts",
			],
			"skipFiles": [],
			"env": {
				"NODE_ENV": "local"
			},
			"console": "integratedTerminal",
			"restart": true,
			"autoAttachChildProcesses": true
}
```
而midway dev启动了子进程，没有将 "--preserve-symlinks" 传入，导致 require my-lib 模块时，目录不是 `packages/midway-app/node_modules/my-lib/**`，而是变成是实际目录`packages/my-lib`.

之后 `my-lib` require `@midwayjs/validate` 时，会找不到依赖根目录的 `/node_modules/@midwayjs/core` 报错。如果根目录安装`@midwayjs/core`，则会重复两份core运行时。

目前的解决办法是，在这里将父进程的execArgv传入

https://github.com/midwayjs/cli/blob/47e39865bdf6a426bd5bf163f7ebdb3ec188a67c/packages/cli-plugin-dev/src/index.ts#L230-L241

`execArgv = execArgv.concat(process.execArgv);`

**Comment by czy88840616** [comment]
理解一下，就是 monorepo 下 midway-app 依赖了 my-lib，我理解快速解法有两个

- 1、直接相对路径引用 ts，ts 能够识别的，midway 库在测试中一直有在用，比如 import * as xx from '../../src';
- 2、如果相对引用觉得不干净，需要 from 'xx' 包的做法，package.json 加了依赖的话，lerna bootstrap 会自动软链，这个时候 my-lib 的 main 指向 src/index.ts 即可实时开发（发布记得改回）。

**Comment by pilaoda** [comment]
midway-app 是需要打包部署的，如果用相对引用的话，没办法把外部的 my-lib 打包进去。
目前是手动链接了的，问题在于 my-lib 里依赖 @midway/core 这一步出了问题

**Comment by pilaoda** [comment]
如果 my-lib 被require运行时，执行路径能保持在 `packages/midway-app/node_modules/my-lib/` 目录下，就能找得到 `packages/midway-app/node_modules/@midwayjs/core`，但是由于子进程没有 --preserve-symlinks，导致my-lib路径变成了实际路径`/node_modules/my-lib/`，而根目录下没有安装 `/node_modules/@midwayjs/core`

**Comment by pilaoda** [comment]
另外补充一下，现在package.json的main指向dist，然后tsconfig里配置 `"declarationMap": true,`，vscode也能自动跳转依赖的src

**Comment by czy88840616** [comment]
main 指向 src，是为了开发时能引到源码实现实时生效，倒不是为了跳转定义。

**Comment by pilaoda** [comment]
明白了，我是习惯用 tsc watch 来开发。不过这并不影响，用哪种开发方式子进程都无法正常 require @midwayjs/core
