### ISSUE TITLE
客户端 POST 请求后，返回值 data 为"空"?

### ISSUE THREAD

**Issue by smr1987** [midwayjs/midway#2774]
### 客户端请求后端数据库增加数据，数据库正常添加数据，操作数据库的命令也正常返回添加的数据，但是 return 给客户端，客户端 data 收到的是 “空“，请问我是哪里写错了吗？

> /mongodb/service.db.ts

```typescript
@Provide()
export class Card {
  @InjectEntityModel(CardModel)
  private cardModel: ReturnModelType<typeof CardModel>;

  async add(body: IPostCardAdd) {
    const num = body.quantity ? body.num : 1;
    const arr = [];
    for (let i = 0; i < num; i++) {
      arr.push({ uuid: uuid().toUpperCase(), notes: body.notes });
    }
    return await this.cardModel.create(arr);
  }
}
```

> /controller/api.controller.ts

```typescript
@Controller('/card')
export class APIControllerCard {
  @Inject()
  ctx: Context;
  @Inject()
  card: Card;

  @Post('/add')
  async add() {
    return await this.card.add(<IPostCardAdd>this.ctx.request.body);
  }
}
```

> 客户端收到的返回值

```json
{
    ...
    data:"" ,
    status:204,
    statusText:"No Content"
    ...
}
```

**Comment by desonyuan** [comment]
看你的返回结果应该是经过中间件包装过的，你可以在这个层面看看是否处理掉了？

**Comment by smr1987** [comment]
> 看你的返回结果应该是经过中间件包装过的，你可以在这个层面看看是否处理掉了？

感谢，就是中间件的问题，我没有写 return await next() ，只是写了 next()！

**Comment by waitingsong** [comment]
> > 看你的返回结果应该是经过中间件包装过的，你可以在这个层面看看是否处理掉了？
> 
> 感谢，就是中间件的问题，我没有写 return await next() ，只是写了 next()！

`return next()` 也行

**Comment by smr1987** [comment]
> > > 看你的返回结果应该是经过中间件包装过的，你可以在这个层面看看是否处理掉了？
> > 
> > 
> > 感谢，就是中间件的问题，我没有写 return await next() ，只是写了 next()！
> 
> `return next()` 也行

好的 感谢!
