### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by guojianlan** [midwayjs/midway#2775]
走新手教程
npm init midway
直接启动报错
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/9145416/222343013-96672dc6-9cdf-4b24-8db7-09eb3846f3e4.png">

**Comment by czy88840616** [comment]
使用默认脚手架没有发现问题，你确认 ts-node，typescript 版本，如有代码修改，请确认修改的部分。

**Comment by guojianlan** [comment]
> 使用默认脚手架没有发现问题，请确认 ts-node，typescript 版本，如有代码修改，请确认修改的部分。

后面我修改typescript的版本为4.0.0才没有问题。你用默认脚手架创建的koa3项目也没问题吗？

**Comment by czy88840616** [comment]
对的，我刚拿 github action 确认了下也没有问题，脚手架创建和测试我们都是有 daily run 的。

![image](https://user-images.githubusercontent.com/418820/222360653-102311e7-6e8b-49c6-98a8-dc357406689e.png)

**Comment by guojianlan** [comment]
> 对的，我刚拿 github action 确认了下也没有问题，脚手架创建和测试我们都是有 daily run 的。
> 
> ![image](https://user-images.githubusercontent.com/418820/222360653-102311e7-6e8b-49c6-98a8-dc357406689e.png)

默认的package.json
用了 typescript "version": "4.8.4",
用了 ts-node  "version": "10.4.0"
启动真的报错
这个是用的项目依赖，我没改过。

**Comment by guojianlan** [comment]
> 对的，我刚拿 github action 确认了下也没有问题，脚手架创建和测试我们都是有 daily run 的。
> 
> ![image](https://user-images.githubusercontent.com/418820/222360653-102311e7-6e8b-49c6-98a8-dc357406689e.png)

开发依赖新增"ts-node": "^10.9.1"解决。

**Comment by czy88840616** [comment]
ts-node 是 cli 工具带的，比如我安装完的结构是：

<img width="512" alt="image" src="https://user-images.githubusercontent.com/418820/222608034-f23889ff-4857-4b95-b8cb-c3714be28dd6.png">

可以 check 一下。
