### ISSUE TITLE
midway-init 官方文档提供的例子运行报错

### ISSUE THREAD

**Issue by cuitianze** [midwayjs/midway#279]
* **Node Version**: v8.11.1
* **Egg Version**:  2.22.2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Mac OS
* **Mini Showcase Repository**:

$ midway-init --type midway-ts-ant-design-pro
$ npm install
$ npm run dev
会出现如下报错：

![image](https://user-images.githubusercontent.com/5918515/61169923-2589aa80-a595-11e9-9fa9-1927717e3c51.png)

**Comment by czy88840616** [comment]
看着像是前端部分编译报错，这个我得找个人。。

**Comment by tw93** [comment]
Node 版本升级到9以上就好了，建议10

**Comment by waitingsong** [comment]
要不 midway 生个 major 版本，node 要求 10+

**Comment by czy88840616** [comment]
可以脚手架先限制掉。
