### ISSUE TITLE
几个部署阿里云 FC 的问题

### ISSUE THREAD

**Issue by zuozuomuxi** [midwayjs/midway#2797]
请教两个问题：
1.我看文档有[Midway应用迁移](https://www.midwayjs.org/docs/serverless/migrate_midway)这部分，但我没太理解，我有一个midway的标准项目，没做这些改动就可以直接部署到阿里云 FC 上跑起来，为什么还要做迁移呢？
2.如果不做任何改动，一个midway标准项目部署到FC上，相比部署到ECS上，除了冷启动时间外，会有别的性能损失吗？

**Comment by czy88840616** [comment]
我简单解释一下

1、现阶段迁移有两种方案，一种是你说不用做任何处理就能部署到阿里云，这是云平台做的，某些平台是不支持的，文档中写的是框架层面做的，用来适配不支持的平台（在很早以前所有平台都不支持）

由于当前腾讯云函数的半废弃状态，我们觉得这块的投入价值很低，后续应该会是全部使用云平台的方案，这个文档就不再需要了。

2、性能问题，1 中的两种方案没有区别，但是和传统ecs 肯定有差异，ecs可以使用多worker执行，性能会更优。

**Comment by zuozuomuxi** [comment]
@czy88840616 感谢解答。第2点我再追问一下，为什么 FC 不能使用多 worker 执行？FC 似乎也能用 pm2 之类的工具来起多个进程，我现在对 FC 的理解就是能自动启动和回收的 ECS。

**Comment by czy88840616** [comment]
FC 的容器和 ECS 还是有略微的不同，一方面是目录，权限，日志采集方案等不同，比如大部分目录是不可写只读的，代码是通过 fc 自己的运行时调用起来的，而 ECS 这块是完全控制，二是数据面架构和普通的 ECS 是完全不同的，流量是经过 FC 内部的各种组件（网关）等，最终才到达 fc 函数（并非真实的 http req/res）

此外，通过一定的手段是可以在容器上使用 pm2 等方式启动多个进程，但是由于一般使用函数容器都是为了省钱，cpu 核数都会限制的比较低，多 worker 并不能在低 cpu 核数下体现出性能优势，反而徒增复杂度，也会影响函数弹性特性。另一方面，假如使用预留容器的方式，价格和传统  ecs 比并没有优势，所以我们一般在函数场景都只考虑单进程模式。

**Comment by zuozuomuxi** [comment]
了解了，感谢。现在阿里云 FC 的预留模式支持 vcpu 闲置计费，我感觉成本还是比较低的，运维成本也很低，在产品的前期阶段感觉足够代替 ECS 了，我先按这个方案跑一段时间试试
