### ISSUE TITLE
egg-sequelize的用法是啥

### ISSUE THREAD

**Issue by yuu2lee4** [midwayjs/midway#28]
egg-sequelize的文档没有class的写法  所以midway model的写法是啥

**Comment by Lellansin** [comment]
参见 [demo 仓库](https://github.com/midwayjs/midway-examples/)

**Comment by sscfaith** [comment]
同问此问题，demo仓库的是sequelize的用法，不是egg-sequelize

**Comment by czy88840616** [comment]
egg-sequelize 在 ts 中用法比较函数化，所以我们一般就不使用了，如果真的要用。。我看看晚些搞个demo。
