### ISSUE TITLE
建议：支持标准项目之间互相import，直接调用控制器或服务

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#2808]
看了一下一体化的代码实现，是在编译的时候，通过读取Api参数的相关信息，另外生成一份ts代码给客户端打包用。
感觉这个思路其实可以拓展到标准项目之间的互相调用。
正常来讲，build会将标准项目编译到`dist`目录。可以再加一个命令，为外部项目生成一份http请求的ts或js代码，放到类似`rpc`目录。

项目1："home-service"
```
src/
    controller/
        home.controller.ts
dist/
    controller/
        home.controller.js
        home.controller.d.js
rpc/
    controller/
        home.controller.ts // 由新命令自动生成
package.json
```

src/controller/home.controller.ts:
```
@Controller("/home")
export class HomeController {
    @Post("/hello")
    async Hello(@Body("text") text: string): Promise<string> {
        return `Hello Midwayjs! ${text}`;
    }
}
```

rpc/controller/home.controller.ts:
```
// 读取各种装饰器信息，自动生成
export class HomeController {
    async Hello(text: string): Promise<string> {
        return await makeHttpRequest(`${env.HOST}/home/hello`, {data:{text}});
    }
}
```

package.json
```
{
    "name": "home-service",
    "exports": {
        "./*": {
            "rpc": "./rpc/*.ts",
            "default": "./src/*.ts"
        }
    }
}
```

外部标准项目
项目2："proxy-service"
src/controller/proxy.controller.ts
```
import { HomeController } from "home-service/controller/home.controller";

@Controller("/proxy")
export class ProxyController {
    @Inject()
    homeController: HomeController

    @Post("/hello")
    async Hello(@Body("text") text: string): Promise<string> {
        return await this.homeController.Hello(text);
    }
}
```

开发阶段，正常IDE例如vscode，从外部项目跳转HomeController定义，就能根据`default`条件跳转到`src`目录下，同时typescript也能进行类型检查。
ts-node运行时或tsc编译时，需要加上resolve condition: rpc，这样就能require `rpc`目录下的ts代码，运行时进行http请求。

这套机制我自己的项目已经实现了可行，不过没用依赖注入而是直接new，装饰器也支持的不全，就不PR了。

**Comment by czy88840616** [comment]
这个有点像 swagger 中的直接生成前端请求包。

**Comment by googoo625** [comment]
正在找这个！
我希望实现若干基础模块，m1,m2,m3，每个模块有自己的controller/service，依赖注入的方式，是完整的某方面的web接口。
上层业务按需引用，比如引用m1,m3，则可以直接访问每个模块定义的web接口。

请问是否有办法支持？

**Comment by czy88840616** [comment]
> 正在找这个！ 我希望实现若干基础模块，m1,m2,m3，每个模块有自己的controller/service，依赖注入的方式，是完整的某方面的web接口。 上层业务按需引用，比如引用m1,m3，则可以直接访问每个模块定义的web接口。
> 
> 请问是否有办法支持？

这就是组件。

**Comment by googoo625** [comment]
> 正在找这个！ 我希望实现若干基础模块，m1,m2,m3，每个模块有自己的controller/service，依赖注入的方式，是完整的某方面的web接口。 上层业务按需引用，比如引用m1,m3，则可以直接访问每个模块定义的web接口。
> 
> 请问是否有办法支持？

试过在configuration里调用 this.webRouterService.addController ，无法解决依赖注入的问题，会报错：
MidwayDefinitionNotFoundError: XXXService in class XXXController is not valid in current context

**Comment by czy88840616** [comment]
> > 正在找这个！ 我希望实现若干基础模块，m1,m2,m3，每个模块有自己的controller/service，依赖注入的方式，是完整的某方面的web接口。 上层业务按需引用，比如引用m1,m3，则可以直接访问每个模块定义的web接口。
> > 请问是否有办法支持？
> 
> 试过在configuration里调用 this.webRouterService.addController ，无法解决依赖注入的问题，会报错： MidwayDefinitionNotFoundError: XXXService in class XXXController is not valid in current context

这是你使用问题，如果独立的组件，调用自己独立的 class controller，service就行，不需要自行注册添加路由。

**Comment by googoo625** [comment]
> 这是你使用问题，如果独立的组件，调用自己独立的 class controller，service就行，不需要自行注册添加路由。

非常感谢，这就去学习组件 ~

**Comment by hooliy** [comment]
@czy88840616 组件中[实体](https://github.com/midwayjs/midway/discussions/3565)怎么办？ 在组件的mikro中配置`entities: [
        Book
    ],` ，在主应用的配置文件中也配置`entities: [
        Author
    ],`  主应用引用组件时，会导致组件中与主应用中配置相同项丢失。也就是说访问组件controller中调用Book实体丢失。

是不是我的用法不对？
