### ISSUE TITLE
如何集成swagger

### ISSUE THREAD

**Issue by tan1444** [midwayjs/midway#281]
如果在Midway体系下集成swagger呢，有没有例子可以参考？

**Comment by anthhub** [comment]
我也有这个问题啊

**Comment by tan1444** [comment]
没人解答吗

**Comment by czy88840616** [comment]
这个我不太了解。。没法答。。。egg-swagger 能满足需求么？

**Comment by anthhub** [comment]
你们不用swagger生成文档吗?

**Comment by czy88840616** [comment]
目前应该是没有用的。。不知道你们的场景是在哪个方面?

**Comment by anthhub** [comment]
midway做中间层, 分发请求, 需要生成api文档swaggerUI给前端用

**Comment by chu-han** [comment]
+1

**Comment by anthhub** [comment]
另外一个issue里面的大哥 说 egg-swagger-doc  可用 大家可以试试  我过端时间页上传一个demo吧

**Comment by tan1444** [comment]
嗯，求个demo

**Comment by czy88840616** [comment]
看了下 egg-swagger-doc 是从注释里解析的数据，有没有同学有兴趣从元数据里直接拿这些信息，可以基于 egg-swagger-doc 来实现，或者单独搞一个插件。

**Comment by waitingsong** [comment]
也可以考虑直接从 model.ts 的 Types 定义中生成 schema 然后转成文档。

**Comment by tan1444** [comment]
![1564024223(1)](https://user-images.githubusercontent.com/16314475/61843040-da449580-aecc-11e9-92f8-749b48571ab6.jpg)
使用了egg-swagger-doc后，原先的注入全部失效了，进入函数后都变成了undfined，这要如何解决？

**Comment by tan1444** [comment]
连中间件也失效了

**Comment by czy88840616** [comment]
提供一个复现仓库?

**Comment by tan1444** [comment]
https://github.com/tan1444/stockclass.git  这个

**Comment by tan1444** [comment]
https://github.com/tan1444/stockclass.git

**Comment by tan1444** [comment]
被删掉了吗

**Comment by czy88840616** [comment]
你那个好大，而且有些秘钥，我就隐了。我简单写了个 demo 试一下。

**Comment by tan1444** [comment]
那我的问题出在哪了，感觉代码是一样的呀

**Comment by tan1444** [comment]
你的控制上面没有加
/**
 * @controller login 登录接口
 */
这段注释

**Comment by tan1444** [comment]
这个注释加上去，注入什么的都没用了

**Comment by zhou-xin-undefined** [comment]
> 这个注释加上去，注入什么的都没用了

加上这个之后, swagger调用接口会报错undefined,   但是不通过swagger可以调用成功

**Comment by kurten** [comment]
可以吧 swaggerdoc.routerMap 设置为 false ，这样就不会重复注册路由了

**Comment by czy88840616** [comment]
@tan1444 看下是否可行。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/63142002-7cfaba80-c01a-11e9-9cf0-f0eb69624e9d.png)

如果出现 `Cannot read property 'prototype' of undefined` 的问题，是因为插件中对 ts 的处理，比如通过 default 导出。

```ts
export default class xxxController {

}
```

**Comment by czy88840616** [comment]
还有其他问题，可以再开。

**Comment by zhou-xin-undefined** [comment]
![1565942386(1)](https://user-images.githubusercontent.com/29814278/63152667-f2788200-c03e-11e9-80cd-cbd647085d03.png)
![1565942373(1)](https://user-images.githubusercontent.com/29814278/63152670-f3a9af00-c03e-11e9-8f47-6955d542d27d.png)
现在的问题是无法访问注入的对象, this为空对象
@czy88840616

**Comment by kurten** [comment]
> ![1565942386(1)](https://user-images.githubusercontent.com/29814278/63152667-f2788200-c03e-11e9-80cd-cbd647085d03.png)
> ![1565942373(1)](https://user-images.githubusercontent.com/29814278/63152670-f3a9af00-c03e-11e9-8f47-6955d542d27d.png)
> 现在的问题是无法访问注入的对象, this为空对象
> @czy88840616

确认一下是否将 config.default.ts 中 config.swaggerdoc.routerMap 这个参数设置为false，你这个异常是因为重复注册了路由导致的

**Comment by zhou-xin-undefined** [comment]
> > ![1565942386（1）](https://user-images.githubusercontent.com/29814278/63152667-f2788200-c03e-11e9-80cd-cbd647085d03.png)
> > ![1565942373（1）](https://user-images.githubusercontent.com/29814278/63152670-f3a9af00-c03e-11e9-8f47-6955d542d27d.png)
> > 现在的问题是无法访问注入的对象，这为空对象
> > @ czy88840616
> 
> 确认一下是否将config.default.ts中config.swaggerdoc.routerMap这个参数设置为false，你这个异常是因为重复注册了路由导致的

确实是这个问题,谢谢,
