### ISSUE TITLE
vscode 调试单元测试

### ISSUE THREAD

**Issue by waitingsong** [midwayjs/midway#282]
* **Node Version**: v10.16.0 64bit

#### 需求：
在 vscode 对 `npm run test`  进行调试

#### 操作：
1. `.vscode/launch.json` 添加如下
  ```json
      {
      "name": "Midway Test Debug",
      "type": "node",
      "autoAttachChildProcesses": true,
      "console": "integratedTerminal",
      "env": {
        "NODE_ENV": "local"
      },
      "port": 9229,
      "protocol": "auto",
      "request": "launch",
      "restart": true,
      "runtimeArgs": [
        "run",
        "test:debug",
        "--",
        "--inspect-brk"
      ],
      "runtimeExecutable": "npm"
    },
  ```
2. `packlage.json`  scripts 增加：
  ```json
  "test:debug": "midway-bin test --ts",
  ```

#### 问题：
1. F5 调试时断点定位 ts 文件行与断点实际位置不符。
2. test 执行完毕后立即再次 F5 运行，错误处提示 `Midway Test Debug 配置已经在运行`。在控制台会出现一条信息 `Waiting for the debugger to disconnect...` 。
大致半分钟后才能继续 F5。 但是在任务管理器中查看 vscode 在调试时启动的 bash 进程并未在调试结束后退出——每调试运行一次就会产生不会自动退出的 bash/cmd 进程，除非退出 vscode 程序本身。
3. 把 `scripts.test:debug` 换成  `mocha --opts test/mocha.opts` 并添加相关配置，调试时断点位置正常，也能正常退出调试进程，但调试会走两次……

**Comment by waitingsong** [comment]
launch.json 不直接用 `test` 原因是先执行 lint 会导致 vscode 无法连接到调试进程（9229端口）。

**Comment by waitingsong** [comment]
vscode 用 mocha 配置来调试会执行两次，而 eggjs 是正确的（一次）：
```json
    {
      "name": "Mocha Tests",
      "type": "node",
      "args": [
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "${workspaceFolder}/test"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "request": "launch"
    }

```

**Comment by waitingsong** [comment]
vscode 如果直接执行 `npm run test` 来调试，一可能 lint 时超时（可增加超时参数解决），二是 test 结束后进程不会自动退出（除非关闭 vscode 程序）。
所以用 mocha 执行方案，当 test 完成后手动中止 debug （Shift+F5）就行了。
PR 见 #292

**Comment by czy88840616** [comment]
一个更简单的 Debug 方案，新版本 VSCode 已经支持了 autoAttach。

第一步，vsc 里按 cmd+shift+p，开启 auto attach。

![image](https://user-images.githubusercontent.com/418820/83840648-b92a1380-a731-11ea-844e-cbbbfbe52720.png)

第二步，修改，或者新增命令，其实就是在原来的命令后面传入调试参数。

```
"test": "npm run lint && midway-bin test --ts --inspect",
```

第三步，加入断点，在 vsc 的控制台（一定要在 vsc 里启动）执行命令，比如上面的 npm run test 即可断到。

![image](https://user-images.githubusercontent.com/418820/83840733-eb3b7580-a731-11ea-9a63-734de6dad59c.png)

**Comment by waitingsong** [comment]
不错。我试试看。

**Comment by waitingsong** [comment]
测试了， mocha 场景下面没成功定位断点
```
    "test": "cross-env TS_NODE_PROJECT=test/tsconfig.json mocha --inspect",
```
无论是普通 npm 模块解构还是 mono-rep 解构。
