### ISSUE TITLE
egg-mongoose 按照 egg 的用法 在 midway 里面不能用 

### ISSUE THREAD

**Issue by yangcecode** [midwayjs/midway#284]
Cannot read property 'find' of undefined

```ts
import { Application } from 'midway'
module.exports = (app: Application) => {
    const mongoose = app.mongoose;
    const Schema = mongoose.Schema;
  
    const UserSchema = new Schema({
        email: { type: String  },
        code: { type: String  },
        data: { type: Number },
        islive: { type: Boolean },
        password: { type: String }
    });
  
    return mongoose.model('User', UserSchema);
}
```

```ts
import { provide, Context, inject } from 'midway';
import { IUserService, IUserResult } from './interface';

@provide('userService')
export class UserService implements IUserService {
  
  @inject()
  ctx: Context;

  async getUser(): Promise<IUserResult> {
    let user = await this.ctx.model.User.find({});
    return user;
  }
}
```

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/61228905-b7daab80-a759-11e9-85ce-b09d033417f9.png)

![image](https://user-images.githubusercontent.com/418820/61228933-c6c15e00-a759-11e9-937f-1cd73370948a.png)


简单测了下。。没发现问题。。

**Comment by yangcecode** [comment]
试了试还是不行 ctx 里面没有 model 对象

**Comment by czy88840616** [comment]
提个仓库吧。

**Comment by yangcecode** [comment]
> 提个仓库吧。

https://github.com/yangcecode/nlna

**Comment by czy88840616** [comment]
恩，如果要使用 egg 插件，就得按 egg 的目录约定来，所以 model 必须放到 app/model 下。

**Comment by yangcecode** [comment]
> 恩，如果要使用 egg 插件，就得按 egg 的目录约定来，所以 model 必须放到 app/model 下。

解决了

**Comment by lsai2270** [comment]
@yangcecode  你是怎么解决的啊! 我这边也是使用egg-mongoose,在service里注入了ctx, ctx.model 是 空对象{}
![image](https://user-images.githubusercontent.com/32258110/125745921-0d9db8f4-e8e2-430d-8238-032d4ce69da6.png)
