### ISSUE TITLE
启用@midwayjs/upload后接口都挂了

### ISSUE THREAD

**Issue by Liu7i-67** [midwayjs/midway#2845]
* **Node Version**:14.19.1
* **Midway Version(Decorator/Core)**:@midwayjs/koa 3.9.9
* **Component Name/Version**: @midwayjs/upload 3.11.0
* **Platform**: window10
* **Mini Showcase Repository**:https://github.com/Liu7i-67/mini_koa

按照 [官网的流程](https://midwayjs.org/docs/extensions/upload#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE)  启用文件上传组件后原来的接口都挂掉了
![image](https://user-images.githubusercontent.com/95481822/229015436-3c8f4146-5b25-4deb-8263-d0bfb10e453d.png)
![image](https://user-images.githubusercontent.com/95481822/229015742-191d0c9a-becc-4560-b282-dfa57f836f16.png)

想请教一下解决方案 qaq

**Comment by echosoar** [comment]
upload 使用了 3.11.0 版本，那么 @midwayjs/core、@midwayjs/koa 需要都使用 3.11.0 版本
![image](https://user-images.githubusercontent.com/14832743/229026823-805c76c6-c5b8-4f92-8e04-6df366edf36e.png)
https://www.midwayjs.org/blog/release/3.11.0

**Comment by Liu7i-67** [comment]
好的，谢谢 

我把@midwayjs/upload降级为3.9.9 之后就可以了

**Comment by eleant001** [comment]
@midwayjs/core": "^3.11.6
@midwayjs/koa": "^3.11.10
@midwayjs/upload": "^3.11.10
1、删除 package-lock.json 或者 yarn.lock
2、彻底删除 node_modules（比如 rm -rf node_modules)
3、重新安装依赖（ npm install 或者 yarn）
