### ISSUE TITLE
从egg迁移到midway的疑惑

### ISSUE THREAD

**Issue by wadeDra** [midwayjs/midway#286]
背景：由于想转成TS开发，所以我们打算直接从egg迁移到midway
疑惑：我们在eggjs的基础上封装了一层企业框架framework，定义了一些方法跟配置，我们在这块迁移的时候是应该fork midway去做吗？还是有什么推荐？

**Comment by czy88840616** [comment]
这得看规模了，上层框架跟插件本身也非常类似，也可以通过插件扩展出来。

**Comment by czy88840616** [comment]
现在可以复用原来的框架，直接使用。https://www.yuque.com/midwayjs/midway_v2/custom_eggjs
