### ISSUE TITLE
需要支持通过 ServerlessFunction 配置 cpu 核数

### ISSUE THREAD

**Issue by zuozuomuxi** [midwayjs/midway#2868]
目前 ServerlessFunction 装饰器支持配置内存大小(memorySize)
```ts
@ServerlessFunction({
    memorySize: 1024,
})
```
但是配置后部署阿里云FC时会报错：
```
the ratio of Memory(in GB) to CPU(in core) must be between 1 and 4, actual: 1.00/0.15(6.67)
```
希望能增加一个 cpu 字段，可以配置 cpu 核数。
阿里云FC的 serverless-devs 工具是支持配置 cpu 的 [serverless-devs](https://docs.serverless-devs.com/fc/yaml/function)

希望把 diskSize gpuMemorySize layers 等字段也加上

我看了下源码， midway serverless 的 deploy 也是用 serverless-devs 做的，似乎只要改 ServerlessFunction 的类型声明就能支持了

**Comment by czy88840616** [comment]
这里不仅仅定义要改，spec 生成也要改一下。

**Comment by czy88840616** [comment]
新版本已经直接使用 serverless devs 和 s.yam 进行部署，应该没有这个问题了。
