### ISSUE TITLE
单元测试错误，我也看不懂，毕竟文档都是错误的，提示：User has not been defined

### ISSUE THREAD

**Issue by YSHIDM** [midwayjs/midway#2870]
我也看不懂，毕竟文档都是错误的
![image](https://user-images.githubusercontent.com/7659872/231114734-55abfb30-c735-43a1-a81a-49a1c151b345.png)
![image](https://user-images.githubusercontent.com/7659872/231115426-53f91f1c-b789-422e-94cb-cd83aaa0fada.png)

我以为程序员都是严谨的，做着核弹的考题，干着搬砖的活这就够惨了，连教程都是欺骗我

**Comment by czy88840616** [comment]
import { Repository } from 'sequelize-typescript';
