### ISSUE TITLE
安装@midwayjs/upload组件后报错：_b.bind is not a function

### ISSUE THREAD

**Issue by weijunext** [midwayjs/midway#2872]
* **Node Version**: v16.15.0
* **Midway Version(Decorator/Core)**: "@midwayjs/decorator": "^3.0.0", "@midwayjs/core": "^3.0.0",
* **Component Name/Version**: "@midwayjs/decorator": "^3.0.0"
* **Platform**: Mac VScode
* **Mini Showcase Repository**:

项目是两个月前开始搭建，今天要开发上传功能，安装了`@midwayjs/upload`包，在`@Configuration`引入`upload`后，所有请求都报错`_b.bind is not a function……`，报错文件是`@midwayjs/core/dist/service/middlewareService.js`。
本想提供一个复现仓库，但是新创建的项目并没有问题，对比后发现是`middlewareService.js`有改动，旧项目把lock和node_modules删掉重新安装依赖，请求就正确了。

可能其他朋友也会遇到这个问题，所以来提个issues。希望我有把问题描述清楚[抱拳]

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/how_to_update_midway

**Comment by echosoar** [comment]
一般来说是安装的 @midwayjs/upload 组件的 y 版本，与 @midwayjs/core 的版本不一致导致的，可以考虑升级 @midwayjs/core 的版本到与 @midwayjs/upload 一致的版本
参考 https://midwayjs.org/docs/how_to_update_midway
