### ISSUE TITLE
我在部署测试环境时，怎么需要用到egg-mock这个库呢

### ISSUE THREAD

**Issue by Topthinking** [midwayjs/midway#2873]
如题所述，在设置环境变量为test时，需要egg-mock这个库，很神奇啊
![image](https://user-images.githubusercontent.com/13382821/231401535-722e1faf-1f37-4b5d-a86a-50db0ac5d131.png)

**Comment by czy88840616** [comment]
你是egg吧，test是egg自己的环境变量，会依赖 egg-mock。

**Comment by Topthinking** [comment]
是的，我发现走到了unittest环境变量

![image](https://user-images.githubusercontent.com/13382821/231413418-6a4a0f1e-eaae-4a91-8d03-eb0c76631803.png)

把这个注释就可以了

**Comment by Topthinking** [comment]
> 你是egg吧，test是egg自己的环境变量，会依赖 egg-mock。

是的，有什么办法么

**Comment by czy88840616** [comment]
bootstrap.js 本身就不是给本地开发或者单测用的，也不会使用 test 变量啊。
