### ISSUE TITLE
Feature: 给`createRequestParamDecorator`增加第三个参数`ParamDecoratorOptions`

### ISSUE THREAD

**Issue by ghostoy** [midwayjs/midway#2878]
* **Node Version**: 18
* **Midway Version(Decorator/Core)**: 3.11.0
* **Component Name/Version**: core
* **Platform**: macOS
* **Mini Showcase Repository**:

使用`createRequestParamDecorator`快速创建参数装饰器的时候，不能抛错来终止流程，会造成报错后仍然进入被装饰的函数，参数被设置成`undefined`。

现在可以使用传统的参数装饰器方式，即`createCustomParamDecorator`和`decoratorService.registerParameterHandler`，来绕过这个问题。

希望给这个函数增加第三个参数，比如`ParamDecoratorOptions`，这样就可以配置`throwErrors = true`，来实现这个功能。

**Comment by czy88840616** [comment]
publish at v3.11.4
