### ISSUE TITLE
如何把接收到的请求的原始body打印出来？  

### ISSUE THREAD

**Issue by huangapple** [midwayjs/midway#2881]
我如何把接收到的请求的原始body打印出来？

**Comment by czy88840616** [comment]
ctx.req

**Comment by huangapple** [comment]
我找到了。应该是这个， ctx.request.rawBody， 可能是我没问题清楚。

**Comment by huangapple** [comment]
好像不行。在请求正确的情况下， ctx.request.rawBody 可以打印出来， 
但如果请求本身是有点问题的， 比如 content-type 写着是 xml, body却发一个json过来， 此时 ctx.request.rawBody打印出来是undefined

**Comment by huangapple** [comment]
是我没配置  bodyParser， 我把xml加上就能打印出来， 不管这个请求对不对。， 

但好像还是有点奇怪， ctx.request.rawBody 应该不受 bodyParser的影响才对

**Comment by czy88840616** [comment]
rawBody就是bodyparser加的吧

**Comment by huangapple** [comment]
额， 那要打印哪个才是原始的body

应该没经过bodyparser是没有原始的body吧。如果真想要， 要自己去接收数据？

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/232226426-44186923-9707-44d7-8d77-8e5a84168188.png)

body 数据如果不经过 bodyparser，不会有 rawbody 属性，而是从 req 对象上解析出来的，具体参考 co-body.
