### ISSUE TITLE
请教一个问题，我依赖的一个包为module, 好像跟项目默认的commonjs冲突了， 不知道怎么解决。

### ISSUE THREAD

**Issue by huangapple** [midwayjs/midway#2883]
我依赖的一个包， package.json的type标识为 module,  导入他的模块只能用import 

然后我们的midway项目最后编译出来的都用是require的， 导致一直报如下错误

```
Error [ERR_REQUIRE_ESM]: require() of ES Module xxx/index.js from service.ts not supported.

```
我尝试修改过midway项目的package.json里的type， 跟tsconfig.json里的module， 都不行。

请问一下， 这种要怎么解决？

**Comment by huangapple** [comment]
@czy88840616 虽然我知道这问题跟midway无关，但必须得打扰下你 寻求下大神的帮助！

**Comment by czy88840616** [comment]
await import

**Comment by huangapple** [comment]
不行额， 编译都过不了

**Comment by huangapple** [comment]
放在async 标志的函数里初始化， 编译可以过
```
   const { ChatGPTAPI } = await import('chatgpt')
```
但还是不行， 还是会报错

跟直接导入报一样的错
```
R_REQUIRE_ESM]: require() of ES Module node_modules/chatgpt/build/index.js from src/service/chatGPT.service.ts not supported.
Instead change the require of index.js in src/service/chatGPT.service.ts to a dynamic import() which is available in all CommonJS modules.

```
头很大

**Comment by czy88840616** [comment]
esm 在 cjs 里用，不能放在文件开始，必须动态引入。

**Comment by huangapple** [comment]
我这肯定算动态载入了吧
```
  async chat(): Promise<{ message }> {
    const { ChatGPTAPI } = await import('chatgpt')
  }
```

**Comment by czy88840616** [comment]
顶层项目必须是 esm 项目。

**Comment by huangapple** [comment]
midway里面怎咋整？

**Comment by czy88840616** [comment]
midway 项目目前不支持 esm 模块（大多数 node 都是 cjs 为主），需要自行研究。

**Comment by huangapple** [comment]
额。好的， 谢谢解答！

**Comment by huangapple** [comment]
这是最近才出的吗？以前好像从没碰到过

**Comment by czy88840616** [comment]
从未支持过 ESM 模块。有些包就是喜欢仅发 EMS 格式的包，那就无法兼容。

**Comment by waitingsong** [comment]
midway 目前不支持纯 esm 模块。
可以自己写个包导入需要的包然后重新导出为 cjs 格式。

**Comment by ZQun** [comment]
@huangapple  试试这个方法在midway中引入esm模块
``` ts
const chatgpt = await (eval('import("chatgpt")') as Promise<typeof import('chatgpt')>);

// chatgpt.xxxxxx

```

**Comment by mirari** [comment]
这个可行，非常感谢，帮大忙了


> @huangapple 试试这个方法在midway中引入esm模块
> 
> ```ts
> // demo1
> const chatgpt = await (eval('import("chatgpt")') as Promise<typeof import('chatgpt')>);
> 
> // demo2
> const { ChatGPTAPI } = await (eval('import("chatgpt")') as Promise<typeof import('chatgpt')>);
> 
> // chatgpt.xxxx
> ```
