### ISSUE TITLE
@midwayjs/view-nunjucks v3.11.3报错

### ISSUE THREAD

**Issue by kaih001** [midwayjs/midway#2890]
1、node 18.16.0和16.17.0都试过了
2、“@midwayjs/view-nunjucks": "^3.11.3"
3、window10
详细步骤：
1、按照文档，到了模板渲染步骤，安装@midwayjs/view-nunjucks，在src/configuration.ts 配置，如图：
![1681783417118](https://user-images.githubusercontent.com/28386151/232651011-46198757-9d11-4113-a5f6-5d1c484e01ee.jpg)
2、报错信息如图：
![1681783542212](https://user-images.githubusercontent.com/28386151/232651214-394a9d58-179e-494c-9290-e849f266124a.jpg)
3、去掉src/configuration.ts 的模板渲染配置，运行正常，降低@midwayjs/view-nunjucks版本也不行

**Comment by czy88840616** [comment]
npx midway-version

**Comment by kaih001** [comment]
> npx midway-version 检查版本。

![image](https://user-images.githubusercontent.com/28386151/232694418-05e09586-2c47-4c2a-95fc-c54c7afd3dd5.png)
![image](https://user-images.githubusercontent.com/28386151/232694485-29351999-cd4a-47fc-ae44-2a594a0b5785.png)

**Comment by kaih001** [comment]
> npx midway-version 检查版本。

![image](https://user-images.githubusercontent.com/28386151/232696406-4c3f523b-76b7-47dc-871d-d12dbf29a963.png)

**Comment by czy88840616** [comment]
我理解就是依赖问题，所以你要删了lock和依赖，然后重装。

**Comment by kaih001** [comment]
> 我理解就是依赖问题，所以你要删了lock和依赖，然后重装。

哎，还是不行，后来全部删了，从新开始，降低了node版本（v14.13.1）可以了
