### ISSUE TITLE
Hook方式自定义SessionStore，在中间件中无法保存session，在Api接口中可以

### ISSUE THREAD

**Issue by zhpoplar** [midwayjs/midway#2891]
* **Node Version**: v18.15.0
* **Midway Version(Decorator/Core)**: 3.11.1
* **Component Name/Version**: 3.1.0
* **Platform**: Windows 11
* **Mini Showcase Repository**:

midway hook项目。使用中间件检测session信息，没有指定的信息则新建一个，保存到session中。但是自定义SessionStore后，在中间件使用session不会自动生成，并且用cookie写入到浏览器，默认不指定session store则可以在中间件操作，并写入cookie
![image](https://user-images.githubusercontent.com/26213974/232655012-94fee9c4-217f-4c8f-a2c2-3607a6cd6082.png)
![image](https://user-images.githubusercontent.com/26213974/232655013-7b1e62f7-42d8-4587-9947-3863d3b5e338.png)

**Comment by czy88840616** [comment]
自定义 session 就跟cookie没什么关系了呀。

**Comment by zhpoplar** [comment]
> 自定义 session 就跟cookie没什么关系了呀。

那是我理解错误？自定义session之后，后续操作session需要完全介入。
但是在api中直接session.xxx是可以正常保存到浏览器的。而且会调用自定义store的set方法。而在middleware中就不行

**Comment by czy88840616** [comment]
session.xxx是可以正常保存到浏览器的 -> 自定一周，session.xx 是保存在自定义 session store，调用 set 方法。

**Comment by czy88840616** [comment]
中间件，都放在 onReady 里加，不放在hooks 里?

**Comment by zhpoplar** [comment]
> 中间件，都放在 onReady 里加，不放在hooks 里?

请指教，这样做不对吗？hook该如何注入？
![image](https://user-images.githubusercontent.com/26213974/232735489-d59c3efc-6a4d-4ee5-9101-4bfc448f3c94.png)

**Comment by czy88840616** [comment]
没看出啥，除了用字符串获取实例可能会拿不到报错之外。
