### ISSUE TITLE
组件模版生成的初始项目中缺少 tsconfig.json

### ISSUE THREAD

**Issue by wflixu** [midwayjs/midway#2898]
* **Node Version**: v18.15.0
* **Midway Version(Decorator/Core)**: 3.11.4
* **Component Name/Version**:
* **Platform**: macos 13.3.1
* **Mini Showcase Repository**:

自定义组件，用npm init midway，选择 component-v3 模板。生成的模版目录中缺少tsconfig.json. .

![image](https://user-images.githubusercontent.com/37231473/233769980-033d1ac4-0c52-47e5-bd42-0c057add7a92.png)

**Comment by czy88840616** [comment]
发包的问题，现已处理，可以重新创建。
