### ISSUE TITLE
egg-graphql的connector无法从ctx上取到service

### ISSUE THREAD

**Issue by yuu2lee4** [midwayjs/midway#29]
```javascript
export default class CarConnector {
    ctx;
    mysql;
    redis;
    service;
    constructor(ctx) {
      this.ctx = ctx;
      this.mysql = ctx.app.mysql.get('g7tv');
      this.redis = ctx.app.redis;
      this.service = ctx.service.carDayCount;
    }

    fail(message: string | Error): Error  {
        if (typeof message === 'string') {
            return new Error(message);
        }
        return message;
    }
    getStatisticsInfo(args) {
        return this.service.getStatisticsInfo(args);
    }
    getCarStatusCount() {
        return this.service.getCarStatusCount();
    }
    async getCarCount({ ymd }) {
        const userinfo = await this.ctx.g7User();
        return this.service.findOne({
            ymd,
            orgroot: userinfo.orgroot,
        });
    }
}

```
这是egg里的写法 能从ctx上取到service。。。但midway这里就取不到。。

**Comment by czy88840616** [comment]
是的，egg 会在启动时扫描 service 目录， 强依赖目录结构，在加载时会构造实例，并且把上下文传入。 

```js
new Service(ctx);
```

而 midway 属于依赖注入，希望能尽量解耦，我们会把对象默认作为请求作用域存在 （scope = request)，ctx 会作为注入的对象。

而对应的，如果 app 上的对象是通过插件写的，那么也可以通过 plugin 装饰器来获取。

```ts
class Service {

  @inject()
  ctx;

  @plugin()
  mysql;

  @plugin()
  redis;

}
```

**Comment by yuu2lee4** [comment]
我上面那段代表是egg-graphql里的connector的写法，egg里是从ctx上取到service，在midway里这样取不到，用@inject('xxxService')也不行，现在不知道怎么取了 是用
````javascript
@inject()
ctx
````
就可以取到ctx，然后取到service？

**Comment by yuu2lee4** [comment]
```javascript
import { provide } from 'midway';
import BaseService from './base';

@provide()
export default class CityService extends BaseService {
}

export class CarConnector {
  @inject('cityService')
  service;

  getCarStatusCount() {
    return this.service.getCarStatusCount();
  }
}
```
试过这样不行 但是在controller上@inject('cityService')是可以的，有空了试试你那种

**Comment by czy88840616** [comment]
默认 midway 会扫描 src/app, src/lib 目录进行加载，不在这两个目录的话不行，可以提供个demo，我们看一下

**Comment by yuu2lee4** [comment]
https://github.com/yuu2lee4/midway_demo/tree/graphql   
npm run dev 之后 
打开http://127.0.0.1:7001/graphql
请求query test 会报错
具体代码在src/app/graphql/test/connector.ts

**Comment by czy88840616** [comment]
没有数据库本地还跑不起来demo。。

**Comment by yuu2lee4** [comment]
插件里把数据库注释掉就好了 我改一下吧

**Comment by czy88840616** [comment]
恩，我补一个graphql 的demo，看看怎么写方便。

**Comment by yuu2lee4** [comment]
现在是什么情况呢

**Comment by czy88840616** [comment]
😢补了一个数据库的demo，但是我对 graphql 没有很熟，还没写出来-。-

**Comment by yuu2lee4** [comment]
demo更新了 所有graphql非业务代码集中放在lib/plugin里了(其实是魔改egg-graphql)  业务代码都在src/app/graphql

**Comment by czy88840616** [comment]
好的，👍，主要是我们没有 graphql 的场景，有个demo真是太好了。

**Comment by yuu2lee4** [comment]
egg-graphql本身不支持加载ts文件 所以我们魔改了 
```
if (process.env.EGG_TYPESCRIPT === 'true') {
    return `${filename}.ts`;
  } else {
    return `${filename}.js`;
  }
```
在开发环境下 加载ts文件，生成环境会加载js文件，在egg的项目里运行良好
apollo是graphql的一个框架,也是egg-graphql的依赖
@Lellansin

**Comment by alex86w** [comment]
@yuu2lee4  请问是怎么处理的呢，不好意思egg 新手，有点不明白你上面的代码是配置在什么位置的呢

**Comment by alex86w** [comment]
@yuu2lee4  不好意思我是从egg 那边过来的，没注意这个是个新的框架，请问知道跟eggjs之间 有什么关联呢

**Comment by yuu2lee4** [comment]
@alex86w 看文档啊 这是基于egg的上层框架 去看看egg的框架开发文档

**Comment by czy88840616** [comment]
midway是在ts领域里做了增强，在现有egg框架的基础上，对全栈应用提供了可维护性的拓展。
yuri <notifications@github.com>于2018年11月5日 周一下午6:53写道：

**Comment by yuu2lee4** [comment]
@czy88840616  解决了？

**Comment by czy88840616** [comment]
这个是graphql的问题？那我看察了以为是数据那个，我reopen先。

**Comment by qgqceo** [comment]
请问demo-plugin-egg-graphql这个demo要怎么才能运行graphql那个测试界面？
文档里面没有提到这点。我在浏览器中运行http://127.0.0.1:7001/graphql和http://127.0.0.1:7001/graphiql都是404 Not Found。

**Comment by czy88840616** [comment]
@yuu2lee4 又仔细看了一下问题，终于理清了。

这里其实有好几个问题。。

- 1、egg-graphql 不支持 load ts 文件，所以我们 demo 里也是 graphql 目录下是 js，而普通的 service 是 ts
- 2、在 js 的 Connector 中如果想要使用别的 service 怎么办？

当初应该是问题 2 没理解。

**Comment by yuu2lee4** [comment]
哦  我正想说什么时候空了 整一下 按照你上回说的 getAsync来 @czy88840616

**Comment by yuu2lee4** [comment]
目前看来在midway下面的使用没啥问题，npm run build的时候把graphql目录拷贝过去就行了，长远看来，需要专门开发一个midway-graphql 采用依赖注入的方式 体验会比较好
