### ISSUE TITLE
模块“"../../../node_modules/midway/dist"”没有导出的成员“Middleware”。

### ISSUE THREAD

**Issue by yangcecode** [midwayjs/midway#290]
写路由中间件时候 直接复制粘贴文档的代码 提示
`
import { Middleware, WebMiddleware, provide } from 'midway';

@provide()
export class ApiMiddleware implements WebMiddleware {

  resolve(): Middleware {
    
  }

}
`

**Comment by czy88840616** [comment]
我看看是不是没导出。

**Comment by waitingsong** [comment]
应该有吧。我测试是正常的。

**Comment by czy88840616** [comment]
我测了最新的 v1.10.2 是有的，更新下依赖吧。

**Comment by yangcecode** [comment]
> 我测了最新的 v1.10.2 是有的，更新下依赖吧。

好的

**Comment by yangcecode** [comment]
更新依赖就没有问题了
