### ISSUE TITLE
midway-bin dev 模式下怎么支持ssl 自定义私钥和证书文件

### ISSUE THREAD

**Issue by Steppenwolf1900** [midwayjs/midway#2900]
![image](https://user-images.githubusercontent.com/22606801/233815786-3a848f25-1efe-41c8-806b-ccde3c19a90c.png)
目前看到可以使用```--ssl```快速启动https服务，但是不能自己指定证书，怎么才能```midway-bin dev```模式下，自定义私钥和证书来启用https服务呢

**Comment by czy88840616** [comment]
直接配置在 config.local 即可。https://midwayjs.org/docs/extensions/koa#https-%E9%85%8D%E7%BD%AE

**Comment by Steppenwolf1900** [comment]
Serverless 项目怎么配置呢

**Comment by Steppenwolf1900** [comment]
我们想在```package.json```中用类似```midway-bin dev --ssl --https.key=./ssl/key.pem --https.cert=./ssl/cert.pem```这种方式指定，目前能支持吗

**Comment by czy88840616** [comment]
serverless 因为 https 都在网关，且框架侧是没有 http 服务的，所以是不做支持的。

**Comment by Steppenwolf1900** [comment]
可是在开发、测试阶段我们有这样需要支持https的场景，而且现在已有```midway-bin dev --ssl```这种方式快速开启https服务，现在我们的需求是能自己指定证书文件，也很容易支持的，我提了一个pr https://github.com/midwayjs/midway/pull/2899
看是否可以支持一下

**Comment by czy88840616** [comment]
没有问题

**Comment by czy88840616** [comment]
@midwayjs/serverless-app@3.11.4
