### ISSUE TITLE
请问有计划升级 typescript 5.0 吗？

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#2909]
看了一下装饰器的变化挺大的，我的monorepo有部分依赖未来会升级 ts 5，不知道midway这边有计划何时升级不？

**Comment by waitingsong** [comment]
如果不修改 tsconfig.json 中 `"experimentalDecorators": true, ` 值，那么直接升级 ts 到 5.0 是没问题的。

**Comment by czy88840616** [comment]
业务用5是没有问题的，只要继续使用老的的decorator兼容即可。esm 和 ts5 的升级都是在计划内的。
