### ISSUE TITLE
一体化项目--测试后端service的问题

### ISSUE THREAD

**Issue by ColinChen2** [midwayjs/midway#2914]
* **Node Version**: 18.15.0
* **Midway Version(Decorator/Core)**: "@midwayjs/cli": "^2.0.15",
* **Component Name/Version**:
* **Platform**: mac
* **Mini Showcase Repository**:

现状：
测试后端service，但是却启动了整个前后端项目
<img width="926" alt="Screenshot 2023-04-27 at 11 27 25" src="https://user-images.githubusercontent.com/7310875/234752117-5a6a195c-675b-43ed-8062-5718f7804861.png">

期望：
希望测试能前后端分离，有配置会控制createAPP可以区分测试前端服务还是后端服务。

复现：

// test.js
```
import { createApp, closeApp, IMidwayKoaApplication } from '@midwayjs/test-util';
import { PromeService } from '../src/api/prome/service';

describe('test/prome/service.ts', () => {
    let app: IMidwayKoaApplication;

    beforeAll(async () => {
        const path = process.cwd();
        app = await createApp(path);
    });

    afterAll(async () => {
        await closeApp(app);
    });

    it('should put all metric', async () => {
        const prome = await app.getApplicationContext().getAsync<PromeService>(PromeService);
        const data = ...
        const response = await prome.putMetric(data);
        expect(response.status).toBe(204)
    })
})
```

// jest.config.js
```
module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    testPathIgnorePatterns:['/node_modules/'],
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1'
    }
}
```

// package.json
```
"test": "midway-bin test --ts"
```

**Comment by ColinChen2** [comment]
后来改成 testEnvironment: 'jsdom', 但是又会有其他问题。 

<img width="905" alt="Screenshot 2023-04-27 at 15 36 28" src="https://user-images.githubusercontent.com/7310875/234792710-ab2177d1-5d04-41a5-b268-49eb467fa68e.png">

比如这个Jose库，会有browser和nodejs的两种版本，它会自动选择成browser。而我们开始只想跑一下node端的service测试代码而已。

**Comment by czy88840616** [comment]
我理解要两份配置，一份 for 前端，一份 for node。

**Comment by ColinChen2** [comment]
@czy88840616 配置两个midway.config.ts? 有相关文档，例子吗？

**Comment by czy88840616** [comment]
jest的配置，jest 测试启动使用不同的配置。

**Comment by ColinChen2** [comment]
@czy88840616 但是问题又回来了，createApp（），一体化项目会前后端都启动。直接报document找不到的错误。。。
那就不用createApp这些方法了？

**Comment by czy88840616** [comment]
应该是可以的，我理解报错是因为执行到了前端目录，所以你在仅执行node代码的时候，需要排除，https://midwayjs.org/docs/container#%E8%87%AA%E5%8A%A8%E7%BB%91%E5%AE%9A

**Comment by plusl894860970** [comment]
现在这个问题有方案了吗？
