### ISSUE TITLE
serverless 使用this.ctx.cookies.set('key', 'value') 报错

### ISSUE THREAD

**Issue by Steppenwolf1900** [midwayjs/midway#2922]
使用`npm init midway`初始化一个serverless项目，在代码中设置cookie时报错
修改代码内容如下：
<img width="797" alt="image" src="https://user-images.githubusercontent.com/22606801/235120482-9e721bd3-e823-4bbb-8cf4-892e835f59be.png">
当请求接口时，报错信息如下：
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/22606801/235120067-5bc06823-354f-4539-a20c-6c40a731d91e.png">

**Comment by czy88840616** [comment]
配置里需要有一个 keys：xxx
