### ISSUE TITLE
@Param @query has some problems

### ISSUE THREAD

**Issue by ssly** [midwayjs/midway#2937]
* **Node Version**: 14.9.3
* **Midway Version(Decorator/Core)**: 3.11.6
* **Component Name/Version**: 
* **Platform**: Mac OS 13.3.1
* **Mini Showcase Repository**: 

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/24356145/236458219-4d0409e3-7552-4e3a-93f4-b66a448b52bf.png">

@Query @Queries @Param 有同样问题，获取到的均像是上下文
@Body使用一切正常

均参考[官网](https://midwayjs.org/docs/controller)使用

出问题的是@Get('/'),在 @Post('/') 下是正常的

**Comment by ssly** [comment]
方法必须是generator，async函数下才能生效

**Comment by waitingsong** [comment]
方法用 `async` 修饰
