### ISSUE TITLE
passport jwt 按照文档示例，中间件直接返回，controller无法执行

### ISSUE THREAD

**Issue by eleant001** [midwayjs/midway#2956]
按照官方文档通过passsport进行jwt验证
@Post('/passport/jwt', { middleware: [JwtPassportMiddleware] })
  async jwtPassport() {
    console.log('jwt user: ', this.ctx.state.user);
    return this.ctx.state.user;
  }
通过验证发现执行了中间件，并且已经验证了token
@Middleware()
export class JwtPassportMiddleware extends PassportMiddleware(JwtStrategy) {
  getAuthenticateOptions(): Promise<AuthenticateOptions> | AuthenticateOptions {
    return {};
  }
}
但是，在中间件这里的return{}直接返回了，controller里无法继续处理业务逻辑，找了好久不知道那里错了？？？？？？？？？？？

**Comment by hisunny520** [comment]
中间件不是await next吗？ 怎么是return

**Comment by eleant001** [comment]
> 中间件不是await next吗？ 怎么是return

官方文档就是这样

**Comment by hisunny520** [comment]
有没有一种可能是验证不通过才执行reutrn，通过next呢

**Comment by eleant001** [comment]
> 有没有一种可能是验证不通过才执行reutrn，通过next呢
试过了，验证通过 return{} ，不通过返回{"name": "UnauthorizedError",
        "code": "401",
        "status": 401}，按照官方文档的写法，进入controller前进入中间件，验证成功，return{}，这时根据洋葱模型应该在next（）回到controller，但是没有，直接return了，也就是controller没有得到执行

**Comment by czy88840616** [comment]
@hisunny520 @eleant001 ，getAuthenticateOptions 只是返回 passport 要求的验证配置，也就是成功或者失败的跳转之类的，实际的中间件逻辑都在继承的基类中。
