### ISSUE TITLE
在serverless项目中，使用@midwayjs/upload组件，上传文件后，内存一直增长并且不释放

### ISSUE THREAD

**Issue by Steppenwolf1900** [midwayjs/midway#2970]
在serverless项目中，使用@midwayjs/upload组件，上传文件后，内存增长后不释放，后面经过排查发现只要使用这个组件，请求了上传文件接口，即使接口不对文件做任何处理，也会导致内存增长不降，所以定位到是 upload组件的问题，按正常逻辑使用```stream```模式上传文件应该占用很小的内存，并且很快就能释放才行;

upload配置如下：
```
upload: {
    mode: 'stream',
    whitelist: null,
  }
```

Node Version: V16.15.1
 @midwayjs/core Version:  "^3.11.4",
 @midwayjs/faas Version: "^3.11.5",
 @midwayjs/upload Version: "^3.11.5"
Platform: Mac
Mini Showcase Repository: https://github.com/Steppenwolf1900/midway-test

目前已经使用在生产环境了，麻烦尽快排查一下，谢谢

**Comment by czy88840616** [comment]
我记得所有的 serverless 平台都不支持流式传输啊

**Comment by Steppenwolf1900** [comment]
<img width="1230" alt="image" src="https://github.com/midwayjs/midway/assets/22606801/ce4ab48e-13bb-4430-97fd-ff0c4cffb7ce">
我看文档上是写了的，总得有依据吧；
并且我也测了，就算不使用 stream 模式，使用 file 模式也有一样的问题，你可以测试一下

**Comment by czy88840616** [comment]
好的，我们看一下

**Comment by Steppenwolf1900** [comment]
请问定位到问题了吗

**Comment by czy88840616** [comment]
暂时还没有，函数环境的调试非常困难。

**Comment by zengshi** [comment]
我标准项目的windows的开发环境和centos的生产环境下也会有这个问题

前端用的Ant Design 的 upload 组件。

midway的config里面的的upload 的 mode 是 file

**Comment by czy88840616** [comment]
我用标准项目调试看看

**Comment by czy88840616** [comment]
使用标准项目测试
- 1、file 和 stream 模式测试上传 10M 文件，运行5w 次无明显内存异常
- 2、增加白名单拦截，使得所有上传文件都报错，同样运行上传 10m 文件 5w 次，无明显异常

**Comment by Steppenwolf1900** [comment]
https://github.com/Steppenwolf1900/midway-test
你可以就用这个仓库试试，详细步骤在readme里面，能看到内存明显飙升，并且一直不释放 @czy88840616

**Comment by czy88840616** [comment]
![image](https://github.com/midwayjs/midway/assets/418820/b1ea54b8-0f83-45b8-ab87-bc5ab4f85ea1)

上传 700M 文件，稳态后内存没有明显变化，在500-580 之间波动。

内存泄露是指内存长时间不释放，只会增加不会减少，如果维持在一个范围内这个不算内存泄露。如果你是说一开始从几十 M 变为500M，这个也没问题，因为 node 本身的内存机制就是如此，会根据当前机器内存获取一个比较合理的 heap 值，并不会说上传完从 500M 变为100m。

**Comment by czy88840616** [comment]
另外一块，faas 的 dev 是模拟的，和实际云上faas完全不一样，所以如果内存泄露，还是以云上监控为准。

**Comment by Steppenwolf1900** [comment]
但是我测的时候，文件只有600m，实际上一次上传就跑到了1300-1500m，是采用stream上传的，既然是流式的，按理说是不会跑到这么高的，而且我用nest框架+busboy也测了，同样的文件，我上传4、5次占用内存也只有100多m，并且很快就释放到初始值

**Comment by Steppenwolf1900** [comment]
我们就是因为在函数计算环境遇到内存的问题才提这个issue的，因为是采用stream上传，所以函数环境本身也不会配置那么高的内存，如果一上传稍微大一点的文件，内存就飚了，stream模式也就没有太大的意义了

**Comment by czy88840616** [comment]
函数的dev跟普通应用不一样是特地做了处理，由于函数是不支持文件流式上传的，所以是先把文件放到缓冲区存起来，再模拟了流的处理。

**Comment by czy88840616** [comment]
经测试。。fc 函数依旧不支持流式请求和响应。
