### ISSUE TITLE
自定义组件，文档是错的

### ISSUE THREAD

**Issue by tianxuzhang** [midwayjs/midway#2971]
* **Node Version**: v12.18.3
* **Midway Version(Decorator/Core)**:^3.0.0
* **Component Name/Version**:
* **Platform**:mac
* **Mini Showcase Repository**:

按文档操作初始化自定义组件仓库：https://midwayjs.org/docs/component_development

运行测试，直接报错
![image](https://github.com/midwayjs/midway/assets/4149550/f07c11a0-5136-404e-93a7-6635eaa92a5c)

**Comment by czy88840616** [comment]
![image](https://github.com/midwayjs/midway/assets/418820/2092a6f2-6506-448a-9ed5-03574d6b4c39)

我创建的没有问题，请检查环境。

**Comment by tianxuzhang** [comment]
node从12升级至14解决，node14才支持可选链语法。如果示例对环境有要求，建议文档上标注下

**Comment by waitingsong** [comment]
node版本太老了吧

**Comment by czy88840616** [comment]
jest 20 要求已经是14以上了，所以开发依赖必须是14以上了，运行时依赖还是12以上。

**Comment by czy88840616** [comment]
文档已在创建流程增加依赖提醒。
