### ISSUE TITLE
Processor 装饰器下的类出错没有日志输出

### ISSUE THREAD

**Issue by Yuliang-Lee** [midwayjs/midway#2984]
* **Node Version**: 18.14.0
* **Midway Version(Decorator/Core)**: 3.10.10
* **Component Name/Version**: 3.11.3
* **Platform**: linux
* **Mini Showcase Repository**: 

代码类似如下结构

```
// a.queue.ts
@Processor()
export class A Implements IProcessor {
  @Inject()
  bService: BService
}

// ./service/b.ts
import { HttpService } from '@midwayjs/axios'

@Inject()
export class B {
  @Inject()
  httpService: HttpService
}
```

这时候在 `configuration.ts` 里没有引入这个插件
```
import * as axios from '@midwayjs/axios'

@Configuration({
  imports: [web, orm, validate, bull, /* axios 缺少引入这个*/],
  importConfigs: [join(__dirname, './config')],
})
```

但是在 error.log 或 bull.log 里都没有看到报错日志，最终要去 redis 里看才能看到错误
<img width="851" alt="image" src="https://github.com/midwayjs/midway/assets/6936358/93bbb804-9b75-4b35-b75d-8c6c332a14a6">

很不方便定位问题。 这里错误日志能输出到 bull.log 或者 error.log 吗？

**Comment by czy88840616** [comment]
这个错应该启动就在 common-error.log 里了吧。。

**Comment by Yuliang-Lee** [comment]
本地启动，控制台没看到错误，common-error 也没看到
