### ISSUE TITLE
faas-v3  阿里云fc的生命周期怎么定义?

### ISSUE THREAD

**Issue by gopkg-dev** [midwayjs/midway#2985]
Initializer回调
初始化回调程序（Initializer回调）在函数实例启动成功之后，运行请求处理程序（Handler）之前执行。函数计算保证在一个实例生命周期内，成功且最多成功执行一次Initializer回调。例如，您的Initializer回调第一次执行失败后系统会重试，直到成功为止，然后再执行您的请求处理程序。

Initializer回调只有一个context输入参数，使用方法和事件请求处理程序一样。

一个最简单的Initializer回调如下所示。

exports.initialize = function(context, callback) {
  console.log('initializer');
  callback(null, "");
};
initialize是Initializer回调方法名，需要与您在[函数计算控制台](https://fcnext.console.aliyun.com/)配置的Initializer 回调程序一致。例如，您为函数配置的Initializer 回调程序为index.initialize，那么函数计算在配置Initializer属性后会去加载index.js中定义的initialize方法。

方法签名
输入参数只有context，为您的FC函数调用提供在调用时的运行上下文信息。
无返回值。
PreFreeze回调
预冻结回调程序（PreFreeze回调）在函数实例冻结前执行，方法签名同Initializer回调。

一个最简单的PreFreeze程序如下所示。

module.exports.preFreeze = function(context, callback) {
  console.log('preFreeze');
  callback(null, "");
};
PreStop回调
预停止回调程序（PreStop回调）在函数实例销毁前执行，方法签名同Initializer回调。

一个最简单的preStop程序如下所示。

module.exports.preStop = function(context, callback){
  console.log('preStop');
  callback(null, "");
}

**Comment by czy88840616** [comment]
初始化名为固定的 xxx.initializer 方法，是被框架生成代码包裹在内部，在平台填写的话，填的就是 “initializer” 方法，在其中会执行框架的 configuration.onReady 等，此外，不支持 PreFreeze/PreStop 等函数自己的生命周期。

**Comment by gopkg-dev** [comment]
了解了,谢谢
