### ISSUE TITLE
[docs] 文档 -->标准项目 --> 快速开始 中国中央气象台 API 报错

### ISSUE THREAD

**Issue by wflixu** [midwayjs/midway#3012]
* **Node Version**: v18.15
* **Midway Version(Decorator/Core)**: 3.11.6
* **Component Name/Version**:
* **Platform**: macos
* **Mini Showcase Repository**:

文档 -->标准项目 --> 快速开始 

weathService  使用的中国中央气象台 API ，实际项目中报错，这个例子是文档的开始，新手尝试就报错，很容易对项目产生不好的印象，是否能换一个稳定的API，或直接使用模拟数据。

![image](https://github.com/midwayjs/midway/assets/37231473/9a1b3069-e2ef-442d-b8c7-bfb4fd1c2279)

![image](https://github.com/midwayjs/midway/assets/37231473/1487d5ee-756d-4ef7-bef1-00d02011e0f8)

![image](https://github.com/midwayjs/midway/assets/37231473/7efcb9b8-4de6-48dc-ad8c-25e35d245529)

**Comment by czy88840616** [comment]
往下看有mock接口的部分，以应对接口失败的情况。

**Comment by conan221** [comment]
支持修正，如果一直都是错误的api，别人一看就会觉得Midway是不是快黄了，文档都没人维护了

**Comment by czy88840616** [comment]
已移除这个天气接口。
