### ISSUE TITLE
配置typeorm 执行迁移出现SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gulugulu-cy** [midwayjs/midway#3015]
* **Node Version**:v16.19.1
* **Midway Version(Decorator/Core)**:midway3.0 kaoV3
* **Component Name/Version**: 标准项目
* **Platform**:
* **Mini Showcase Repository**:

我运行npm init midway 创建一个全新的koa V3项目，tsconfig.json不做改变的情况下，直接根据平台的组件 typeorm  配置，执行迁移就会出现一下的错

query: SELECT * FROM current_schema()
Error during migration run:
E:\self\Website\backend\node_modules\typeorm\browser\decorator\entity\Entity.js:1
import { getMetadataArgsStorage } from "../../globals";
^^^^^^

SyntaxError: Cannot use import statement outside a module

我在以前的项目中是可以执行迁移，
这是我的迁移命令 npx mwtypeorm migration:run -d ./src/config/config.default.ts

**Comment by gulugulu-cy** [comment]
执行 npx mwtypeorm migration:run -d ./src/config/config.prod.ts，生产配置的不会出现上面的情况

**Comment by czy88840616** [comment]
一般来说是在非 ts 环境中跑了这个代码，这个需要完整的示例，不然是无法排查的。

**Comment by cyjake** [comment]
怎么跑的是 browser 版本，识别了 package.json 的 module 入口？试试把 node_modules/typeorm 加到 tsconfig include 里面好了

**Comment by gulugulu-cy** [comment]
> 一般来说是在非 ts 环境中跑了这个代码，这个需要完整的示例，不然是无法排查的。

这是我的案例代码https://github.com/gulugulu-cy/backend

**Comment by gulugulu-cy** [comment]
> 怎么跑的是 browser 版本，识别了 package.json 的 module 入口？试试把 node_modules/typeorm 加到 tsconfig include 里面好了

我也尝试过，也不行

**Comment by cyjake** [comment]
把 node_modules/typeorm 加到 compilerOptions.paths 或者 include 里面试试？

**Comment by rojer95** [comment]
![image](https://github.com/midwayjs/midway/assets/20662049/887c74a8-865f-4a6a-b081-282f3716edf2)
