### ISSUE TITLE
扩展context对象中调用this上的方法报错

### ISSUE THREAD

**Issue by yylgit** [midwayjs/midway#302]
示例仓库： https://github.com/yylgit/midway-error

**Comment by czy88840616** [comment]
原因：

- ioc 启动自动扫描所有 src 下的文件，因为文件内容是属性，自动被执行

解决方法：

- 1、可以将js的自定义插件挪到 src 外头
- 2、或者将 lib/plugin 排除在 ioc 扫描目录外

```ts
// config.default.ts

  config.container = {
    ignore: [
      './lib/plugin'
    ]
  }
```
