### ISSUE TITLE
在koa下，使用bull导致filter处理异常失效

### ISSUE THREAD

**Issue by yw-mao** [midwayjs/midway#3023]
* **Node Version**: 18
* **Midway Version(Decorator/Core)**: 3.11.10
* **Component Name/Version**: bull 3.11.10
* **Platform**: MacOS
* **Mini Showcase Repository**: https://github.com/yw-mao/midway-filter-bull-conflict

在加入bull组件后，throw出来的错误不被error filter捕获

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/req_res_app#main-application

**Comment by yw-mao** [comment]
> https://midwayjs.org/docs/req_res_app#main-application

大佬您好，我更新了下还是不太起作用
![image](https://github.com/midwayjs/midway/assets/88931049/3e2b4670-8d4f-4116-a439-9320efdb25db)

context还是没有经过DefaultErrorErrorFilter
![image](https://github.com/midwayjs/midway/assets/88931049/505d23c0-bcaa-4365-973a-538df1e53e81)

去除bull后，正常
![image](https://github.com/midwayjs/midway/assets/88931049/8437a260-9233-4177-b7c2-4ca863809a61)

是否还有哪里不对的地方，谢谢指导下

**Comment by czy88840616** [comment]
意思很清楚了呀，

**Comment by yw-mao** [comment]
> 意思很清楚了呀，你的 main framework 是 bull，所有的未显式指定的 app 就是 bull 的app，你的中间件和过滤器都加到bull上了呀。
> 
> @configuration({ imports: [ bull, koa, ] })

感谢 明白了，之前没仔细看说明
