### ISSUE TITLE
函数注入 provider 函数签名问题

### ISSUE THREAD

**Issue by nilptr** [midwayjs/midway#304]
providerWrapper 参数的 provider 方法签名为 (context?: IApplicationContext) => any 
所以说 provider 里不一定能获取到 context ？
![image](https://user-images.githubusercontent.com/16560775/62283552-62560c80-b484-11e9-8ce3-b94225c7cec0.png)

**Comment by czy88840616** [comment]
这个 context 是 IoC 容器。

**Comment by nilptr** [comment]
不是。我知道这个是 IoC 容器，provider 里应该确保能拿到 IoC 容器吧？那 context 参数的类型为什么是 IApplicationContext **| undefined** 呢？

**Comment by czy88840616** [comment]
这个是编译后，作为可选的定义生成出来的。

https://github.com/midwayjs/midway/blob/master/packages/midway-core/src/providerWrapper.ts

**Comment by nilptr** [comment]
在使用 providerWrapper 向容器注册函数时，provider 的 context 参数是获取依赖的唯一方式了。

因此对开发者来说，context 参数是一定要取到 IoC 容器的，不能是 undefined 。

```typescript
// context 不是一个可选参数
// 函数签名为 (context: IApplicationContext) => any
function contextHandler(context: IApplicationContext): any {
    const dep = context.get('dep');
    return function () {
        dep.doSomething();
        return true;
    };
}

providerWrapper([{
    id: 'contextHandler',
    provider: contextHandler,
}]);
```

IoC 框架也应该保证调用 provider 的时候不能传进 undefined 的。但是 [源码](https://github.com/midwayjs/midway/blob/master/packages/midway-core/src/providerWrapper.ts) 里，context 是一个可选参数：

```typescript
export function providerWrapper(wrapperInfo: Array<{
  id: ObjectIdentifier;
  provider: (context?: IApplicationContext) => any; // 等价于 (context: IApplicationContext | undefined) => any
  scope?: Scope;
  isAutowire?: boolean;
}>): void {
  for (const info of wrapperInfo) {
    Object.defineProperty(info.provider, FUNCTION_INJECT_KEY, {
      value: info,
      writable: false,
    });
  }
}
```

而在 TypeScript 里，`(context: IApplicationContext) => any` 是不能赋值给 `(context: IApplicationContext | undefined) => any` 的。这个类型提示会让开发者误解。

**Comment by czy88840616** [comment]
本来想着，这里可以放任意的返回值，比如直接一个回调，返回一个字符串，不过这样好像一样不大，强制有个 context 定义也没问题。

**Comment by nilptr** [comment]
说到底是 ts 类型的问题。返回值 any 没有问题。主要是 context 不能是可选参数，太容易让人误解了。
