### ISSUE TITLE
一体化方式，web中间件，可以封装为npm包吗

### ISSUE THREAD

**Issue by wzy2023** [midwayjs/midway#3048]
http://www.midwayjs.org/docs/hooks/middleware

我把某个中间件，写成单独的 npm 包后，

useContext()的返回值一直是 undefined

ps:
在这个单独的 npm 包里，也有安装一份 @midwayjs/hooks 和 @midwayjs/koa
是这个原因吗

**Comment by czy88840616** [comment]
一体化属于在用户代码测扩展的行为，在组件模块中无效，如需扩展，请使用标准的组件方式，标准的类写法。
