### ISSUE TITLE
midwayjs/cli v2.1.1 打包时 js文件丢失

### ISSUE THREAD

**Issue by pkjy** [midwayjs/midway#3052]
* **Node Version**: v16.19.1
* **Midway Version(Decorator/Core)**: v3.11.6
* **Component Name/Version**: 
* **Platform**: Macos 13.0
* **Mini Showcase Repository**:

ts项目里，夹杂着一些js文件。midwayjs/cli 版本1.3.20时，打包一切正常。版本升级到 2.1.1 打包后，js文件丢失了。

2.1.1打包如下图：
![2.1.1打包](https://github.com/midwayjs/midway/assets/14119424/3422d03f-0e8b-4ae3-8f4a-f29eedb309d5)

1.3.20打包如下图：
![1.3.20 打包](https://github.com/midwayjs/midway/assets/14119424/ebc973ce-4b43-4e19-ae34-2281575cf817)

**Comment by czy88840616** [comment]
非标功能，如需拷贝 js，请开启 tsconfig 中的 allowJs

**Comment by pkjy** [comment]
ok 感谢🙏
