### ISSUE TITLE
把依赖midway @plugin @inject的模块通过自定义脚本运行，有什么办法吗？

### ISSUE THREAD

**Issue by daduryi** [midwayjs/midway#308]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
https://midwayjs.org/injection/guide.html#%E5%BC%82%E6%AD%A5%E5%88%9D%E5%A7%8B%E5%8C%96

**Comment by daduryi** [comment]
不启动webserver情况下，运行脚本。inject拿到的是undefined
`
import { provide, inject, scope, ScopeEnum, controller } from 'midway';
import * as fs from 'fs';

async function sleep(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms);
    });
}

@provide('uModel')
export class UserModel {
    async get(userId: number) {
        await sleep(1000);
        return userId;
    }
}

@provide('user')
export class UserService {

    @inject('uModel')
    userModel: UserModel;

    async getUser(userId) {
        // const userModel = new UserModel();
        console.log(this.userModel);                       // undefined
        return await this.userModel.get(userId);
    }
}

(async function f() {
    const userService = new UserService();
    const user = await userService.getUser(1);
    console.log(user);
})();
`

**Comment by daduryi** [comment]
> https://midwayjs.org/injection/guide.html#%E5%BC%82%E6%AD%A5%E5%88%9D%E5%A7%8B%E5%8C%96

我需要把在不启动webserver时，完成这个脚本中getUser的运行 @init不起作用。
`js
import { provide, inject, scope, ScopeEnum, controller, init, Container, plugin } from 'midway';
import * as fs from 'fs';

async function sleep(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms);
    });
}

@provide('uModel')
export class UserModel {
    async get(userId: number) {
        await sleep(1000);
        return userId;
    }
}

@provide('user')
export class UserService {

    @inject('uModel')
    userModel: UserModel;

    @plugin('redis')
    redis;

    async getUser(userId) {
        console.log(this.userModel); 
        console.log(this.redis);
        return await this.userModel.get(userId);
    }
}
`

手动使用注册可以运行。redis插件怎么注册？
`
(async function createContainer() {
    // const userService = new UserService();
    const container = new Container();
    container.bind('user', UserService);
    container.bind('uModel', UserModel);

    const service: UserService = await container.getAsync('user');

    const user = await service.getUser(1);
    console.log(user);
})();
`

有没有其他方法在不启动webserver情况下，自动完成注册，并运行脚本？

**Comment by czy88840616** [comment]
可能你要的是这个? #203
