### ISSUE TITLE
elementtree安装后无法用

### ISSUE THREAD

**Issue by stlinjs** [midwayjs/midway#3100]
* **Node Version**:
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:
* **Mini Showcase Repository**:

* **Node Version**: v18.16.0
* **Midway Version(Decorator/Core)**:"@midwayjs/decorator": "^3.11.1",@midwayjs/core": "^3.11.1",
* * **Component Name/Version**:elementtree /  "@types/elementtree": "^0.1.1",
* * **Platform**:vscode
* * **Mini Showcase Repository**:swagger/@midwayjs/swagger": "^3.11.3",
*问题如下：
pnpm add --save @types/elementtree 后midway无法启动
configuration.ts中出现
import { ElementTree } from 'elementtree';
但是
@Configuration({
  imports: [ElementTree ]无法引入
node_modules\@types\elementtree\index.d.ts对类的输出是

export class ElementTree {
    constructor(element: Element);

    getroot(): Element;
    _setroot(element: Element): void;

    parse(source: string): Element;
    find(path: string): Element | null;
    findtext(path: string): ElementText | undefined;
    findall(path: string): Element[];
    write(options?: ElementTreeWriteOptions): string;
}
请问这个elementtree是不是不能用，还是我装的不好？还是引用的不好 ？

![417652dcea0f843fec9813dcdcdef95](https://github.com/midwayjs/midway/assets/32725175/32d8ddb4-2714-4df3-955d-dbb7e3f987db)

**Comment by czy88840616** [comment]
引入的包引起的错误，要么是ts类型错误，要么是类型检测错误，具体哪一种，看错误提示。

**Comment by czy88840616** [comment]
另外，imports: [ElementTree ] 没有这种用法，不要瞎用。
