### ISSUE TITLE
使用midwayjs的KeyCenter 加密解密redis password 密码还没解密 redis就注入报错了

### ISSUE THREAD

**Issue by mynamexjl** [midwayjs/midway#3103]
src/cache -> 实现了一个rediscache类
src/configuration.ts    在onConfigLoad中去密钥中心解密获取redis 密码替换到config上

问题 ：
  框架直接先实例化了redis  redis密码还未去解密 还未获取密码
  如果不通过 keycenterService 去获取redis密码  直接在config上配置密码的话 就不会有这个问题（业务场景不能将密码明文暴露）

错误提示：
  2023-07-24 14:10:20,561 ERROR 17656 [midway:redis] client error: Error: getaddrinfo ENOTFOUND r-8vb99504b715e5a4.redis.zhangbei.rds.aliyuncs.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'r-8vb99504b715e5a4.redis.zhangbei.rds.aliyuncs.com'

**Comment by mynamexjl** [comment]
[redis-err-demo.zip](https://github.com/midwayjs/midway/files/12142412/redis-err-demo.zip)
复现demo 代码

**Comment by czy88840616** [comment]
报错提示是网络问题，自行检查

**Comment by waitingsong** [comment]
`getaddrinfo` 多半是网络问题，比如域名解析失败
