### ISSUE TITLE
http-proxy 代理组件如何支持 intercept 拦截

### ISSUE THREAD

**Issue by chennyshan** [midwayjs/midway#3104]
* **Midway Version(Decorator/Core)**: 3.11.x
* **Component Name/Version**: http-proxy

如果用midway来创建网关server，通常需要使用http proxy功能来聚合背后的多个业务server。 我们该如何在代理请求转发之前、和之后做必要的拦截？比如转发之前做登录态校验，转发之后做response的结构体统一。

类似 http-proxy-middleware 2.x (https://github.com/chimurai/http-proxy-middleware) 中的 onProxyReq、onProxyRes 功能。谢谢

**Comment by chennyshan** [comment]
请问作者能给一点思路吗？个人尝试了两种途径，还没有完全成功：

途径1： 接入koa2中间件 [http-proxy-middleware 2.x](https://blog.csdn.net/weixin_44869002/article/details/120787964)，使用 onProxyReq、onProxyRes 达成拦截目的。写的中间件在 koa2 工程中能生效，但放到咱们的 midway-koa工程里，onProxyReq有回调、而代理请求却一直不返回，onProxyRes 始终没有回调。通过断点看起来是 http-proxy 库里的 proxyReq.on('response', function(proxyRes) {...}) 没有调用。。。 没有能力继续解决😭

途径2：参考 midway 中间件http-proxy 并自定义
在 async execProxy()函数中，我如何能够拦截并修改proxy返回的response呢？

**Comment by czy88840616** [comment]
流式直接转发没法做拦截吧
