### ISSUE TITLE
[Bug Report] Cannot resolve plugins in monorepo

### ISSUE THREAD

**Issue by meteorlxy** [midwayjs/midway#311]
## Description

If we put midway application into one of the workspace in yarn workspaces, midway cannot resolve egg plugins correctly.

For example:

- Project root dir: `/path/to/project-root`
- Midway application workspace: `/path/to/project-root/midway-workspace`
- `egg-onerror` is located in `/path/to/project-root/node_modules`

The error message:

```sh
Error: Can not find plugin egg-onerror in \
  "/path/to/project-root/midway-workspace/node_modules, \
   /path/to/project-root/node_modules/midway-web/node_modules, \
   /path/to/project-root/node_modules/egg/node_modules, \
   /path/to/project-root/midway-workspace/node_modules"
```

## Related code

https://github.com/midwayjs/midway/blob/7e23ec5ca4d156ba1d8dc2c6838c64b11876f8aa/packages/midway-web/src/loader/webLoader.ts#L63-L98

Following snippet could be a possible solution:

```js
try {
  const test = path.join(require.resolve(`${name}/package.json`), '../..')
  lookupDirs.push(test);
} catch (e) {}
```

## Related issue

- https://github.com/eggjs/egg/issues/3680

**Comment by czy88840616** [comment]
印象里我留了个口子，因为 midway 也是 lerna 开发的，碰到过这个问题。。。比如：https://github.com/midwayjs/midway/blob/master/packages/midway-mock/test/.setup.js#L4

**Comment by czy88840616** [comment]
#316
