### ISSUE TITLE
Use different bucket name for OSS trigger in different environments?

### ISSUE THREAD

**Issue by andantei** [midwayjs/midway#3111]
* **Node Version**: 16.x
* **Midway Version(Decorator/Core)**: 3.11
* **Component Name/Version**: Serverless Trigger
* **Platform**: ubuntu 22
* **Mini Showcase Repository**:  See code below.

Hi there, thanks for this amazing framework again. We ran into a problem with oss trigger bucket name configuration and hope someone would be able to help us.

We have two deployment environments, **staging** and **production**, each has its own bucket for the same purpose. Let's say staging triggers on bucket `stagingfilebucket`, and prod triggers on bucket `prodfilebucket`. The oss trigger handler looks like this:

```typescript
@Provide()
export class OSSTriggerService {
  @Inject()
  ctx: Context;

  @ServerlessTrigger(ServerlessTriggerType.OS, {
    bucket: 'stagingfilebucket', // <-- We want to be able to use different bucket name in different environments here.
    events: ['oss:ObjectCreated:*', 'oss:ObjectRemoved:DeleteObject'],
    filter: {},
  })
  async handleOSSEvent(ossEvent: FC.OSSEvent) {
    const successes = await Promise.all(
      ossEvent.events.map(evt => this.processOSS(evt.eventName, evt.oss.object.key)),
    );
    return {
      success: successes.every(s => s),
    };
  }
}
```

When running the deploy script, we encountered the following errors:
```
Deploy error: POST XXX failed with 400. requestid: XXX, message: event source 'oss' returned error: Cannot specify overlapping prefix and suffix with same event type..
```
Looks like it means we have two functions with oss triggers pointing to the same bucket. How can we config this oss trigger handler to trigger on different `bucket` in different enviroments? I know we have `@Config`, but that doesn't work inside `@ServerlessTrigger`.

**Comment by czy88840616** [comment]
It's difficult because property in the decorator are submitted to the serverless platform at build time, not at runtime.may be it can generate different yml file when use build, like 'xxx-prod.yml' and 'xxx-staging.yml'.
