### ISSUE TITLE
midway 怎么搞将 koa server 打包成一个 .exe 可执行程序？

### ISSUE THREAD

**Issue by zhuzeyu22** [midwayjs/midway#3118]
midway 怎么搞将 koa server 打包成一个 .exe 可执行程序？
我想要在 没有nodejs 的环境中执行

* **Node Version**: 14
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**: koa
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
https://midwayjs.org/docs/deployment#%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%96%87%E4%BB%B6%E9%83%A8%E7%BD%B2
