### ISSUE TITLE
swagger的@ApiHeaders装饰器只显示第一个

### ISSUE THREAD

**Issue by crx-96** [midwayjs/midway#3120]
@ApiHeaders([{ name: 'test1' }, { name: 'test2' }])
我设置了两个自定义属性，只有第一个生效，还有怎么样全局设置自定义header

**Comment by czy88840616** [comment]
![image](https://github.com/midwayjs/midway/assets/418820/1df1d975-196c-4694-9eb8-a96aab5d5a5c)

**Comment by czy88840616** [comment]
好像是有bug
