### ISSUE TITLE
路由内部转发怎么实现？

### ISSUE THREAD

**Issue by ritjc** [midwayjs/midway#3121]
在控制器A中定义路由 /a/a1，在控制器B中定义路由/b/b1, 如果想路由/b/b1 转发到 /a/a1， 这个怎么弄？

**Comment by czy88840616** [comment]
@Inject b...b.xxxxx(ctx)

**Comment by wangxiaogang94** [comment]
重定向

**Comment by ritjc** [comment]
> @Inject b...b.xxxxx(ctx)

//b.controller.ts
import { A } from './a.controller'
...
@Inject()
ac: A

@Post('/b/b1')
async postBb1(@body() args: any) {
  await this.ac.postAa1(args)
}
....

测试ok!

**Comment by ritjc** [comment]
> 重定向

如果是get请求复用路由，重定向是个好建议，也可考虑代理层（如nginx）做转发。

此场景是想在内部直接复用已定义好的接口，可以直接复用返回，也可以获取复用接口的返回值再进一步包装处理返回。

上面 @czy88840616 给的思路符合预期效果
