### ISSUE TITLE
ApiTags 似乎分组有问题

### ISSUE THREAD

**Issue by zhuzeyu22** [midwayjs/midway#3124]
同一个控制器里面的 ApiTags 如果不同，那么会出现两组 ApiTags ，里面都包含了控制器里面的所有 api

* **Node Version**:14
* **Midway Version(Decorator/Core)**:
* **Component Name/Version**:
* **Platform**:win10
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
指的是？ 有图示例么。

**Comment by czy88840616** [comment]
看了一眼，多个 tags 展示多遍是正常的，生成的 schema 没有问题， swagger 的展示就是这样。

**Comment by zhuzeyu22** [comment]
@czy88840616  想要的效果是 通过 tag 去做自定义分组，目前的效果是根据控制器去生成的分组，多个 tag 可能会重复多组。就是 tag 挂在 methed 上面似乎是异常的。

**Comment by czy88840616** [comment]
可以控制器不加，加在方法上的吧。
