### ISSUE TITLE
过滤器中使用i18n插件返回undefined

### ISSUE THREAD

**Issue by timi137137** [midwayjs/midway#3131]
* **Node Version**: v18
* **Midway Version(Decorator/Core)**: 3.11.15
* **Component Name/Version**: idk
* **Platform**: idk
* **Mini Showcase Repository**: idk

根据文档
![image](https://github.com/midwayjs/midway/assets/36812439/fe0943a5-5d8e-436d-90c8-10e38f27830f)

在Filter中使用以下代码尝试获取到翻译信息
```ts
@Catch()
export class DefaultErrorFilter {
  async catch(err: Error, ctx: Context) {
    const i18nService = await ctx.requestContext.getAsync<MidwayI18nService>(MidwayI18nService);
    ctx.logger.error(`\n${i18nService.translate('error.unknown')}: ${err.name} - ${err.message}\n${err.stack}\n`);

    return {
      code: 500,
      message: 'Internal Server Error',
    } as GenericErrorResponse;
  }
}
```

但实际上`i18nService.translate`方法固定返回了undefined
![image](https://github.com/midwayjs/midway/assets/36812439/59f09bbb-6b4f-4f64-85ef-6b8a65462d0b)

经过测试能直接获取到实例内容如下：
```ts
i18nServiceSingleton: MidwayI18nServiceSingleton {
    localeTextMap: Map(2) { 'en-us' => [Map], 'zh-cn' => [Map] },
    fallbackMatch: [],
    localeMatchCache: {},
    i18nConfig: [Getter],
    defaultLocale: 'zh-cn'
  },
  ctx: {
    request: { method: 'POST', url: '/api/auth/sign-out1', header: [Object] },
    response: {
      status: 404,
      message: 'Not Found',
      header: [Object: null prototype] {}
    },
    app: { subdomainOffset: 2, proxy: false, env: 'local' },
    originalUrl: '/api/auth/sign-out1',
    req: '<original node req>',
    res: '<original node res>',
    socket: '<original node socket>'
  }
}

```

使用`i18nService.getLocaleMapping('zh-cn')`、`i18nService.getLocaleMapping('zh_CN')`等各种大小写均返回undefined
插入一个自定义中间件可以获得配置
![image](https://github.com/midwayjs/midway/assets/36812439/474dffc9-26c9-49b3-a74c-4554c79622b4)
证明翻译文案读取并设置成功，因此实在没有头绪只能求助大家。希望解惑

**Comment by timi137137** [comment]
补充： 在中间件获取的`i18nService`服务同样返回undefined

**Comment by czy88840616** [comment]
如果没有返回，我理解就是没有匹配到合适的文案。

**Comment by czy88840616** [comment]
![image](https://github.com/midwayjs/midway/assets/418820/82908578-bb96-4c40-9cd5-9b4e8fe8452c)

**Comment by timi137137** [comment]
> ![image](https://user-images.githubusercontent.com/418820/258055113-82908578-bb96-4c40-9cd5-9b4e8fe8452c.png)

在上方已经截图给出all config，因此不存在没有匹配到合适的文案，并且使用getLocaleMapping方法返回的也是undefined，总不能说我连文案都没初始化吧？那挺匪夷所思的

**Comment by czy88840616** [comment]
你这是设置了不同的分组，error 是分组名，文本 key 是 unknown。。

你得

```ts
this.i18nService.translate('unknown', {
  group: 'error',        // 指定其他分组
});

```

**Comment by timi137137** [comment]
嗯...
确实如果这么看就可以用了
但是说句实话
在隔壁vue-i18n中，默认规则是语言下的属性即为key，如`message.hello`，对应的config是
```json
"zh_CN": {
    "message": {
        "hello": "你好，我的世界"
    }
}
```

像这种默认当成一个分组的情况实属闻所未闻，并非说必须人家怎么做就怎么做，而是最起码官方文档应该注明清楚，在[官方文档多语言描述](http://www.midwayjs.org/docs/extensions/i18n#%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%96%87%E6%A1%88%E5%88%86%E7%BB%84)中，只提到了
![image](https://github.com/midwayjs/midway/assets/36812439/61392ae6-d7ba-45cd-ac9a-185f66e6491d)

我只能知道并且只会认为在config中设定了分组引入了多个文案文件才会独立分组，而我下意识会以为我只有一个文案文件，那就默认会归类到default分组中，这一点就很迷惑。不是说必须要修改，只是说起码标注的更清楚一些。感谢帮助

**Comment by czy88840616** [comment]
不同的分组是为了让不同的组件可以隔离自己的文案，不然会重复。

**Comment by timi137137** [comment]
> 分组是为了让不同的组件可以隔离自己的文案，减少重复的发生。

i know，但是文档需要更清晰的指引
