### ISSUE TITLE
如何实现koa的router.all('/'）

### ISSUE THREAD

**Issue by qingfengpark** [midwayjs/midway#3134]
"@midwayjs/koa": "^3.0.0",
 "koa2-ueditor": "^1.1.3",

我想用ueditor，koa下是这样写的，
```ts
router.all('/editor/controller', ueditor(['public', { 
	"imageAllowFiles": [".png", ".jpg", ".jpeg"] ,
	"imagePathFormat": "/upload/ueditor/image/{yyyy}{mm}{dd}/{filename}" 
	}
]))
```
请问怎么实现上面的代码呢？

**Comment by czy88840616** [comment]
这货应该就是个 koa 中间件吧，可以全局 use， 也可以单独加在路由上。

![image](https://github.com/midwayjs/midway/assets/418820/a9df3c7c-85e0-4708-957c-d82fee122f1f)
