### ISSUE TITLE
midway-ts-boilerplate incremental配置疑问

### ISSUE THREAD

**Issue by dewfall123** [midwayjs/midway#314]
midway-ts-boilerplate  里`tsconfig.json`包含配置
```
"incremental": true,
"tsBuildInfoFile": ".vscode/.tsbuildinfo"
```
在第二次npm run build的时候会由于-c删除原dist内容，导致dist无输出。
有-c 清理dist逻辑的话，是不是应该去掉`"incremental": true,`?

**Comment by waitingsong** [comment]
是的，如果仅删除 dist 内容 会导致下次 tsc build 我输出。
这个 https://github.com/midwayjs/midway/pull/309

**Comment by czy88840616** [comment]
我现在发一下：）

**Comment by czy88840616** [comment]
发好了
