### ISSUE TITLE
sequelize-auto-midway 生成实体类后，调用sql 时候报错

### ISSUE THREAD

**Issue by zzwex** [midwayjs/midway#3147]
{"errcode":1000,"msg":"Model not initialized: Member \"findAndCountAll\" cannot be called. \"reportEntity\" needs to be added to a Sequelize instance."}

**Comment by czy88840616** [comment]
提供更详细代码。

**Comment by zzwex** [comment]
1.首先使用 sequelize-auto-midway 逆向生成实体类后 如：reportEntity
2. 执行 await reportEntity.findAndCountAll()后，就提示如下：
    Model not initialized: Member "findAndCountAll" cannot be called. "reportEntity" needs to be added to a Sequelize instance."

**Comment by czy88840616** [comment]
这我也看不出啊。。你得提供代码啊。。

**Comment by zzwex** [comment]
`import { Column, DataType, Table, Model } from 'sequelize-typescript';

@Table({
  tableName: 'statistics_quarter',
  timestamps: false,
  indexes: [
   {
    name: "PRIMARY",
    unique: true,
    using: "BTREE",
    fields: [
     { name: "id" },
    ]
   },
   {
    name: "uq_year_quarter_appid",
    unique: true,
    using: "BTREE",
    fields: [
     { name: "year" },
     { name: "quarter" },
     { name: "app_id" },
    ]
   },
  ]
})
export class StatisticsQuarterEntity extends Model {
  @Column({
   autoIncrement: true,
   type: DataType.INTEGER,
   allowNull: false,
   primaryKey: true,
   comment: "主键"
  })
  id: number;
}`

**Comment by zzwex** [comment]
`import { Inject, Provide } from '@midwayjs/decorator';
import { ReportDTO } from "../dto/report.dto"
import { StatisticsQuarterEntity } from "../sequelize/entity/statisticsQuarter.entity"

@Provide()
export class ReportService {

    async getReportList(reportDTO: ReportDTO) { 

         await StatisticsQuarterEntity.findAndCountAll()
        
    
    }

    
}
`

**Comment by czy88840616** [comment]
config的配置代码，这些 entity 都是在配置里配置了才加载进去的。

**Comment by zzwex** [comment]
其他 都是 midway 自带，没有更改

**Comment by czy88840616** [comment]
我需要看你的数据源配置怎么写的。

**Comment by czy88840616** [comment]
没有 entities 配置啊，而且结构好像也不对

**Comment by zzwex** [comment]
确实没有，好的 ，我看看
