### ISSUE TITLE
midway 3.9 不支持 node 12

### ISSUE THREAD

**Issue by zhuzeyu22** [midwayjs/midway#3148]
yarn 安装依赖时出错

error triple-beam@1.4.1: The engine "node" is incompatible with this module. Expected version ">= 14.0.0". Got "12.22.12"
error Found incompatible module.

因为需要支持在 windows 7  环境下运行，所以需要降低版本至 node 12，然后发现不太支持，安装依赖报错

* **Node Version**:  12.22.12
* **Midway Version(Decorator/Core)**: 3.9.0
* **Component Name/Version**:
* **Platform**: windows11
* **Mini Showcase Repository**:

**Comment by MarquisVIP** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by waitingsong** [comment]
可以试用 midway v2。
node12 早就不维护了
https://github.com/nodejs/release#release-schedule

**Comment by czy88840616** [comment]
triple-beam 应该是 logger winston 中的依赖，可以自行锁包到低版本。
