### ISSUE TITLE
写了一篇，midway 介绍文。

### ISSUE THREAD

**Issue by shenqidebaozi** [midwayjs/midway#315]
https://juejin.im/post/5d4d02d2e51d4561ab2be9b1

**Comment by waitingsong** [comment]
不错

**Comment by czy88840616** [comment]
👏 我看看怎么整理个新闻合集

**Comment by shenqidebaozi** [comment]
> 新闻
可以鸭嘿嘿嘿。可以搞个官方的 blog，然后定期收录一些文章? 也可以作者自己提交一个PR？然后官方合并

**Comment by shenqidebaozi** [comment]
> 👏 我看看怎么整理个新闻合集

可以鸭嘿嘿嘿。可以搞个官方的 blog，然后定期收录一些文章? 也可以作者自己提交一个PR？然后官方合并

**Comment by shenqidebaozi** [comment]
现阶段，midway 的文章还是比较少的

**Comment by czy88840616** [comment]
恩，因为我们近一年也没宣传，干活为主。。

**Comment by thierryxing** [comment]
👍我们也刚刚把一个 Eggjs 项目整体用 Midway 重构，和楼主的情况很类似。

**Comment by shenqidebaozi** [comment]
> 👍我们也刚刚把一个 Eggjs 项目整体用 Midway 重构，和楼主的情况很类似。

我司还没重构，未来可能这个项目也不会改，因为有个核心功能，估计不会随便重构

**Comment by terenceyhj** [comment]
Midway是不是所为的eggjs的3.0？

**Comment by czy88840616** [comment]
虽然两边很熟，但是的确不是...

**Comment by waitingsong** [comment]
@terenceyhj  midway 是基于 eggjs 扩展的开发框架。

**Comment by czy88840616** [comment]
#339
