### ISSUE TITLE
如何在midway 使用jest ?

### ISSUE THREAD

**Issue by skmdev** [midwayjs/midway#318]
https://github.com/eggjs/examples/tree/master/unittest-jest

我按照`eggjs` 的例子去integrate jest, 但似乎由於midway的關係並未能讀取controller, config等file 而出現`can't get [] before ready`
```
  ● test/app/controller/health.test.ts › should assert

    can't get config before ready

      4 | describe('test/app/controller/health.test.ts', () => {
      5 |   it('should assert', async () => {
    > 6 |     assert(app.config.keys.startsWith(pkg.name));
        |                ^
      7 |     // const ctx = app.mockContext({});
      8 |     // await ctx.service.xx();
      9 |   });

      at Object.get (node_modules/egg-mock/lib/app.js:189:36)
      at Object.it (test/app/controller/health.test.ts:6:16)
```

之後我發現使用原生的`midway-bin test` 能夠先自動讀取file, 所以又改了一下 `bootstrap.ts`, 但沒有作用
```
import assert from 'power-assert';
import { mm as mock } from 'midway-mock/dist';

const options = {
  typescript: true,
};

const app = mock.app(options);

beforeAll(() => app.ready());

afterEach(mock.restore);

export { assert, app, mock };
```

請問現在有辦法integrate jest 嗎?

**Comment by waitingsong** [comment]
要换测试框架估计得折腾一番。

**Comment by czy88840616** [comment]
我测试一下。

**Comment by czy88840616** [comment]
这是一个使用 jest 的例子。https://github.com/midwayjs/midway-examples/tree/support_jest/demo-unittest-jest

我翻看了 jest 的文档，本想用[这篇文章](https://medium.com/airbnb-engineering/unlocking-test-performance-migrating-from-mocha-to-jest-2796c508ec50)里的方法兼容，使用了 setupFiles 和 globalSetup，都无法在 global 上挂载 beforeAll 方法，所以暂时没办法直接使用 `midway-mock/boostrap`。

如果有好的办法，也可以帮忙 pr。

**Comment by skmdev** [comment]
剛checkout 了貌似一樣結果
```
$ node -v
v10.15.0
```
<img width="1328" alt="Screenshot 2019-08-14 at 1 07 12 AM" src="https://user-images.githubusercontent.com/31434614/62961739-ecf91d00-be2f-11e9-882b-dade0598e61d.png">

**Comment by skmdev** [comment]
剛才又試了一次
如果先build 再test 才能成功, 暫時未知原因

```
// step
yarn build
yarn test
```

**Comment by czy88840616** [comment]
因为 ts-jest 貌似机制不一样，我用 `require.extensions['.ts']` 没判断到 ts 环境，就走了 dist

**Comment by skmdev** [comment]
> 因为 ts-jest 貌似机制不一样，我用 `require.extensions['.ts']` 没判断到 ts 环境，就走了 dist

照道理會options 會overwrite 你的default value
```
// midway-mock/dist/index.js :27

 return mock.app(Object.assign({
        framework: options.framework || 'midway',
        typescript: !!require.extensions['.ts'],
    }, options));
```

**Comment by czy88840616** [comment]
不，内部还有一个判断是走 src 目录还是 dist 目录的判断。不管怎么改，jest 的 require 似乎都是新的对象，导致判断失败。

**Comment by skmdev** [comment]
剛才又試了一下，具體位置在 `midway-web/src/loader/webLoader.ts` 對嗎?
不過就算by pass了`isTypeScriptEnvironment()`, 在egg底層`egg-core/lib/utils/index.js` 的`loadFile()` 也是根據`extensions` 去讀取file, 所以根本問題是`ts-jest` 的`extensions`?

**Comment by czy88840616** [comment]
是的。。我也跑到了 egg-core 的 `!Module._extensions[extname] ` 这里，没有 .ts 的话，读出来就会变成 Buffer。

ts-jest 的机制看起来是用 typescript transform 成了 js。

**Comment by skmdev** [comment]
看來暫時沒辦法用jest 了

**Comment by heavenkiller2018** [comment]
都2020年了， 还没法使用jest吗？
