### ISSUE TITLE
对于midway加上swagger-doc编写文档一直报prototype是undefined

### ISSUE THREAD

**Issue by Aqincheng** [midwayjs/midway#319]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
应该还是加了controller doc的问题。

**Comment by Aqincheng** [comment]
> 应该还是加了controller doc的问题。

我如何修改呢，我只是在midway框架加上egg-swagger-doc来写文档

**Comment by Aqincheng** [comment]
> 应该还是加了controller doc的问题。
还有就是我用的是ts

**Comment by czy88840616** [comment]
https://github.com/midwayjs/midway-examples/tree/master/demo-plugin-egg-swagger-doc 这里有个例子，但是加上 controller doc 似乎就会报错了。

**Comment by Aqincheng** [comment]
> https://github.com/midwayjs/midway-examples/tree/master/demo-plugin-egg-swagger-doc 这里有个例子，但是加上 controller doc 似乎就会报错了。

有什么好的解决办法吗？这个例子我下载下来安装完依赖npm run dev都运行不起来

**Comment by Aqincheng** [comment]
我可以加一下你的微信或者qq，探讨一下这个问题

**Comment by czy88840616** [comment]
@czy88840616 微信单聊我吧

**Comment by kurten** [comment]
可以更新一下例子，我这边已经修复了问题

**Comment by czy88840616** [comment]
image
![image](https://user-images.githubusercontent.com/418820/63142115-0f02c300-c01b-11e9-9f80-5be810b2678a.png)

如果出现 Cannot read property 'prototype' of undefined 的问题，是因为插件中对 ts 的处理，比如通过 default 导出。

export default class xxxController {

}
