### ISSUE TITLE
关于程序退出时 SIGINT 信号的处理咨询

### ISSUE THREAD

**Issue by xnng** [midwayjs/midway#3190]
我正在使用 pm2 的优雅重启功能
https://pm2.keymetrics.io/docs/usage/signals-clean-restart/

我需要拦截 SIGINT 信号，做一个延迟退出，等待异步任务处理完成后再退出进程

这是我想要实现的效果

<img width="581" alt="image" src="https://github.com/midwayjs/midway/assets/38936252/c4db9660-6191-45eb-880b-39e6d2609158">

但是我看日志发现一接到信号就立即退出了，看了下源码是接了这个信号后立即退出了

<img width="637" alt="image" src="https://github.com/midwayjs/midway/assets/38936252/47282bbf-6e24-4e75-98ee-8e5cfee6b455">

请问这个 SIGINT 信号有没有办法让我自己处理

**Comment by czy88840616** [comment]
你看看能不能直接 removeListener，再自己加一个。

**Comment by xnng** [comment]
非常感谢，在 onStop 里等是符合预期的
