### ISSUE TITLE
typescript5.2 dev调试错误，自动修改的module与moduleResolution配置不兼容

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#3198]
ts5.2会严格要求tsconfig里的`module`与`moduleResolution`配置一致。
但是midway的调试会自动把用户 tsconfig 的 module 改回 commonjs，导致 typescript 编译报错。
https://github.com/midwayjs/cli/blob/ccc07cc6b397c697e90e4c30e7d003594b468dd4/packages/cli-plugin-dev/src/index.ts#L539

```
start error: ⨯ Unable to compile TypeScript:
error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.
```

建议不要再更改用户的tsconfig配置了，项目模板的配置能调试就行了，后面用户自己想怎么就怎么改。

**Comment by czy88840616** [comment]
用 esm 脚手架https://github.com/midwayjs/midway-boilerplate/tree/master/v3/midway-framework-koa-esm/boilerplate

**Comment by pilaoda** [comment]
> 用 esm 脚手架https://github.com/midwayjs/midway-boilerplate/tree/master/v3/midway-framework-koa-esm/boilerplate

我用的也不是esm啊，只是moduleResolution需要node16.

**Comment by czy88840616** [comment]
可以尝试使用 esm 的工具体系，我们在计划逐步迁过去，原有的因为一些适配前端代码的关系不是很好调整。

比如 dev 使用：
```
"dev": "cross-env NODE_ENV=local mwtsc --watch --run @midwayjs/mock/app",
```

**Comment by pilaoda** [comment]
可以调试了，以后编译也用`mwtsc`，不再用midway-bin了吗？
这里的 esm 具体是指的什么，package.json需要改成`"type": "module"`吗？
不太想把整个monorepo都改成 esm，编译出来的文件还是支持 commonjs 的项目 require 的吧？

**Comment by czy88840616** [comment]
编译是 tsc，dev 是 mwtsc，其实是同一个东西。如果没有 esm 需求可以保持现状，目前 midway 暂时还是以 commonjs 为主，工具链不区分 esm 还是 commonjs。

**Comment by pilaoda** [comment]
看了一下mwtsc源码，所以现在是完全不需要 ts-node 了吗？

**Comment by waitingsong** [comment]
> 可以调试了，以后编译也用`mwtsc`，不再用midway-bin了吗？ 这里的 esm 具体是指的什么，package.json需要改成`"type": "module"`吗？ 不太想把整个monorepo都改成 esm，编译出来的文件还是支持 commonjs 的项目 require 的吧？

node 模块目前多数是 cjs/esm 都编译发布，少数是纯 esm 编译发布。不过趋势是纯 ESM 模块。
而 cjs 项目是无法直接引入纯 esm 模块的（有变通方式加载不过麻烦）。
可以考虑逐步迁移了。
