### ISSUE TITLE
这个问题有计划修复吗 过去半年了

### ISSUE THREAD

**Issue by maodajie** [midwayjs/midway#3202]
这个问题有计划修复吗 过去半年了
![image](https://github.com/midwayjs/midway/assets/74534430/4f545f03-3037-4954-9304-e4ad955b09a5)

**Comment by czy88840616** [comment]
之前已经给方案了，直接用 tsc 即可。后续 midway-bin 也将逐渐都替换成 tsc，不再维护一套工具。

**Comment by maodajie** [comment]
懂了懂了 我以为是临时解决方案
