### ISSUE TITLE
"outDir": "dist" 必须是dist目录嘛 修改后报错 koa-v3-esm

### ISSUE THREAD

**Issue by maodajie** [midwayjs/midway#3206]
"outDir": "dist" 必须是dist目录嘛 修改后报错 koa-v3-esm
```
E:\nodejs\midway\node_modules\.pnpm\@midwayjs+mock@3.12.3\node_modules\@midwayjs\mock\dist\creator.js:162
                throw new Error(`Can not get main framework, please check your ${getFileNameWithSuffix('configuration')}.`);
                      ^

Error: Can not get main framework, please check your configuration.js.
```

**Comment by czy88840616** [comment]
这个目前是写死了，后面看看怎么放开吧。

**Comment by czy88840616** [comment]
最新版已经支持修改输出目录， tsconfig.json 中的 outDir 修改即可。

**Comment by muyetuge** [comment]
> 最新版已经支持修改输出目录， tsconfig.json 中的 outDir 修改即可。

有个小问题  outDir修改后  第一次dev报错找不到configuration 第二次dev正常

**Comment by czy88840616** [comment]
报错堆栈看看？

**Comment by muyetuge** [comment]
> 报错堆栈看看？

比如outDir改为build  然后删除build和dist文件夹 重新dev就会这样
默认情况下直接把dist改为build是没问题的 会直接生成build目录
`D:\Development\midway-project\node_modules\.pnpm\@midwayjs+mock@3.14.11\node_modules\@midwayjs\mock\dist\creator.js:166
                throw new Error(`Can not get main framework, please check your ${getFileNameWithSuffix('configuration')}.`);
                      ^
Error: Can not get main framework, please check your configuration.js.
    at create (D:\Development\midway-project\node_modules\.pnpm\@midwayjs+mock@3.14.11\node_modules\@midwayjs\mock\dist\creator.js:166:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createApp (D:\Development\midway-project\node_modules\.pnpm\@midwayjs+mock@3.14.11\node_modules\@midwayjs\mock\dist\creator.js:180:23)
    at D:\Development\midway-project\node_modules\.pnpm\@midwayjs+mock@3.14.11\node_modules\@midwayjs\mock\app.js:18:9`

**Comment by czy88840616** [comment]
已修复 @muyetuge
