### ISSUE TITLE
Bull 的定时任务在某个环境中并没有定时执行

### ISSUE THREAD

**Issue by grapewheel** [midwayjs/midway#3211]
* **Node Version**:  16..17 和 18.7
* **Midway Version(Decorator/Core)**: 3.8.0
* **Component Name/Version**: @midwayjs/bull 3.12.1
* **Platform**: Linux
* **Mini Showcase Repository**: 暂无

```
@Processor('transferMoneyRequest', {
	repeat: {
		cron: '0 0 8 * * *',
	},
})
```
设置了Bull的定时任务，出现以下情况：
1. 在本地用dev环境模式正常执行
2. 在本地用pm2 cluster 2个进程 dev环境模式正常执行
3. 在远程用pm2 cluster 2个进程 pro环境模式**不执行**
4. 远程已经完全重启服务，相关组件都已经安装，无报错，就是到点不执行
5. 远程服的node版本是16.17，本地node是18,7，本地node切换到16.17可以正常执行
6. 执行代码并没有任何 dev 和 pro 环境之分的判断
7. 使用bull 的 context 上下文环境附带的 logger记录日志，却无任何日志输出或者记录
8. 手写了一个controller手动触发这个任务，本地和远程都是可正常触发

很奇怪，为何远程并没有到点执行定时任务？

**Comment by czy88840616** [comment]
检查远端环境机器时区？

**Comment by grapewheel** [comment]
> 
远程服务器时区信息（国内服务器）：
      Local time: Thu 2023-08-31 14:00:18 CST
  Universal time: Thu 2023-08-31 06:00:18 UTC
        RTC time: Thu 2023-08-31 14:00:17
       Time zone: Asia/Shanghai (CST, +0800)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: yes

Warning: The system is configured to read the RTC time in the local time zone.
         This mode can not be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.

**Comment by grapewheel** [comment]
> 检查远端环境机器时区？
远程服务器还挂有另一个nodejs的服务，那个服务也有定时任务，那个服务定时是正常执行的，所以我感觉是midwayjs本身原因

**Comment by grapewheel** [comment]
@czy88840616 
```
import { Context, IProcessor, Processor } from '@midwayjs/bull'

@Processor('transferMoneyRequest', {
	repeat: {
		cron: '0 15 14 * * *',
	},
})
export class TransferMoneyRequest implements IProcessor {
    @Inject()
    ctx!: Context

    async execute() {
          this.ctx.logger.info('开始处理转账...') // 实际上本地和远程都没有记录日志，无论是手动或者自动执行任务
    }
}
```

没有任务日志，我根本无法跟踪是什么原因导致出错或者不执行

**Comment by czy88840616** [comment]
我没法告诉你为什么不执行，任务调度依靠 bull + redis 本身。

有可能是环境问题（时区不对），也有可能是使用问题（同一个任务只要有一台机器的一个线程接收执行了，就算执行了，其他机器是不会收到消息的）

成功记录都在 redis 中，可以在 redis 的记录中查找。

**Comment by grapewheel** [comment]
@czy88840616 
时区不对应该可以排除，本地和远程时区一样，远程只有一台机器2个线程一个log文件，手动执行的成功记录在redis中可查到，就是没有定时执行的记录～ 真的非常奇怪，本地我已经完全模拟远程环境都可以定时执行

**Comment by czy88840616** [comment]
redis的时区？

**Comment by grapewheel** [comment]
> redis的时区？

@czy88840616 
远程默认没设置过，我试下手动设置，本地redis也是默认的

**Comment by grapewheel** [comment]
@czy88840616 
经过测试并不是时区问题，而是redis的版本问题，本地redis版本是7.0, 远程的redis版本是3.0，@midwayjs/bull 的repeat装饰器对低版本的redis并不起作用，而要在configuration.ts里面手动调用带有repeat参数的runJob，才能在低版本redis启动定时任务，没有成功启动定时任务前，redis中并没有下图中的repeat目录
![1693637798273](https://github.com/midwayjs/midway/assets/490426/c0f29772-c40d-4940-9141-5a5f49f76d19)

低版本redis，必须如下手动启动
```
export class MainConfiguration {
	@Bull.InjectQueue('transferMoneyRequest')
	queue!: Bull.BullQueue

	async onServerReady() {
		await this.queue.runJob(
			{},
			{
				repeat: {
					cron: '0 0 8 * * *',
				},
			}
		)
	}
}
```

**Comment by czy88840616** [comment]
这个。。。我的确没想到。。

**Comment by grapewheel** [comment]
@czy88840616 兄弟，5年前架设的服务器，redis只是用于key-value短暂存储，为了稳定，不会随意升级的，搞了我半天，终于发现问题了，还好手动启动也可以

**Comment by czy88840616** [comment]
应该是 bull 初始化和添加走的 lua 脚本不是同一个，初始化可能某些参数低版本的 redis 不支持。

**Comment by grapewheel** [comment]
嗯，你看看要不要加入说明提示，或者修复，这个情况是比较特殊

**Comment by czy88840616** [comment]
我可以加个 tip。
