### ISSUE TITLE
一体化Vue模板不支持复杂动态类型推导吗？

### ISSUE THREAD

**Issue by WzyisWeb** [midwayjs/midway#3212]
/**
* 自动生成pinia入口文件
*/
import { ToRefs } from 'vue';
import userStore from '@/store/user';

const storeMap = {
  user: userStore,
} 

export function $useStore<T extends keyof typeof storeMap>(storeName: T) {
  const store = storeMap[storeName]()
  const storeRefs = storeToRefs(store)
  /**
   * ReturnType 获取函数类型，返回类型
   * ToRefs<ReturnType<typeof storeMap[T]>> 加上调用提示
   */
  return {...store,...storeRefs }  as ToRefs<ReturnType<typeof storeMap[T]>>
}

在vue页面中使用
import {$useStore} from'@/store/index'
const { tabArr } = $useStore('user')

tabArr 报错 类型“ToRefs<Store<string, {}, {}, {}>>”上不存在属性“tabArr”。ts(2339)

这个方式在uniapp 跟 vue3 项目中是正常使用，一体化不行。

**Comment by czy88840616** [comment]
这个我不知道。。我们不用 vue。。。

**Comment by WzyisWeb** [comment]
复杂的动态类型推导，你们那边用是正常的吗？

**Comment by WzyisWeb** [comment]
复杂的动态类型推导，你们那边用是正常的吗？

**Comment by czy88840616** [comment]
目前没有使用很复杂的推导。

**Comment by WzyisWeb** [comment]
那没办法了，只能改代码了。没事了
