### ISSUE TITLE
使用midway写的项目可以在阿里云serverless中部署吗？

### ISSUE THREAD

**Issue by zwl1619** [midwayjs/midway#322]
使用midway写的项目可以在阿里云serverless中部署吗？
如果有一些限制，那么什么情况下可以部署，什么情况不能部署？

**Comment by czy88840616** [comment]
serverless 会稍微有一些不一样，比如在长连接，缓存，数据库等方面，serverless 就需要慎重。serverless 下应该有特定的 js-sdk。
