### ISSUE TITLE
typeorm中的listeners不生效

### ISSUE THREAD

**Issue by MineFurjiko** [midwayjs/midway#3225]
[https://github.com/typeorm/typeorm/blob/master/docs/listeners-and-subscribers.md#entity-listeners-and-subscribers](url)
typeorm文档中有listeners，我写了个实体的基类，想实现ID的唯一和可排序（因为需要跨网同步）。
基类定义：
![image](https://github.com/midwayjs/midway/assets/23348616/04b73514-f237-4dd6-9547-e8617fa67105)

实例化代码：
![image](https://github.com/midwayjs/midway/assets/23348616/d7eab244-3eca-42ca-ba6b-31bf9f70d969)

***********************************************************************************
**但是测试过程中，@BeforeInsert装饰的generateUUID方法始终没有工作！！！！**
***********************************************************************************

不知道什么原因。

顺便提一句：Event Subscriber方式中的beforeInsert是可以工作的。

**Comment by czy88840616** [comment]
我无法告知原因，这部分的代码是typeorm 自身的能力。

**Comment by MineFurjiko** [comment]
![image](https://github.com/midwayjs/midway/assets/23348616/2ac2d818-619d-413b-8a78-c6116df9629d)

经过再次测试，发现BeforeInsert这些钩子通过上图第一种形式 save一个类的实例才能触发。

那只能通过Event Subscriber来兼容各种形式的save了。
