### ISSUE TITLE
logger组件产生的日志文件权限为600(rw-------)

### ISSUE THREAD

**Issue by chennyshan** [midwayjs/midway#3226]
* **Node Version**: node 16.14.2
* **Midway Version(Decorator/Core)**:3.12.0
* **Component Name/Version**: logger, pm2
* **Platform**: centos

logger组件打印出的日志文件，在centos上默认权限是 rw-------，导致查看时较麻烦。请问如何能赋予默认权限 666？
已知：使用 pm2 管理工具

**Comment by czy88840616** [comment]
为啥会查看麻烦？日志创建应该是使用当前用户来做的，应该不存在执行的需求吧。

**Comment by chennyshan** [comment]
> 为啥会查看麻烦？日志创建应该是使用当前用户来做的，应该不存在执行的需求吧。

实际场景是运维部门以root启动服务，并生成log。而分配给我们的账号是普通用户，如果log文件权限是rw-------, 那我们就读不了。
不存在执行，只是想拥有“读”权限

**Comment by czy88840616** [comment]
@midwayjs/logger@2.18.0

配置里可以加一个 fileOptions，默认值是 { flags: 'a'}，你可以自己传递想要的东西。
