### ISSUE TITLE
请教如何修改query或者Queries序列化

### ISSUE THREAD

**Issue by willcong** [midwayjs/midway#3246]
前端用的umijs@4，GET 请求参数序列化格式是  a: [1,2,3] => a[]=1&a[]=2&a[]=3，后端取到的参数是a[]:[1,2,3]，并不是a:[1,2,3]，midway@3这边如何调整，还是只能前端调整？

**Comment by czy88840616** [comment]
正常的请求，变数组应该是 a=1&a=2 => a: [1,2] 这种吧

**Comment by willcong** [comment]
好的，了解了，谢谢
