### ISSUE TITLE
midway 不定时worker异常退出

### ISSUE THREAD

**Issue by caixiayangdd01** [midwayjs/midway#325]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

2019-08-28 06:00:56 | logger:project-clearing-settlement-system stream:stdout kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:2019-08-27 22:00:56,085 INFO 94 in typescript current dir change to /srv/dist @timestamp:2019-08-28 06:00:56 _id:7xUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -
-- | --

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at Object.onceWrapper (events.js:317:30) @timestamp:2019-08-28 06:00:55 _id:6hUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: @timestamp:2019-08-28 06:00:55 _id:7hUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:name: "AppWorkerDiedError" @timestamp:2019-08-28 06:00:55 _id:6xUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:pid: 40 @timestamp:2019-08-28 06:00:55 _id:7BUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:hostname: clearing-settlement-system-6d47f46c8d-7s4pt @timestamp:2019-08-28 06:00:55 _id:7RUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at Messenger.send (/srv/node_modules/egg-cluster/lib/utils/messenger.js:102:12) @timestamp:2019-08-28 06:00:55 _id:5RUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at ChildProcess.worker.process.once (internal/cluster/master.js:191:13) @timestamp:2019-08-28 06:00:55 _id:6RUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at Master.emit (events.js:211:7) @timestamp:2019-08-28 06:00:55 _id:4xUY1WwBAwrXYVbTsdZb_type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at emitThree (events.js:141:20) @timestamp:2019-08-28 06:00:55 _id:5xUY1WwBAwrXYVbTsdZb_type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at EventEmitter.emit (events.js:217:7) @timestamp:2019-08-28 06:00:55 _id:6BUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at Master.onAppExit (/srv/node_modules/egg-cluster/lib/master.js:411:21) @timestamp:2019-08-28 06:00:55 _id:4RUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at emitOne (events.js:116:13) @timestamp:2019-08-28 06:00:55 _id:4hUY1WwBAwrXYVbTsdZb_type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at Messenger.sendToMaster (/srv/node_modules/egg-cluster/lib/utils/messenger.js:137:17)@timestamp:2019-08-28 06:00:55 _id:5BUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message: at EventEmitter.cluster.on (/srv/node_modules/egg-cluster/lib/master.js:280:22) @timestamp:2019-08-28 06:00:55 _id:5hUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stdout kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:2019-08-27 22:00:54,902 INFO 40 [master] app_worker#1:56 disconnect, suicide: false, state: disconnected, current workers: ["1","3","4"] @timestamp:2019-08-28 06:00:55 _id:3RUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27_score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stdout kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:2019-08-27 22:00:54,902 INFO 40 [master] app_worker#4:94 start, state: none, current workers: ["1","3","4"] @timestamp:2019-08-28 06:00:55 _id:3hUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:2019-08-27 22:00:54,902 ERROR 40 nodejs.AppWorkerDiedError: [master] app_worker#1:56 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: ["3","4"] @timestamp:2019-08-28 06:00:55 _id:4BUY1WwBAwrXYVbTsdZb _type:fluentd_index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:[2019-08-27 22:00:54.898] [cfork:master:40] worker:56 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: false) @timestamp:2019-08-28 06:00:55 _id:2xUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:[2019-08-27 22:00:54.901] [cfork:master:40] new worker:94 fork (state: none) @timestamp:2019-08-28 06:00:55 _id:3BUY1WwBAwrXYVbTsdZb _type:fluentd _index:project-all-v2-2019.08.27 _score: -

  | 2019-08-28 06:00:55 | logger:project-clearing-settlement-system stream:stderr kubernetes.container_name:clearing-settlement-system kubernetes.host:ip-192-168-248-229.ap-southeast-1.compute.internal index:project-all-v2 log#message:[2019-08-27 22:00:54.902] [cfork:master:40] worker:56 exit (code: null, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: true, worker.disableRefork: false) @timestamp:2019-08-28 06:00:55 _id:3xUY1WwBAwrXYVbTsdZb _type:fluentd_index:project-all-v2-2019.08.27 _score: -

没有捕获到其他异常日志，求教大神

**Comment by waitingsong** [comment]
日志有两处，一个是全局的 logs 目录下，另外一个是项目名目录

**Comment by czy88840616** [comment]
这里看不出什么，看看其他比如common-error里的

**Comment by caixiayangdd01** [comment]
> 日志有两处，一个是全局的 logs 目录下，另外一个是项目名目录

我项目的根目录是clearing-settlement-system，我在这个目录下有个logs目录，里面包含各种类型的日志，是你说的全局logs目录吧，项目名目录，没看到有日志文件。

**Comment by waitingsong** [comment]
项目目录下的 logs 目录保存的是开发调试阶段（ npm run dev|debug）的日志。
生产环境（npm start）的日志是在 %userprofile% 下面的。

**Comment by caixiayangdd01** [comment]
> 项目目录下的 logs 目录保存的是开发调试阶段（ npm run dev|debug）的日志。
> 生产环境（npm start）的日志是在 %userprofile% 下面的。

class RedactConsoleTransport extends ConsoleTransport {
  public log(level, args, meta) {
    const str = util.format.apply(null, args)
    // redact data
    const re = /mongodb.*:\/\/\S+/
    const redactStr = str.replace(re, 'mongodb+srv://[REDACTED]')

    return super.log(level, [redactStr], meta)
  }
}
public configWillLoad(): void {
    this.app.getLogger('coreLogger').set(
      'console',
      new RedactConsoleTransport({
        level: 'INFO',
      })
    )
    this.app.getLogger('logger').set(
      'console',
      new RedactConsoleTransport({
        level: 'INFO',
      })
    )
  }
我的理解是日志都被转到console上了，所有的日志都被K8S收集了，所以没有额外的日志了，这个是理解错了么？
另外，我 有加全局的异常捕获，也有没有捕获到异常日志。
config.onerror = {
    all(err: BaseError, ctx: Context) {
      ctx.logger.error('onerror catched', util.inspect(err).replace(/\n/g, ''))
      ctx.body = err.data
      ctx.status = err.statusCode
    },
  }
日志除了一下配置没有其他的了：
config.logger = {
    disableConsoleAfterReady: false,
  }
这个worker异常时不时发生，程序运行到一半异常退出，重新运行（同样的任务，同样的数据，同样的环境）又没有问题，不知道从哪里查起了。
想请教下，如果是内存问题被Kill的，midway会记录日志么？

**Comment by waitingsong** [comment]
个人理解 egg 内置的 logger 在生产环境下是不会输出控制台的，而是写文件.

**Comment by czy88840616** [comment]
如果是直接 kill 话，应该不会有日志，这个时候就得还原现场，看日志最后的记录，做 coredump 等。比如上 alinode 什么的。。

**Comment by caixiayangdd01** [comment]
> 个人理解 egg 内置的 logger 在生产环境下是不会输出控制台的，而是写文件.

我们现在是用K8S+Docker，程序异常退出后，会重新启动Docker，这样会丢失日志文件。想请教下，我们能设置日志文件的位置么？另外有个疑问，现在的服务都容器化了，日志都定向到标准输出再收集分析。Midway把一部分日志只能写文件，不能重定向到标准输出的设计初衷是啥？

**Comment by czy88840616** [comment]
可以换日志输出位置，其实midway提供的是一套类似 spring 的ioc 机制，本质上日志这些能力还是egg提供的。。

**Comment by czy88840616** [comment]
由于长期没更新，close 此 issue，后续如有需求，可以再 open。
