### ISSUE TITLE
计划做脚手架改造

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#326]
- 1、用 light-generator 替换原本的 egg-init 的机制，和未来的 midway-faas 使用同一种机制
- 2、脚手架包分开维护，每个脚手架将发布到 npm，midway-init 只留一个 json 指向包，这样脚手架包不一定在同一个仓库，可以分别维护
- 3、应该可以彻底解决 windows 生成不了脚手架的问题了。。。
- 4、内外脚手架合并，不会再出现内部使用外部脚手架的问题了 #263

**Comment by terenceyhj** [comment]
还有个建议就脚手架能方便 应用VUE!!!

**Comment by czy88840616** [comment]
@terenceyhj 应用vue？集成 vue 的脚手架？

**Comment by terenceyhj** [comment]
是的

**Comment by czy88840616** [comment]
我们这边好像写 vue 的特别少。。所以也没啥实践。。

**Comment by terenceyhj** [comment]
您的前端解决方案是。。。？

**Comment by ZQun** [comment]
@terenceyhj 直接用前后端分离呀

**Comment by czy88840616** [comment]
改造完毕。

**Comment by waitingsong** [comment]
那我可继续更新模板了哈

**Comment by czy88840616** [comment]
嗯
