### ISSUE TITLE
redis存取速度慢，请问是否需要配置redis连接池信息

### ISSUE THREAD

**Issue by Logan80s** [midwayjs/midway#3264]
* **Node Version**:
* **Midway Version(Decorator/Core)**:3.12.4
* **Component Name/Version**:16.20.1
* **Platform**:
* **Mini Showcase Repository**:

请问在1000+并发的情况下，redis需要手动设置配置参数吗，比如说连接池的配置，目前压测看来redis读取存取速度比较慢最慢的13+秒

**Comment by czy88840616** [comment]
我们无法回答调优相关的问题，这个跟所在的网络环境，数据大小，调用方法以及 redis 版本等都有关系。
