### ISSUE TITLE
package.json main 希望能指定文件全名，包括扩展名

### ISSUE THREAD

**Issue by pilaoda** [midwayjs/midway#3265]
https://github.com/midwayjs/midway/blob/349c169fbff7aa07102754c1d0b95d2c5b304b3a/packages/decorator/package.json#L5
例如这里改成`dist/index.js`。
有一些库使用`main`时不支持省略扩展名，例如`tsconfig-paths`：https://github.com/dividab/tsconfig-paths/issues/254

**Comment by czy88840616** [comment]
好的。
