### ISSUE TITLE
midway中使用egg-socket.io无法获取到service

### ISSUE THREAD

**Issue by GuiaLiang** [midwayjs/midway#327]
* **Node Version**:
v10.16.3
* **Midway Version**:
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
v4.1.6
* **Platform**:
* **Mini Showcase Repository**:
// app/io/controller/user.ts
module.exports = (app: Application) => {
  class Controller extends app.Controller {
    async getUser() {
      const { io } = app;
      const nsp = io.of('/chat');
      const message = this.ctx.args[0];
      // 无法获得到service
      // const say = await this.service.userTest.say();
      nsp.emit('res', 'say');
    }
  }
  return Controller;
};
// app/service/userTest.ts
import { Application } from 'midway';

module.exports = (app: Application) => {
  class UserTest extends app.Service {
    async say() {
      return 'Hello Man!';
    }
  }
  return UserTest;
};

**Comment by czy88840616** [comment]
恩，拿不到 ioc 的 service，因为 socket 那个类不在 ioc 中，可以用 `await ctx.requestContext.getAsync('userTest');` 拿

**Comment by GuiaLiang** [comment]
> 恩，拿不到 ioc 的 service，因为 socket 那个类不在 ioc 中，可以用 `await ctx.requestContext.getAsync('userTest');` 拿

之前看了关于egg-graphql的issue，尝试过去使用this.ctx.requestContext.getAsync，但是console这个是undefined，请问是还需要什么配置的吗？

**Comment by czy88840616** [comment]
https://github.com/midwayjs/midway-examples/blob/master/demo-plugin-egg-socket-io/src/app/io/controller/chat.ts#L5

**Comment by GuiaLiang** [comment]
感谢大佬指导~
