### ISSUE TITLE
midway的在run目录生成大量文件，几天就有好几百个了。

### ISSUE THREAD

**Issue by lovelytan** [midwayjs/midway#3272]
midway的在run目录生成大量文件，这个可以配置吗？为什么不覆盖，而是带上戳呢，几天就有好几百个了。

<img width="328" alt="image" src="https://github.com/midwayjs/midway/assets/17985841/c19d6f34-7be1-4242-92c8-c1ef1b28a7c0">

<img width="341" alt="image" src="https://github.com/midwayjs/midway/assets/17985841/e5025eac-37e1-467f-a44f-f54eeee3f26c">

_Originally posted by @lovelytan in https://github.com/midwayjs/midway/discussions/3223_

**Comment by czy88840616** [comment]
非 midway 输出，是egg的功能。
