### ISSUE TITLE
按照官方示例使用@midwayjs/http-proxy代理不成功

### ISSUE THREAD

**Issue by Steppenwolf1900** [midwayjs/midway#3284]
如题，我们需要代理一个接口，按照官方提供的示例，出现404的情况，最小仓库地址：***https://github.com/Steppenwolf1900/midway-faas-http-proxy-test***
<img width="945" alt="image" src="https://github.com/midwayjs/midway/assets/22606801/f69bb0b1-f609-4752-b3a3-f90d422743f7">

**Comment by czy88840616** [comment]
faas不支持流式代理。

**Comment by Steppenwolf1900** [comment]
<img width="1242" alt="image" src="https://github.com/midwayjs/midway/assets/22606801/dbd50425-4b45-48b7-aec4-b0bd6f8a9bd9">
能否调整一下官方文档对faas支持的情况，包括faas不支持流式文件上传这些。避免其他人也会遇到像我们调研跟实际落地不一样的情况

**Comment by czy88840616** [comment]
感谢，faas 不支持主要是faas平台层面的不支持，并非框架本身，对于建议，文档在涉及到流式处理的地方新增了提示。

**Comment by Erchoc** [comment]
> 感谢，faas 不支持主要是faas平台层面的不支持，并非框架本身，对于建议，文档在涉及到流式处理的地方新增了提示。

有同样的疑问，普通 faas 场景 http 请求代理不生效，而且 `@midwayjs/http-proxy` 这个库是没有开源么？
