### ISSUE TITLE
三方认证文件需根目录访问验证

### ISSUE THREAD

**Issue by hisunny520** [midwayjs/midway#3312]
项目运行 127.0.0.1:7001 , 静态文件默认开放public ，现有第三方认证文件需根目录访问验证，
现有v.txt文件。
如何通过 127.0.0.1:7001/public/v.txt 转为 127.0.0.1:7001/v.txt 路径，

**Comment by czy88840616** [comment]
![image](https://github.com/midwayjs/midway/assets/418820/43dfe4d8-d70b-46eb-bbd7-5ff241feec42)
