### ISSUE TITLE
运行npm run build后dist目录文件经常生成不完整

### ISSUE THREAD

**Issue by hanfei0501** [midwayjs/midway#333]
* **Node Version**: 11.6.0
* **Egg Version**:  
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Mac OS
* **Mini Showcase Repository**: 

运行npm run build后dist目录文件经常生成不完整，必须先运行npm run clean后才可以正常生成。

**Comment by czy88840616** [comment]
是因为开了增量编译的缘故，已经对脚手架做了紧急处理，可以照着改一下。https://github.com/midwayjs/midway/pull/332/files

**Comment by waitingsong** [comment]
不好意思，看来这个配置坑了不少同学 😂

**Comment by hanfei0501** [comment]
原来是这样的，修改完后现在可以了，谢谢～

**Comment by wsdqr001** [comment]
> 是因为开了增量编译的缘故，已经对脚手架做了紧急处理，可以照着改一下。https://github.com/midwayjs/midway/pull/332/files
> 
> 同时把 `tsconfig.json` 里的 incremental 删除。

这么修改完后，启动不成功了。。。
[egg-scripts] Wait Start: 87...
[egg-scripts] Wait Start: 88...
[egg-scripts] Wait Start: 89...
[egg-scripts] Wait Start: 90...
[egg-scripts] Wait Start: 91...
[egg-scripts] Wait Start: 92...
[egg-scripts] Wait Start: 93...

**Comment by waitingsong** [comment]
@wsdqr001  试试
- 删除 `dist` 目录
- 执行 `npm run build`
- 测试 `npm run dev`

**Comment by wsdqr001** [comment]
> @wsdqr001 试试
> 
> * 删除 `dist` 目录
> * 删除 `.vscode/` 目录下存在的 .tsbuildinfo 文件
> * 执行 `npm run build`
> * 测试 `npm run dev`

npm run dev没问题，npm start无法启动
