### ISSUE TITLE
导入 midway-mock/bootstrap 后，编译时提示 Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by xcatliu** [midwayjs/midway#337]
* **Node Version**: v10.16.0
* **Egg Version**: 2.23.0
* **Plugin Name**: midway-mock
* **Plugin Version**: 1.11.1
* **Platform**: MacOS
* **Mini Showcase Repository**: 见下面的代码

```ts
import { app } from 'midway-mock/bootstrap';
```

当导入了 midway-mock/bootstrap 后，执行 `midway-bin build -c`，会提示以下错误：

```bash
node_modules/midway-mock/src/index.ts:41:41 - error TS2532: Object is possibly 'undefined'.

41     if (process.env.MIDWAY_BASE_DIR && !options.baseDir) {
                                           ~~~~~~~

node_modules/midway-mock/src/index.ts:42:9 - error TS2532: Object is possibly 'undefined'.

42         options.baseDir = process.env.MIDWAY_BASE_DIR;
           ~~~~~~~
```

原因是我的 tsconfig.json 配置了 `"strictNullChecks": true,`，在导入 `midway-mock/bootstrap` 时，会找到 `node_modules/midway-mock/bootstrap.d.ts` 文件，而这个文件引用了 `'./src'`：

```ts
import * as assert from 'power-assert';
import { MidwayMock, MidwayMockApplication } from './src';

export { assert };
export declare const app: MidwayMockApplication;
export declare const mock: MidwayMock;
export declare const mm: MidwayMock;
```

导致执行 `midway-bin build` 时会去用我的 tsconfig 配置来编译 `midway-mock/src/index.ts`，我的 tsconfig 配置比 midway-mock 的更加严格，故报错了。

### 建议的解决方案

将
```ts
import { MidwayMock, MidwayMockApplication } from './src';
```
改为
```ts
import { MidwayMock, MidwayMockApplication } from './dist';
```
这样就不会用我的 tsconfig 重新编译 `src` 下的文件了

**Comment by waitingsong** [comment]
我这儿相同strict设置，没有报错呢。

**Comment by waitingsong** [comment]
提个复现代码库？

**Comment by xcatliu** [comment]
https://github.com/xcatliu/midway-mock-test

**Comment by waitingsong** [comment]
tsconfig.json 增加:
```json
  "include": [
    "src/**/*.ts"
  ],
```

**Comment by waitingsong** [comment]
另外，建议使用 eslint 替换已快废弃的 tslint .
配置可以参考这个  https://github.com/waitingsong/midway-base

**Comment by xcatliu** [comment]
我就是需要用到 midway-mock/bootstrap 这个库做一些自动化的事情，所以需要编译这条语句：

```ts
import { app, assert } from 'midway-mock/bootstrap';
```

**Comment by waitingsong** [comment]
https://github.com/waitingsong/midway-base/blob/master/test/app/home/home.test.ts#L3

**Comment by xcatliu** [comment]
我更新了下我的复现仓库，把 test 目录加到了 exclude 里面了。
但是我的需求就是 src 目录下需要用到 `midway-mock/bootstrap`

**Comment by xcatliu** [comment]
https://github.com/xcatliu/midway-mock-test/blob/master/src/someUtil.ts

**Comment by xcatliu** [comment]
回到这个问题，`midway-mock/bootstrap.js` 作为一个可以供其他地方引用的模块，它的类似声明文件 `midway-mock/bootstrap.d.ts` 不应该再去引用 `src` 下的未编译的内容，而应该引用 `dist` 下的已编译好的类型声明文件。

不然其他地方引用 `midway-mock/bootstrap.js` 的时候，会重新编译一次 `src/index.js`

**Comment by waitingsong** [comment]
@343   #343 修复了此问题。请等待新版本发布。

**Comment by czy88840616** [comment]
已经发布。
