### ISSUE TITLE
midway-init ant-pro-design 无法安装peer dependencies

### ISSUE THREAD

**Issue by timyilong** [midwayjs/midway#338]
npm 6.11.3
node v12.9.1
peer dependenies
![image](https://user-images.githubusercontent.com/54894402/65499877-ebbc1500-def0-11e9-812b-b86618f35b81.png)

在package.json 中加了 peerDependencies, remove node_modules 也没有成功。

**Comment by tw93** [comment]
我看一下

**Comment by wwwmewww** [comment]
我也有这个问题，tw93 看的咋样了？

**Comment by tw93** [comment]
重新试试，已经发布1.1.6版本，升级到了antd4
同时warnning可以先不管，不影响使用
