### ISSUE TITLE
monorepo 下的几个问题

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#341]
## 问题一

```
"start": "egg-scripts start --daemon --title=egg-server-midway-base --framework=midway --ts --workers=4",
```
egg-scripts 不支持往上查找框架，如果 lerna 采用了 hoist 模式，会碰到找不到 midway 的问题。

![image](https://user-images.githubusercontent.com/418820/65827111-6ace9600-e2c1-11e9-9da1-e5a3c22bb008.png)

## 问题二

如果依赖里没有 typescript，似乎启动时不会传递 typescript 参数，导致 midway 切换目录失败。（待测试）

表现为扫描到了 ts 文件。

![image](https://user-images.githubusercontent.com/418820/65828436-82ac1700-e2cd-11e9-8956-3ceb0c13ce7d.png)

根本原因在于入口传递的 options 参数不同，少了 typescript 参数。

![image](https://user-images.githubusercontent.com/418820/65828507-2269a500-e2ce-11e9-8264-9312aef3c710.png)

```
但是经过测试，在非 monorepo 下是正常的。
```

**Comment by czy88840616** [comment]
补充，排查后发现，问题二的原因为 egg-scripts 走的为框架提供的 startCluster 方法，没有透传 typescript 参数。

非 monorepo 的仓库，因为 midway 额外做了判断，查找了当前的依赖中包含了 typescript，则自动进入 typescript 模式，而 monorepo 下找不到。。所以就报错了。

**Comment by waitingsong** [comment]
问题一我认为不是问题： 
 子模块肯定会在  `dependencies` 依赖中添加 `midway` ，而不会在顶层中添加。否则在子模块中执行 `npm i --prod` 就没有 midway ，那么发布出去也是无法运行的（不可能是整个 mono repo 目录发布）

**Comment by waitingsong** [comment]
问题二，之前我的 PR
https://github.com/midwayjs/midway/pull/255
https://github.com/midwayjs/midway/pull/255/commits/35576df89a5f747ba94b9d9648ad1c435f5bef84
