### ISSUE TITLE
插件测试 

### ISSUE THREAD

**Issue by bobohuochai** [midwayjs/midway#345]
* **Node Version**:
10.16.3
* **Egg Version**:
egg@^2.20.0
* **Plugin Name**:

* **Plugin Version**:
* **Platform**:
mac
* **Mini Showcase Repository**:

测试目录 和 egg-plugin 模版一样，
tsconfig.json 
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "declaration": false, 
    "inlineSourceMap": false,
    "module": "commonjs",
    "noImplicitAny": false,
    "noImplicitThis": false,
    "noUnusedLocals": false,
    "target": "ESNEXT"
  },
  "include": [
      "**/*.ts"
  ],
  "exclude": [
    "asset/",
    "node_modules*",
     "**/*.d.ts",
     "**/*.spec.ts"
  ]
}

但运行test 的时候报如下错误：
No test files found with test/**/*.test.ts,!test/fixtures,!test/node_modules

没有地方配置过!test/fixtures，不知道怎么上传截图。

**Comment by waitingsong** [comment]
这个貌似有问题
```
"include": [
"/.ts"
],
```
应该是没有匹配的测试用例，于是mocha认为是失败。
你改成 
```
"include": [
"test/**/*.ts" 
],
```
试试看

**Comment by bobohuochai** [comment]
上面 我传的是test/**/*.ts ，不知道为什么显示这样了。
谢谢这么及时回答。我找到问题了，我的目录结构还是错了。。。
不过为什么midway-init 的时候没有一个plugin 的选项呢，建议加一个哈。

**Comment by czy88840616** [comment]
因为 midway 没设计插件的部分，是直接复用了 egg 的插件，然后发现用 ts 写 egg 插件由于目录结构 js和ts混合在一起不是很优雅，就尽量不用 ts 写插件复用了，而换成了 ioc 的机制，使用纯粹的 npm 包来复用了。。

**Comment by bobohuochai** [comment]
好吧，懂你们的意思了。 那我把问题关了。

**Comment by czy88840616** [comment]
😁

**Comment by waitingsong** [comment]
也可以按照常用 ts 方式（src）编写，不过编译目录改为根就行了，只是编译后的文件看着有点别扭。
比如我这个 https://github.com/waitingsong/egg-fetch

**Comment by bobohuochai** [comment]
我已经按照ts 写了一遍了，然后写测试用例的时候在fixtures 目录下建了一个应用，在里面的 home controller 里用@plugin gateway 注入我的插件， 但是在跑test 的时候 发现gateway 还是没有。

**Comment by bobohuochai** [comment]
最后我放弃这个写法了，觉的写测试用例的时候，插件没有自动注入。 用老得js 写法写这个插件了。

**Comment by czy88840616** [comment]
这么看来的确可以加一个插件的 ts 脚手架。。
