### ISSUE TITLE
关于项目生成的 run 目录, 是改成了 appInfo.root 吗? 也没有办法手动指定吗

### ISSUE THREAD

**Issue by zhangxh1023** [midwayjs/midway#354]
新人刚学 midway, 今天发现项目生成的 `run`  目录, 在运行环境不为 `local` 的时候, 会生成到 `HOME` 目录下,  看了下代码, [似乎是这段](https://github.com/midwayjs/midway/blob/master/packages/midway-web/config/config.default.js#L11)   
因为 `Eggjs` 是用的 [`appInfo.baseDir`](https://github.com/eggjs/egg/blob/master/config/config.default.js#L127), 所以我比较好奇这是有什么特殊的用意吗? 而且这个文件生成到项目之外, 如果有多个项目一起跑不是也不安全吗.

**Comment by czy88840616** [comment]
的确，应该是在 baseDir 下，当初应该是有什么缘故，现在想不起来了。。

**Comment by czy88840616** [comment]
done
