### ISSUE TITLE
TypeError: core_2.RequestContext.createAsync is not a function

### ISSUE THREAD

**Issue by hooliy** [midwayjs/midway#3545]
引入mikro后访问报错

<img width="1051" alt="image" src="https://github.com/midwayjs/midway/assets/3368691/a69acaf3-d406-43db-9792-a4b6bd378be5">

**Comment by hooliy** [comment]
<img width="905" alt="image" src="https://github.com/midwayjs/midway/assets/3368691/46fe23e3-494f-4f4b-b1b2-3a3f43a248dc">

**Comment by czy88840616** [comment]
v3.14.0 已处理。
