### ISSUE TITLE
error TS5023: Unknown compiler option '--clean-build'.

### ISSUE THREAD

**Issue by hooliy** [midwayjs/midway#3562]
<img width="436" alt="image" src="https://github.com/midwayjs/midway/assets/3368691/993bf70c-5991-4c74-b903-84d1badab4fc">

使用 `npm init midway` 创建一个组件，build 时提示 
<img width="402" alt="image" src="https://github.com/midwayjs/midway/assets/3368691/c2465362-7274-4d07-a453-51faa2b2bd8c">

**Comment by czy88840616** [comment]
got。

脚手架已经修复，请手动调整为 --cleanOutDir 参数，
