### ISSUE TITLE
[RFC] Midway 扩展能力

### ISSUE THREAD

**Issue by kurten** [midwayjs/midway#371]
> 下面回复已有更新方案

### 背景
* 结合 IoC 的能力，提供便捷框架扩展方式

#### 模块化扩展方式

![image](https://user-images.githubusercontent.com/589831/70627207-c07bd300-1c60-11ea-9b6e-ec0ae77c46c6.png)

* 新增 midway.plugin.js 文件

```JSON
{
  // 单个扩展模块
  "xxx扩展": {
    "enable": true,
    "package": "midway-xxx扩展"
  }
}
```

* midway-bin 
  * 扩展脚手架
  ```
  xxx扩展
    dist
      index.ts
    src
      index.ts
    test
      index.ts
    ioc.json
    package.json
  ```
  * 构建扩展模块时生成 ioc.json，存储扫描目录(需要区分 src、dist 目录)

  ```JSON
  { "dirs": ["xxx/xxx", "ttt"], "files": ["xxx", "sss"] }
  ```

* 扩展模块需要依赖 midway-core、midway-decorator
  * 新增生命周期装饰器
    * willReady，支持 priority，在应用 ready 时期调用执行
    * willStop，应用停止时执行
  * middleware 装饰器
    * controller、get、post、put 等这些装饰器参数中传入的 middlewares 不够优雅，而且无法被用来做全局 middleware
    * 使用该装饰器，同时支持以路径作为参数，这样可以用来作为全局 middleware 或者相应路径的 middleware
  * 使用 provide 等现有装饰器
* midway-loader
  * 获取 midway.plugin.js 中配置的扩展模块，load 时加载扩展模块中 ioc.json 中的目录文件

* context 方法增强 
  * ctx.requestContext.getAsync('myService') -> ctx.getRequestContextInstance('myService')
  * ctx.applicationContext.getAsync('myService') -> ctx.getApplicationContextInstance('myService')

#### 非模块化扩展
* 直接在当前应用中使用装饰器、相关类即可

### 举例

* willReady

```TypeScript
@priority(-1)
@willReady()
@provide()
class XxxWillReadyClass {
  @inject()
  xxx; // 注入 xxx
  @inject()
  db; // 注入 db

  @init()
  async initialize() {
    // 执行 xxx 的函数
    await this.xxx.doSomething();
    
    // 执行 db 连接
    await this.db.connect();
  }

}
```

* willStop

```TypeScript
@willStop()
@provide()
class XxxWillStopClass {
  @inject()
  db; // 注入 db
  
  @init()
  async initialize() {
    // 关闭数据库连接
    await this.db.close();
  }
}
```

* middleware

```TypeScript
// '/xxx' 表示匹配该路径规则后执行当前 middleware
// 如果路径为空表示全局 middleware
@middleware('/xxx')
@provide()
class XxxMiddlewareClass implements WebMiddleware {

  @inject()
  myService;  // 由于中间件实例属于单例，这个实例即使注入也无法获取到 ctx

  resolve(): Middleware {
    return async (ctx, next) => {
      // 必须通过从请求作用域中获取对象的方式，来绑定上下文
      ctx.service = await ctx.getRequestContextInstance('myService');
      await next();
    };
  }

}
```

### 相关 issue

#369 
#349 
#203

**Comment by Lellansin** [comment]
顺序是？

**Comment by kurten** [comment]
> 顺序是？

可以使用 priority 来定义，compose 时使用 sort 先排序即可

**Comment by waitingsong** [comment]
这个扩展(模块) 类似 egg 的插件么？

**Comment by czy88840616** [comment]
是，是midway体系里的跨场景通用的能力，利用 ioc 去扩展能力。上面的 RFC 不太对，之后更新一版。

**Comment by czy88840616** [comment]
## 背景

现有的 midway 是复用了 egg 生态的插件，但是在 midway-faas 下是没有扩展能力的，同时仅仅靠 ioc.json 去加载包也是不足的，需要对各个能力进行弥补。

我们希望在 midway 体系在上层能够通过场景的切分，解决复合场景的问题。通过扩场景扩展能力，提供原有的插件能力。

现有 IoC 的扫描 + 装饰器属于文件系统全扫描，基于文件的分散体系，不是基于功能聚合的插件思路，具体的能力完全依靠上层框架（midway，midway-faas 等）来做聚合实现，理论上来说，所有的扩展插件，在所有的 midway IoC 体系下都能通用。


![image](https://user-images.githubusercontent.com/418820/73907477-65253480-48e1-11ea-99e0-c6515d6e7b9f.png)


## 目标

- 1、产出不同 midway 场景下，能复用的垂直扩展能力


## 思路


### 入口配置的设计

midway 系列一直没有一个入口文件，也没有设计 midway 自己的扩展方案。<br />这层设计有几个目的：

- 1、配置 IoC 行为，优先加载执行
- 2、配置扩展能力（加载哪些包）
- 3、其他额外能力

最终需要有 API 以及装饰器语法糖两种方式。

**API**

```typescript
const containerConfiguration = container.createConfiguration();
containerConfiguration.addImports([
  'midway-plugin-xxx',
  'midway-plugin-xxx',
]);
containerConfiguration.addImportObjects({
  sequelize: require('sequelize')
});

```

**语法糖**


```typescript
@Configuration({
  importPackages: [
    'midway-plugin-xxx',
    'midway-plugin-xxx',
  ],
  configs: [
    'config.*.ts'
  ],
  importObjects: {
  	sequelize: require('sequelize')
  }
})
class AutoConfiguration {
}
```

### 扩展流程

流程整个分成几个阶段，如下图，传统 midway 应用只扫描一次自己应用中的目录，而扩展的加入，给 midway 赋予了更灵活的同时，也额外增加了扫描的区域，目前 midway-faas 的 ioc.json 也是类似的行为。


![image](https://user-images.githubusercontent.com/418820/73907525-9998f080-48e1-11ea-8d61-fe9c96e186f0.png)



### 扩展内容

针对扩展包的内容，没有特别限制，只要是 [@Provide](#) 暴露出来的 class，都能被原生顶层框架扫描到，并将定义加载到内存中，如何使用，则是看顶层模块如何依赖，以及装饰器如何实现。

**Comment by waitingsong** [comment]
扩展流程 下方配图中 “查找@configuration” 节点没有出口？

**Comment by czy88840616** [comment]
有的。。图箭头混了
