### ISSUE TITLE
关于类继承的小疑问

### ISSUE THREAD

**Issue by SuperHuangXu** [midwayjs/midway#374]
* **Node Version**:v12.13.0
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:https://github.com/SuperHuangXu/midway-demo.git

在这个Mini Showcase Repository中，为什么home路由不起作用，user路由却可以生效？

**Comment by czy88840616** [comment]
controller 入口比较特殊，类继承的场景我的确没有测过，我测一下。

**Comment by czy88840616** [comment]
现阶段，继承的场景已经处理，明确只支持属性装饰器继承。
