### ISSUE TITLE
关于 schedule 的疑问

### ISSUE THREAD

**Issue by HaloXie** [midwayjs/midway#377]
想请问 如果上一个任务没有执行完, 那么后续会出现新的任务吗?
interval 属性是上一次的任务结束有关还是上一次任务启动有关?

感谢, 感谢

**Comment by czy88840616** [comment]
> 想请问 如果上一个任务没有执行完, 那么后续会出现新的任务吗?

会。

**Comment by czy88840616** [comment]
这个功能是完全是 egg 的。

![image](https://user-images.githubusercontent.com/418820/71893435-a3b2bc80-3186-11ea-8112-d850356f034b.png)

所以，interval 就是时间间隔，和是否执行结束无关。
