### ISSUE TITLE
midway-init创建项目出现错误

### ISSUE THREAD

**Issue by southorange1228** [midwayjs/midway#382]
* **Node Version**: v10.12.0
* **Egg Version**: 
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: deepin linux v15.11
* **Mini Showcase Repository**:

使用midway-init创建新项目时，第一次创建项目之后，再使用midway-init报错如下：
无法创建目录"midway-boilerplate-typescript-1.0.3": 文件已存在

![a](https://user-images.githubusercontent.com/32590310/74122149-20610c80-4c05-11ea-8a8b-fe44bb6fc7f5.png)

**Comment by czy88840616** [comment]
奇怪。。按理mkdir之前已经删了才对。。

https://github.com/midwayjs/light-generator/blob/master/src/generator/NpmPatternGenerator.ts#L40

**Comment by czy88840616** [comment]
已经发布新版本 light-generator，理论上修复了这个问题，麻烦重新装一下 midway-init。
