### ISSUE TITLE
middleware执行顺序

### ISSUE THREAD

**Issue by southorange1228** [midwayjs/midway#383]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

中间件的执行顺序是怎么定制的，目前通过plugin定制顺序，这个顺序能否完全高度定制use顺序，比如部分中间件需要在router之前执行,部分需要在router之后执行，这部分是如何考虑的。

**Comment by czy88840616** [comment]
目前中间件分两种

- 1、全局中间件，由 egg 提供配置能力（插件里就是这种）
- 2、单路由中间件，由 midway 的 @get/post 等装饰器提供，可以针对某个特定路由，特定路由的 prefix 添加。

egg 中间件执行顺序由插件依赖排序指定，用户不可指定插件中的中间件加载顺序。

**Comment by southorange1228** [comment]
这几个点我都比较清楚，主要是有一个点：在全局中间件中我定义了中间件A，我想要在router之后执行，也就是在app.use(route.allowedMethods())这样的之后执行，这种是怎么考虑的？默认的全局中间件都是在router之前执行么

**Comment by czy88840616** [comment]
中间件是洋葱模型，在route之后可以写的吧。

**Comment by southorange1228** [comment]
```javascript
const koa = require("koa");
const koarouter = require("koa-router")();

const app = new koa();

koarouter.get("/", async (ctx, next) => {
  console.log(1)
  ctx.body = "hello world";
});

app.use(koarouter.routes());
app.use(koarouter.allowedMethods());

app.use(async(ctx,next) => {
  console.log(2)
  await next();
})

app.listen(3000);
```
这里有个例子，比如我有个中间件console.log(2)需要在router之后执行，也就是说我全局中间件需要在controller之后执行，这部分的中间件是如何区分的呢？还是说全局的中间件都是默认在controller之前执行？

**Comment by czy88840616** [comment]
egg的规则，业务自己定义的中间件都会在插件，以及egg内置的中间件之后执行，如果要控制内置的，只能通过插件定义修改，在 app.js 中调整 config.coreMiddleware 数组（好像是叫这个）。

**Comment by southorange1228** [comment]
那么你们是否有考虑过这种情况相关中间件的问题呢？虽然这种场景应该不是很常见。

**Comment by czy88840616** [comment]
Web 层的能力目前全部是 follow egg 的，不太能做大的修改，似乎也没法改。。除非 web 层不使用 egg。。比如我们之前尝试的 midway-koa ...

**Comment by southorange1228** [comment]
好的，谢谢解答。

**Comment by Yuliang-Lee** [comment]
抱歉，挖个坟。
如果自定义的全局插件都是在 router 之前执行，比如现在有需要检查接口合法性等一些操作，想确保请求是合法的路由才去检查，非法路由就不浪费资源去检查了，当前实现不了？

**Comment by czy88840616** [comment]
你是说自定义的中间件吧，你说的场景就是中间件做的事情，匹配到路由，判断条件，然后继续走。

**Comment by Yuliang-Lee** [comment]
> 

对的，自定义中间件，说错了。
但是现在 全局自定义中间件 在 匹配到路由之前执行了，这时候还不知道有没有匹配的 controller？

**Comment by czy88840616** [comment]
不知道controller，只知道 ctx.path，Router 是最后一个中间件，所以自定义中间件里只有“走”或者"不走“两个行为。

**Comment by Yuliang-Lee** [comment]
比如现在想实现的效果是，有一个校验接口登录态中间件，但是只想针对系统已有的路由校验，如果请求来的是不存在的路由不要校验，直接返回 404，有优雅的实现方式吗？

**Comment by czy88840616** [comment]
有个办法是把中间件加到每个路由中或者 controller 上，这样是可以等明确的进到路由才执行的，但是明显用起来繁琐。事实上登录应该是基于数据（参数，值）来做，而不是根据 path 来做，毕竟大部分的路由都应该要登陆，并且在鉴权完之后保存到 session 等，后续就不需要再做了。

**Comment by Yuliang-Lee** [comment]
现在并没有想根据 path 来做，而是不想中间件不管三七二十一都去执行，因为会消耗资源请求远端服务什么的。现在是想在其他接口里校验 session 是否包含已登录的那些信息。写到每个路由里繁琐，自己维护一个 list 保存系统所有 route path 在中间件里自行判断也繁琐。。

**Comment by czy88840616** [comment]
虽然有路由表，但是用户实际是没有办法去用的（否则就重做了一遍路由逻辑，而且正则匹配啥的一般和实际路由还不太一样），根据session 是否包含登录并请求鉴权，这也是标准的逻辑了，这个消耗是根据用户来的，整体也还好吧。

**Comment by Yuliang-Lee** [comment]
是to c 的系统，任意进来的请求都执行这些逻辑，感觉在安全性和系统鲁棒性上都会有一点影响吧。

**Comment by czy88840616** [comment]
还好吧，这就是正常的业务逻辑，和安全稳定性没有太大的关系，鉴权登录系统本身就需要抗这个压力的。中间件里判断路由，就是个鸡蛋问题，不管是哪一边先，必然是得先处理一遍，如果想尽可能的减少，那只能在中间件里处理 path，尽可能的过滤不可能的路由。
