### ISSUE TITLE
midwayjs 配置文件格式支持yml和json吗

### ISSUE THREAD

**Issue by TimLiu1** [midwayjs/midway#385]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
不支持。。。因为egg只会读特定文件(config.js/ts)。。不过可以变通，比如在js/ts 中再去 require。

> ps: midway2 可能可以。。
