### ISSUE TITLE
service test 获取不到 ctx

### ISSUE THREAD

**Issue by monkindey** [midwayjs/midway#433]
* **Node Version**: v10.0.0
* **Platform**: Mac
* **Mini Showcase Repository**:  https://github.com/monkindey/midway-ctx-test-example

执行`npm run test ./test/app/service/user.test.ts` ctx 是打印不出来的，执行 `./test/app/controller/home.test.ts` 是可以的，可能两者用的 container 不一样？

**Comment by czy88840616** [comment]
是的，service是从applicationContext中获取的，也就是说出来的是单例，没有ctx。而controller是从请求链路过来，拿的是ctx.requestContext离的内容。

具体测试方式正好为midway2，前两天补充了一些，可以看 https://www.yuque.com/tccb3e/zahvcd/nu6wmm

**Comment by monkindey** [comment]
👍 这种写法还是挺清晰的

```js
import { app, assert } from 'midway-mock/bootstrap';
import { IUserService } from '../../src/interface';

describe('test/service/user.test.ts', () => {
  it('#getUser', async () => {
    // 创建匿名上下文
    const ctx = app.mockContext();
    // 取出 userService
    const user = await ctx.requestContext.getAsync<IUserService>('userService');
    const data = await user.getUser({ id: 1 });
    assert(data.id === 1);
    assert(data.username === 'mockedName');
  });
});
```

midway1.x 不打算支持了吗？

**Comment by czy88840616** [comment]
目前使用是一样的

**Comment by monkindey** [comment]
好像 mockContext 执行后返回的 ctx 是 egg 那边，并没有 requestContext 字段。

**Comment by czy88840616** [comment]
收到，我明天看一下，太困了……

**Comment by czy88840616** [comment]
https://github.com/midwayjs/midway/pull/436 加了个case，似乎没有问题

**Comment by monkindey** [comment]
我这边 TypeScript 并没有提示

![image](https://user-images.githubusercontent.com/6913898/77073415-3646c600-6a2a-11ea-913f-67a4410a8241.png)

**Comment by czy88840616** [comment]
这个是定义缺失了的问题，实际是有的。

**Comment by monkindey** [comment]
👍 确实是可以的，但是如果定义加上就更好了，有思路吗？

**Comment by czy88840616** [comment]
v1.8.2 已经修复定义
