### ISSUE TITLE
全局中间件不能定义成 class 的形式?

### ISSUE THREAD

**Issue by yyyang1996** [midwayjs/midway#440]
* **Node Version**: v13.2.0
* **Egg Version**: 2.26.0
* **Platform**: Windows 10 
* **Midway Version**: 1.0.0

![midway-middleware](https://user-images.githubusercontent.com/34713301/77230430-1270b500-6bcf-11ea-8ddf-4e87ef7ee91e.png)

在 app.config 里使用会报错, 但是如果改成下面这种 `function` 的写法就不会报错了
```js
export function demo() {
  return async (ctx, next) => {
    next()
  }
}
```

**Comment by czy88840616** [comment]
是的，这点我们一直觉得比较遗恨，egg没有留全局中间件的口子，要做只能hack。

**Comment by yyyang1996** [comment]
> 是的，这点我们一直觉得比较遗恨，egg没有留全局中间件的口子，要做只能 hack，并且调用私有方法，这个就比较恶心了。
> 
> 
> 
> 之前有个用户提了个办法，在文件内写两个，class 的 resolve 引用方法的写法，方法导出给全局用，class 给路由上用。
> 
> 
> 
> ```ts
> 
> // middleware/xxx.ts
> 
> 
> 
> export function api() {
> 
>   return async (ctx, next) => {
> 
>     next()
> 
>   }
> 
> }
> 
> 
> 
> @provide()
> 
> export class APIMiddlware {
> 
> 
> 
> 	resolve() {
> 
> 		return api();
> 
> 	}
> 
> }
> 
> 
> 
> 
> 
> ```



> 是的，这点我们一直觉得比较遗恨，egg没有留全局中间件的口子，要做只能 hack，并且调用私有方法，这个就比较恶心了。
> 
> 
> 
> 之前有个用户提了个办法，在文件内写两个，class 的 resolve 引用方法的写法，方法导出给全局用，class 给路由上用。
> 
> 
> 
> ```ts
> 
> // middleware/xxx.ts
> 
> 
> 
> export function api() {
> 
>   return async (ctx, next) => {
> 
>     next()
> 
>   }
> 
> }
> 
> 
> 
> @provide()
> 
> export class APIMiddlware {
> 
> 
> 
> 	resolve() {
> 
> 		return api();
> 
> 	}
> 
> }
> 
> 
> 
> 
> 
> ```

倒也是个办法😂

**Comment by czy88840616** [comment]
内部midway我们是直接改了loadMiddleware方法的。。但是外部实在是觉得不是特别好。。也没啥好办法。

**Comment by czy88840616** [comment]
2.x 已经处理完毕全局中间件也可以用 class 了。

**Comment by jiachaosun** [comment]
class方式如何拿到app对象呀

**Comment by czy88840616** [comment]
@jiachaosun @App() 呀。
