### ISSUE TITLE
IoC扩展外部模块中无法注入ctx

### ISSUE THREAD

**Issue by lyd600lty** [midwayjs/midway#442]
* **Node Version**: v12.10.0
* **Midway core Version**: 2.0.5
* **Platform**: MacOS 10.15.3

1. 通过@Configuration import的模块无法@Inject ctx
![image](https://user-images.githubusercontent.com/2917899/77413542-7925e680-6dfa-11ea-8cd4-8f110340e45f.png)

2. 通过@Configuration 无法import src（ts文件），build之后才生效，开发时很麻烦，希望可以有更好的方式

**Comment by kurten** [comment]
1. 确认是个bug
2. 本地测试，可以先把 main 设置到 src，我们想一下开发态是否有更好的方案。

**Comment by kurten** [comment]
1. 已经修复
