### ISSUE TITLE
用midway-init生成的项目， 按文档说明使用jest测试框架运行错误

### ISSUE THREAD

**Issue by heavenkiller2018** [midwayjs/midway#462]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

用midway-init生成的项目， 按文档说明使用jest测试框架运行错误
```js
使用 Jest

Midway 在单元测试框架上，不仅支持 Mocha，也对 Jest 做了相应支持。具体使用步骤如下：

1.在项目根目录安装以下依赖：

$ npm install jest @types/jest ts-jest -D

    修改 tsconfig.json，避免 Mocha 与 Jest 的类型定义文件冲突

{
  "compilerOptions": {
    "types": ["jest"]
  }
}

    在项目根目录下新增 jest.config.js 文件，内容如下：

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'midway-bin/jest/env.js'
};

    配置 npm scripts，修改 test 命令

{
  "scripts": {
    "test": "jest"
  }
}

    运行 npm scripts，即可使用 Jest 完成单测

npm run test

```

 ` # npx jest`
 FAIL  test/app/home/home.test.ts
  ● Test suite failed to run

    ReferenceError: before is not defined

      at Object.<anonymous> (node_modules/midway-mock/src/bootstrap.ts:10:1)
      at Object.<anonymous> (node_modules/midway-mock/bootstrap.js:9:10)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        12.217s
Ran all test suites.

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at MockApplication.[init] (node_modules/egg-mock/lib/app.js:77:17)
          at Object.<anonymous>.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)

这是什么问题啊？

为什么 midway文档里提到 的很多示例都是不能正常运行的啊？
譬如这个也是：

我们也提供了可运行 demo 供大家参考：demo-unittest-jest

**Comment by czy88840616** [comment]
应该是可以的，我们看一下

**Comment by Yiniau** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/17947783/150503519-23cd7a05-d291-4060-943f-cbf9c345e115.png">
这个问题好了吗

**Comment by czy88840616** [comment]
你这是依赖没装对吧。。

**Comment by Yiniau** [comment]
> 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/17947783/150737288-674c9899-5b46-47b9-a375-cba11b64e25b.png">
有少装吗，不应该init的时候模版里都有的吗

**Comment by czy88840616** [comment]
看着像是 supertest 的定义不太对。

**Comment by Yiniau** [comment]
那我这边可以做什么吗？

**Comment by Yiniau** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/17947783/150750427-80e5a180-3177-427d-93c8-6201bab81c74.png">
我自己临时搞了一下。能用

**Comment by czy88840616** [comment]
我并未发现这个问题，猜测可能是 egg-mock 自带了 mocha，和 jest 冲突导致的，跟环境，安装方式有比较大的关系。
