### ISSUE TITLE
稳定版本是1.x 还是 2.x

### ISSUE THREAD

**Issue by zzh-a** [midwayjs/midway#472]
建议给版本打上 latest release 的 tag , 每次更新 latest release 的时候加上改动点。

**Comment by czy88840616** [comment]
是 1.x

**Comment by waitingsong** [comment]
2.x 是给 fass 用的～～

**Comment by czy88840616** [comment]
我把2.x 切到 next，现在每次发都会自动到 latest，虽然使用怎么不影响，但是不好看。。
