### ISSUE TITLE
this.app怎样赋值和获取?

### ISSUE THREAD

**Issue by ChungTak** [midwayjs/midway#474]
在eggjs中
启动文件app.js :    app.cities  ='xxoo';
任何一个 service  文件中可以通过 this.app.cities 获取

请问在midway中如何实现这个流程？我直接this.app提示undefine

**Comment by czy88840616** [comment]
把东西挂在app并不是很合适，我们希望能和app解耦，

在 midway 中比较适合的方式是通过注入进行。

比如任意类中使用 @inject

当然，如果是egg或者其他情况已经挂在在了 app，那么可以通过几个方法获取这个对象。

第一种是@inject（） ctx，ctx.app 即为这个app

第二种是使用 @plugin（）装饰器，等价于 app.xxx
