### ISSUE TITLE
新增 service 后 globby 扫描时间很长

### ISSUE THREAD

**Issue by boogunote** [midwayjs/midway#478]
* **Node Version**: 10.15.1
* **Egg Version**: 2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Windows 10
* **Mini Showcase Repository**:

新增 service 后 globby 扫描时间达到了 170096 毫秒。时间是通过对这部分代码执行时间的监测得出的。https://github.com/midwayjs/midway/blob/master/packages/midway-core/src/container.ts#L217

**Comment by czy88840616** [comment]
我们重写了扫描逻辑，看看现在有没有
