### ISSUE TITLE
在Singleton单例中如何获取logger对象

### ISSUE THREAD

**Issue by ChungTak** [midwayjs/midway#487]
如果在Singleton中注入logger对象，实现日志功能呢？
直接注入会报错: logger in class SipImpl is not valid in current context

出错代码：

`
scope(ScopeEnum.Singleton)
@async()
@provide()
export default class EntityManager {

    @inject()
    logger; // 这里出错

    @init()
    async connect() {
  		this.logger.info('==start==');
    }
}`

**Comment by czy88840616** [comment]
标准是使用@logger装饰器注入
