### ISSUE TITLE
没有出现egg 的 typings 目录，请问如何处理？

### ISSUE THREAD

**Issue by caihaibin1991** [midwayjs/midway#492]
没有出现egg 的 typings 目录，请问如何处理？

**Comment by czy88840616** [comment]
今天整组不在公司，要晚一点看这个问题 😢

**Comment by caihaibin1991** [comment]
@czy88840616 谢谢

**Comment by czy88840616** [comment]
是在使用egg-ts-helper没生成插件定义的问题吧。

**Comment by caihaibin1991** [comment]
看启动 egg-bin 这种启动是有typing目录的 mid-bin  这种需要配置什么吗？ 能在example中补充一个typings的示例吗？

**Comment by czy88840616** [comment]
egg启动是因为他的插件机制需要这个来生成定义，这个我打算加上

**Comment by czy88840616** [comment]
typings 生成的目录和内容不太对，已经联系 egg-ts-helper 的作者处理。

**Comment by caihaibin1991** [comment]
@czy88840616 辛苦了，谢谢

**Comment by czy88840616** [comment]
2.x 已经提供了。

**Comment by family2hu** [comment]
你好，我生成的typings目录下config文件夹下的文件是对的，app文件夹下没有extend/controller/middleware/service/model等文件夹，请问怎么处理？

**Comment by czy88840616** [comment]
typings 里不需要这些文件夹啊。
