### ISSUE TITLE
不同模块，同名控制器如何解决？模块在月来越多的情况下。很难避免这个问题

### ISSUE THREAD

**Issue by caihaibin1991** [midwayjs/midway#494]
不同模块，同名控制器如何解决？模块在月来越多的情况下。很难避免这个问题

**Comment by czy88840616** [comment]
有一些逻辑⬆️的避免方案，比如代码本身是按领域去维护的，那么每个controller就是一个领域，所有该领域下的路由应该在一起。

另一块，框架层也在做重复类的检查能力，以及包复用的定义作用域。
