### ISSUE TITLE
mac   midway-init  Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by alvinjstu** [midwayjs/midway#495]
➜  code sudo midway-init
✔ Hello, traveller.
  Which template do you like? · midway-ts-strict - Simple midway application boilerplate by ts with ng style and strict eslint rules.(by @waitingsong)
✔ The directory where the boilerplate should be created · gkleaf
✔ Fetch the boilerplate which you like...
Error: ENOENT: no such file or directory, stat '/tmp/gen_15901/midway-boilerplate-ts-strict-1.0.4.tgz'

**Comment by czy88840616** [comment]
I tried it in my macbook, and this error did not occur. I suspect that it is related to permissions or the network.

Midway-init download the template package from npm and unzip it.

This is my operation video.

![2020-05-23 00-21-56 2020-05-23 00_25_22](https://user-images.githubusercontent.com/418820/82688753-f7342b80-9c8b-11ea-9998-dbce9b7733ee.gif)
