### ISSUE TITLE
app.ts require package.json build 的时候会出问题

### ISSUE THREAD

**Issue by monkindey** [midwayjs/midway#497]
* **Node Version**: v10.0.0
* **Egg Version**: 2.26.1

重现步骤，midway init 一个新仓库，然后在 app.ts 加上 require package.json 的代码

```js
import * as pkg from '../package.json'
```

然后 npm run build 之后生成的目录结构变成

```
├── app
│   └── public
├── package.json
└── src
    ├── app
    ├── app.d.ts
    ├── app.js
    ├── config
    ├── interface.d.ts
    ├── interface.js
    └── service
```

最后我是用 fs readFile 方法解决了，主要这个问题比较隐晦。是否可以通过文档或者在 application 扩展加上另外一个属性是 package.json ，还是在 midway-bin 的 build 命令进行一些改动 来解决这个问题呢？

**Comment by czy88840616** [comment]
这。。其实是 tsc 的问题。。它编译有个最小原则，比如 src/app/app.js 和 src/app/index.js，那么编译出来的根目录就会是 app。。

**Comment by monkindey** [comment]
同样是因为 tsc 的情况，我在仓库加了一个 plugin，里面有 package.json，编译的时候没有同步过去。部署的时候 egg 那边会报没有找到 package.json ，但是本地是可以正常开发的。感觉本地&部署的时候代码的一致性对稳定性还是很重要的。

**Comment by czy88840616** [comment]
因为 tsc 就不支持非 ts 文件的拷贝。。所以。。我们在build的时候加了一个功能。

![image](https://user-images.githubusercontent.com/418820/86897343-d9d2f800-c139-11ea-8988-8047fc459a26.png)

https://midwayjs.org/midway/tool_set.html#build-%E5%91%BD%E4%BB%A4
