### ISSUE TITLE
自动生成流程图

### ISSUE THREAD

**Issue by monkindey** [midwayjs/midway#502]
看了下 injection 是可以生成依赖图的，不知道 midway 能否做到生成流程图语法，这样子我访问某个接口，就可以看到他到哪些方法了。

**Comment by czy88840616** [comment]
那个是依赖关系图，还不是流程图。

**Comment by monkindey** [comment]
不好意思，突然想到 midway 也不知道这个流程会走到哪里，这个是运行时才知道，生成流程图确实太难了，先关了。

**Comment by czy88840616** [comment]
畅想是可以的。。比如有 AOP 能力，自动在调用链上染色，就能渲染出图了，就是性能可能影响非常大，这个也就是社区常见的 Tracing。

**Comment by monkindey** [comment]
额额，如果可以做到开发调试的时候才染色也是可以的。可视看一个请求链路调用的 service 感觉对于调试非常有用。

**Comment by czy88840616** [comment]
最近在做vscode插件，可以考虑进去。
