### ISSUE TITLE
你好，我想问下如何解析微信公众号返回的xml数据

### ISSUE THREAD

**Issue by Tmamasay** [midwayjs/midway#507]
ctx.req是IncomingMessage对象，我不知道怎样才能解析微信公众号返回回来的xml数据包

**Comment by czy88840616** [comment]
微信公众号开发我没有涉猎，我理解是 post body 的解析，可以尝试拿 ctx.request.body 的内容。

**Comment by echosoar** [comment]
node 中xml解析可以尝试 https://github.com/echosoar/dolmx

**Comment by Tmamasay** [comment]
@czy88840616 拿ctx.request.body里的数据可以解析出来   感谢帮助

**Comment by Tmamasay** [comment]
@echosoar 谢谢
