### ISSUE TITLE
控制器，业务层命名问题

### ISSUE THREAD

**Issue by caihaibin1991** [midwayjs/midway#510]
调整了控制器和业务层的命名。
控制器:AdminController.ts
业务层:AdminService.ts
模型层:AdminModel.ts
这种写的时候。同时打开多就不容易乱。不然控制器。业务。模型，同时打开。都叫 admin.ts 看文件有些懵。。。

然后这边暂时没什么问题。我想了解下，这种有什么潜在影响吗？

**Comment by czy88840616** [comment]
没啥问题，按领域划分重新组合都ok的
