### ISSUE TITLE
egg-cache cache-manager-fs 驱动配置会丢失，不知道为啥。。。

### ISSUE THREAD

**Issue by caihaibin1991** [midwayjs/midway#512]
eggjs es版本调试观察
![image](https://user-images.githubusercontent.com/5326638/85366281-9b461680-b559-11ea-9cc7-72e15ffecd81.png)
midway 调试观察

![image](https://user-images.githubusercontent.com/5326638/85366308-a8fb9c00-b559-11ea-85eb-9cfeea82e60d.png)

driver变没了。导致默认直接走memory类型。重启数据丢失。麻烦看下。。。

**Comment by caihaibin1991** [comment]
上面这种不正常
// import {cacheManagerFs} from 'cache-manager-fs';
下面这种正常
import * as cacheManagerFs from "cache-manager-fs";

**Comment by czy88840616** [comment]
恩。。ts import 的问题。
