### ISSUE TITLE
使用midway的sequelize-typescript demo项目代码，修改src/lib目录的文件不会触发reload

### ISSUE THREAD

**Issue by gzlock** [midwayjs/midway#513]
* **Node Version**: 12.18
* **Midway Version**: ^1.20.1
* **Plugin Name**: sequelize-typescript
* **Plugin Version**: 1.1.0
* **Platform**: macOS 10.15.5
* **Mini Showcase Repository**: [https://github.com/midwayjs/midway-examples/tree/master/demo-sequelize-typescript](https://github.com/midwayjs/midway-examples/tree/master/demo-sequelize-typescript)

![image](https://user-images.githubusercontent.com/2311740/85612697-b1ec8a80-b68b-11ea-8d0f-41f1f741c9a5.png)

没改变过demo的目录结构

```
./src/lib
app.ts
```

这些文件的修改都没有触发reload
尝试去`config/config.default.ts`增加
```js
  config.development = {
    overrideDefault: true,
    watchDirs: ['src/'],
  }
```
也无效

**Comment by gzlock** [comment]
依照midway-init创建的模板修改development就可以了

**Comment by czy88840616** [comment]
example是禁用了一些东西，我记得默认有lib目录
