### ISSUE TITLE
Midway Faas How to connect VPC Mongodb 

### ISSUE THREAD

**Issue by zhongjixiuxing** [midwayjs/midway#527]
Faas 怎样链接 VPC 内的MongoDB ？

**Comment by czy88840616** [comment]
如果不在阿里云云工作台的话，这个就需要在 yml 配置 https://help.aliyun.com/knowledge_detail/72959.html?spm=a2c4g.11186623.6.621.140a5d6c51NcOP.

对应的结构 https://www.yuque.com/midwayjs/faas/serverless_yml

**Comment by zhongjixiuxing** [comment]
@czy88840616 
![image](https://user-images.githubusercontent.com/8935235/87317742-003dcc80-c55a-11ea-9ee6-52c947bf1a0e.png)
![image](https://user-images.githubusercontent.com/8935235/87317872-2bc0b700-c55a-11ea-91d0-145346581f21.png)

**Comment by czy88840616** [comment]
额。我才看到，这个得提下工单问下阿里云的客服了，我也不清楚平台改到哪儿了。

**Comment by zhongjixiuxing** [comment]
**最新结果：** 阿里云技术客服回答暂不支持仅VPC访问模式。

**另一种方式可以实现仅VPC内访问**： 阿里云API 网关与Faas结合

**Comment by czy88840616** [comment]
额。。。好吧。。
