### ISSUE TITLE
重名的类在 ioc 中的处理方案讨论

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#54]
有几种处理：

1、默认能重名，重名即覆盖，增加警告输出？(container 默认行为)
2、不能重名，报错 （injection 默认行为）
3、midway 中增加配置，默认不能重名

**Comment by czy88840616** [comment]
@kurten @guangwong @mariodu

**Comment by mariodu** [comment]
增加配置，默认应该可以重名吧

**Comment by czy88840616** [comment]
重名我觉得是少数需求啊。。。

**Comment by kurten** [comment]
推荐默认不重名，重名抛错。允许重名是特殊需求。都碰到过好几回了，都是因为重名导致执行出错。

**Comment by czy88840616** [comment]
结论：默认不允许重名，需要的话开启配置

**Comment by Lellansin** [comment]
LGTM，默认重名报错

**Comment by czy88840616** [comment]
脚手架已经默认增加重名检查。
