### ISSUE TITLE
windows环境下config文件加载问题

### ISSUE THREAD

**Issue by dashing-devtool** [midwayjs/midway#541]
**windows环境下faas-standard 工程，在config目录下创建config.**.ts文件会导致报目录权限问题，报错如下：**

`[Error: EPERM: operation not permitted, lstat 'F:\System Volume Information'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'F:\\System Volume Information'
}`

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/89613767-9d6bf680-d8b5-11ea-8b50-3e396995cc2d.png)

![image](https://user-images.githubusercontent.com/418820/89613759-980eac00-d8b5-11ea-8a4f-de759f7914c1.png)

修了个windows bug，暂时没发现问题，有问题可以再开。
