### ISSUE TITLE
@config失效？还是我的写法有问题？

### ISSUE THREAD

**Issue by dhy1994** [midwayjs/midway#550]
![Lark20200723-172641](https://user-images.githubusercontent.com/18366547/88271440-b8613700-cd09-11ea-8a86-a881a0ecdbee.png)
![Lark20200723-172748](https://user-images.githubusercontent.com/18366547/88271532-d9c22300-cd09-11ea-9f49-53177cc7ce1c.png)
一直搞不清楚为什么报错？
属性“mongoosePrefix”没有初始化表达式，且未在构造函数中明确赋值。

**Comment by czy88840616** [comment]
看着像是开了严格的tslint导致的。。附一个初始化值就行，比如 `= null`

**Comment by dhy1994** [comment]
> 看着像是开了严格的tslint导致的。。附一个初始化值就行，比如 `= null`

在tsconfig.json中加这个配置就解决了
"strictPropertyInitialization": false,
