### ISSUE TITLE
io 走多线程访问，多核，会一直断开重联。修改成单核启动，就正常。请问有人反馈过这个问题吗？

### ISSUE THREAD

**Issue by caihaibin1991** [midwayjs/midway#554]
io 走多线程访问，多核，会一直断开重联。修改成单核启动，就正常。请问有人反馈过这个问题吗？

**Comment by czy88840616** [comment]
是多进程启动？当前函数体系都以单进程运行，在小规格容器中适合的，暂时不考虑多进程的情况。在后面的应用部署模型中，会考虑对等的多进程部署方式。

**Comment by caihaibin1991** [comment]
只io还是所有都是？socket io 对 cpu消耗还是挺大的， 麻烦处理好通知下

**Comment by czy88840616** [comment]
socketio？指的midway v1的应用？

**Comment by lingtoo** [comment]
pm2 多work启动，socket.io 客户端会一直断开重联，修改成单work正常，且我已经在bootstrap.js中配置了redis的粘性会话

**Comment by czy88840616** [comment]
我今天测试下。

**Comment by lingtoo** [comment]
文档中介绍的ws，同样在pm2多worker运行会出问题，虽然不会断开重联，但在多worker下，推数据（后端主动推）会丢失数据。最后自己撸了一个跨进程、跨服务器通迅的ws.（结合redis）

**Comment by caihaibin1991** [comment]
> 文档中介绍的ws，同样在pm2多worker运行会出问题，虽然不会断开重联，但在多worker下，推数据（后端主动推）会丢失数据。最后自己撸了一个跨进程、跨服务器通迅的ws.（结合redis）

已经有人实现，走redis订阅处理。https://www.npmjs.com/package/egg-websocket-plugin

**Comment by czy88840616** [comment]
是一样的，ws 多进程也是需要 redis 做消息分发的。

**Comment by lingtoo** [comment]
@caihaibin1991 @czy88840616 谢谢百忙中回答问题。
