### ISSUE TITLE
【feature request】在提交代码时自动格式化已改动的代码

### ISSUE THREAD

**Issue by Lxxyx** [midwayjs/midway#557]
RT。

在提交 PR 时经常会有忘记加分号等情况，而每次都需要单独通过 lint 检测来确认是否格式正确，并且返回手动修改。实际上这并不是一种好的实践。

格式化的问题通过机器发现，也应当通过机器来修复，这儿我推荐：在提交代码时自动格式化改动的代码（**只格式化本次改动的代码**）。类似于 lint-staged + prettier 的组合。

与其小心翼翼手动fix，这部分工作就交给机器完成吧。这样也能确保整体代码风格是统一的。

**Comment by legendecas** [comment]
mwts fix 是可以自动修复格式问题的。现在没有把这个通过 git hooks 等等在 commit 的时候自动做，这里有两个考虑：

1. git hooks 是开发者本地的开发环境，如果个人有需要可以自行添加。
2. 因为 git hooks 是本地可以修改、禁用的，所以通过 git hooks 的检查只能是建议性质的；我们会通过 CI 来强制格式检查，检查结果与是否能否合并以 CI 为准。

**Comment by Lxxyx** [comment]
@legendecas 通过 husky + lint-staged 的组合，实际上可以很好的 cover 住 commit 时自动格式化代码这个诉求。

然后用了 git hooks，ci 阶段的lint依然可以保留着。这俩不冲突，前者只是尽可能的减少“提交代码 -> CI Lint 报错 -> 手动 fix” 这个操作

对于绝大部分用户而言，是不会改动 git hooks 的，而且也能减少非常多不必要的 lint 报错。  @legendecas

**Comment by waitingsong** [comment]
vscode 配合 eslint/tslint 插件是可以在保存的时候自动调用规则来格式化代码的。
