### ISSUE TITLE
config.default.ts中的导出变量的方式？

### ISSUE THREAD

**Issue by dhy1994** [midwayjs/midway#564]
使用@config 引入config.default.ts中的变量的时候，只有再constructor 当做参数@config 才有效，在class中直接声明变量，最终是没有效果的
但是config.local.ts中的变量，在constructor外，直接申明变量是有效的？
这是什么原因？
![1](https://user-images.githubusercontent.com/18366547/88494659-99a0c000-cfe9-11ea-95d1-287888521685.png)
![2](https://user-images.githubusercontent.com/18366547/88494663-9c9bb080-cfe9-11ea-84d8-b463eddc17c9.png)

**Comment by czy88840616** [comment]
这两没有特别本质的区别，实现基本是相同的，能否提交一个可复现的最小 demo，方便快速排错。

**Comment by dhy1994** [comment]
> 这两没有特别本质的区别，实现基本是相同的，能否提交一个可复现的最小 demo，方便快速排错。

https://github.com/dhy1994/midway-demo-test

**Comment by czy88840616** [comment]
@dhy1994 

![image](https://user-images.githubusercontent.com/418820/88519795-42204580-d025-11ea-9d07-51341120056b.png)

- 1、构造器里属性的注入都是无效的，因为属性注入是在 new Class() 之后
- 2、注入的key写错了（welconMsg => welcomeMsg)

**Comment by dhy1994** [comment]
> @dhy1994
> 
> ![image](https://user-images.githubusercontent.com/418820/88519795-42204580-d025-11ea-9d07-51341120056b.png)
> 
> * 1、构造器里属性的注入都是无效的，因为属性注入是在 new Class() 之后
> * 2、注入的key写错了（welconMsg => welcomeMsg)
> 
> Tip: 尽量不使用构造器注入，都用属性注入，构造器留空。如下是构造器注入的功能展示。
> 
> ![image](https://user-images.githubusercontent.com/418820/88520539-4731c480-d026-11ea-943c-7872ad1a3214.png)

是我之前写错了
