### ISSUE TITLE
egg-scripts 启动的一些问题

### ISSUE THREAD

**Issue by lsxu** [midwayjs/midway#574]
现在app.ts 和agent.ts 是放在src目录下的  egg-scripts 启动 现在并没有识别到这两个文件
使用egg-scripts 启动  具体该如何配置呢

**Comment by czy88840616** [comment]
用 egg-scripts 要前先build。

**Comment by lsxu** [comment]
npm run build 之后也是没效果
目前我们是这样配置的   build之后 dist里面是空的
![image](https://user-images.githubusercontent.com/32353606/88748415-8c1f3d80-d183-11ea-81a1-267371e989c2.png)
![image](https://user-images.githubusercontent.com/32353606/88747278-08fce800-d181-11ea-8371-c5c6bac29134.png)
![image](https://user-images.githubusercontent.com/32353606/88748159-ebc91900-d182-11ea-91f9-f0cce3eb51e9.png)

**Comment by lsxu** [comment]
目录结构
目前开发时  midway-bin 启动没有问题
![image](https://user-images.githubusercontent.com/32353606/88748528-d1436f80-d183-11ea-817a-99bec9e9d236.png)

**Comment by lsxu** [comment]
app.ts 和agent.ts 目前保留 以前egg项目的启动自定义的写法
configWillLoad()  willReady()  Boot类的方式

**Comment by lsxu** [comment]
build后dist 空 我们解决了 是tsconfig的参数问题
build后的目录 
![image](https://user-images.githubusercontent.com/32353606/88755382-9d704600-d193-11ea-9370-c0ec81cbaf76.png)

但是egg-scripts 启动  app.ts 和 agent.ts  还是失效

**Comment by lsxu** [comment]
找到了原因  因为我们使用了 resolveJsonModule   用了一个json文件和src同级  在src的代码里引入之后   在build时会因为这个  导致dist 里面  把src和 json文件 同时引入  把需要引用的json文件等 放入src下 就可以了
