### ISSUE TITLE
请问不使用注入依赖，如何获取app？或者说app.config?

### ISSUE THREAD

**Issue by dhy1994** [midwayjs/midway#576]
在函数中而非class中要使用 config,env等值，如何引入？

**Comment by czy88840616** [comment]
非 class？ 在 class 中拿到后，通过参数传递。

不过在函数中都是请求流，跟 app 其实没太大关系了，不应该跟 app 有关。不过为了之后和应用融合，我们还是提供了一个 app 的注入方式，不过这块的 API 是 midway 特有的。。

```ts
import {App, IMidwayApplication } from '@midwayjs/decorator';

class xxxx {

  @App()
  app: IMidwayApplication;

  invoke() {
	// app.getConfig()
  }

}

```

**Comment by dhy1994** [comment]
> 非 class？ 在 class 中拿到后，通过参数传递。
> 
> 不过在函数中都是请求流，跟 app 其实没太大关系了，不应该跟 app 有关。不过为了之后和应用融合，我们还是提供了一个 app 的注入方式，不过这块的 API 是 midway 特有的。
> 
> ```ts
> import {App, IMidwayApplication } from '@midwayjs/decorator';
> 
> class xxxx {
> 
>   @App()
>   app: IMidwayApplication;
> 
>   invoke() {
> 	// app.getConfig()   // 未加载 egg 模块，midway 通用的 API
>     // app.config        // 加载了 egg 模块，mixin 了 egg 的 API 可以和以前一样（不过定义里没有）
>   }
> 
> }
> ```

通过参数传递，这个有点不方便吧，比如isProduction()这中类似的函数，正常情况下应该在util中，还说直接放在config中比较好

**Comment by czy88840616** [comment]
我觉得工具类应该是在 util 中的。

**Comment by dhy1994** [comment]
> 我觉得工具类应该是在 util 中的，config 放的是和环境做区分的业务配置，本质上其实 require 进来就行了，但是配置是因为有特殊的合并逻辑，所以才显得不一样。
还有一种解决办法，把变量转换成类，把类中的函数用静态函数，这样就可以用@config env了

**Comment by czy88840616** [comment]
这样也是可以的。
