### ISSUE TITLE
请问以下框架默认注入的 ctx、appDir、baseDir、logger 具体指的是什么类

### ISSUE THREAD

**Issue by lleohao** [midwayjs/midway#579]
![image](https://user-images.githubusercontent.com/12764126/89098222-25668200-d418-11ea-8469-c694f1a63edb.png)

想知道 @Inject 是如何知道 ctx 等属性指向的是什么？难道是通过代码写死的吗？

**Comment by czy88840616** [comment]
inject 会获取到当前属性的 key，从 ioc 容器中查询匹配的值。这些 key 默认的值是框架提前配置好的，属于默认的行为。

比如这个地方，https://github.com/midwayjs/midway/blob/master/packages/midway-web/src/loader/webLoader.ts#L177 就是注入了 appDir 这个值。

https://github.com/midwayjs/midway/blob/master/packages/midway-core/src/requestContainer.ts#L23 这个地方注入了 ctx 和 logger。

**Comment by lleohao** [comment]
是否可以给默认注入的对象添加 interface ？如 

```typescritp
interface Context {
 ...
}

@inject()
ctx: Context;
```

这样方便使用，不然现在的注入的对象对开发者来说就是个黑盒，完全不知道怎么去使用

**Comment by czy88840616** [comment]
可以的，其实有定义。

```ts
import { Context } from 'midway';
```
