### ISSUE TITLE
midway可以直接使用egg-validate吗？

### ISSUE THREAD

**Issue by dhy1994** [midwayjs/midway#581]
在plugin.ts中配置了
````
export const validate = {
  enable: true,
  package: "egg-validate",
};
````
直接调用ctx.validate()
报错Cannot read property 'app' of undefined
好像是没有把validate绑定到ctx上

**Comment by ddzyan** [comment]
插件对象将挂载在 app 对象上
![image](https://user-images.githubusercontent.com/9130123/89172941-07368880-d5b6-11ea-84b6-94b39bf50808.png)

**Comment by czy88840616** [comment]
@dhy1994 测试了下函数和 midway v1 的应用，均未发现问题 ，ctx 上均有 validate 属性并正常执行。

![image](https://user-images.githubusercontent.com/418820/89205379-39fa7400-d5ea-11ea-862b-dd068c4578b8.png)
![image](https://user-images.githubusercontent.com/418820/89205397-4088eb80-d5ea-11ea-9e6a-28e72daeb907.png)

**Comment by dhy1994** [comment]
> @dhy1994 测试了下函数和 midway v1 的应用，均未发现问题 ，ctx 上均有 validate 属性并正常执行。
> 
> ![image](https://user-images.githubusercontent.com/418820/89205379-39fa7400-d5ea-11ea-862b-dd068c4578b8.png)
> ![image](https://user-images.githubusercontent.com/418820/89205397-4088eb80-d5ea-11ea-9e6a-28e72daeb907.png)

````
const { validate } = this.ctx;
console.log(validate({ id: "id" }, { id: "123" }));
````
this.ctx.validate()正常
用解构后的validate()就会报错

**Comment by czy88840616** [comment]
@dhy1994 这个咋解构。。有示例么。。

**Comment by dhy1994** [comment]
> @dhy1994 这个咋解构。。有示例么。。

const { validate } = this.ctx;
console.log(validate({ id: "id" }, { id: "123" }));

**Comment by czy88840616** [comment]
@dhy1994 我拿egg应用测了下也的确是这样，结构了绑定的 this 就变了。看起来是 egg 体系的问题，这里不能用解构的写法。

**Comment by dhy1994** [comment]
> @dhy1994 我拿egg应用测了下也的确是这样，结构了绑定的 this 就变了。看起来是 egg 体系的问题，这里不能用解构的写法。

en
