### ISSUE TITLE
在midway中使用sequelize 关系模型查询，字段无法聚合

### ISSUE THREAD

**Issue by tkvern** [midwayjs/midway#595]
midway.js项目中使用 sequlize关系模型，查询出来的结果没有聚合。请问是配置问题吗？

### 现象
![image](https://user-images.githubusercontent.com/10667077/89879462-94e92800-dbf5-11ea-9fcb-7150a883adb6.png)

### 源码截图
![image](https://user-images.githubusercontent.com/10667077/89879578-c19d3f80-dbf5-11ea-85f9-766219b87d54.png)

![image](https://user-images.githubusercontent.com/10667077/89879634-d083f200-dbf5-11ea-840d-ee337acdedb1.png)

### 仓库地址
https://github.com/fsd-nodejs/service

**Comment by kurten** [comment]
抱歉，这个和midway本身没有关系，建议要使用的话查阅一下  https://github.com/RobinBuschmann/sequelize-typescript#how-to-enable-repository-mode。
另，我定位了一下，应该是你find 参数时传了 ```raw: true ``` 导致返回结果转换了数据。

**Comment by tkvern** [comment]
@kurten 谢谢，我流下了惭愧的汗水～
