### ISSUE TITLE
示例中的vue一体化项目启动成功后，监听请求一直报这个错

### ISSUE THREAD

**Issue by Tmamasay** [midwayjs/midway#607]
Info: find url "/api/index" match pattern "/api/index", functionName="index"
Error: Command failed: curl 127.0.0.1:50714
'curl' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by czy88840616** [comment]
因为用了 curl。。windows 不兼容。。

**Comment by czy88840616** [comment]
已修复发布，更新即可。

**Comment by Tmamasay** [comment]
收到

**Comment by Tmamasay** [comment]
更新@midwayjs/faas-cli的版本为1.2.4后，通过f create --template-package=@midwayjs-examples/faas-with-vue 生成的vue一体化项目还是报上述的错误，大佬帮帮忙

**Comment by czy88840616** [comment]
容我找台 windows 机器……

**Comment by Tmamasay** [comment]
...................

**Comment by Tmamasay** [comment]
好得

**Comment by czy88840616** [comment]
我的 windows 上未出现，你可以删了 package-lock.json 再安装试试。

**Comment by Tmamasay** [comment]
要得，我试试

**Comment by czy88840616** [comment]
@techbirds 看看 `api.index` 的那个 class，是否和别的 class 重命名了，以及是否写了 @Func('api.index')

**Comment by czy88840616** [comment]
@techbirds 是在 windows 上么？

**Comment by techbirds** [comment]
> os Mac 10.14.6

@czy88840616 mac

**Comment by echosoar** [comment]
![image](https://user-images.githubusercontent.com/14832743/91851593-0b77c380-ec92-11ea-9044-ccf688c0ee1b.png)

刚刚跑了下没有复现出来问题，重新安装了最新版的 @midwayjs/faas-cli，使用 cnpm 安装的依赖，我的环境是：
Mac 10.14.2
node 12.16.2
typescript 3.8.3
