### ISSUE TITLE
不支持egg-socket.io

### ISSUE THREAD

**Issue by yuu2lee4** [midwayjs/midway#61]
midway的controller与egg-socket.io的controller似乎有冲突

**Comment by czy88840616** [comment]
我看一下

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/48692436-065a9900-ec11-11e8-96d4-203af8261f5e.png)

是找不到controller的错么 ？

**Comment by czy88840616** [comment]
egg-socket.io 里的普通控制器写法是支持的，装饰器写法应该没有支持。

https://github.com/midwayjs/midway-examples/blob/master/socket-io/src/app/io/controller/chat.ts

**Comment by yuu2lee4** [comment]
现在是写了egg-socket.io的controller 就报HomeController重复定义 删除midway的controller目录 就不报了 但是router调不通  在egg没问题

**Comment by czy88840616** [comment]
HomeController ？ 这个一般是用了 `const xxx` 多次导致的。

**Comment by czy88840616** [comment]
我发现问题了，貌似是加载路由的时候 egg 先加载了一遍导致判重了。

**Comment by czy88840616** [comment]
fixed

**Comment by xiongsongsong** [comment]
请问什么时候支持装饰器的写法呢？
