### ISSUE TITLE
f package 执行后AnalyzeResult，ProjectType不确定，导致部署失败，跟src 建立pages目录有关？

### ISSUE THREAD

**Issue by maqi1520** [midwayjs/midway#616]
## 遇到问题
本地调试可以，部署失败
![image](https://user-images.githubusercontent.com/9312044/90784707-23675300-e334-11ea-8281-665738f4372a.png)
## 实现步骤
- 使用 f create  react模板
![image](https://user-images.githubusercontent.com/9312044/90785211-abe5f380-e334-11ea-99bf-383f9ec31842.png)

f deploy 部署成功
- 使用 f create  react模板
在src 下建立`pages` 的空文件夹

f deploy 部署失败

![image](https://user-images.githubusercontent.com/9312044/90785062-848f2680-e334-11ea-8dcd-1df43755c0e4.png)

pages 改成page 就可以成功了

**Comment by czy88840616** [comment]
嗯，是的，识别默认是看目录结构，有一些特殊文件
