### ISSUE TITLE
[Error] Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session. AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.

### ISSUE THREAD

**Issue by qiang911217** [midwayjs/midway#624]
使用@midwayjs/orm组件， 以http方式调用函数。
初次调用api地址 ，一切正常。
更换api地址后就报错：[Error] Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session. AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.

例：
项目启动后 
访问http://localhost:3000/api/index/_index1, 这时候一切正常
然后访问http://localhost:3000/api/index/_index2, 就会报错

**Comment by czy88840616** [comment]
预期内行为，因为函数现在每个接口是单独启动的，而 orm 在每次执行都被完整启动了一次，typeorm 还有缓存，导致实例重复。这个和之前有个issue 相同。

线上没问题，只有本地存在。 @echosoar 思考下如何解决。

**Comment by echosoar** [comment]
fixed: https://github.com/midwayjs/midway-component/pull/12
