### ISSUE TITLE
middway文档-依赖注入手册一节中的警告信息中的新地址报404

### ISSUE THREAD

**Issue by shuidian** [midwayjs/midway#635]
midway-依赖注入手册一节：https://midwayjs.org/midway/ioc.html

第一行的警告内容中说最新文档已迁移到新的地址：https://midwayjs.org/injection/guide.html

但是这个新的地址无法打开，是404

补充一下，应该不只是这个地址，这一节中应该是所有的外链地址都不对了

**Comment by czy88840616** [comment]
不好意思，官网从 github 迁移到阿里云的时候漏了一部分，已恢复。
