### ISSUE TITLE
简化函数zip文件

### ISSUE THREAD

**Issue by wanghq** [midwayjs/midway#652]
todo示例，是否这些文件都是需要的？

`The function render has been packaged. A total of 1741 files were compressed and the final size was 3.48 MB`

![image](https://user-images.githubusercontent.com/321684/94625261-2e839c00-026d-11eb-9d70-697e1610f959.png)

**Comment by czy88840616** [comment]
需要的吧，build是前端构建出的文件，示例里是由函数托管了，实际我觉得交给cdn比较好，dist是函数文件。
