### ISSUE TITLE
Swagger组件：体验版异常汇总

### ISSUE THREAD

**Issue by ZQun** [midwayjs/midway#675]
### 异常1：param query参数undefined
![image](https://user-images.githubusercontent.com/12726554/96449136-fe656280-1246-11eb-9ff2-0a8d8da48ead.png)
![image](https://user-images.githubusercontent.com/12726554/96449199-189f4080-1247-11eb-9715-c1547f6436b0.png)

### 异常2：Try it out 账号密码文本框输入会被自动删除
![image](https://user-images.githubusercontent.com/12726554/96449420-6156f980-1247-11eb-947b-bd4044e84783.png)

### 异常3：点击Execute没有反应
![image](https://user-images.githubusercontent.com/12726554/96449499-8481a900-1247-11eb-994c-d968e7c56e94.png)

### 异常4：Param参数取path路径参数时swagger无填写路径参数的文本框，另外Execute也无法点击
![image](https://user-images.githubusercontent.com/12726554/96450022-420c9c00-1248-11eb-991d-f085d8bb35d1.png)
![image](https://user-images.githubusercontent.com/12726554/96450113-5b154d00-1248-11eb-8001-36dce1d97e94.png)

### 异常5：param携带body example参数在swagger文档内显示空对象{}
![image](https://user-images.githubusercontent.com/12726554/96450813-44bbc100-1249-11eb-89a9-71916b87b7c5.png)
![image](https://user-images.githubusercontent.com/12726554/96450915-69179d80-1249-11eb-81bb-c9af48ae9a47.png)

### 异常6：Try it out 携带body参数发起GET请求报错，不携带body参数正常！
![image](https://user-images.githubusercontent.com/12726554/96451205-d0355200-1249-11eb-810d-90da402e96a6.png)

**Comment by ZQun** [comment]
### 异常7：在swagger中取不到query上绑定的DTO
![image](https://user-images.githubusercontent.com/12726554/96452745-1095cf80-124c-11eb-8cb2-2da4af129404.png)

**Comment by ZQun** [comment]
@czy88840616 下午测试写文档，发现整体文档输出没有问题，基本就是这些小异常了

**Comment by czy88840616** [comment]
加了name以及方法名获取方式后，应该没问题了
