### ISSUE TITLE
支持指定多端口本地开发吗？--port=7002

### ISSUE THREAD

**Issue by ZQun** [midwayjs/midway#68]
https://github.com/midwayjs/midway/blob/c0d58b72e044397f83f1b1e3a5f05843948b0044/packages/midway-bin/lib/cmd/dev.js#L7

NODE_ENV=local midway-bin dev --ts --port=7002

**Comment by czy88840616** [comment]
可以的

**Comment by ZQun** [comment]
@czy88840616 厉害了   重新npm install 可以了

**Comment by fritx** [comment]
`npm run dev -- --port=7009` 或 `NODE_ENV=local midway-bin dev --ts --port=7009` 才可以
`PORT=7009 npm run dev` 不行

**Comment by czy88840616** [comment]
`midway-server-options` 是给服务器启动用的。

`midway-bin dev --ts --port=7002` 是把 port 参数传递给 midway-bin 命令，实际上是传递给了 egg-bin，普通走环境变量的确不行。

**Comment by fritx** [comment]
看看可否支持下 开多个的时候 去pkg里改--port 不大方便

**Comment by czy88840616** [comment]
今天年会，之后看看

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/52171402-7cde5000-2797-11e9-9ede-fe8a30493603.png)
@fritx 不好意思拖久了。

看了下，似乎egg-scripts是支持 PORT 环境变量，但是 `midway-bin/egg-bin` 不支持，但是本身会支持一个自动找空端口启动的能力，也就是说，同时启动多个，会自动分派不同的端口启动。

当然，如果需要指定的话，还是得改下。

**Comment by fritx** [comment]
@czy88840616 好的稍后提一个
