### ISSUE TITLE
typeorm 订阅如何注入context

### ISSUE THREAD

**Issue by xcore-oss** [midwayjs/midway#682]
我想在订阅里面使用context，试了inject没用，不知道有没有办法可以在订阅里面使用context

**Comment by kurten** [comment]
具体case可以用代码例举一下吗？

**Comment by xcore-oss** [comment]
`import { Inject } from "@midwayjs/decorator";
import { EventSubscriberModel } from "@midwayjs/orm";
import { Context } from "midway";
import { EntitySubscriberInterface, InsertEvent } from "typeorm";

@EventSubscriberModel()
export class EntitySubscriber implements EntitySubscriberInterface {
    @Inject()
    ctx: Context

    beforeInsert(event: InsertEvent<any>) {
        if (this.ctx) {
            // ctx为undefined
        }
        console.log(`BEFORE ENTITY INSERTED: `, event.entity);
    }
}`

**Comment by kurten** [comment]
1. 这个目前是typeorm自己内部发的事件、订阅，全局性的，不能绑定ctx。
2. orm 组件实现的时候，因为本身没有必要去大量改动内部事件订阅相关的逻辑，所以还是维持 typeorm 原有的逻辑。

**Comment by xcore-oss** [comment]
那有没有什么办法可以在事件订阅里面获取到当前的请求上下文呢?例如spring boot的SecurityContextHolder这样的

**Comment by kurten** [comment]
可以在 entity 上实现一下这个事件函数，然后 entity 设置一下 ctx 作为参数
https://github.com/typeorm/typeorm/blob/master/sample/sample9-entity-listeners/entity/Post.ts#L45

**Comment by xcore-oss** [comment]
这样做还是需要每次都手动赋值,那就跟直接把属性每次都赋值一遍没有任何区别了,有没有办法把上下文弄个线程安全的静态变量呢

**Comment by xcore-oss** [comment]
我想问个比较低级的问题
`process["context"] = ctx;`
这样写线程安全吗?会不会出现多个用户同时请求导致错乱

**Comment by czy88840616** [comment]
@xcore-oss 肯定会乱的。

**Comment by czy88840616** [comment]
新版版已实现

**Comment by zhengjunxin** [comment]
@czy88840616 新版已经可以在 Typeorm 中拿到 context 了？怎么拿啊？

**Comment by czy88840616** [comment]
文档已更新，事实上增加 @Provide，使用 @Inject() ctx 就好，和普通 service 一样。

**Comment by xcore-oss** [comment]
`@Provide()
@EventSubscriberModel()
export class EntitySubscriber implements EntitySubscriberInterface {
    @Inject()
    context: Context

    beforeInsert(event: InsertEvent<any>) {
        console.log(`BEFORE ENTITY INSERTED: `, this.context.data);
    }
}`
[ Midway ] start error: context in class EntitySubscriber is not valid in current context

**Comment by czy88840616** [comment]
看了下，这里有歧义，现在 orm 引入时是单例，和ctx是无法关联的。之前只是实现了@Config 这些的注入。
