### ISSUE TITLE
参数校验和转换

### ISSUE THREAD

**Issue by Hufe921** [midwayjs/midway#683]
使用文档中@Validate装饰器，没法进行验证结果拦截统一封装，如：
DTO：
![image](https://user-images.githubusercontent.com/27001251/97243698-db801300-1831-11eb-8c5e-05a1890f636c.png)

验证出错，因为属于方法装饰器，无法被catch捕获，不能对出参统一封装处理
![image](https://user-images.githubusercontent.com/27001251/97243727-ea66c580-1831-11eb-8b6f-7ead70cf3fef.png)

请问有没有好的验证结果捕获机制？

**Comment by czy88840616** [comment]
现阶段可以使用拦截器进行捕获，有增加校验器的计划。

**Comment by waitingsong** [comment]
@czy88840616  我认为使用 json-schema 格式定义规则可能更好，基于这种格式的校验包比较多。
比如 [ajv](https://github.com/ajv-validator/ajv) ，使用 ts->schema 转换包可以让一个类型定义同时适用于ts开发以及运行时的校验。适用性更广。

**Comment by Hufe921** [comment]
> 现阶段可以使用拦截器进行捕获，有增加校验器的计划。

我采用了方法拦截器，但是发现一个十分费解的问题：
![image](https://user-images.githubusercontent.com/27001251/97511177-67747500-19c1-11eb-8c52-e620ecb09729.png)

发起接口请求的时候，try捕获到了错误，会到catch里面，我会在ctx设置一个新key（ctx.hufe），用于middleware后续做判断
![image](https://user-images.githubusercontent.com/27001251/97511106-3ac05d80-19c1-11eb-9461-b052c8682c93.png)
但是发现问题：仅第一次ctx.hufe会有值，以后无论怎么失败ctx.hufe都是undefined，移除aspect就没事了

**Comment by czy88840616** [comment]
ctx 问题已修复，validate的问题后续有问题再开。
