### ISSUE TITLE
 Cannot find module when use paths alias in a faas-vue project

### ISSUE THREAD

**Issue by yoodu** [midwayjs/midway#684]
[Error Message] Cannot find module '@/apis/env'

I use paths alias in index.ts
`import { isDev } from "@/apis/env";`

and tsconfig.json is default settings
```
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
```

**Comment by Lxxyx** [comment]
前端也需要配置 path alias，ref：https://segmentfault.com/a/1190000016135314

**Comment by yoodu** [comment]
> 前端也需要配置 path alias，ref：https://segmentfault.com/a/1190000016135314

I have tried, but still can't work
```
module.exports = {
  outputDir: "build",
  pluginOptions: {
    faas: {
      // ...
    }
  },
  configureWebpack: {
    resolve: {
      alias: {
        "@": "src"
      }
    }
  }
};

```

**Comment by Lxxyx** [comment]
duplicate with #685
