### ISSUE TITLE
egg-scripts加入dependencies

### ISSUE THREAD

**Issue by yuu2lee4** [midwayjs/midway#69]
如题

**Comment by czy88840616** [comment]
之前想的是用pandora做默认启动器，不过正好pandora要出v2，可以把egg-scripts加上。

**Comment by czy88840616** [comment]
提个 mr ？
https://github.com/midwayjs/midway/blob/master/packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json#L6
