### ISSUE TITLE
midway v2版本如何在build的时候将json文件拷贝到dist文件夹下？

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#696]
json文件路径：
![image](https://user-images.githubusercontent.com/35318575/97839772-cf0e2580-1d1d-11eb-86e5-b2e028acac0a.png)

按照v1版本提供的构建增强方案：
![image](https://user-images.githubusercontent.com/35318575/97839800-db927e00-1d1d-11eb-951d-a9601781a478.png)

但build之后，并没有在dist文件夹发现mapper/user.json

**Comment by echosoar** [comment]
fixed: https://github.com/midwayjs/cli/pull/20
