### ISSUE TITLE
@midway/swagger插件使用问题

### ISSUE THREAD

**Issue by Hufe921** [midwayjs/midway#697]
当swagger响应类型设置成json的时候生成显示的内容格式不对：
代码：
![image](https://user-images.githubusercontent.com/27001251/97850848-895a5880-1d2f-11eb-82e2-5c8c73b29679.png)

swagger文档：
![image](https://user-images.githubusercontent.com/27001251/97850899-98d9a180-1d2f-11eb-9802-6c9756f208a1.png)

**Comment by czy88840616** [comment]
展示成对象的话：

- 1、要么类型变成text，
- 2、要么指定schema，但是我觉得返回值变成 DTO 结构有点麻烦

**Comment by tkvern** [comment]
返回值能否读 TS
