### ISSUE TITLE
如何使用 sequelize 事务

### ISSUE THREAD

**Issue by xialvjun** [midwayjs/midway#707]
拿不到 sequelize 实例

**Comment by ZQun** [comment]
@xialvjun 
```ts
const transaction: any = await this.ctx.model.transaction();
```

**Comment by xialvjun** [comment]
我知道了, 不过你的方式是 egg-sequelize 的方式, midway 的话, 似乎是要我们自己注册一个 单例 的 DB 对象, 在这个对象里注册所有的 Model... sequelize 实例也是在这个对象上.
