### ISSUE TITLE
egg-aixos 使用问题

### ISSUE THREAD

**Issue by EasonQwQ** [midwayjs/midway#728]
当前版本 
"midway": "^2.3.0",
"egg-axios": "^1.1.5",

文件plugins.ts 中 

import { EggPlugin } from 'egg';
export default {
  static: false, // default is true
  jwt: {
    enable: true,
    package: 'egg-jwt',
  },
  http: {
    enable: true,
    package: 'egg-axios',
  },
} as EggPlugin;

文件userService.ts中
  @Plugin()
  http;
async getCode(){
         const res= await this.http.get('https://api.weixin.qq.com/sns/jscode2session');
         console.logI(res)  // undefined
}

遇到的问题： res 是undefined

**Comment by EasonQwQ** [comment]
使用 const axios = require('axios');
使用const res = axios.get('xxxxx);
console.log(res)   // 也是undefined

**Comment by ZQun** [comment]
可以直接用egg的HttpClient呀 https://eggjs.org/zh-cn/core/httpclient.html

**Comment by EasonQwQ** [comment]
egg-axios   中的axios 版本问题，从0.18升级到0.21问题解决
