### ISSUE TITLE
midway cli fail in new prject

### ISSUE THREAD

**Issue by iot-lorawan** [midwayjs/midway#731]
Hi,
   when I use midway cli create project,but it always fail,
![图片](https://user-images.githubusercontent.com/30143031/100202188-f1b9e580-2f3b-11eb-9afb-5f22e9cb1d95.png)

![图片](https://user-images.githubusercontent.com/30143031/100202471-52492280-2f3c-11eb-8c70-b510034a5b55.png)

![图片](https://user-images.githubusercontent.com/30143031/100202517-612fd500-2f3c-11eb-80df-620234950d90.png)

![图片](https://user-images.githubusercontent.com/30143031/100202446-49f0e780-2f3c-11eb-95f0-e081a5e60900.png)

**Comment by czy88840616** [comment]
You can try node v12.

**Comment by iot-lorawan** [comment]
Hi，
   Thanks you for your help，now use mw new xxx --npm=npm can run ok
![图片](https://user-images.githubusercontent.com/30143031/100296120-5b7ed180-2fc6-11eb-8449-e5cf6779f2bd.png)
