### ISSUE TITLE
咨询个1.x版本的变量覆盖问题

### ISSUE THREAD

**Issue by caihaibin1991** [midwayjs/midway#732]
最近项目新增个功能，碰到一个很诡异的问题。循环，然后嵌套多层。发现调试模式，运行就正常。如果编译后启动，存在变量被覆盖的诡异问题。请问有没有人碰到过？

**Comment by czy88840616** [comment]
你这个要上代码了。。光描述不够了。。

**Comment by waitingsong** [comment]
如果有用 ESLint ，加上这条规则看看
https://eslint.org/docs/rules/no-shadow

**Comment by caihaibin1991** [comment]
> 如果有用 ESLint ，加上这条规则看看
> https://eslint.org/docs/rules/no-shadow

这边先从代码上加了标志，避免了问题。。。
我这两天看看能不能复现出来。。有点诡异。 一个http请求。。。回来，变量被替换的感觉。。
