### ISSUE TITLE
Cannot find module '@midwayjs/bootstrap'

### ISSUE THREAD

**Issue by falstack** [midwayjs/midway#739]
`@midwayjs/faas`从版本`1.x`升级到`2.5.0`后，本地`npm run dev`就报这个错了

**Comment by falstack** [comment]
Node.js             v12.13.1
@midwayjs/cli       v1.2.30
系统是 mac

**Comment by czy88840616** [comment]
2.x的版本的工具链还没有准备好，还是先使用 1.x 哦。
