### ISSUE TITLE
@midwayjs/swagger DTO层关联问题

### ISSUE THREAD

**Issue by tkvern** [midwayjs/midway#745]
关联到别的DTO去了

- 生成的文档和DTO
![image](https://user-images.githubusercontent.com/10667077/101738599-5e6add80-3b01-11eb-8141-4d7249ed7b0b.png)

- 应该要关联的DTO
![image](https://user-images.githubusercontent.com/10667077/101738718-85c1aa80-3b01-11eb-9486-add4e7d9b121.png)

- 最后错误关联的DTO
![image](https://user-images.githubusercontent.com/10667077/101738741-8fe3a900-3b01-11eb-86d5-35a0285dbf6a.png)

## 复现地址

https://github.com/fsd-nodejs/service-mw2
切换到develop分支

**Comment by czy88840616** [comment]
3.x 已实现。
