### ISSUE TITLE
egg 中用 onReady 配置没生效

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#746]
![image](https://user-images.githubusercontent.com/418820/101747942-d7b8ff00-3b06-11eb-9a60-1cc76bb51492.png)

理论上会生效的，记录后续排查下。

**Comment by mirari** [comment]
看看是不是config目录下的配置覆盖了
config.prod里如果写了config.middleware = []，就会覆盖onReady的里写的中间件

**Comment by czy88840616** [comment]
现在应该没问题了。
