### ISSUE TITLE
faas-standard项目本地运行总是Error: EPERM: operation not permitted, lstat '//Library/Caches/com.apple.aned'

### ISSUE THREAD

**Issue by nmvr2600** [midwayjs/midway#762]
系统是big sur
node版本v14.15.0

本地执行yarn dev的时候总是报这个错误
  Error: EPERM: operation not permitted, lstat '//Library/Caches/com.apple.aned'

Error: EACCES: permission denied, scandir '//var/agentx'
error Command failed with exit code 1.

**Comment by czy88840616** [comment]
这是啥。。。。看起来像是 alinode 在 var 下写文件没权限啥的。。

**Comment by nmvr2600** [comment]
本地启动完 一访问就报错 为什么需要访问/var下这么多文件夹 提示一个加了权限 又提示另外一个

**Comment by czy88840616** [comment]
我们并不要这些权限。。也不会对 var 写文件。你要看看是不是其他（不限于 node/npm 等）造成的。。

**Comment by nmvr2600** [comment]
那先放置一下吧，就是f create生成的代码
