### ISSUE TITLE
使用f deploy提示app_index sizes exceed 50M

### ISSUE THREAD

**Issue by nmvr2600** [midwayjs/midway#764]
使用mw生成了项目代码，添加f.yml
`service: mw-ts ## 应用发布到云平台的名字

provider:
  name: aliyun ## 发布的云平台，aliyun，tencent 等

deployType: egg ## 部署的应用类型
`
使用f deploy发布的时候报错
Waiting for service mw-ts to be deployed...
	Waiting for function app_index to be deployed...
		Waiting for packaging function app_index code...

Fun detected that your function mw-ts/app_index sizes exceed 50M.
? Use OSS bucket/object  as a function code, the codeSizeLimit can be expanded to 100M.You can deploy function with co? comm
and "fun package && fun deploy" Yes
Executing command 'fun package && fun deploy'...
Current folder not a fun project.
Deploy error: Command failed: fun package && fun deploy
%

这个有解决的方法吗？

**Comment by czy88840616** [comment]
把package-lock删了再试试

**Comment by nmvr2600** [comment]
有效！

**Comment by xmsz** [comment]
我也遇到了 这个是什么原理？

**Comment by czy88840616** [comment]
你这是真的大。。。因为 "@midwayjs/cli-plugin-faas": "^1.2.73", 这个应该在 devDep 里。。。。

**Comment by xmsz** [comment]
> 你这是真的大。。。因为 "@midwayjs/cli-plugin-faas": "^1.2.73", 这个应该在 devDep 里。。。。

嗯 我后面也发现了，不过流程是这样的

- cli创建项目
- deploy
- 提示我没安装`@midwayjs/cli-plugin-faas`
- cli自动帮我安装了
- 但是居然是安装在生产dep里而不是devDep
- 后面才看到

所以cli安装@midwayjs/cli-plugin-faas的时候应该处理一下

**Comment by czy88840616** [comment]
这是由于不同的npm 安装策略不同，有些版本会丢以来，有些又不会，你可以把依赖手写到dev依赖里

**Comment by xmsz** [comment]
> 这是由于不同的npm 安装策略不同，有些版本会丢以来，有些又不会，你可以把依赖手写到dev依赖里

ok
