### ISSUE TITLE
apis如何引用apis外的文件

### ISSUE THREAD

**Issue by xmsz** [midwayjs/midway#769]
需求背景
- src
 - apis
  - lambda
   - user.ts
- models
 - user.ts

我想在lambda/user.ts引用user.ts的内容
更具体的需求就是，前后端共用一份typescript类型。

但是我在lambda/user.ts引用user.ts（存放类型的地方）则提示不能引用apis外得文件

这样得需求要怎么解决

**Comment by Lxxyx** [comment]
目前因为打包优化，暂不支持引用 apis 外的文件。

建议把共用的类型放在 apis 内，前端可以引用 apis 内的文件

**Comment by xmsz** [comment]
> 目前因为打包优化，暂不支持引用 apis 外的文件。
> 
> 建议把共用的类型放在 apis 内，前端可以引用 apis 内的文件

好吧 那我先这么处理
