### ISSUE TITLE
v1.0 的发布

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#78]
计划在 12 月中旬发布 1.0，尽快进入 1.0 的版本迭代，这样在开发过程中的版本升级会变的比较容易。

TODO

- 和 egg 一样的文档部分需要补充
- 现有的 MR 和 issue 能清理的尽量清理掉
- 发布稿 (ATA, 知乎，掘金等）

**Comment by ZQun** [comment]
@czy88840616 1.0之后要用pandora做默认启动器吗？

[_package.json](https://github.com/midwayjs/midway/blob/master/packages/midway-init/boilerplate/midway-ts-boilerplate/boilerplate/_package.json)

**Comment by czy88840616** [comment]
暂时不会，pandora正在做v2的重构
ZQun <notifications@github.com>于2018年12月10日 周一下午6:50写道：

**Comment by ZQun** [comment]
@czy88840616 1.0在npm还没发布吗？

**Comment by czy88840616** [comment]
发了，在beta的tag上

**Comment by qiqizjl** [comment]
Hi.这边看到 已经发布了1.0.3了~ 这是否代表着这个项目已经稳定，且可以用于线上环境呢？

**Comment by czy88840616** [comment]
没问题，我们线上从最开始就已经使用了大半年，最近几个月内淘宝的应用都逐步迁移到到这个体系上，稳定性没有问题。
耐小心 <notifications@github.com>于2018年12月29日 周六下午9:02写道：
