### ISSUE TITLE
第一次看到这个框架，有点懵，请指教v1和v2的区别

### ISSUE THREAD

**Issue by text88888** [midwayjs/midway#785]
文档显然不一样。这是两个版本？还是两个部分？

那么分别对应的代码分支是哪个？

谢谢你

**Comment by czy88840616** [comment]
v2是年底新发布的版本，v2的文档也多很多，新项目请使用 v2，对应分支 https://github.com/midwayjs/midway/tree/2.x

**Comment by text88888** [comment]
> v2是年底新发布的版本，v2的[文档](https://www.yuque.com/midwayjs/midway_v2)也多很多，新项目请使用 v2，对应分支 https://github.com/midwayjs/midway/tree/2.x

谢谢您的指点
