### ISSUE TITLE
config/logger 实例的定义

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#79]
用户提出缺少这个定义，在使用时不是很方便。同时也要考虑下插件以及整个 midway 体系的定义机制。

**Comment by CheneyZhangCH** [comment]
eggjs的配置在midway内没有生效
`  config.logger = {
    disableConsoleAfterReady: false,
  };`

**Comment by czy88840616** [comment]
已经将常用的定义通过 midway 导出。
