### ISSUE TITLE
连接池的基础类

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#80]
在使用 knex，mysql，sequelize 等三方类的定义中，需要获取一个connection，但是在 midway 的体系中，默认的 ioc 是请求作用域，这就导致如果用户在连接池实例的配置上不做处理的话，每个请求都会创建一个连接导致出问题。

建议在 DAO 层产出一个基础单例类，用于使用

**Comment by solarhell** [comment]
这个有后续吗？

**Comment by czy88840616** [comment]
目前sequelize-typescript，type-orm都能使用，暂时没有时间做这个了。

**Comment by solarhell** [comment]
好的 谢谢 暂时参考这个例子了 https://github.com/midwayjs/midway-examples/tree/master/demo-sequelize-typescript

**Comment by czy88840616** [comment]
已经提供了 orm 组件。
