### ISSUE TITLE
run 目录的问题

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#81]
- 1、看起来需要有个命令去清理它，或者每次开发时清理上一次
- 2、看起来需要一份 pluginContext 的key，方便用户可以  @plugin()  插件
- 3、run/router 中没有路由装饰器的信息

**Comment by ZQun** [comment]
可以把基础命令补充在midway-init -> _package.json 里面吧？

**Comment by czy88840616** [comment]
恩，主要是昨天整理文档发现已经做了这个命令，所以备注一下，怕忘了
