### ISSUE TITLE
RuleType 中的 empty 不生效

### ISSUE THREAD

**Issue by sinceseason** [midwayjs/midway#812]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

dto
```
class Dto{
    @Rule(RuleType.string().empty().trim())
    note: string;
}
```

http请求
```
{
    id:1,
    note:""
}
```

报错信息：
![image](https://user-images.githubusercontent.com/14029440/105260153-3ecad880-5bc8-11eb-9757-366ad7bed5d8.png)

如果允许为空，应该怎么做呢？

**Comment by czy88840616** [comment]
RuleType.string（）.required（）

**Comment by czy88840616** [comment]
好像没搜到 https://joi.dev/api/ empty 方法。。我理解默认是允许不传，如果必传，直接用 require() 就行了吧。

**Comment by stone-jin** [comment]
```
class Dto{
    @Rule(RuleType.string().empty('').trim())
    note: string;
}
```

你是说这样吗？在empty()的参数里面加一个空字符串

**Comment by stone-jin** [comment]
https://joi.dev/api/#anyemptyschema

![image](https://user-images.githubusercontent.com/6525544/105275483-72166300-5bda-11eb-8469-0bd498402df9.png)

**Comment by stone-jin** [comment]
如果你的需求是，比如用户不传参数，你给他一个默认值可以如下：

```
Joi.string()
    .empty('')
    .default('default value');
```

也就是:

```
class Dto{
    @Rule(RuleType.string().empty('').trim().default('hello world'))
    note: string;
}
```

不知道哪种满足你需求，详细可以查看Joi的文档：https://joi.dev/api/?v=17.3.0，看看哪种能满足你需求？

**Comment by sinceseason** [comment]
需求是允许 node 这个字段传入一个空字符串，不指定其默认值
另外： allow("") 可以实现这个需求
```
class Dto {
    @Rule(RuleType.string().trim().allow("").empty())
    note: string;
}
```

**Comment by sinceseason** [comment]
> 如果你的需求是，比如用户不传参数，你给他一个默认值可以如下：
> 
> ```
> Joi.string()
>     .empty('')
>     .default('default value');
> ```
> 
> 也就是:
> 
> ```
> class Dto{
>     @Rule(RuleType.string().empty('').trim().default('hello world'))
>     note: string;
> }
> ```
> 
> 不知道哪种满足你需求，详细可以查看Joi的文档：[https://joi.dev/api/?v=17.3.0，看看哪种能满足你需求？](https://joi.dev/api/?v=17.3.0%EF%BC%8C%E7%9C%8B%E7%9C%8B%E5%93%AA%E7%A7%8D%E8%83%BD%E6%BB%A1%E8%B6%B3%E4%BD%A0%E9%9C%80%E6%B1%82%EF%BC%9F)

这样可以了

**Comment by stone-jin** [comment]
ok，那欢迎继续提问，我close这个问题了
