### ISSUE TITLE
midway2 如何在配置文件修改默认端口？

### ISSUE THREAD

**Issue by Lxsbw** [midwayjs/midway#818]
我在config.default.ts中这么写没有效果，是相比1.X变了吗

  config.cluster = {
    listen: {
      path: "",
      port: 7002,
      hostname: "127.0.0.1",
    },
  };

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
config.cluster是 egg-cluster 的配置，midway 在 dev 时已经不再使用 egg-cluster，所以不会生效。

相应的，可以在 dev 时增加端口解决。

```bash
"dev": "midway-bin dev --ts --port=6001"
```

部署时，如果使用 egg-scripts，将会继续生效。
