### ISSUE TITLE
controller 是否需要增加中间件match能力

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#82]
现在 controller 里没法向以前 router 中那样前置中间件，要么只能全局，通过配置 match 特定的路由加，不是很方便和直观。

**Comment by ZQun** [comment]
这个功能很好！👍

**Comment by atzcl** [comment]
@czy88840616 我看了源码，觉得可以在 `controller`、`路由（get..等）` 装饰器里面加中间件的配置，我现在粗略实现了在路由装饰器里面添加对应 `egg router` 的限定参数
```js
// controller
...
import VerifyJwt from '@my_modules/user/middlewares/verify-jwt';
...

@get('/', { name: 'test', middleware: [ VerifyJwt ] })
async index() {
...
}
```
修改的源码：
`routerName?: any`  ====> `routerOptions?: { name?: string, middleware:  Function[] }`

```js
// loader/webLoader.ts
                           const middleware = [];
                            const { routerOptions } = mappingInfo;
                            if (routerOptions &&
                                routerOptions.middleware &&
                                Array.isArray(routerOptions.middleware) &&
                                routerOptions.middleware.length > 0
                            ) {
                                routerOptions.middleware.forEach(fn => {
                                    if (typeof fn === 'function') {
                                        middleware.push(fn(app));
                                    }
                                })
                            }

                            const routerArgs = [
                                routerOptions && routerOptions.name ? routerOptions.name : undefined,
                                mappingInfo.path,
                                ...middleware,
                                this.generateController(`${controllerId}.${methodName}`),
                            ];
```

**Comment by atzcl** [comment]
`middleware` 的值，我觉得可以是直接传入中间件函数，或者是先把中间件注册到 `IoC` 容器中，然后就只需要传入对应的中间件 id

**Comment by atzcl** [comment]
在 `controller` 装饰器里面拓展：
```js
...
import VerifyJwt from '@my_modules/user/middlewares/verify-jwt';
...

@controller('/test', { middleware: [ VerifyJwt ] })
export class TestController {
 //
}
```

修改源码：
```ts
// decorators/application.ts

export function controller(routerPrefix: string, options = {}) {
  return function (target: any): void {
    Reflect.defineMetadata(WEB_ROUTER_PREFIX_CLS, [ routerPrefix, options ], target);
    scope(ScopeEnum.Request)(target);
  };
}
```

```ts
// loader/webLoader.ts
...
const [ controllerPrefix, controllerOptions ] = Reflect.getMetadata(metaKeys_1.WEB_ROUTER_PREFIX_CLS, target);
...

// 剩下的就跟上面的路由装饰器一样，不同的是要给每一个路由都添加由 controller  传入的中间件，如果 controller、路由装修都实现这样的功能，那么可能还要考虑一下合并重复项的问题
```

**Comment by czy88840616** [comment]
这块也可以讨论下，中间件有两部分，一是全局中间件，egg 使用的那种，应用于所有 router，通过 ignore 和  match 来匹配路由。

另一类是特定路由需要的 koa middleware，主要是这一块。

和 @atzcl 的大体差不多，其实只需要一个 id 或者函数名即可，由于 egg 只有全局中间件会加载到 app.middleware 中，所以这块用不上。

我之前计划的是参考 nest 的方式，提供标准的中间件接口，类似下面的。

```ts

@provide('indexMiddlware')
export class IndexMiddleware implements WebMiddleware {

  resolve(options) {
    return async (ctx, next) => {
	  
    }
  }
}


@provide()
@controller()
@middleware(['indexMiddlware'])  // 能放这里
export class HomeController {

  @middleware(['indexMiddlware'])  // 也能放这里
  @get('/')
  index() {
    // TODO
  }
}

```

后来发现其实 RPC 提供服务，包括未来的 serverless 体系，似乎都有类似的需求，比如在做服务发布的时候，有一些接口需要统一的校验，这个时候就非常像 koa middleware 的方式，同时又不太适合类继承的模式。

想着是不是需要一个统一的 filter/pipeline/validate 的模型，这块还没想好。

**Comment by atzcl** [comment]
@czy88840616  你说的这些感觉在正常的业务里面都会用到，不过个人觉得官方只需要把跟整个框架耦合的部分，实现了对应的装饰器来操作就可以了，其他的就由开发者自己实现也可以，无非就是类装饰器、方法装饰器，比如我自己就实现了  `validate` 验证、`resource` Api 资源转换等等，当然如果官方都能提供对应的最佳实践，那肯定是最好的啦

**Comment by czy88840616** [comment]
恩，我们会提供一些通用的，跟框架耦合比较紧密的。

**Comment by atzcl** [comment]
@czy88840616 大佬，这个大概什么时候可以用上呢~😂

**Comment by czy88840616** [comment]
@Lellansin 有空搞不。。既然自定义装饰器搞好了。。

**Comment by Lellansin** [comment]
自定义装饰器替换原本的逻辑，后面可能不太好做最小改动的替换，可能要直接用新的自定义装饰器 feature 重写 @controller 然后在加这个 @middleware 装饰器的功能

**Comment by atzcl** [comment]
@czy88840616 @Lellansin 大佬们，有任何进展嘛？

**Comment by czy88840616** [comment]
我先把装饰器分离出来吧。

**Comment by czy88840616** [comment]
先回复一个，代码基本实现完了。

思考了一下，实现过程中觉得 @atzcl 的方式好一些，原因如下：

- 1、middleware属于web范围，只会出现在 @controller / @get/@post 这几个装饰器出现的时候，没有单独的可能性
- 2、参数校验装饰器虽然和 middleare 很像，但是本质上有着不同，因为 middleare 的参数和校验器不太一样，逻辑也不同，这一层没法抽象
- 3、ts 中，middleware装饰器的返回值目前不能既是方法装饰器，又是类装饰器，不好明确定义，实现过程中只能变成 any，也不怎么优雅，属于 ts 的问题

**Comment by czy88840616** [comment]
可以看看，回头我更新到文档里。https://github.com/midwayjs/midway/pull/155

**Comment by atzcl** [comment]
@czy88840616 大佬辛苦了~ 特性一非常棒，加上本来就使用 `IoC` 来解耦依赖关系，这样无意间就解决了 `egg` 本身没有解决的事情：单应用多模块开发 (虽然可以自己使用 `loader` 来解决，但是也很麻烦)
相关 issue [#2216](https://github.com/eggjs/egg/issues/2216)、[#735](https://github.com/eggjs/egg/issues/735)

**Comment by czy88840616** [comment]
我们在 sandbox 的开发中也实践过，可以单独抽离一个 service 包，然后在 container 的加载中配置上就行了，反正都是 ioc 扫描，放哪都行。

**Comment by atzcl** [comment]
期待合并、发版 🎉🎉🎉

**Comment by czy88840616** [comment]
昨天本来想把类也加进去。。发现没法定义。。

**Comment by czy88840616** [comment]
先发了一版 midway@next

**Comment by ZQun** [comment]
@czy88840616 更新到midway@next   schedule定时任务会有报错：must use @schedule to setup.

**Comment by czy88840616** [comment]
哦，对，schedule 插件那边还没支持。 @Lellansin

**Comment by czy88840616** [comment]
同步下进展 https://github.com/midwayjs/midway/pull/156

- 支持 @schedule 装饰器到最新版 egg-schedule
- 和 egg-schedule 基本解耦
- 不支持 egg-schedule 的自定义策略，只支持默认的两个（谁会自定义。。。)
- 还差一个 runSchedule。。等等改。

**Comment by czy88840616** [comment]
改完了，发了  midway@1.4.2，可以试试先 @ZQun  @atzcl

**Comment by ZQun** [comment]
@czy88840616 
体验了一下，在src/app和src/lib目录内创建controller/service都没有问题，在src/下新建其他目录，保存文件时不会自动刷新终端

**Comment by czy88840616** [comment]
这个应该是 watcher 之前配置的问题，干脆直接配 src 好了。。

**Comment by czy88840616** [comment]
@ZQun https://github.com/midwayjs/midway/pull/24/files#diff-6d5a47204caab757fba3d8c4fbd82f9c 是因为之前改的这个地方么？

**Comment by ZQun** [comment]
@czy88840616 对，试了一下，通过配置文件更改config.development没有办法配置到src根目录

```typescript
// 方法1
config.development = {
    watchDirs: [''],// 配置为程序根目录 src 会重复执行重新加载 error
    overrideDefault: true,
};
// 方法2
config.development = {
    reloadPattern: ['**'],// 配置为通配符不生效，程序里没看到这块的逻辑
};
```
https://github.com/eggjs/egg-development/blob/769975f207532f8e5b53b030facbcdcac5ed13b3/agent.js#L69

不行还是通过配置文件development.watchDirs手动加入[Array]配置自动刷新的目录吧😂

**Comment by Lellansin** [comment]
> 哦，对，schedule 插件那边还没支持。 @Lellansin

@czy88840616  可以的，相信你 🦊

**Comment by czy88840616** [comment]
@ZQun 我看了下 development 插件，目前 reloadPattern 也是基于 baseDir 的，所以也无法生效，最简单的方法也还是自己在 watchDirs 中加目录。

**Comment by atzcl** [comment]
已经更新，正在使用，感谢大佬们的奉献~

**Comment by czy88840616** [comment]
如果没有问题，我计划待会儿就切到 latest。

**Comment by czy88840616** [comment]
已经切到 midway@latest，使用 next 的请修改。
