### ISSUE TITLE
有关方法拦截器的疑问

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#821]
1、方法拦截器的作用于是单例的吗？我设置作用域为请求上下文，但发现还是在服务启动的时候进行实例化，并不是想象中当调用api的时候去创建。
2、方法拦截器中该如何获取请求上下文。像其他代码一样@Inject() ctx:Context; 打印之后是undefined
![image](https://user-images.githubusercontent.com/35318575/105673638-491b0880-5f21-11eb-842f-dbac44988bda.png)

**Comment by czy88840616** [comment]
拦截器固定是单例，可以通过 point.target.ctx 获取（如果注入了 ctx 的话）

**Comment by feiyueXH** [comment]
难顶，目标不是的作用域并不在一个请求上下文中，ctx是注入不了的。

**Comment by feiyueXH** [comment]
难顶，目标的作用域并不在请求上下文中的，没办法注入ctx。

**Comment by czy88840616** [comment]
如果目标本身就不在请求作用域，那肯定拿不到ctx 啊-、-

**Comment by feiyueXH** [comment]
是这样的，我的项目使用的数据库ORM是mongoose，我想在执行数据库操作时默认添加事务（暂时先是请求级别的事务），所以想用方法切面对方法入参进行修改，自动添加session参数。但现在因为方法拦截器是单例的，卡在这了。

**Comment by feiyueXH** [comment]
是否能像中间件那样为声明周期方法提供请求上下文

**Comment by czy88840616** [comment]
因为拦截器是直接应用到实例本身的，如果实例不是请求作用域，也是没有办法拿到上下文的。。

**Comment by feiyueXH** [comment]
嘿，我发现一个问题，await this.dbCtx.switchModel('cart').update(
      { cartId: cart.getCartId() },
      { lastUpdateTime: Date.now() }
    );
我对dbCtx中的方法进行拦截，当我这样子去链式调用，发现只能拦截switchModel方法，update方法拦截不了，除非我老老实实将switchModel和update分开调用，update才能被拦截调用。
