### ISSUE TITLE
EntityModel中如何去获取 app.config

### ISSUE THREAD

**Issue by sinceseason** [midwayjs/midway#827]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

```
@EntityModel({ name: "base" })
export class BaseModel {
	
	@Column({ type: "text" })
	url: string;

	httpUrl:string

	@AfterLoad()
	setHttpUrl(ctx: Context) {
		// this.httpUrl = process.env.prefix + this.filename
		this.httpUrl = ctx.app.config['prefix'] + this.filename  // undefined
	}
}
```
请教一下，entity 中如何去获取 app.config 呢，目前是undefined.
直接用process.env.prefix ?

**Comment by czy88840616** [comment]
orm 的环境是独立的，这里拿不到 ctx/app，实体这里也不应该拿到配置吧。。要拿的话在外层 service 处理吧。

**Comment by boostbob** [comment]
entity 不应该读取配置.
