### ISSUE TITLE
@midwayjs/socketio 如何配置SocketIO的初始化信息

### ISSUE THREAD

**Issue by ghostoy** [midwayjs/midway#828]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**: @midway/socketio
* **Plugin Version**: 2.7.0
* **Platform**:
* **Mini Showcase Repository**:

按照[packages/socketio/test/fixtures/base-app](https://github.com/midwayjs/midway/tree/2.x/packages/socketio/test/fixtures/base-app)构建的项目，默认只能使用/socket-io作为入口，想要传入`path`来自定义这个入口，但是没有找到@midwayjs/socketio这个组件自定义配置的入口。

**Comment by czy88840616** [comment]
应该是在 @WSController 的参数上写的。

**Comment by 329988300** [comment]
> * **Node Version**:
> * **Egg Version**:
> * **Plugin Name**: @midway/socketio
> * **Plugin Version**: 2.7.0
> * **Platform**:
> * **Mini Showcase Repository**:
> 
> 按照[packages/socketio/test/fixtures/base-app](https://github.com/midwayjs/midway/tree/2.x/packages/socketio/test/fixtures/base-app)构建的项目，默认只能使用/socket-io作为入口，想要传入`path`来自定义这个入口，但是没有找到@midwayjs/socketio这个组件自定义配置的入口。

请问你是怎么配置的，我装上这个socketio后，api全404了，而且实例里面没见到需要配置东西

**Comment by ghostoy** [comment]
> > * **Node Version**:
> > * **Egg Version**:
> > * **Plugin Name**: @midway/socketio
> > * **Plugin Version**: 2.7.0
> > * **Platform**:
> > * **Mini Showcase Repository**:
> > 
> > 按照[packages/socketio/test/fixtures/base-app](https://github.com/midwayjs/midway/tree/2.x/packages/socketio/test/fixtures/base-app)构建的项目，默认只能使用/socket-io作为入口，想要传入`path`来自定义这个入口，但是没有找到@midwayjs/socketio这个组件自定义配置的入口。
> 
> 请问你是怎么配置的，我装上这个socketio后，api全404了，而且实例里面没见到需要配置东西

`src/configuration.ts`
```typescript
import { App, Configuration } from '@midwayjs/decorator';
import { ILifeCycle } from '@midwayjs/core';
import { IMidwaySocketIOApplication } from '@midwayjs/socketio';

@Configuration()
export class ContainerLifeCycle implements ILifeCycle {
  @App()
  app: IMidwaySocketIOApplication;

  async onReady(): Promise<void> {
    this.app.on('connection', socket => {
      console.log('global connection', socket.id);

      this.app.on('my', () => {
        console.log('got my event');
      });

      this.app.on('disconnect', () => {
        console.log('closing socket server');
      });
    });
  }
}

```

`src/socket/api.ts`
```typescript
import {
  Emit,
  Inject,
  OnConnection,
  OnDisConnection,
  OnMessage,
  Provide,
  WSController,
} from '@midwayjs/decorator';
import { UserService } from '../service/user';
import { IMidwaySocketIOContext } from '@midwayjs/socketio';

@Provide()
@WSController('/')
export class APIController {
  @Inject()
  ctx: IMidwaySocketIOContext;

  @Inject()
  userService: UserService;

  @OnConnection()
  init(): void {
    console.log(`namespace / got a connection ${this.ctx.id}`);
  }

  @OnMessage('my')
  @Emit('ok')
  async gotMyMessage(payload) {
    return await this.userService.getUser(payload);
  }

  @OnDisConnection()
  disconnect(reason: string) {
    console.log(this.ctx.id + ' disconnect ' + reason);
  }
}

```

**Comment by czy88840616** [comment]
已经发布，文档已更新。
