### ISSUE TITLE
使用 koa 作为 Web 框架时 @Body 数据为 undefined

### ISSUE THREAD

**Issue by xuxucode** [midwayjs/midway#834]
* **Node Version**: v14.15.0
* **@midwayjs/koa Version**: 2.7.2 
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: mac OS Big Sur
* **Mini Showcase Repository**: https://github.com/xuxucode/midway-koa-body-undefined

#### 1. 初始化项目：`mw new hello_koa --template=@midwayjs-examples/applicaiton-koa`，并添加 Post 方法：
```js
// hello_koa/src/controller/home.ts
import { ALL, Body, Controller, Post, Provide } from '@midwayjs/decorator';
import { User } from '../interface';

@Provide()
@Controller('/api/user')
export class HomeController {

  @Post('/')
  async updateUser(@Body(ALL) user: User ) {
    console.log('=== user: ', user); // user 为 undefined
    return {
      user,
    }
  }
}
```
#### 2. 前端发送 POST 请求：
```http
POST http://localhost:7001/api/user HTTP/1.1
content-type: application/json

{
  "id": 1,
  "name": "aaa"
}
```
#### 3. 结果：获取不到 @Body 的 user 数据

但使用 Egg.js 作为 Web 框架时可以获取到 body 数据

**Comment by czy88840616** [comment]
恩，设计是这样的，koa 的用户一般是希望最少最精简的功能，我们默认只包含了 koa-router，没有给用户提供 koa-body/koa-bodyparser，作为弥补，我刚在脚手架中增加一个默认的 bodyparser 作为示例。

代码如下：

```ts
// configuration.ts
import { Configuration, App, Config } from '@midwayjs/decorator';
import { ILifeCycle } from '@midwayjs/core';
import { Application } from '@midwayjs/koa';
import * as bodyParser from 'koa-bodyparser';

@Configuration()
export class ContainerLifeCycle implements ILifeCycle {
  @App()
  app: Application;

  async onReady() {
    this.app.use(bodyParser());
  }
}
```

**Comment by xuxucode** [comment]
能否考虑下把 bodyparser 作为 @midwayjs/koa 的默认中间件，这样 midway 在不同 web 框架上会有更大程度的一致性。Web 框能够处理 json 的话能方便绝大多数场景。

**Comment by czy88840616** [comment]
这个我们考虑过，但是细想下去，会有些问题，目前没有加入一些默认的中间件，有一些原因：

- 1、koa 是属于比较开放、精简、自由的框架，如果加入一些我们选择的默认中间件，比如 bodyparser，koa-onerror，koa-session，static 等等，如果一旦有用户想替换，这是很困难的，而且默认加入的内容也不太好掌握度，加多了其实就和 egg 差不多了
- 2、这些中间件是会需要默认配置，比如 bodyparser 的 parse 类型，大小，static 的目录，session 的key，以及还要考虑让用户可以覆盖这些默认配置，以及中间件的加载顺序等等，koa 的灵活性会受到影响
- 3、考虑到使用 koa，而不是 egg 的用户应该也是属于对 koa 比较熟悉，希望能轻量运行，能完全自定义的这类人群，也有可能是希望能自定义框架能力的人群，所以我们还是把扩展的职责交还给用户本身

在这些情况下，如果使用 koa 框架，那么可以完全的自定义，去创造一个属于自己的上层框架，比如给团队定制。

有两种方法：

- 1、编写一个组件，引入一些默认的中间件即可，然后每个用户在入口出引入
- 2、从当前 koa 框架继承并覆盖一些能力，可以参考https://www.yuque.com/midwayjs/midway_v2/framework_development#QYhUj

不知道这样是否能理解。

**Comment by xuxucode** [comment]
解释得通，理解了。

**Comment by czy88840616** [comment]
@xuxucode 感谢理解 Thanks♪(･ω･)ﾉ

**Comment by waitingsong** [comment]
就是方向性选择吧： 要么使用较为大而全、开箱即用的 egg，要么自己根据需求以 koa 为基础做定制开发。

**Comment by czy88840616** [comment]
恩，是的，midway 只是将所有框架，加上 ts、依赖注入、装饰器写法的能力，尽可能不对上层框架做过度的封装、选型。
