### ISSUE TITLE
建议优化日志写入文件格式

### ISSUE THREAD

**Issue by he-zhiyong** [midwayjs/midway#839]
* **Node Version**: 14.15.4
* **Egg Version**: 2.0.0
* **Plugin Name**: @midwayjs/web
* **Plugin Version**: 2.7.3
* **Platform**: Centos8

日志写入文件时，Error的message部分的堆栈信息第一行没有换行，不便于对日志文件的二次处理，建议优化。
![image](https://user-images.githubusercontent.com/23294703/106840657-8dee2e80-66db-11eb-86a3-b9c744fa860e.png)

**Comment by czy88840616** [comment]
是服务器上么？

我本地（mac）看似乎是好的。。

![image](https://user-images.githubusercontent.com/418820/106927936-a1d27880-674d-11eb-962e-b5b0fb8d3f72.png)

**Comment by he-zhiyong** [comment]
@czy88840616 是在服务器环境，Centos 8（Linux version 4.18.0-240.1.1.el8_3.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Thu Nov 19 17:20:08 UTC 2020）

**Comment by czy88840616** [comment]
@he-zhiyong 之前应该是有个版本，egg日志和 midway 日志混合了。可以用新版本看看。

**Comment by Lellansin** [comment]
使用 docker 在 v14.15.4 和 CentOS 8.3.2011 (Linux 323843aac2bc 4.19.76-linuxkit) 情况下没哟复现，初步看下来是跟操作系统没有关系：
![image](https://user-images.githubusercontent.com/2081487/107317744-320a1800-6ad6-11eb-839a-957b5c112018.png)

**Comment by he-zhiyong** [comment]
@czy88840616 @Lellansin 使用midway 日志包后已没有问题，感谢两位
