### ISSUE TITLE
midway-bin-clean 没有删除自定义文件夹

### ISSUE THREAD

**Issue by sinceseason** [midwayjs/midway#842]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

package.json
```
"build": "midway-bin build -c",
"midway-bin-clean": [
	".vscode/.tsbuildinfo",
	"dist",
	"busss"
],
```
运行 npm run build 并没有删除 busss 文件夹，是否还需要其他配置？

**Comment by echosoar** [comment]
`midway-bin build -c` 仅会删除 dist 目录，不会处理 `midway-bin-clean` 配置。
`midway-bin clean` 会根据 `midway-bin-clean` 配置进行删除

**Comment by czy88840616** [comment]
脚本中添加 `clean: midway-bin clean` 即可。
