### ISSUE TITLE
自定义装饰器的需求

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#85]
可以支持 CQRS + EventSourcing的架构

@kurten @wang-ran 可以一起看看。

**Comment by czy88840616** [comment]
需要改造到 injection，或者到扫描层的扩展机制。

每次 binding 完对 object 做一个筛选归类，特定的装饰器可以注册不同的处理程序，每次创建对象时都会被相应的处理程序调用。

**Comment by czy88840616** [comment]
另外有了这层能力，理论上不需要把文件放在特定的目录，我们只需要出一个简单的推荐目录就好，比如现在的 schedule 其实还是要限定目录去 load，但是本意其实并不需要目录，所以我们可能后面只简单推荐放在 `/src/schedule` 或者类似的目录，就行，至于用户希望分多个，也没有问题。

**Comment by Lellansin** [comment]
@kurten plugin 里有自定义装饰器咋办

**Comment by kurten** [comment]
@Lellansin 这个感觉就没必要提供了吧，要提供也可以，框架扩展一种加载文件的类型，专门来初始化插件自定义的装饰器

**Comment by czy88840616** [comment]
转由我实现。

**Comment by czy88840616** [comment]
基础实现 https://github.com/midwayjs/injection/pull/2

**Comment by mengxingshike2012** [comment]
请问现在最新的版本，支持自定义装饰器了吗， 好像没有看到相关的文档

**Comment by czy88840616** [comment]
有的，参考 https://www.yuque.com/midwayjs/zahvcd/wcuv2d

**Comment by mengxingshike2012** [comment]
> 有的，参考 https://www.yuque.com/midwayjs/zahvcd/wcuv2d

谢谢， 请问midway有专门的答疑群吗，内部的也可以，有集团外包账号

**Comment by czy88840616** [comment]
可以参考#295
