### ISSUE TITLE
请问我该怎么在[filename].test.ts中为post请求传递body参数

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#857]
如题

**Comment by czy88840616** [comment]
应用的话，参考下图。

![image](https://user-images.githubusercontent.com/418820/108692863-1ff99200-7538-11eb-88c8-6dbb9b0af7ef.png)

https://www.yuque.com/midwayjs/midway_v2/testing#uX9aC

**Comment by feiyueXH** [comment]
OK

**Comment by waitingsong** [comment]
第二个 POST 的是 `json`  格式么？

**Comment by czy88840616** [comment]
对
