### ISSUE TITLE
closeApp egg没有强制退出

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#863]

**Comment by boostbob** [comment]
使用 --forceExit 参数也不行.

**Comment by czy88840616** [comment]
forceExit 那还是可以的。。

**Comment by tkvern** [comment]
看看这个，--forceExit 可以退出 [强制退出 app](https://github.com/fsd-nodejs/service-mw2/blob/master/package.json#L48)

**Comment by tkvern** [comment]
> 我比较希望能正常退出，而不是走强制退出，应该是有什么事件监听卡住了。

排查不到，不加强制，跑 CI 无法停止

**Comment by czy88840616** [comment]
已处理修复。
