### ISSUE TITLE
抛出异常的默认请求状态码为404，意思是要手动设置ctx.statu为500吗？

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#864]
![image](https://user-images.githubusercontent.com/35318575/109121713-9093ef00-7782-11eb-9d36-e94cb573de26.png)
![image](https://user-images.githubusercontent.com/35318575/109121738-9be71a80-7782-11eb-8253-f39c69dc0f6b.png)

**Comment by czy88840616** [comment]
不会啊。。你看看是不是中间件拦截了。

![image](https://user-images.githubusercontent.com/418820/109121992-ee283b80-7782-11eb-8745-3109aa3d516b.png)

**Comment by feiyueXH** [comment]
是的，我加了一个异常处理中间件。
![image](https://user-images.githubusercontent.com/35318575/109124230-a35bf300-7785-11eb-878c-8c042ced88fd.png)
![image](https://user-images.githubusercontent.com/35318575/109124263-ae168800-7785-11eb-9dff-71fb51b4f648.png)

**Comment by feiyueXH** [comment]
我创建了一个新的项目，没有加中间件之前是状态为500，但是加了中间件之后，在catch中，ctx.status默认为404

**Comment by czy88840616** [comment]
是的，如果你是用中间件 catch 了之后，路由外侧认为没有返回结果（默认的状态码是 404），也没有赋值，所以结果为 404，所以如果有错误，可以明确设置 ctx.status = 500，koa-onerror 也是这么做的。
