### ISSUE TITLE
统一 tslint

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#87]
- [x] @然云 提供了 tslint 基础包
- [x] 基础包发布
- [x] 内部 midway 框架使用
- [x] midway 框架及相关模块使用
- [x] midway 相关 demo 使用
- [x] 脚手架统一修改
- [x] 文档记录

**Comment by atzcl** [comment]
应该要转移到 [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) 来吧？

**Comment by czy88840616** [comment]
不用吧，ts 本身已经有 tsc + tslint，不需要 eslint 了吧。
