### ISSUE TITLE
Windows平台Powershell和Cmd中midway-init无法初始化midway-ts项目

### ISSUE THREAD

**Issue by SilverLeaves** [midwayjs/midway#88]
* **Node Version**: 10.14.2
* **Egg Version**: midway-ts
* **Npm Version**:6.4.1/6.5
* **Platform**:Windows 10 1703
* **Mini Showcase Repository**:  --

* **Desc**: 注意看时间,,, 拉不到项目模板.

![default](https://user-images.githubusercontent.com/31165554/49989671-faff5100-ffb5-11e8-8ae0-daf0988ce282.png)

![default](https://user-images.githubusercontent.com/31165554/49989724-297d2c00-ffb6-11e8-8b79-af032166c0dc.png)

**Comment by czy88840616** [comment]
大概率是我们没有支持 windows……

**Comment by SilverLeaves** [comment]
> 我直接拉midway-ts的example仓库下来,是可以用的. 
🍂 
> 请求支持一下windows嘛,我是从egg过来的.
🍂

**Comment by czy88840616** [comment]
好的，我们得排查下哪个包不支持windows

**Comment by SilverLeaves** [comment]
@czy88840616 灰常感谢啦!!!!

**Comment by brucecodezone** [comment]
@SilverLeaves 使用wsl就好了

**Comment by czy88840616** [comment]
👍

**Comment by czy88840616** [comment]
已经处理，现在创建应该没问题了。

**Comment by ZQun** [comment]
@czy88840616 windows 初始化项目应该还是有问题

<img width="773" alt="2018-12-28 18 00 31" src="https://user-images.githubusercontent.com/12726554/50511956-9b7f6600-0aca-11e9-825f-454b6d427ff1.png">

**Comment by czy88840616** [comment]
我测一下

**Comment by czy88840616** [comment]
我发现自带的命令行问题很多，连敲个 midway-init -v都会卡住。

**Comment by ZQun** [comment]
https://github.com/yargs/yargs/pull/457

**Comment by czy88840616** [comment]
现在就是直接继承了egg-init，然而 egg-init 也是有问题的。

![image](https://user-images.githubusercontent.com/418820/50534117-f10f4d80-0b72-11e9-8a28-ace8a15a4435.png)

**Comment by czy88840616** [comment]
silent 模式下，文件可以生成，但是也会hang住，这个排查了一下是 mem-fs-editor 提交部分造成的。

![image](https://user-images.githubusercontent.com/418820/50535128-8e717e00-0b81-11e9-9712-21a95b7d8913.png)

非 silent 模式我继续看看。

**Comment by lvzhenbang** [comment]
这么多天过去了，这个问题怎么还存在

**Comment by SilverLeaves** [comment]
@lvzhenbang Windows的Powershell和Cmd还是拉不到midway-ts模板。。

**Comment by czy88840616** [comment]
先拷贝模板吧，windows 的排查现在在第三方库的地方卡住了，要计划换库了。

**Comment by yabcer** [comment]
@czy88840616  Windows平台下使用 Git Bash 可以建立项目

**Comment by SilverLeaves** [comment]
@yabcer (〃￣︶￣)人(￣︶￣〃) 机智！以后用gitbash可以咯。
@czy88840616 这个ISSUE是不是可以关掉了？

**Comment by czy88840616** [comment]
gitbash有什么特别么🤔，想不通

**Comment by binbin1808** [comment]
这个问题还是没有解决吗

**Comment by czy88840616** [comment]
目前还没解决。。而且不知道为啥。。。根据上面的反馈 gitbash 可以使用，推荐先。

**Comment by binbin1808** [comment]
我win7使用gitbash  没用不过我前天用的时候还可以用不过感觉项目目录和文档的说明不一样
![x8 zj0i1 a4v4qxr1x0u9 k](https://user-images.githubusercontent.com/39072622/53540817-05ab9a00-3b52-11e9-8a16-4999b567b4cd.png)

**Comment by czy88840616** [comment]
<1.4 版本的 midway，除了 controller 和 schedule 需要限定目录外，其他的都不限定目录，只要在 src 中即可。

service 的代码可以随意放在 `src/service` 或者其他目录中。

**Comment by binbin1808** [comment]
好的

**Comment by lake2** [comment]
我也遇到这个问题。。

**Comment by czy88840616** [comment]
@lake2 是脚手架创建失败么？可以试试用 gitbash。

**Comment by lake2** [comment]
> @lake2 是脚手架创建失败么？可以试试用 gitbash。

我直接从midway-init目录下拷贝出来了。。
另外问下，如何调试单元测试用例？

**Comment by czy88840616** [comment]
直接断点就好了。。 idea 直接配置 npm 命令，vscode 参考https://github.com/midwayjs/midway/issues/169

**Comment by lake2** [comment]
> 直接断点就好了。。 idea 直接配置 npm 命令，vscode 参考#169

调试controller我成功了，调试测试用例没成功
使用如下的配置：
```js
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Test",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run", "test"],
      "console": "integratedTerminal",
      "protocol": "auto",
      "port": 9229,
      "autoAttachChildProcesses": true
    },
```
似乎运行的就是 Npm run test ？
我的package.json里的配置为：
```js
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-gspLive-server --framework=midway",
    "stop": "egg-scripts stop --title=egg-server-gspLive-server",
    "start_build": "npm run build && NODE_ENV=development midway-bin dev",
    "dev": "set NODE_ENV=local && midway-bin dev --ts",
    "debug": "set NODE_ENV=local && midway-bin debug --ts",
    "test": "midway-bin test --ts",
    "cov": "midway-bin cov --ts",
    "lint": "tslint -c tslint.json --project .",
    "ci": "npm run cov",
    "build": "midway-bin build -c"
  },
``
报错：
![image](https://user-images.githubusercontent.com/6293752/56111574-0d50c200-5f8b-11e9-9d19-40d47e2d96be.png)
似乎 midway-bin test --ts 没有启动调试？

**Comment by czy88840616** [comment]
看起来没有问题。。

**Comment by lake2** [comment]
但是 debugger 和断点都无法停下来。测试用例跑完就直接退出了。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/56113923-e3e76480-5f91-11e9-9b93-78f1985b8096.png)

出现这个错貌是应用没启动成功的意思。

**Comment by lake2** [comment]
> 我用的没问题。。。
> 
> ![image](https://user-images.githubusercontent.com/418820/56114004-1f822e80-5f92-11e9-934a-44df63e1df51.png)
> 
> 出现这个错貌是应用没启动成功的意思，看看控制台输出吧。

控制台无报错，是不是window10环境的问题？
![image](https://user-images.githubusercontent.com/6293752/56120632-1e0c3280-5fa1-11e9-8e99-b4e257cb34d0.png)

**Comment by SilverLeaves** [comment]
@czy88840616 gitbash还有一个神器的特性，就是不会阻塞（这个是在egg上运行时发现的）。前一段时间公司经常有人反馈，服务没反应，后来测试发现cmd、poweshell会出现莫名其妙的阻塞，但是用gitbash就不会阻塞。

**Comment by czy88840616** [comment]
对，就是不明不明真相的阻塞，微软新出的终端不知道有没有改进。

**Comment by waitingsong** [comment]
win7 下面 cmd 会卡住， git-bash 可以初始化（不过在方向键选择模板时显示不会更新）。
