### ISSUE TITLE
RuleType 怎么实现 参数 A or 参数 B 仅一个必填?

### ISSUE THREAD

**Issue by jsbay** [midwayjs/midway#880]
```ts
import { Rule, RuleType } from '@midwayjs/decorator';
export class TestDTO {
  @Rule(RuleType.string().when('B', {
      is: RuleType.exist(),
      then: RuleType.forbidden(),
    })
    A: string;

  @Rule(RuleType.string().when('A', {
      is: RuleType.exist(),
      then: RuleType.forbidden(),
    })
    B: string;
}
```
错误信息: 
`item added into group accounts created a dependencies error`

希望可以判断 
- 当 传 A 时, B 不能传;
- 当 传 B 时, A 不能传;

**Comment by stone-jin** [comment]
你好，请试一下下面的操作：

```
import { Rule, RuleType } from '@midwayjs/decorator';
export class TestDTO {
  @Rule(RuleType.string().when('B', {
      is: RuleType.exist(),
      then: RuleType.forbidden(),
      otherwise: Joi.required()
    })
    A: string;

  @Rule(RuleType.string())
    B: string;
}
```

**Comment by jsbay** [comment]
谢谢, 我查阅了很多的文档, 但是就是没想到, 仅判断 A 或 B 中的其中一个值即可,非常感谢!!

严谨点,  您其中包含了一小处错误 `otherwise: Joi.required()` => `otherwise: RuleType.required()`; 
希望后面的同学不会因为这个小问题卡住
> 你好，请试一下下面的操作：
> 
> ```
> import { Rule, RuleType } from '@midwayjs/decorator';
> export class TestDTO {
>   @Rule(RuleType.string().when('B', {
>       is: RuleType.exist(),
>       then: RuleType.forbidden(),
>       otherwise: Joi.required()
>     })
>     A: string;
> 
>   @Rule(RuleType.string())
>     B: string;
> }
> ```
