### ISSUE TITLE
应用开发时通过@Inject() Class引入组件（命名空间）问题

### ISSUE THREAD

**Issue by ZQun** [midwayjs/midway#888]
应用开发时引入开发过程中的组件，json_a在组件开发过程中可以正常使用，但是编译dist后就不能使用了，json_b开发和编译后都可正常使用；组件支持下json_a : Inject() Class用法😃

```ts
import { Json } from 'midway-orm-json'

@Provide()
@Controller('/')
export class HomeController {
    @Inject()
    json_a: Json

    @Inject('JSON:json')
    json_b: Json
}
```

**Comment by czy88840616** [comment]
好像没这问题。。我测试了 midway-test-component 里面的 [bookService](https://github.com/czy88840616/midway-test-component/blob/master/src/service/bookService.ts)，以及 @midwayjs/grpc 中的 clients，似乎都没有问题，可以正常注入。

**Comment by ZQun** [comment]
@czy88840616  嗯，现在开发已经习惯把组件命名空间填写上了，以免不同组件内Class命名冲突，还是写上的好😄
