### ISSUE TITLE
原serverless支持单个函数用path去匹配http前缀路径，serverless2.0做成了整体解决方案后，希望可以支持匹配路径参数

### ISSUE THREAD

**Issue by mumudev** [midwayjs/midway#889]
service:
  name: midway-faas-examples          ## 函数组名，可以理解为应用名

provider:
  name: aliyun                        ## 发布的平台，这里是阿里云

aggregation:                          ## 对 HTTP 函数使用聚合模式部署
  all:
    pre_path: /api/xxxxx             ##  TODO 支持前置路径匹配
    functionsPattern:
       '*'

**Comment by mumudev** [comment]
查源码后，发现可以用这种方式，临时覆盖原有的入口

functions:
  app_index:
    handler: index.handler
    concurrency: 5
    events:
      - http:
          path: /api/*

**Comment by czy88840616** [comment]
嗯，原来的用法都是支持的。
