### ISSUE TITLE
app里的controller不会运行全局中间件，src下的controller可以正常运行全局中间件

### ISSUE THREAD

**Issue by apifox001** [midwayjs/midway#894]
* **Node Version**:12.14.0
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOS
* **Mini Showcase Repository**:https://gitee.com/apifox001/mw-test 

app里的controller不会运行全局中间件，src下的controller可以正常运行全局中间件。

**Comment by czy88840616** [comment]
核心原因是，先加载了 egg 的路由，再加载了中间件。
