### ISSUE TITLE
引入公司的egg框架，启动失败

### ISSUE THREAD

**Issue by LiZhouYang5612** [midwayjs/midway#904]
报错显示
![image](https://user-images.githubusercontent.com/38031780/110732803-d14e3680-825f-11eb-98d5-e774638c505d.png)

![image](https://user-images.githubusercontent.com/38031780/110732730-ae238700-825f-11eb-99a6-42c584690640.png)

原框架插件
![image](https://user-images.githubusercontent.com/38031780/110732846-e5923380-825f-11eb-803c-9e15f97c7612.png)

package.json
![image](https://user-images.githubusercontent.com/38031780/110733358-bd570480-8260-11eb-80eb-dc379fe43767.png)

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
[typings.zip](https://github.com/midwayjs/midway/files/6120357/typings.zip)

可以用已经生成好的 egg tyings 看看能否执行，排除框架的问题。

**Comment by LiZhouYang5612** [comment]
> [typings.zip](https://github.com/midwayjs/midway/files/6120357/typings.zip)
> 
> 可以用已经生成好的 egg tyings 看看能否执行，排除框架的问题。

谢谢 已经找到问题了

**Comment by czy88840616** [comment]
😮，是啥原因。。
