### ISSUE TITLE
单例service注入model失败(作用域为Singleton的Service中InjectEntityModel,读取使用时为空)

### ISSUE THREAD

**Issue by zengyuhang** [midwayjs/midway#921]
case:  https://github.com/zengyuhang/midway-case

环境:
yarn run v1.22.0
$ luckyeye

  Base check

  ¤  Hostname => PC-20161121GFFG (570ms)
  ¤  VM CPU => 8 (581ms)
  ¤  USER HOME => C:\Users\Administrator (582ms)
  ¤  Node.js Version => v14.16.0 (644ms)
  ¤  NPM Version => 6.14.11 (1460ms)

  Midway v2 check

  ¤  midway decorator version => 2.8.11 (966ms)
  ¤  midway core version => 2.8.11 (968ms)
  ¤  midway logger version => 2.8.11 (970ms)
  ¤  midway mock version => 2.8.11 (973ms)
  √ Check Node.js Version（>=12） => true (974ms)
  √ multiple @midwayjs/decorator => true (906ms)
  √ multiple @midwayjs/core => true (906ms)
  √ old midway-bin must be removed => true (907ms)
  √ old midway-mock must be removed => true (907ms)
  √ upgrade to ts4 => ? (908ms)

**Comment by kurten** [comment]
问题原因是多层级 MidwayContainer 引发 resolverHandler 注册层级不一致，导致最终创建单例实例时 getHandler 获取到 undefined
    * 具体 case： Request Scope 因在 RequestContainer 中已经注册 resolverHandler 所以没有问题，但是 Singleton Scope 需要在最上层 Conainer 中创建实例，但 component 中注册的 handler 在中间层，没有注册在最上层。
    * 层级
  ```
    MidwayRequestContainer
      MidwayContainer     ---> 该层存在 orm data handler
        MidwayContainer   ---> 该层不存在 orm data handler，singleton 对象在这里创建
  ```

我想想怎么修复这个问题

**Comment by zengyuhang** [comment]
比较诡异的是我这边上周三后才陆续出问题 现在一样的代码也还跑在很多节点上   我对比了一下可以跑的节点跟有问题的节点  midway相关的库都是一样的版本
