### ISSUE TITLE
@midway/rabbitmq 无法在config中配置参数

### ISSUE THREAD

**Issue by letheliu** [midwayjs/midway#932]
* **Node Version**:  12.21.0
* **Egg Version**:  midwayjs 2.8.13
* **Plugin Name**: @midway/rabbitmq
* **Plugin Version**: 2.8.13
* **Platform**: Windows
* **Mini Showcase Repository**: @midway/rabbitmq 无法在config中配置参数

midway使用Eggjs作为上层框架，单独使用@midway/rabbitmq，已经在configuration.ts中导入，但在config配置文件中无法配置rabbit连接参数，一直默认连接127.0.0.1：5672

**Comment by czy88840616** [comment]
作为独立的 Framework，目前配置只有在 bootstrap.js 启动的时候才能修改(new 的阶段），和 egg 是不一样的。

ps: 下个版本应该可以放 config 里了。

**Comment by letheliu** [comment]
谢谢
