### ISSUE TITLE
请问依赖注入遇到有参构造函数该如何处理?

### ISSUE THREAD

**Issue by feiyueXH** [midwayjs/midway#936]
如题

**Comment by czy88840616** [comment]
有具体事例么，我理解应该不存在构造函数的问题。

**Comment by feiyueXH** [comment]
![image](https://user-images.githubusercontent.com/35318575/111964540-b026f900-8b2f-11eb-9d9d-6a52877a06fe.png)
我需要在创建实例的时候传入构造函数的入参

**Comment by czy88840616** [comment]
这个 modelClazz 应该是注入进来的吧。。。

**Comment by feiyueXH** [comment]
不是。

**Comment by feiyueXH** [comment]
看了Java的IoC有关如何注入有参构造函数，发现是将构造函数所需的参数先写死在xml文件里面，也不是我想要的。我想要的是在运行时创建实例时动态传入参数。

**Comment by feiyueXH** [comment]
没别的方法的话，就封装一个工厂方法，通过容器创建实例后，执行初始化方法吧。

**Comment by czy88840616** [comment]
你可以使用 https://www.yuque.com/midwayjs/midway_v2/container#d13e1609

**Comment by feiyueXH** [comment]
好的 我研究下怎么用

**Comment by feiyueXH** [comment]
3Q
