### ISSUE TITLE
前端框架集成目录约定

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway#95]
最近有在做类似 antd 的集成 #92 ，思考一些目录结构上的问题，像 antd 这样的框架，目前也有 ts 的版本，如果集成的话，可能会在环境上和后端产生冲突。

这是 antd-ts 产生的目录结构。
![image](https://user-images.githubusercontent.com/418820/50503568-bfc74c80-0aa2-11e9-95ab-5bbe64eaa4f4.png)

以及这是 egg 和 antd design 集成的例子。https://github.com/eggjs/egg-ant-design-pro

@midwayjs/midwaycollaborators 可以一起看看

**Comment by czy88840616** [comment]
# 方案一

分别提供 server/client 目录。

**Comment by czy88840616** [comment]
## 方案二

以 server 为主，添加客户端目录。

**Comment by czy88840616** [comment]
另外，两套方案都需要定的

- 1、前端打包的目录约定
- 2、统一的命令管理，比如都需要 build/start 命令

**Comment by czy88840616** [comment]
## 结论

经过内部讨论，和 ice 以及未来的和其他前端框架结合的目录结构统一走 **方案1**，目录结构确定为server/client 模式。

**Comment by kurten** [comment]
方案1，直接把 static 的目录指向client/build 结果不行么？为啥还要copy？

**Comment by czy88840616** [comment]
@kurten 不会 copy，直接改 config 的目录。

**Comment by czy88840616** [comment]
在不分仓库的场景下，分两个目录还是合适的，未来就算想拆多库，发cdn，都可以按照目录结构完整的处理，目前就按方案1进行处理。

**Comment by czy88840616** [comment]
@ZQun 我设想是通用的，至少 server 目录不变，只是 client 包的内容不同

**Comment by ZQun** [comment]
@czy88840616 有点前后端分离的感觉，如果集成其他框架，会不会因为各个框架build目录不同，父级总控目录的package.json不好配置

**Comment by czy88840616** [comment]
@ZQun 目前看问题还好，前端都需要打包到一个特定目录，我们提供的脚手架可以统一是 build，然后在 server 端配置就好。

父级的 pkg 我还在设计命令，最终执行的其实都子包里自己的命令，应该不太冲突。

**Comment by ZQun** [comment]
@czy88840616 是通过脚手架package.json来配置前端打包入口，脚手架将前端打包后的文件copy到server，统一client和server的build命令方式吗
