### ISSUE TITLE
再开一个 群呀  2群 满了

### ISSUE THREAD

**Issue by xiaobo1215** [midwayjs/midway#950]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
应该没有满的，2 群上限 1000 人，现在才 99。。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/112588460-66455800-8e3a-11eb-9b79-1f5bd3fd19e1.png)
