### ISSUE TITLE
为啥npm run dev和npm run start行为不一致？

### ISSUE THREAD

**Issue by B1anker** [midwayjs/midway#951]
## 1.修改默认启动端口
start要改bootstrap.js才能修改端口号
```typescript
const web = new WebFramework().configure({
  port: 6666
});
```
dev则是要在script里面加```--port```参数
![image](https://user-images.githubusercontent.com/17514962/112592248-a3144d80-8e40-11eb-8b17-a258299c3d1a.png)

## 2.修改日志路径
start则是修改
```typescript
const fileLogger = createLogger("customFileLogger", {
  level: "info",
  dir: __dirname + "/log/server",
});

const web = new WebFramework().configure({
  port: 6666,
  logger: fileLogger
});
```
dev则没有办法修改！还必须要NODE_ENV=local才有日志输出，NODE_ENV=development啥也没有

* **Node Version**:
* v12.14.1
* **Egg Version**:
* "@midwayjs/bootstrap": "^2.3.0",
    "@midwayjs/decorator": "^2.3.0",
    "@midwayjs/koa": "^2.3.0"
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by czy88840616** [comment]
1、dev 是本地快速启动，bootstrap 是线上部署的入口，两者是不同的，如果希望相同，可以采用 --entryFile 参数。
文档：https://www.yuque.com/midwayjs/midway_v2/multi_framework_start#4r5Xm

这样开发和部署都是走 bootstrap，但是这样启动的端口需要在 bootstrap.js 设置，但是也可以使用配置，文档中有描述。

2、NODE_ENV=development 一般是已经在服务器上了，服务器上一般是远程 SSH 上去，运行输出到控制台其实是看不到的，如果需要修改这个行为，可以调整控制台等级。

固定调整等级：初始化一个日志时添加 consoleLevel，默认日志等级 https://www.yuque.com/midwayjs/midway_v2/logger#hagAK
动态调整等级文档：https://www.yuque.com/midwayjs/midway_v2/logger#iNQ63
