### ISSUE TITLE
疑问讨论：Midway2是否考虑过使用koa作为默认的底层框架

### ISSUE THREAD

**Issue by joyexpr** [midwayjs/midway#959]
纯讨论~~

我们知道，目前midway2是使用eggjs作为默认主推的底层框架，但从个人感觉来看，eggjs本身已经比较复杂，有自己一套比较复杂的机制和规范，如多进程模型、目录规范、插件框架机制等等，

midway2基于eggjs，总觉得是复杂上再加复杂，心力成本高且容易产生坑，不利于项目选型，而且从文档上来看，文档中有很多关于eggjs的特别说明，感觉midway和eggjs的一些理念并不完全一致，在硬打补丁

如果不考虑历史包袱的话（eggjs和midway同属阿里系），midway是否曾考虑地使用简单的Koa作为默认主推的底层框架（虽然现在也支持，但不是主推，包括文档或示例等），如果使用koa会不会更简单且可控、更有利于midway的设计、使用和发展？

**Comment by czy88840616** [comment]
没有问题，midway 有完全的基于 koa 的框架。https://www.yuque.com/midwayjs/midway_v2/koa

**Comment by tkvern** [comment]
其实 egg 也只是在 koa 上做了一些上层实现，用起来更加方便，又有在阿里业务实践的插件，整体而言用起来 Egg + Midway 是比较舒服的。而且前面的坑已经有人躺过了，[midway2.x 深度躺坑记(持续更新)](https://github.com/fsd-nodejs/service-mw2/wiki/midway2.x-%E6%B7%B1%E5%BA%A6%E8%BA%BA%E5%9D%91%E8%AE%B0(%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0))

**Comment by cc4dogman** [comment]
目前V2比较稳定,部署到sls上bug也相对较少,如果只是简单的业务建议直接使用serverless模式去搞会更加合适一点点,复杂的用eggjs也不是不行,只是学习成本高一点,不过熟悉后没问题

**Comment by czy88840616** [comment]
这个 issue 该关了。。
