### ISSUE TITLE
使用@midwayjs/swagger定义一个response对象的描述过于繁琐

### ISSUE THREAD

**Issue by hcg1023** [midwayjs/midway#961]
目前定义对象类型返回值的description只能通过content，然后一层一层往下定义，希望可以参考一下隔壁家的[nestjs swagger response](https://nestjs.bootcss.com/openapi/operations#responses)
```
content: {
        'application/json': {
          schema: {
            properties: {
              success: {
                description: 'server response is success',
                type: 'boolean',
                example: true,
              },
              message: {
                description: 'server response message',
                type: 'string',
              },
            },
          },
        },
      }
```

**Comment by czy88840616** [comment]
有计划重写。

**Comment by waitingsong** [comment]
用 schema 来定义结构也不会简单。 
不知道直接用 ts 的（返回）类型来处理是否可行。

**Comment by czy88840616** [comment]
处理不了的，promise的结果拿不到里面的类型，除非不写 promise...

**Comment by hcg1023** [comment]
就算可以处理，也会影响到定义多个status的返回值吧

**Comment by hcg1023** [comment]
还有一个问题就是，我们的服务端返回类型一般都是这样的，这种结构在swagger中能不能定义一次，然后全局使用呢？
```
interface Response<T> {
  success: boolean
  message: string
  result: T
  code: number
}
```

**Comment by czy88840616** [comment]
多个返回值的确是需要单独定义。

**Comment by czy88840616** [comment]
interface 在编译后就没了，体会需要运行时获取，必须编写为class

**Comment by hcg1023** [comment]
那如果复用返回值可能是类似下边这样的
```typescript
class Response<T> {
  success: boolean
  message: string
  result: T
  code: number
}
class UserResponse extends Response<User> {
}
```

**Comment by waitingsong** [comment]
> 
> 
> 还有一个问题就是，我们的服务端返回类型一般都是这样的，这种结构在swagger中能不能定义一次，然后全局使用呢？
> 
> ```
> interface Response<T> {
>   success: boolean
>   message: string
>   result: T
>   code: number
> }
> ```

我也是采用这种方式定义

1. 接口定义返回的是 T
2. 中间件（判断返回  MIME json 类型时）把 T 包裹成 Resp<T> 的结构

**Comment by waitingsong** [comment]
> 
> 
> 处理不了的，promise的结果拿不到里面的类型，除非不写 promise...另一种是ast分析，就又回去了..

这个不大明白，不能用泛型传入个类型么。 有没有个代码参考

**Comment by hcg1023** [comment]
> > 还有一个问题就是，我们的服务端返回类型一般都是这样的，这种结构在swagger中能不能定义一次，然后全局使用呢？
> > ```
> > interface Response<T> {
> >   success: boolean
> >   message: string
> >   result: T
> >   code: number
> > }
> > ```
> 
> 我也是采用这种方式定义
> 
> 1. 接口定义返回的是 T 或者 Promise
> 2. 中间件（判断返回  MIME json 类型时）把 T 包裹成 Resp 的结构

这种我明白，是返回值的处理，但目前的问题是swagger的response定义没有办法通过这种方式处理~

**Comment by czy88840616** [comment]
3.x 已实现。

**Comment by cc4dogman** [comment]
> 3.x 已实现。

src/modules/biz/vo/CommonVO.ts:2:17 - error TS4060: Return type of exported function has or is using private name 'ResponseVO'.

2 export function BaseResponseVO<T extends Type>(ResourceCls: T) {
                  ~~~~~~~~~~~~~~

src/modules/biz/vo/vos.ts:4:36 - error TS4020: 'extends' clause of exported class 'WxLoginResult' has or is using private name 'ResponseVO'.

4 export class WxLoginResult extends BaseResponseVO(WxLoginVO) {}


build的时候报上面的错,应该是通过function返回的class是私有内部类,无法导出,开发模式启动没有这个问题,目前通过修改tsconfig.json的declaration:false临时解决这个问题
