### ISSUE TITLE
新版本midway 插件加载顺序改变, controller 内容执行在 plugin.ts前

### ISSUE THREAD

**Issue by wfory** [midwayjs/midway#962]
你好，刚更新了midway最新版，发现dev启动失败(build 和 start没问题)，原因通过tsconfig-paths设置的路径别名找不到。
 我原来是在 plugin.ts里引入了 'tsconfig-paths/register'，在controller里用到了路径别名。 当我把'tsconfig-paths/register'
在controller里直接引入时就能正常启动了。
      想问下，新版本是调整了插件等组件加载顺序了吗？我在dev环境里如需引入 tsconfig-paths，要加在哪个位置好一点？之前是
推荐在plugin.ts里引入的，说插件是第一个加载的。

**Comment by czy88840616** [comment]
你可以放在 interface.ts 里。

**Comment by wfory** [comment]
我建了个interface文件夹，里面细分了很多的接口

**Comment by czy88840616** [comment]
interface.ts是我们本地开发第一加载的文件，可以加一个。

**Comment by wfory** [comment]
加一个的话与我的一个文件夹名字重复了，刚看文档加了个 src/configuration.ts文件，在里面引入 tsconfig-paths，解决了。感谢你的解答！

**Comment by czy88840616** [comment]
configration也算是比较前面，也行。
