### ISSUE TITLE
Prometheus 能否添加访问HTTP的path、平均的RT，访问HTTP的get、post的情况

### ISSUE THREAD

**Issue by Benevole** [midwayjs/midway#979]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by Benevole** [comment]
有进展吗？

**Comment by czy88840616** [comment]
应该还没有，最近开始忙着准备大促了，需求比较多。

**Comment by stone-jin** [comment]
https://www.yuque.com/midwayjs/midway_v2/prometheus
