### ISSUE TITLE
configuration.ts配置中conflictCheck有bug

### ISSUE THREAD

**Issue by zhoujiayingvana** [midwayjs/midway#989]
* **Node Version**:
* 12.18.3
* **Egg Version**:
* 2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* windows 10
* **Mini Showcase Repository**:

新创建的项目，运行npm run dev ，configuration里面设置冲突检查报错，后面路径解析出现了个正斜杠('/')，应该是getDefinition方法里面拼接路径有问题。。。
![image](https://user-images.githubusercontent.com/43395552/114548186-fe906900-9c91-11eb-8b0d-0e790899ca0d.png)
![image](https://user-images.githubusercontent.com/43395552/114548200-051ee080-9c92-11eb-9fc5-bf33b3a31105.png)
![image](https://user-images.githubusercontent.com/43395552/114548212-0819d100-9c92-11eb-92e0-2e06c7efe104.png)
![image](https://user-images.githubusercontent.com/43395552/114548217-0b14c180-9c92-11eb-8480-c4ba1611d43a.png)

**Comment by czy88840616** [comment]
已经有 #984 处理了
