### ISSUE TITLE
midway-serverless 方案讨论

### ISSUE THREAD

**Issue by ZQun** [midwayjs/midway#99]
重新开个issues，在这里讨论有关midway-serverless吧😊
https://github.com/midwayjs/midway/issues/96

**Comment by czy88840616** [comment]
@kurten @Lellansin

**Comment by ZQun** [comment]
https://github.com/eggjs/egg/issues/3352#issuecomment-451136902

**Comment by SilverLeaves** [comment]
serverless很棒棒哦，那么问题来了，midway和函数计算怎么选择好呢

**Comment by czy88840616** [comment]
midway-serverless 可以看成一个 serverless framework，解决的是不同平台希望能有统一的开发体验的问题。

**Comment by SilverLeaves** [comment]
还没方案吗？凉了吗？

**Comment by czy88840616** [comment]
我们现在主要在做函数计算这块。正在内部使用中。

**Comment by SilverLeaves** [comment]
焦急又耐心的等待

**Comment by ZQun** [comment]
@czy88840616  函数计算大概什么时候上线？

**Comment by czy88840616** [comment]
现在的问题在于内部方案和社区方案并没有特别一致。简单来说现在阿里云的fc是没法自定义运行时的，只是开放了函数部分，如果要一致的话，这样很多的逻辑就得从运行时移动到用户代码中，感觉不是特别好。

为了和 midway 系列的注入用法，以及跨模块的复用，我们目前还是希望 fc 的写法是 ts + 装饰器的用法，通过不同的生成器来屏蔽入口的差异，这样可以部署到 fc/amazon 等不同的平台上。

举个例子：

我们会把 fc 的参数进行一些包装。

```js
exports.handler = (event, callback) => {
}
```

变成类似下面的形式。

```ts
@func()
export class MainFunction {

  @inject()
  ctx;

  async handler(event) {

  }
}
```

就目前来说，集团内的场景趋于稳定，但是社区的变数还是比较多，如何和各方的工具链协作也是一个问题，不过 就 midway-faas 本身的代码变化不大，大概也就 150 行代码，非常简单。。

**Comment by ZQun** [comment]
@czy88840616 先开源一部分，在慢慢升级呢

**Comment by danielsss** [comment]
黄花菜都凉透了~ @czy88840616  赶紧申请开源啊！

**Comment by czy88840616** [comment]
本周提流程。
