### ISSUE TITLE
请问 不需要参数校验的参数也必须要加@Rule的装饰器吗  如果参数很多 但是需要校验的参数只有几个 不是很麻烦？

### ISSUE THREAD

**Issue by GarJune** [midwayjs/midway#991]
Controller:

```
@Post('/save')
  @ContentType('application/json')
 @Validate()
  async savePhoto(@Body(ALL) req: PhotoReq) {
    const photo = new Photo();
    photo.name = req.name;
    photo.description = req.description;
    photo.filename = req.filename;
    photo.views = req.views;
    photo.isPublisher = req.isPublisher;
    const entity = await this.photoService.savePhoto(photo);
    return entity.id;
  }
```

DTO:

```
export class PhotoReq {
  @Rule(RuleType.string().required())
  name: string;
  description: string;
  filename: string;
  @Rule(RuleType.number().equal(1) || RuleType.number().equal(2))
  views: number;
  @Rule(RuleType.boolean().required())
  isPublisher: boolean;
}
```

POST 请求参数body:

```
{
    "name":"张三",
    "description":"我是法外狂徒张三",
    "filename":"张三入狱照.jpg",
    "views":"1",
    "isPublisher": false
}
```

控制台报错:
 ```

ValidationError: "description" is not allowed
2021-04-14 17:37:26,827 ERROR 55278 [-/::1/-/67ms POST /photo/save] ValidationError: "description" is not allowed


```
如果DTO改成
```

export class PhotoReq {
  @Rule(RuleType.string().required())
  name: string;
  @Rule(RuleType.string())
  description: string;
  @Rule(RuleType.string())
  filename: string;
  @Rule(RuleType.number().equal(1) || RuleType.number().equal(2))
  views: number;
  @Rule(RuleType.boolean().required())
  isPublisher: boolean;
}
```

就正常了...

**Comment by stone-jin** [comment]
我这边测试了一下并没有这个问题。请问一下你的版本？或者提供一下简单的仓库？

我按照你的方法测试的：并没有出现description没有填导致校验失败的情况。

![image](https://user-images.githubusercontent.com/6525544/114977889-05e68b00-9ebb-11eb-8e0e-b793ea2fb7d3.png)

代码如下：
![image](https://user-images.githubusercontent.com/6525544/114977911-0ed75c80-9ebb-11eb-8098-929dbad3a96a.png)

**Comment by GarJune** [comment]
没有传这个参数的时候是可以的，但是传了未加@Rule的参数时，比如你的body改成
```
{
"name":"123",
"description":"456"
}
```
时就会报错但是description这个参数本身是可有可无的。

**Comment by stone-jin** [comment]
我补了单测，确实存在这个问题，不是很合理，我看看怎么修复一下

**Comment by hackycy** [comment]
@stone-jin 我觉得合理把，已经是参数校验都已经知道哪些参数是存在的，多传了一些未知参数也算是一种不合法的行为把。
如果需要这些参数是变为可选就可以使用`@Rule(RuleType.string().allow('').allow(null).optional())`等手段来让该参数变为非必选就好了。

**Comment by stone-jin** [comment]
@hackycy ，那我在config里面加一个validate的参数，用来配置，是否allowUnknown这种的配置。默认比如不开启，跟joi一样。如果config.default.ts里面用户修改了这种属性，则允许 @GarJune 这样的需求。

**Comment by hackycy** [comment]
@stone-jin nice

**Comment by stone-jin** [comment]
@hackycy @GarJune ，我们这边到时语雀文档里面出一个RFC文档，内部在讨论一下。

**Comment by GarJune** [comment]
goodjob

**Comment by GarJune** [comment]
@hackycy 我的理解跟你可能不太一样 可选参数加上@Rule可以解决这个问题 但是当需要校验的参数只有一个而有十个不需要校验的参数时 我必须要给每个参数加上@Rule才能保证不会报错 而这一步比较麻烦

**Comment by tong3jie** [comment]
@GarJune 不要偷懒 😊

**Comment by mkanako** [comment]
经翻阅代码，最终找到一个偏门办法搞定，想要未知的参数不做检验处理
`
import { defaults } from 'joi/lib/common.js'
defaults.allowUnknown = true
`

**Comment by liuwensa** [comment]
> @hackycy ，那我在config里面加一个validate的参数，用来配置，是否allowUnknown这种的配置。默认比如不开启，跟joi一样。如果config.default.ts里面用户修改了这种属性，则允许 @GarJune 这样的需求。

这个目前有进展了吗，感觉很有必要性。

**Comment by DevanXU** [comment]
> > @hackycy ，那我在config里面加一个validate的参数，用来配置，是否allowUnknown这种的配置。默认比如不开启，跟joi一样。如果config.default.ts里面用户修改了这种属性，则允许 @GarJune 这样的需求。
> 
> 这个目前有进展了吗，感觉很有必要性。

同问

**Comment by stone-jin** [comment]
@DevanXU 参考你上上楼层的解法：
```
import { defaults } from 'joi/lib/common.js'
defaults.allowUnknown = true
```

本来想框架层加上这个功能，但是有人反对有人同意。本来PR也有了，然后没合并。

**Comment by stone-jin** [comment]
> > @hackycy ，那我在config里面加一个validate的参数，用来配置，是否allowUnknown这种的配置。默认比如不开启，跟joi一样。如果config.default.ts里面用户修改了这种属性，则允许 @GarJune 这样的需求。
> 
> 这个目前有进展了吗，感觉很有必要性。

参考你上一楼层的解法

**Comment by riskgod** [comment]
感觉这个很有必要啊

**Comment by czy88840616** [comment]
@riskgod https://midwayjs.org/docs/extensions/validate#1%E5%85%81%E8%AE%B8%E6%9C%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E5%AD%97%E6%AE%B5
